// 8 GATES — MERU · BURGERS: THE SHIFT [meruBurgers]. Ben works the counter at Sizzle's brand-new diner (a full new interior, Meru toon style).
// Start in the diner, tap PUT ME TO WORK and the camera glides behind the counter (like the tavern dart board), then a 3-minute BURGER RUSH.
// v1 stations: GRILL (patties cook, burn if left) · BUN + TOPPINGS (drag pieces onto the bun on the board) · FRYER · DRINKS / SHAKES · BAG + HAND OVER (drag the bag to the customer) · PAY (give the right change).
// Customers are Meru townsfolk. Each day is a little harder and unlocks a recipe; pay = wage + prices + tips in gold; EMPLOYEE OF THE DAY star; the BURGERS uniform (cap + apron); kitchen upgrades.
// v2 (later): clean tables, the delivery run with Bun. MERGE: createBurgerShift({ container }) stands alone; buildDiner(ctx) builds the interior from a Meru-style ctx
// ({ THREE, M, toon, makeFox, canvasTex, scene, origin }) so meru-game.js can swap its old Burgers room for this one, and startShift() runs the same game there.
import * as THREE from '../../vendor/three/three.module.js';
import { rr, clamp, damp, makeGradient, glowTexture, Ambience, smooth, pick } from '../../village-game.js';
import { crestTex, canvasTex } from '../../meru-game.js';
import { foxKit } from '../../fox-kit.js';
import { CAST } from '../../engine/cast.js';
import { save } from '../../engine/save.js';
import { createStage, cameraFit, hintRings, registerKit, dinerUniform, vegArt } from '../../engine/restaurant-kit.js';

export const BURGERS = { name: 'BURGERS · THE SHIFT', room: 'meruBurgers', shift: 180 };
// ingredients (stack heights in m) + prices in gold
export const ING = {
  bunB: { name: 'BOTTOM BUN', col: '#e0a24a', h: 0.054, r: 0.15 }, bunT: { name: 'TOP BUN', col: '#e8a84c', h: 0.1, r: 0.15, dome: true },
  patty: { name: 'PATTY', col: '#6e3f22', h: 0.045, r: 0.16 }, cheese: { name: 'CHEESE', col: '#ffc93a', h: 0.008, r: 0.17, sq: true },
  lettuce: { name: 'LETTUCE', col: '#6fbf3a', h: 0.02, r: 0.175, wavy: true }, tomato: { name: 'TOMATO', col: '#e2412e', h: 0.022, r: 0.13 },
  pickle: { name: 'PICKLES', col: '#7c9a2a', h: 0.012, r: 0.11 }, onion: { name: 'ONION', col: '#f2e6ef', h: 0.016, r: 0.14, ring: true }, sauce: { name: 'SAUCE', col: '#c42d3c', h: 0.008, r: 0.12 } };
export const RECIPES = [
  { id: 'plain', name: 'MERU BURGER', day: 1, stack: ['patty'], price: 6 },
  { id: 'garden', name: 'GARDEN BURGER', day: 1, stack: ['patty', 'lettuce', 'tomato'], price: 7 },
  { id: 'cheese', name: 'CHEESEBURGER', day: 2, stack: ['patty', 'cheese'], price: 7 },
  { id: 'castle', name: 'THE CASTLE', day: 3, stack: ['patty', 'cheese', 'lettuce', 'tomato', 'sauce'], price: 9 },
  { id: 'pickle', name: 'PICKLE BACK', day: 3, stack: ['patty', 'pickle', 'onion', 'sauce'], price: 8 },
  { id: 'double', name: 'DOUBLE GATE', day: 4, stack: ['patty', 'cheese', 'patty', 'cheese'], price: 11 },
  { id: 'melt', name: 'MERU MELT', day: 5, stack: ['patty', 'cheese', 'onion', 'sauce', 'patty'], price: 12 }];
export const SIDES = { fries: { name: 'FRIES', day: 2, price: 3 }, cola: { name: 'COLA', day: 1, price: 2, col: '#5a2a1a' }, orange: { name: 'ORANGE', day: 1, price: 2, col: '#ff8a1a' }, shake: { name: 'SHAKE', day: 3, price: 4, col: '#f7b6d2' } };
export const UPGRADES = [
  { id: 'grill4', name: '4TH GRILL SPOT', cost: 40, line: 'Cook four patties at once.' },
  { id: 'bell', name: 'FRYER BELL', cost: 30, line: 'Fries stay golden 4 s longer.' },
  { id: 'fastPour', name: 'FAST POUR', cost: 35, line: 'Drinks pour twice as fast.' },
  { id: 'warmer', name: 'PATTY WARMER', cost: 50, line: 'Cooked patties never burn.' },
  { id: 'jukebox', name: 'DINER JUKEBOX', cost: 60, line: 'Happy customers wait 20% longer.' }];
const CUSTOMERS = [
  { name: 'KIA', role: 'Item Shop', torso: ['#38bdf8', '#e0f2fe', '#0369a1'] }, { name: 'PELL', role: 'Crestview doorman', torso: ['#1f2937', '#e6b45a', '#111827'] },
  { name: 'OTTO', role: 'Lakeside doorman', torso: ['#2f5d2a', '#e6b45a', '#1a3318'] }, { name: 'MARLA', role: 'Arena market', torso: ['#f472b6', '#fce7f3', '#9d174d'] },
  { name: 'MICHAEL JAY', role: 'Diner regular', torso: ['#e6ecf4', '#dc2626', '#7f1d1d'] }, { name: 'THE FISHERMAN', role: 'Lake jetty', torso: ['#0e7fb8', '#e0f2fe', '#0b3a52'] },
  { name: 'THE SAGE', role: 'Ruins museum', torso: ['#a78bfa', '#ede9fe', '#5b21b6'] }, { name: 'GATE GUARD', role: 'Castle Path', torso: ['#ffffff', '#e7edf4', '#6b7d93'], outfit: 'armor' },
  { name: 'DOC BRAUN', role: 'Tavern', torso: ['#f6f8fb', '#e2e8f0', '#94a3b8'], outfit: 'coat' }, { name: 'FLICK', role: 'Darts', torso: ['#c42d3c', '#f3f2f2', '#7a1d2a'], outfit: 'coat' }];
const LINES = { order: ['Hungry!', 'The usual, please.', 'Make it quick?', 'Smells amazing in here.', 'One of those, please!'], happy: ['Perfect!', 'Delicious!', 'Best in Meru!', 'You are good at this!'], meh: ['Hm, close enough.', 'Not quite what I asked.'], angry: ['Too slow!', 'I am going to the tavern.'] };
// ---------------- ingredient art (shared by the bins and the board) ----------------
export function makeIng(T3, toon, k, state, outline) {
  const g = new T3.Group(), add = (geo, col, x = 0, y = 0, z = 0, o = 0.012, r) => { const m = new T3.Mesh(geo, toon(col)); m.position.set(x, y, z); m.castShadow = true; if (outline && o) outline(m, o, r); g.add(m); return m; };
  const wavy = (r, h, waves, amp, ruff = 0, seg = 40) => { const geo = new T3.CylinderGeometry(r, r, h, seg, 1); const p = geo.attributes.position; for (let i = 0; i < p.count; i++) { const x = p.getX(i), z = p.getZ(i), rr2 = Math.hypot(x, z); if (rr2 < r * 0.5) continue; const a = Math.atan2(z, x), s = 1 + amp * Math.sin(a * waves) + amp * 0.5 * Math.sin(a * waves * 2.3 + 1); p.setX(i, x * s); p.setZ(i, z * s); p.setY(i, p.getY(i) + ruff * Math.sin(a * waves + 0.7)); } geo.computeVertexNormals(); return geo; };
  const lathe = pts => new T3.LatheGeometry(pts.map(([x, y]) => new T3.Vector2(x, y)), 28);
  if (k === 'bunB') { add(lathe([[0, 0], [0.13, 0], [0.152, 0.012], [0.158, 0.03], [0.15, 0.048], [0, 0.05]]), '#d98f3a', 0, 0, 0, 0.01, 0.16); add(new T3.CylinderGeometry(0.142, 0.142, 0.006, 28), '#f6dca0', 0, 0.05, 0, 0); }
  else if (k === 'bunT') { add(lathe([[0, 0], [0.152, 0], [0.16, 0.012], [0.152, 0.04], [0.12, 0.072], [0.07, 0.094], [0, 0.1]]), '#e39a42', 0, 0, 0, 0.01, 0.16); add(new T3.CylinderGeometry(0.15, 0.15, 0.004, 28), '#f6dca0', 0, 0.001, 0, 0);
    for (let i = 0; i < 14; i++) { const a = i * 2.4 + 0.3, r = 0.025 + (i % 5) * 0.022, y = 0.1 - (r / 0.16) ** 2 * 0.085; const s = add(new T3.SphereGeometry(0.009, 6, 4), '#fff6d8', Math.cos(a) * r, y + 0.002, Math.sin(a) * r, 0); s.scale.set(1, 0.55, 1.6); s.rotation.y = a; } }
  else if (k === 'patty') { const col = state && state !== 'raw' ? ({ rare: '#c4523e', medium: '#8a4a26', well: '#5a3018', burnt: '#2a1a14', done: '#6e3f22' }[state] || '#6e3f22') : '#e57373'; add(wavy(0.16, 0.045, 9, 0.035), col, 0, 0, 0, 0.012, 0.16);
    if (state && state !== 'raw') for (const dz of [-0.06, 0, 0.06]) add(new T3.BoxGeometry(0.24, 0.004, 0.016), state === 'burnt' ? '#120a08' : '#2a160c', 0, 0.0235, dz, 0).rotation.y = 0.6;
    else for (let i = 0; i < 8; i++) add(new T3.SphereGeometry(0.012, 5, 4), '#f2a0a0', Math.cos(i * 2.1) * 0.09, 0.022, Math.sin(i * 2.1) * 0.09, 0).scale.y = 0.4; }
  else if (k === 'cheese') { const geo = new T3.BoxGeometry(0.29, 0.012, 0.29, 8, 1, 8), p = geo.attributes.position; for (let i = 0; i < p.count; i++) { const x = p.getX(i), z = p.getZ(i), c = (Math.max(Math.abs(x), Math.abs(z)) / 0.145) ** 3; p.setY(i, p.getY(i) - c * 0.03 * (0.6 + 0.4 * Math.abs(Math.sin(x * 40 + z * 30)))); } geo.computeVertexNormals(); add(geo, '#ffc93a', 0, 0, 0, 0.006).rotation.y = 0.4; }
  else if (k === 'lettuce') { add(wavy(0.172, 0.012, 11, 0.09, 0.012), '#5aa83a', 0, 0, 0, 0.006); add(wavy(0.15, 0.012, 13, 0.1, 0.01), '#86d44e', 0, 0.01, 0, 0.006).rotation.y = 0.5; }
  else if (k === 'tomato') { for (const [x, z, r] of [[-0.04, 0.02, 0.085], [0.05, -0.02, 0.08]]) { add(new T3.CylinderGeometry(r, r, 0.018, 24), '#d83a28', x, 0, z, 0.008, r); add(new T3.CylinderGeometry(r * 0.78, r * 0.78, 0.02, 24), '#f06a52', x, 0.0005, z, 0); for (let i = 0; i < 4; i++) { const a = i * Math.PI / 2 + 0.4; const s = add(new T3.SphereGeometry(r * 0.22, 8, 5), '#ffc9a8', x + Math.cos(a) * r * 0.42, 0.011, z + Math.sin(a) * r * 0.42, 0); s.scale.set(1, 0.25, 0.6); s.rotation.y = -a; } } }
  else if (k === 'pickle') { for (const [x, z] of [[-0.06, 0.03], [0.05, 0.05], [0.0, -0.06]]) { add(wavy(0.045, 0.01, 7, 0.06), '#5f7d1e', x, 0, z, 0.006, 0.045); add(new T3.CylinderGeometry(0.03, 0.03, 0.011, 16), '#a8c45a', x, 0.0005, z, 0); } }
  else if (k === 'onion') { for (const [r, c] of [[0.12, '#f2e6ef'], [0.085, '#e8c9e0'], [0.05, '#f6eef4']]) { const m = add(new T3.TorusGeometry(r, 0.013, 6, 28), c, 0, 0, 0, 0.004); m.rotation.x = Math.PI / 2; m.scale.z = 0.6; } }
  else if (k === 'sauce') { add(wavy(0.11, 0.006, 6, 0.18), '#c42d3c', 0, 0, 0, 0); add(wavy(0.06, 0.007, 5, 0.2), '#e0493f', 0.02, 0.002, 0.01, 0); }
  return g; }
const SAVE = { day: 'meru.burgers.day', best: 'meru.burgers.best', upg: 'meru.burgers.upg.' };

// ---------------- the diner interior (shared by the stand-alone page and, later, meru-game.js) ----------------
export function buildDiner(ctx) {
  const { THREE: T3, M, toon, canvasTex: CTX, scene, origin = { x: 0, z: 0 } } = ctx, root = new T3.Group(); root.position.set(origin.x, 0, origin.z); scene.add(root);
  const W = 12, D = 10, H = 4.2, red = toon('#c42d3c'), white = toon('#f6f3ee'), chrome = toon('#d7dde3'), ink = toon('#201e1d'), wood = toon('#8a5a32'), teal = toon('#5cc6c0');
  const floorT = CTX(256, 256, c => { for (let y = 0; y < 8; y++) for (let x = 0; x < 8; x++) { c.fillStyle = (x + y) % 2 ? '#f6f3ee' : '#c42d3c'; c.fillRect(x * 32, y * 32, 32, 32); } }); floorT.wrapS = floorT.wrapT = T3.RepeatWrapping; floorT.repeat.set(W / 1.2, D / 1.2);
  const fl = new T3.Mesh(new T3.PlaneGeometry(W, D), new T3.MeshToonMaterial({ map: floorT, gradientMap: ctx.grad })); fl.rotation.x = -Math.PI / 2; fl.receiveShadow = true; root.add(fl);
  { const kt = floorT.clone(); kt.needsUpdate = true; kt.repeat.set(W / 1.2, 8 / 1.2); const kf = new T3.Mesh(new T3.PlaneGeometry(W, 8), new T3.MeshToonMaterial({ map: kt, gradientMap: ctx.grad })); kf.rotation.x = -Math.PI / 2; kf.position.set(0, -0.002, -D / 2 - 4); root.add(kf); }
  const wallT = CTX(256, 256, c => { c.fillStyle = '#f2e8d8'; c.fillRect(0, 0, 256, 256); c.fillStyle = '#5cc6c0'; c.fillRect(0, 150, 256, 106); c.fillStyle = '#c42d3c'; c.fillRect(0, 140, 256, 10); c.fillStyle = '#d9cbb3'; for (let i = 0; i < 256; i += 32) c.fillRect(i, 150, 2, 106); }); wallT.wrapS = T3.RepeatWrapping; wallT.repeat.set(4, 1);
  const wallM = new T3.MeshToonMaterial({ map: wallT, gradientMap: ctx.grad });
  const cut = []; for (const [x, z, w, ry] of [[0, -D / 2, W, 0], [-W / 2, 0, D, Math.PI / 2], [W / 2, 0, D, -Math.PI / 2]]) { const m = new T3.Mesh(new T3.PlaneGeometry(w, H), wallM); m.position.set(x, H / 2, z); m.rotation.y = ry; root.add(m); if (!ry) cut.push(m); }
  { const fw = new T3.Mesh(new T3.PlaneGeometry(W, H), wallM); fw.position.set(0, H / 2, D / 2); fw.rotation.y = Math.PI; fw.userData.front = true; root.add(fw); }
  cut.push(M(new T3.BoxGeometry(W, 0.2, D), toon('#e8dccb'), 0, H + 0.1, 0, root, 0));
  // the big front window onto the square (bright), the door
  const front = [], booths = []; { const fc = root.children.length; const win = new T3.Mesh(new T3.PlaneGeometry(6, 2), new T3.MeshBasicMaterial({ color: 0xbfe6ff })); win.position.set(-1.6, 1.9, D / 2 - 0.02); win.rotation.y = Math.PI; root.add(win); for (const x of [-4.6, -1.6, 1.4]) M(new T3.BoxGeometry(0.12, 2.1, 0.12), red, x, 1.9, D / 2 - 0.06, root, 0.01); M(new T3.BoxGeometry(6.1, 0.12, 0.14), red, -1.6, 2.92, D / 2 - 0.06, root, 0.01); M(new T3.BoxGeometry(6.1, 0.12, 0.14), red, -1.6, 0.88, D / 2 - 0.06, root, 0.01);
    const door = new T3.Mesh(new T3.PlaneGeometry(1.6, 2.6), new T3.MeshBasicMaterial({ color: 0xd8f0ff })); door.position.set(4, 1.3, D / 2 - 0.02); door.rotation.y = Math.PI; root.add(door); M(new T3.BoxGeometry(1.8, 0.14, 0.14), red, 4, 2.64, D / 2 - 0.06, root, 0.01); front.push(...root.children.slice(fc)); }
  // KITCHEN (back): flat-top grill, fryer, drink machine, prep board, ingredient bins, bag stand, register
  const KZ = -2.6, K = { root, z: KZ, cut, front, booths };
  cut.push(M(new T3.BoxGeometry(W - 0.4, 0.9, 1.0), chrome, 0, 0.45, KZ - 1.4, root, 0.03));   // back counter
  M(new T3.BoxGeometry(5.8, 0.95, 1.75), white, 0, 0.475, KZ + 0.2, root, 0.03); M(new T3.BoxGeometry(5.9, 0.06, 1.85), chrome, 0, 0.98, KZ + 0.2, root, 0.015); M(new T3.BoxGeometry(5.9, 0.12, 0.06), red, 0, 0.82, KZ + 1.13, root, 0);
  K.top = 1.01;
  // grill (left)
  K.grill = { x: -1.75, z: KZ - 0.05 }; M(new T3.BoxGeometry(1.3, 0.04, 0.9), ink, K.grill.x, K.top + 0.02, K.grill.z, root, 0.01); M(new T3.BoxGeometry(1.34, 0.18, 0.06), chrome, K.grill.x, K.top + 0.09, K.grill.z - 0.46, root, 0.006);
  for (let i = 0; i < 6; i++) M(new T3.BoxGeometry(1.22, 0.003, 0.02), toon('#3a3836'), K.grill.x, K.top + 0.042, K.grill.z - 0.4 + i * 0.16, root, 0);
  K.grillSlots = [[-0.3, -0.2], [0.3, -0.2], [-0.3, 0.22], [0.3, 0.22]].map(([dx, dz]) => ({ x: K.grill.x + dx, z: K.grill.z + dz }));
  K.patBox = { x: K.grill.x - 0.82, z: KZ + 0.05 }; M(new T3.BoxGeometry(0.42, 0.14, 0.34), toon('#dbeafe'), K.patBox.x, K.top + 0.07, K.patBox.z, root, 0.008);
  for (let i = 0; i < 3; i++) M(new T3.CylinderGeometry(0.11, 0.11, 0.03, 14), toon('#e57373'), K.patBox.x - 0.1 + i * 0.1, K.top + 0.15 + i * 0.012, K.patBox.z, root, 0);
  // prep board (centre) + bins along the front edge
  K.board = { x: 0, z: KZ - 0.05 }; M(new T3.BoxGeometry(0.98, 0.04, 0.7), toon('#e9d2a8'), K.board.x, K.top + 0.02, K.board.z, root, 0.01); for (let i = 0; i < 5; i++) M(new T3.BoxGeometry(0.96, 0.002, 0.004), toon('#d4b98a'), K.board.x, K.top + 0.041, K.board.z - 0.28 + i * 0.14, root, 0);
  K.bins = {}; const binKeys = ['bunB', 'cheese', 'lettuce', 'tomato', 'pickle', 'onion', 'sauce', 'bunT'];
  K.chop = { x: -2.55, z: KZ + 0.72 }; M(new T3.BoxGeometry(0.62, 0.04, 0.44), toon('#c99a62'), K.chop.x, K.top + 0.02, K.chop.z, root, 0.01); for (let i = 0; i < 4; i++) M(new T3.BoxGeometry(0.6, 0.002, 0.004), toon('#b07f4a'), K.chop.x, K.top + 0.041, K.chop.z - 0.15 + i * 0.1, root, 0);
  K.binPiles = {}; binKeys.forEach((k, i) => { const x = -1.26 + i * 0.36, z = KZ + 0.66; M(new T3.BoxGeometry(0.34, 0.06, 0.4), chrome, x, K.top + 0.03, z, root, 0.008); const inner = new T3.Mesh(new T3.PlaneGeometry(0.29, 0.35), toon('#7d8790')); inner.rotation.x = -Math.PI / 2; inner.position.set(x, K.top + 0.062, z); root.add(inner);
    for (const [dx, dz, w, d] of [[0, 0.19, 0.34, 0.02], [0, -0.19, 0.34, 0.02], [0.16, 0, 0.02, 0.4], [-0.16, 0, 0.02, 0.4]]) M(new T3.BoxGeometry(w, 0.03, d), chrome, x + dx, K.top + 0.075, z + dz, root, 0);
    if (k === 'sauce') { M(new T3.CylinderGeometry(0.055, 0.062, 0.24, 14), toon('#c42d3c'), x, K.top + 0.18, z, root, 0.008, 0.062); M(new T3.CylinderGeometry(0.057, 0.057, 0.07, 14), toon('#f6f3ee'), x, K.top + 0.17, z, root, 0); M(new T3.ConeGeometry(0.035, 0.07, 10), toon('#c42d3c'), x, K.top + 0.335, z, root, 0.006); M(new T3.CylinderGeometry(0.006, 0.006, 0.04, 6), toon('#c42d3c'), x, K.top + 0.385, z, root, 0); }
    else { const n = k === 'bunT' || k === 'bunB' ? 3 : 4; for (let j = 0; j < n; j++) { const pc = makeIng(T3, toon, k, null, ctx.addOutline); const s = k === 'bunT' || k === 'bunB' ? 0.92 : k === 'cheese' ? 0.95 : 1.0; pc.scale.setScalar(s); pc.position.set(x + (j - (n - 1) / 2) * 0.012, K.top + 0.07 + j * (k === 'bunT' ? 0.035 : k === 'bunB' ? 0.03 : 0.014), z - 0.09 + j * 0.06); pc.rotation.set(-0.22, j * 0.7, 0); root.add(pc); (K.binPiles[k] = K.binPiles[k] || []).push(pc); } }
    K.bins[k] = { x, z }; });
  // fryer (right)
  K.fryer = { x: 1.55, z: KZ - 0.1 }; M(new T3.BoxGeometry(0.8, 0.12, 0.7), chrome, K.fryer.x, K.top + 0.06, K.fryer.z, root, 0.01); { const oil = new T3.Mesh(new T3.PlaneGeometry(0.66, 0.56), new T3.MeshToonMaterial({ color: '#d79a2a', gradientMap: ctx.grad })); oil.rotation.x = -Math.PI / 2; oil.position.set(K.fryer.x, K.top + 0.121, K.fryer.z); root.add(oil); K.oil = oil; }
  K.baskets = [-0.17, 0.17].map(dx => ({ x: K.fryer.x + dx, z: K.fryer.z }));
  K.friesBox = { x: K.fryer.x + 0.2, z: KZ + 0.62 }; M(new T3.BoxGeometry(0.3, 0.2, 0.3), toon('#fde68a'), K.friesBox.x, K.top + 0.1, K.friesBox.z, root, 0.008);
  // drink machine (back counter, right)
  K.drinks = { x: 2.45, z: KZ + 0.2 }; M(new T3.BoxGeometry(0.66, 0.5, 0.36), red, K.drinks.x, K.top + 0.25, K.drinks.z, root, 0.02); M(new T3.BoxGeometry(0.68, 0.1, 0.38), white, K.drinks.x, K.top + 0.52, K.drinks.z, root, 0.01);
  K.taps = ['cola', 'orange', 'shake'].map((k, i) => { const x = K.drinks.x + 0.21 - i * 0.21; M(new T3.BoxGeometry(0.17, 0.15, 0.06), toon(SIDES[k].col), x, K.top + 0.38, K.drinks.z - 0.2, root, 0.005); M(new T3.CylinderGeometry(0.075, 0.075, 0.03, 16), toon(SIDES[k].col), x, K.top + 0.585, K.drinks.z - 0.06, root, 0.008, 0.075); M(new T3.CylinderGeometry(0.02, 0.02, 0.07, 8), chrome, x, K.top + 0.27, K.drinks.z - 0.21, root, 0); return { k, x, z: K.drinks.z - 0.3, y: K.top }; });
  // tray + bag stand + register (front right of the counter)
  K.tray = { x: 0.85, z: KZ + 0.2 }; M(new T3.BoxGeometry(0.6, 0.02, 0.42), red, K.tray.x, K.top + 0.01, K.tray.z, root, 0);
  K.bagStand = { x: -2.55, z: KZ - 0.35 }; M(new T3.BoxGeometry(0.34, 0.06, 0.34), white, K.bagStand.x, K.top + 0.03, K.bagStand.z, root, 0.006); for (let i = 0; i < 3; i++) M(new T3.BoxGeometry(0.26, 0.02, 0.2), toon('#fbfbf7'), K.bagStand.x, K.top + 0.07 + i * 0.02, K.bagStand.z, root, 0);
  K.register = { x: 2.3, z: KZ + 1.62 }; M(new T3.BoxGeometry(0.42, 0.3, 0.34), ink, K.register.x, K.top + 0.15, K.register.z - 0.62, root, 0.01); M(new T3.BoxGeometry(0.36, 0.12, 0.04), toon('#22c55e'), K.register.x, K.top + 0.34, K.register.z - 0.79, root, 0);
  // FRONT COUNTER where customers stand (chrome + red stools) — the customer side faces the camera's look
  M(new T3.BoxGeometry(5.6, 1.05, 0.5), red, 0, 0.525, KZ + 1.42, root, 0.03); M(new T3.BoxGeometry(5.7, 0.06, 0.62), chrome, 0, 1.08, KZ + 1.42, root, 0.015); K.pass = { z: KZ + 1.42, y: 1.11 };
  K.spots = [-1.7, 0, 1.7].map(x => ({ x, z: KZ + 2.4 }));
  // dining room: booths, stools, jukebox, menu board, neon
  for (const x of [-4.6, -2.6]) for (const z of [1.2, 3.4]) { const bc = root.children.length; M(new T3.BoxGeometry(1.4, 0.06, 0.9), white, x, 0.78, z, root, 0.01); M(new T3.CylinderGeometry(0.06, 0.06, 0.75, 8), chrome, x, 0.39, z, root, 0); for (const sz of [-0.75, 0.75]) { M(new T3.BoxGeometry(1.4, 0.5, 0.45), red, x, 0.25, z + sz, root, 0.02); M(new T3.BoxGeometry(1.4, 0.8, 0.14), red, x, 0.8, z + sz * 1.25, root, 0.02); } booths.push(...root.children.slice(bc)); }
  for (let i = 0; i < 6; i++) { const x = -2.4 + i * 0.95; M(new T3.CylinderGeometry(0.06, 0.08, 0.7, 8), chrome, x, 0.35, KZ + 2.95, root, 0); M(new T3.CylinderGeometry(0.24, 0.22, 0.12, 14), red, x, 0.74, KZ + 2.95, root, 0.01); }
  { const j = new T3.Group(); j.position.set(5.2, 0, 2.6); j.rotation.y = -Math.PI / 2; root.add(j); M(new T3.BoxGeometry(0.9, 1.5, 0.55), red, 0, 0.75, 0, j, 0.02); M(new T3.CylinderGeometry(0.45, 0.45, 0.55, 18, 1, false, 0, Math.PI), toon('#ffd23a'), 0, 1.5, 0, j, 0.02).rotation.set(Math.PI / 2, 0, Math.PI / 2); }
  const menuT = CTX(1024, 512, c => { c.fillStyle = '#1f2b27'; c.fillRect(0, 0, 1024, 512); c.fillStyle = '#ffd23a'; c.font = '900 76px Archivo, Arial'; c.fillText("SIZZLE'S BURGERS", 40, 92); c.fillStyle = '#f2f1e8'; c.font = '700 40px Archivo, Arial'; RECIPES.forEach((r, i) => { const x = 40 + (i % 2) * 500, y = 170 + Math.floor(i / 2) * 64; c.fillText(r.name, x, y); c.fillText(r.price + 'g', x + 380, y); }); c.fillStyle = '#ff9a8a'; c.fillText('FRIES 3g · DRINKS 2g · SHAKES 4g', 40, 470); });
  { const mb = new T3.Mesh(new T3.PlaneGeometry(4.4, 2.2), new T3.MeshBasicMaterial({ map: menuT })); mb.position.set(0, 3.0, -D / 2 + 0.07); root.add(mb); cut.push(mb, M(new T3.BoxGeometry(4.6, 2.4, 0.06), wood, 0, 3.0, -D / 2 + 0.01, root, 0.01)); }
  const neonT = CTX(512, 128, c => { c.clearRect(0, 0, 512, 128); c.font = '900 86px Archivo, Arial'; c.textAlign = 'center'; c.textBaseline = 'middle'; c.shadowColor = '#ff3a3a'; c.shadowBlur = 26; c.strokeStyle = '#ff5a5a'; c.lineWidth = 8; c.strokeText('BURGERS', 256, 66); c.fillStyle = '#fff'; c.fillText('BURGERS', 256, 66); });
  { const n = new T3.Mesh(new T3.PlaneGeometry(3.2, 0.8), new T3.MeshBasicMaterial({ map: neonT, transparent: true, depthWrite: false })); n.position.set(-4.4, 3.4, 0.6); n.rotation.y = Math.PI / 2; root.add(n); }
  // pendant lamps over the counter
  K.lamps = []; for (const x of [-1.8, 0, 1.8]) { cut.push(M(new T3.CylinderGeometry(0.01, 0.01, 1.1, 4), ink, x, H - 0.55, KZ + 0.6, root, 0)); const sh = M(new T3.ConeGeometry(0.3, 0.3, 16, 1, true), red, x, H - 1.2, KZ + 0.6, root, 0.01); sh.material.side = T3.DoubleSide; K.lamps.push(sh); cut.push(sh); }
  cut.forEach(m => m.traverse(o => o.castShadow = false));
  return K; }

// ---------------- the stand-alone game ----------------
export async function createBurgerShift({ container, onState = () => {} }) {
  const ST = createStage(container), { touch, CW, CHh, renderer, scene, camera, grad, glowTex, cache, V3, toon, outlineMat, addOutline, M, kit, audio, sun, tone, puff, smokeS } = ST;
  const K = buildDiner({ THREE, M, toon, canvasTex, scene, grad, addOutline });
  const lampGl = K.lamps.map(l => { const s = new THREE.Sprite(new THREE.SpriteMaterial({ map: glowTex, color: 0xffd8a0, transparent: true, depthWrite: false, opacity: 0.55, blending: THREE.AdditiveBlending })); s.position.copy(l.position).add(V3(0, -0.25, 0)); s.scale.setScalar(1.4); scene.add(s); return s; });

  // ---------- cast ----------
  const sizzle = kit.makeFox({ ...CAST.player, look: { ...CAST.player.look, fur: '#c96a2a', furDark: '#8f4515' }, torso: ['#33333d', '#1a1a22', '#0a0a0e'], outfit: 'vest', crest: '8', gear: 'none', mood: 'happy' });
  const SZ = sizzle.userData.P; if (SZ.sword) SZ.sword.visible = false; if (SZ.gun) SZ.gun.visible = false; sizzle.position.set(-2.95, 0, K.z - 0.9); sizzle.rotation.y = 0.5; scene.add(sizzle);
  const ben = kit.makeFox({ ...CAST.player, outfit: 'tee', torso: ['#fbfbf7', '#fbfbf7', '#c42d3c'], crest: '', gear: 'none', mood: 'happy' }); ben.position.set(-1.0, 0, K.z + 3.5); ben.rotation.y = 0.3; const BP = ben.userData.P; if (BP.sword) BP.sword.visible = false; if (BP.gun) BP.gun.visible = false; scene.add(ben);
  const uniform = new THREE.Group(); {
    // the big burger printed on the T-shirt
    const print = canvasTex(256, 256, g => { g.clearRect(0, 0, 256, 256); g.lineJoin = 'round'; g.translate(128, 128); g.scale(1.22, 1.22); g.translate(-128, -138); const X = 128, w = 100, st = () => { g.strokeStyle = '#201e1d'; g.lineWidth = 7; g.stroke(); };
      g.fillStyle = '#e39a42'; g.beginPath(); g.ellipse(X, 112, w, 62, 0, Math.PI, 0); g.closePath(); g.fill(); st(); g.fillStyle = '#fff6d8'; for (const [dx, dy] of [[-44, 84], [-14, 70], [18, 74], [46, 88], [-26, 98], [6, 96], [34, 102]]) { g.beginPath(); g.ellipse(X + dx, dy, 8, 4.5, 0.3, 0, 7); g.fill(); }
      g.fillStyle = '#6fbf3a'; g.beginPath(); g.moveTo(X - w - 8, 112); for (let i = 0; i <= 14; i++) g.lineTo(X - w - 8 + i * (w * 2 + 16) / 14, 120 + (i % 2 ? 12 : 0)); g.lineTo(X + w + 8, 112); g.closePath(); g.fill(); st();
      g.fillStyle = '#ffc93a'; g.beginPath(); g.moveTo(X - w, 128); g.lineTo(X + w, 128); g.lineTo(X + w - 10, 144); g.lineTo(X + 22, 144); g.lineTo(X + 8, 164); g.lineTo(X - 6, 144); g.lineTo(X - w + 10, 144); g.closePath(); g.fill(); st();
      g.fillStyle = '#6e3f22'; g.beginPath(); g.roundRect(X - w - 4, 140, (w + 4) * 2, 34, 17); g.fill(); st();
      g.fillStyle = '#d98f3a'; g.beginPath(); g.roundRect(X - w, 176, w * 2, 34, 14); g.fill(); st();
      g.save(); g.translate(X, 154); g.rotate(-0.08); g.textAlign = 'center'; g.textBaseline = 'middle'; g.lineJoin = 'round';
      g.fillStyle = '#201e1d'; g.beginPath(); g.moveTo(-122, -24); g.lineTo(126, -30); g.lineTo(116, 34); g.lineTo(-130, 30); g.closePath(); g.fill(); g.fillStyle = '#c42d3c'; g.beginPath(); g.moveTo(-114, -18); g.lineTo(118, -24); g.lineTo(110, 26); g.lineTo(-121, 23); g.closePath(); g.fill();
      g.font = 'italic 900 66px Archivo, "Arial Black", Arial, sans-serif'; g.lineWidth = 16; g.strokeStyle = '#201e1d'; g.strokeText('SIZZLE', 5, 6); g.fillStyle = '#201e1d'; g.fillText('SIZZLE', 5, 6); g.strokeText('SIZZLE', 0, 0);
      const gr = g.createLinearGradient(0, -26, 0, 26); gr.addColorStop(0, '#fff3a0'); gr.addColorStop(0.5, '#ffd23a'); gr.addColorStop(0.51, '#ffb020'); gr.addColorStop(1, '#ff8a1a'); g.fillStyle = gr; g.fillText('SIZZLE', 0, 0);
      g.lineWidth = 3; g.strokeStyle = 'rgba(255,255,255,0.9)'; g.strokeText('SIZZLE', -2, -3); g.fillStyle = '#ffffff'; for (const [sx, sy] of [[-108, -26], [104, -30], [116, 22]]) { g.beginPath(); for (let k = 0; k < 8; k++) { const a = k / 8 * Math.PI * 2, r = k % 2 ? 4 : 11; g.lineTo(sx + Math.cos(a) * r, sy + Math.sin(a) * r); } g.closePath(); g.fill(); } g.restore(); });
    uniform.userData.parts = dinerUniform(ST, ben, { print, printY: 1.17 }).parts; }
  // BURGERS crest: the 8 with a hamburger as its bottom loop, on the uniform's red ring
  const burgerCrest = (() => { const c = document.createElement('canvas'); c.width = c.height = 256; const g = c.getContext('2d'), circ = (r, col) => { g.fillStyle = col; g.beginPath(); g.arc(128, 128, r, 0, 7); g.fill(); };
    circ(128, '#c42d3c'); circ(126, '#8f1d2a'); circ(118, '#ffd23a'); circ(106, '#f6f3ee'); circ(90, '#201e1d'); g.strokeStyle = '#f6f3ee'; g.globalAlpha = 0.3; g.lineWidth = 3; g.beginPath(); g.arc(128, 128, 80, 0, 7); g.stroke(); g.globalAlpha = 1;
    g.lineCap = 'round'; g.lineJoin = 'round'; g.save(); g.translate(128, 128); g.scale(1.3, 1.3); g.translate(-128, -148);
    const X = 128, w = 46, rr2 = (x, y, ww, hh, r, col) => { g.fillStyle = col; g.beginPath(); g.roundRect(x - ww, y - hh / 2, ww * 2, hh, r); g.fill(); };
    g.fillStyle = '#e39a42'; g.beginPath(); g.ellipse(X, 140, w, 26, 0, Math.PI, 0); g.closePath(); g.fill(); g.strokeStyle = '#201e1d'; g.lineWidth = 4; g.stroke();
    g.fillStyle = '#fff6d8'; for (const [dx, dy] of [[-22, 128], [-6, 122], [10, 125], [24, 131], [-12, 134], [4, 133]]) { g.beginPath(); g.ellipse(X + dx, dy, 4, 2.4, 0.3, 0, 7); g.fill(); }
    g.fillStyle = '#6fbf3a'; g.beginPath(); for (let i = 0; i <= 12; i++) { const x = X - w - 4 + i * (w * 2 + 8) / 12; g.lineTo(x, 146 + (i % 2 ? 6 : 0)); } g.lineTo(X + w + 4, 142); g.lineTo(X - w - 4, 142); g.fill();
    g.fillStyle = '#ffc93a'; g.beginPath(); g.moveTo(X - w, 150); g.lineTo(X + w, 150); g.lineTo(X + w - 6, 158); g.lineTo(X + 12, 158); g.lineTo(X + 4, 168); g.lineTo(X - 4, 158); g.lineTo(X - w + 6, 158); g.fill();
    rr2(X, 166, w + 2, 18, 9, '#6e3f22'); g.strokeStyle = '#201e1d'; g.lineWidth = 4; g.beginPath(); g.roundRect(X - w - 2, 157, (w + 2) * 2, 18, 9); g.stroke();
    rr2(X, 186, w, 18, 8, '#d98f3a'); g.beginPath(); g.roundRect(X - w, 177, w * 2, 18, 8); g.stroke(); g.restore();
    const tx = new THREE.CanvasTexture(c); tx.colorSpace = THREE.SRGBColorSpace; tx.anisotropy = 4; return new THREE.MeshToonMaterial({ map: tx, gradientMap: grad }); })();
  const crestSlots = []; ben.traverse(m => { if (m.isMesh && Array.isArray(m.material) && m.material[1] && m.material[1].map && m.material[1] !== burgerCrest) crestSlots.push({ m, orig: m.material[1] }); });
  const setUniform = on => { uniform.userData.parts.forEach(p => p.visible = on); crestSlots.forEach(s => { s.m.visible = !on; }); };
  setUniform(true);
  const custFox = CUSTOMERS.map(cu => { const f = kit.makeFox({ ...CAST.player, torso: cu.torso, outfit: cu.outfit || 'vest', crest: '', gear: 'none', mood: 'happy' }); const P = f.userData.P; if (P.sword) P.sword.visible = false; if (P.gun) P.gun.visible = false; f.visible = false; scene.add(f); return f; });

  // ---------- cameras ----------
  const CAM = { pos: V3(), look: V3(), from: null, t: 1, dur: 1 };
  const wideShot = () => { const port = CW() < CHh(), z = K.z, sz = z - 0.9, T = K.top, benBox = [V3(-1.5, 0.05, z + 3.5), V3(-0.5, 0.05, z + 3.5), V3(-1.5, 2.25, z + 3.5), V3(-0.5, 2.25, z + 3.5)], foxes = [V3(-3.4, 0.25, sz), V3(-2.5, 0.25, sz), V3(-3.4, 2.15, sz), V3(-2.5, 2.15, sz), ...benBox, V3(-3.5, T, z + 0.3), V3(-0.9, T, K.pass.z)];
    return port ? shotFor('wideP3', () => [...benBox, V3(-1.0, 2.5, z + 3.5)], 0.1, Math.PI - 0.25, 0.1) : shotFor('wideL4', () => [...benBox, V3(-1.0, 2.5, z + 3.5)], 0.12, Math.PI - 0.3, 0.05); };
  const wideShotOld = () => { const a = CW() / CHh(); return a < 1 ? { pos: V3(0.6, 2.0, 3.4), look: V3(0.6, 1.2, K.z) } : { pos: V3(-0.6, 2.1, 3.0), look: V3(0.6, 1.25, K.z) }; };
  const FOCUS = { cut: [-2.35, 1.6, -2.4, 1.7, 0.72], all: [0.1, null], grill: [-1.15, 2.35, -1.85, 2.5], board: [-0.05, 2.25, -0.05, 2.8], fryer: [1.5, 1.75, 1.55, 2.0], drinks: [2.25, 2.0, 2.2, 2.4], bag: [-0.4, 4.7] };
  function workShot(id = S.focus || 'all') { const port = CW() < CHh(); return shotFor('w:' + id, () => shotPoints(id), port ? 1.2 : 0.92, 0, id === 'all' ? 0.03 : 0.05); }
  function workShotOld(id) { const a = CW() / CHh(), port = a < 1, F = FOCUS[id] || FOCUS.all, wantW = F[1] ? (port ? (F[3] || F[1]) : F[1] * 1.55) : (port ? 5.7 : 7.0), cx = port && F[2] != null ? F[2] : F[0], fov = 50 * Math.PI / 180, hw = Math.tan(fov / 2) * a, dist = clamp(wantW / 2 / hw, F[1] ? 1.6 : 2.4, 13), up = port ? 0.95 : 0.76, back = Math.sqrt(1 - up * up), lz = F[4] != null ? F[4] : F[1] && id !== 'bag' ? 0.2 : port ? 0.7 : 0.4; return { pos: V3(cx, K.top + dist * up, K.z + 0.5 - dist * back + (F[1] && id !== 'bag' ? -0.2 : 0)), look: V3(cx, K.top, K.z + lz) }; }
  function setFocus(id) { if (!FOCUS[id] || S.focus === id) return; S.focus = id; S.userFocusT = performance.now(); }
  const { SAFE, fitShot, shotFor } = cameraFit(ST);
  function shotPoints(id) { const T = K.top, P = (x, z, y = T) => V3(x, y, z), out = [];
    if (id === 'grill') { out.push(P(K.grill.x - 0.7, K.grill.z + 0.55), P(K.patBox.x - 0.32, K.patBox.z - 0.22), P(K.patBox.x + 0.2, K.patBox.z + 0.22, T + 0.18), ...K.grillSlots.map(s => P(s.x, s.z, T + 0.05)), P(K.grill.x - 0.65, K.grill.z - 0.45), P(K.grill.x + 0.65, K.grill.z + 0.45), P(K.board.x - 0.5, K.board.z), P(K.board.x + 0.3, K.board.z - 0.3), P(K.board.x + 0.3, K.board.z + 0.3)); }
    else if (id === 'board') { for (const b of Object.values(K.bins)) out.push(P(b.x - 0.18, b.z - 0.2, T + 0.1), P(b.x + 0.18, b.z + 0.2)); out.push(P(K.board.x - 0.5, K.board.z - 0.36), P(K.board.x + 0.5, K.board.z + 0.36)); }
    else if (id === 'fryer') { out.push(...K.baskets.map(b => P(b.x, b.z - 0.25, T + 0.18)), P(K.fryer.x + 0.4, K.fryer.z + 0.35), P(K.friesBox.x - 0.16, K.friesBox.z - 0.16), P(K.friesBox.x + 0.16, K.friesBox.z + 0.16, T + 0.22), P(K.tray.x - 0.3, K.tray.z)); }
    else if (id === 'drinks') { for (const tp of K.taps) out.push(P(tp.x, tp.z, T + 0.25), P(tp.x, K.drinks.z, T + 0.62)); out.push(P(K.drinks.x - 0.6, K.drinks.z + 0.3), P(K.drinks.x + 0.55, K.drinks.z - 0.6), P(K.drinks.x - 0.6, K.drinks.z - 0.6), P(K.drinks.x + 0.55, K.drinks.z + 0.3)); }
    else if (id === 'cut') { out.push(P(K.chop.x - 0.32, K.chop.z - 0.24), P(K.chop.x + 0.32, K.chop.z + 0.24), P(K.chop.x, K.chop.z, T + 0.28)); }
    else if (id === 'bag') { out.push(P(K.bagStand.x - 0.2, K.bagStand.z - 0.2), P(K.bagStand.x + 0.2, K.bagStand.z + 0.2, T + 0.3), ...K.spots.flatMap(s => [P(s.x - 0.45, s.z, 2.2), P(s.x + 0.45, s.z, 2.2), P(s.x - 0.45, s.z, 0.9), P(s.x + 0.45, s.z, 0.9)])); }
    else { out.push(P(-2.9, K.z - 0.5), P(2.9, K.z - 0.5), P(-2.9, K.chop.z + 0.3), P(2.9, K.register.z), ...K.spots.map(s => P(s.x, s.z, 1.3))); }
    return out; }
  function glideTo(shot, dur = 1.6) { CAM.from = { pos: camera.position.clone(), look: CAM.look.clone() }; CAM.to = shot; CAM.t = 0; CAM.dur = dur; }
  { const w = wideShotOld(); camera.position.copy(w.pos); CAM.look.copy(w.look); camera.lookAt(CAM.look); }

  // ---------- game state ----------
  const S = { focus: 'all', phase: 'intro', day: Math.max(1, save.stat(SAVE.day, 1)), t: 0, gold: 0, earned: 0, tips: 0, stars: 0, served: 0, lost: 0, starList: [], flash: null, flashT: 0, say: '', sayT: 0, pay: null, next: 3, done: null, combo: 0 };
  const upg = id => !!save.stat(SAVE.upg + id, 0);
  const grill = [], fryer = [null, null], cups = [], orders = []; let board = [], bag = null, drag = null, idSeq = 1;
  const flash = (txt, col = '#ffd23a', t = 1.4) => { S.flash = { txt, col }; S.flashT = t; }, say = (s, t = 3.5) => { S.say = s; S.sayT = t; };
  const avail = () => RECIPES.filter(r => r.day <= S.day), sidesAvail = () => Object.entries(SIDES).filter(([, v]) => v.day <= S.day).map(([k]) => k);

  // meshes for pieces
  function pieceMesh(k, state) { const gp = makeIng(THREE, toon, k, state, addOutline); return gp; }
  function pieceMeshOld(k, state) { const I = ING[k]; let geo; if (I.sq) geo = new THREE.BoxGeometry(I.r * 1.9, I.h, I.r * 1.9); else if (I.dome) geo = new THREE.SphereGeometry(I.r, 18, 10, 0, Math.PI * 2, 0, Math.PI / 2); else if (I.ring) geo = new THREE.TorusGeometry(I.r * 0.8, 0.025, 6, 18); else geo = new THREE.CylinderGeometry(I.r, I.r * (I.wavy ? 1.08 : 1), I.h, 18);
    const col = k === 'patty' ? (DN_COL[state] || (state === 'raw' ? '#e57373' : I.col)) : I.col; const m = new THREE.Mesh(geo, toon(col)); if (I.ring) m.rotation.x = Math.PI / 2; if (I.dome) m.scale.y = 0.55; m.castShadow = true; addOutline(m, 0.012, I.ring ? null : I.r); if (k === 'bunT') for (let i = 0; i < 7; i++) { const s = new THREE.Mesh(new THREE.SphereGeometry(0.012, 5, 4), toon('#fff6d8')); const a = rr(0, 6.28), r = rr(0.02, 0.11); s.position.set(Math.cos(a) * r, Math.sqrt(Math.max(0, I.r * I.r - r * r)) * 0.98, Math.sin(a) * r); m.add(s); } return m; }
  const boardGroup = new THREE.Group(); boardGroup.position.set(K.board.x, K.top + 0.04, K.board.z); scene.add(boardGroup);
  function rebuildBoard() { while (boardGroup.children.length) boardGroup.remove(boardGroup.children[0]); let y = 0; for (const p of board) { const I = ING[p.k], m = pieceMesh(p.k, p.dn || p.st); m.position.y = y + (p.k === 'bunB' || p.k === 'bunT' ? 0 : I.h / 2); m.rotation.y = p.rot || 0; boardGroup.add(m); y += I.h * (p.k === 'sauce' ? 0.5 : 1); } }
  const trayGroup = new THREE.Group(); trayGroup.position.set(K.tray.x, K.top + 0.03, K.tray.z); scene.add(trayGroup);
  const tray = { burgers: [], fries: 0, drinks: [] };
  function rebuildTray() { while (trayGroup.children.length) trayGroup.remove(trayGroup.children[0]); tray.burgers.forEach((b, i) => { const w = new THREE.Mesh(new THREE.CylinderGeometry(0.15, 0.16, 0.16, 16), toon('#fbe7b5')); w.position.set(-0.17 + i * 0.2, 0.08, -0.05); addOutline(w, 0.01, 0.16); trayGroup.add(w); const lb = new THREE.Mesh(new THREE.CylinderGeometry(0.152, 0.152, 0.03, 16), toon('#c42d3c')); lb.position.copy(w.position).setY(0.1); trayGroup.add(lb); });
    for (let i = 0; i < tray.fries; i++) { const f = friesCarton(); f.position.set(0.12 + i * 0.12, 0, 0.1); trayGroup.add(f); }
    tray.drinks.forEach((k, i) => { const c = cupMesh(k, 1); c.position.set(0.22, 0, -0.12 + i * 0.12); trayGroup.add(c); }); }
  function friesCarton() { const g = new THREE.Group(); const b = new THREE.Mesh(new THREE.CylinderGeometry(0.06, 0.045, 0.12, 4), toon('#c42d3c')); b.rotation.y = Math.PI / 4; b.position.y = 0.06; addOutline(b, 0.006); g.add(b); for (let i = 0; i < 7; i++) { const f = new THREE.Mesh(new THREE.BoxGeometry(0.014, 0.1, 0.014), toon('#f7c948')); f.position.set(rr(-0.03, 0.03), 0.14, rr(-0.03, 0.03)); f.rotation.z = rr(-0.25, 0.25); g.add(f); } return g; }
  function cupMesh(k, fill) { const g = new THREE.Group(); const c = new THREE.Mesh(new THREE.CylinderGeometry(0.055, 0.042, 0.17, 14), toon('#f6f3ee')); c.position.y = 0.085; addOutline(c, 0.006, 0.055); g.add(c); const s = new THREE.Mesh(new THREE.CylinderGeometry(0.056, 0.056, 0.03, 14), toon(SIDES[k].col)); s.position.y = 0.06 + 0.1 * fill; g.add(s); const lid = new THREE.Mesh(new THREE.CylinderGeometry(0.058, 0.058, 0.012, 14), toon('#c42d3c')); lid.position.y = 0.175; lid.visible = fill >= 1; g.add(lid); const st = new THREE.Mesh(new THREE.CylinderGeometry(0.006, 0.006, 0.12, 5), toon('#ffd23a')); st.position.set(0.015, 0.23, 0); st.rotation.z = 0.2; st.visible = fill >= 1; g.add(st); return g; }
  const bagMesh = (() => { const g = new THREE.Group(), b = new THREE.Mesh(new THREE.BoxGeometry(0.26, 0.3, 0.18), toon('#fbfbf7')); b.position.y = 0.15; addOutline(b, 0.008); g.add(b); const band = new THREE.Mesh(new THREE.BoxGeometry(0.262, 0.06, 0.182), toon('#c42d3c')); band.position.y = 0.2; g.add(band); g.visible = false; scene.add(g); return g; })();

  // grill + fryer + cups visuals
  const ringMat = new THREE.MeshBasicMaterial({ color: 0x22c55e, transparent: true, opacity: 0.9, depthWrite: false }), ringGeo = new THREE.RingGeometry(0.15, 0.19, 24).rotateX(-Math.PI / 2);
  function addPatty(slot) { const m = pieceMesh('patty', 'raw'); m.position.set(K.grillSlots[slot].x, K.top + 0.07, K.grillSlots[slot].z); scene.add(m); const ring = new THREE.Mesh(ringGeo, ringMat.clone()); ring.position.copy(m.position).setY(K.top + 0.05); ring.visible = true; scene.add(ring); const gc = document.createElement('canvas'); gc.width = 256; gc.height = 44; const gt = new THREE.CanvasTexture(gc); gt.colorSpace = THREE.SRGBColorSpace; const gauge = new THREE.Sprite(new THREE.SpriteMaterial({ map: gt, depthTest: false, transparent: true })); gauge.renderOrder = 25; gauge.scale.set(0.42, 0.072, 1); gauge.position.copy(m.position).add(V3(0, 0.26, 0)); scene.add(gauge); const g = { slot, t: 0, d: 0, st: 'raw', m, ring, gauge, gc, gt, press: false, flipT: 0, flipped: false, want: null, lastD: -1 }; grill[slot] = g; gaugeTex(g); audio.burst && audio.burst(0.25, 2400, 0.08); }
  const dropPatty = g => { scene.remove(g.m); scene.remove(g.ring); scene.remove(g.gauge); grill[g.slot] = null; };
  function setPattyState(p, st) { if (p.st === st) return; p.st = st; p.m.material = toon(st === 'raw' ? '#e57373' : st === 'burnt' ? '#2a1a14' : '#6e3f22'); if (st === 'done') { p.ring.visible = true; tone(1320, 0.08, 0.04); } if (st === 'burnt') { p.ring.visible = true; p.ring.material.color.setHex(0xec3013); tone(220, 0.25, 0.04, 'sawtooth'); } }
  // DONENESS: hold the patty to press + grill it (fast); left alone it cooks slowly. Quick tap = FLIP. Orders ask RARE / MEDIUM / WELL DONE.
  const DN = { rare: [0.35, 0.55], medium: [0.55, 0.78], well: [0.78, 1.0] }, DN_NAME = { raw: 'RAW', rare: 'RARE', medium: 'MEDIUM', well: 'WELL DONE', burnt: 'BURNT' }, BURN_D = 1.08;
  const dnOf = d => d < DN.rare[0] ? 'raw' : d < DN.medium[0] ? 'rare' : d < DN.well[0] ? 'medium' : d < BURN_D ? 'well' : 'burnt';
  const DN_COL = { raw: '#e57373', rare: '#c4523e', medium: '#8a4a26', well: '#5a3018', burnt: '#2a1a14' }, ZONE_COL = { raw: 0x9ca3af, rare: 0xe57373, medium: 0xe6b45a, well: 0x8a5a32, burnt: 0xec3013 };
  const bid = x => x.split('|')[0], bdn = x => x.split('|')[1];
  function gaugeTex(g) { const c = g.gc, x = c.getContext('2d'), W = c.width, H = c.height, sx = v => 6 + v / 1.2 * (W - 12); x.clearRect(0, 0, W, H); x.fillStyle = '#201e1d'; x.fillRect(0, 8, W, H - 16);
    [['raw', 0, DN.rare[0], '#9ca3af'], ['rare', DN.rare[0], DN.rare[1], '#e57373'], ['medium', DN.medium[0], DN.medium[1], '#e6b45a'], ['well', DN.well[0], BURN_D, '#8a5a32'], ['burnt', BURN_D, 1.2, '#ec3013']].forEach(([k, a, b, col]) => { x.fillStyle = col; x.fillRect(sx(a), 13, sx(b) - sx(a) - 2, H - 26); if (g.want === k) { x.strokeStyle = '#ffd23a'; x.lineWidth = 5; x.strokeRect(sx(a) - 1, 10, sx(b) - sx(a), H - 20); } });
    const m = sx(Math.min(1.2, g.d)); x.fillStyle = '#ffffff'; x.beginPath(); x.moveTo(m - 9, 0); x.lineTo(m + 9, 0); x.lineTo(m, 12); x.closePath(); x.fill(); x.fillRect(m - 2, 8, 4, H - 16); g.gt.needsUpdate = true; }
  const spat = (() => { const s = new THREE.Group(); const blade = new THREE.Mesh(new THREE.BoxGeometry(0.26, 0.012, 0.22), toon('#d7dde3')); addOutline(blade, 0.006); s.add(blade); const neck = new THREE.Mesh(new THREE.BoxGeometry(0.03, 0.012, 0.16), toon('#9aa3ab')); neck.position.set(0, 0.04, -0.17); neck.rotation.x = -0.5; s.add(neck); const h = new THREE.Mesh(new THREE.CylinderGeometry(0.022, 0.022, 0.22, 8), toon('#6b4a2c')); h.rotation.x = Math.PI / 2 - 0.5; h.position.set(0, 0.12, -0.32); addOutline(h, 0.006, 0.022); s.add(h); s.visible = false; scene.add(s); return s; })();
  const basketMesh = () => { const g = new THREE.Group(); const b = new THREE.Mesh(new THREE.BoxGeometry(0.26, 0.12, 0.42), toon('#9aa3ab')); b.position.y = 0.06; addOutline(b, 0.006); g.add(b); const h = new THREE.Mesh(new THREE.BoxGeometry(0.03, 0.03, 0.3), toon('#201e1d')); h.position.set(0, 0.14, 0.32); g.add(h); const ff = new THREE.Group(); for (let i = 0; i < 12; i++) { const f = new THREE.Mesh(new THREE.BoxGeometry(0.016, 0.016, 0.12), toon('#f2e3a8')); f.position.set(rr(-0.09, 0.09), 0.1, rr(-0.14, 0.14)); f.rotation.y = rr(-1, 1); ff.add(f); } g.add(ff); g.userData.ff = ff; return g; };
  function addFries(i) { const g = basketMesh(); g.position.set(K.baskets[i].x, K.top + 0.02, K.baskets[i].z); scene.add(g); fryer[i] = { t: 0, st: 'cook', g }; audio.burst && audio.burst(0.4, 1800, 0.1); }
  const FRY_DONE = 6;
  function addCup(tap) { const g = cupMesh(tap.k, 0); g.position.set(tap.x, tap.y, tap.z); scene.add(g); const st = new THREE.Mesh(new THREE.CylinderGeometry(0.016, 0.02, 1, 10), new THREE.MeshBasicMaterial({ color: new THREE.Color(SIDES[tap.k].col).offsetHSL(0, 0.1, 0.05) })); const so = new THREE.Mesh(st.geometry, new THREE.MeshBasicMaterial({ color: 0x201e1d, side: THREE.BackSide })); so.scale.set(1.35, 1, 1.35); st.add(so); scene.add(st); cups.push({ k: tap.k, t: 0, fill: 0, g, tap, stream: st }); S.pourShot = { tap, t: 0 }; tone(520, 0.4, 0.03, 'sine'); }

  // ---------- customers + orders ----------
  function newOrder() { const free = K.spots.findIndex((_, i) => !orders.some(o => o.spot === i)); if (free < 0) return; const used = orders.map(o => o.ci), pool = CUSTOMERS.map((_, i) => i).filter(i => !used.includes(i)), ci = pick(pool);
    const rec = avail(), sides = sidesAvail(), d = S.day, nB = d >= 4 && Math.random() < 0.25 ? 2 : 1, burgers = Array.from({ length: nB }, () => pick(rec.slice(-Math.min(rec.length, 3 + d)))), fries = sides.includes('fries') && Math.random() < 0.5 ? 1 : 0, drinkList = sides.filter(k => k !== 'fries'), drinks = Math.random() < 0.6 ? [pick(drinkList)] : [];
    const dns = burgers.map(() => d <= 1 ? (Math.random() < 0.7 ? 'medium' : 'well') : pick(['rare', 'medium', 'medium', 'well'])); const total = burgers.reduce((s, b) => s + b.price, 0) + fries * SIDES.fries.price + drinks.reduce((s, k) => s + SIDES[k].price, 0), patMax = (52 - Math.min(16, (d - 1) * 4)) * (upg('jukebox') ? 1.2 : 1);
    const f = custFox[ci]; f.visible = true; f.position.set(K.spots[free].x + 6, 0, K.spots[free].z + 1.6); f.rotation.y = Math.PI; f.userData.mood = 'happy';
    orders.push({ id: idSeq++, ci, spot: free, burgers, dns, fries, drinks, total, pat: patMax, patMax, st: 'walk', f, line: pick(LINES.order) }); }
  function orderNeeds(o) { return { burgers: o.burgers.map(b => b.id), fries: o.fries, drinks: o.drinks.slice() }; }
  function burgerMatches(stack) { // what's on the board between the buns, as a recipe id (or null)
    const mid = stack.filter(p => p.k !== 'bunB' && p.k !== 'bunT'); if (mid.some(p => p.k === 'patty' && (!p.dn || p.dn === 'raw' || p.dn === 'burnt'))) return null; const keys = mid.map(p => p.k);
    const eq = (a, b) => { const sa = [...a].sort().join(','), sb = [...b].sort().join(','); return sa === sb; }; const r = RECIPES.find(r => eq(r.stack, keys)); return r ? r.id : 'custom'; }
  function grade(o, bagged) { // how well does the bag match the order (0..1)
    let want = 0, got = 0; o.dnMiss = 0; const bb = bagged.burgers.slice(); o.burgers.forEach((b, j) => { want++; let i = bb.indexOf(b.id + '|' + o.dns[j]); if (i < 0) { i = bb.findIndex(x => bid(x) === b.id); if (i >= 0) o.dnMiss++; } if (i >= 0) { got++; bb.splice(i, 1); } });
    want += o.fries; got += Math.min(o.fries, bagged.fries); const dd = bagged.drinks.slice(); for (const k of o.drinks) { want++; const i = dd.indexOf(k); if (i >= 0) { got++; dd.splice(i, 1); } }
    return want ? got / want : 0; }
  function serve(o) { const q = grade(o, bag), pq = o.pat / o.patMax, stars = q >= 1 ? (o.dnMiss ? 2 : pq > 0.55 ? 3 : 2) : q >= 0.5 ? 1 : 0;
    if (stars === 0) { startReact(o, 'insulted', 0, null); bagMesh.visible = false; return false; }
    o.st = 'pay'; o.stars = stars; const level = stars === 3 ? (pq > 0.75 ? 'thrilled' : 'happy') : stars === 2 ? 'neutral' : 'unhappy'; o.tip = level === 'thrilled' ? Math.ceil(o.total * 0.4) + 3 : level === 'happy' ? Math.ceil(o.total * 0.25) + 1 : level === 'neutral' ? 1 : 0; bag = null; bagMesh.visible = false;
    const bill = [5, 10, 20, 50].find(b => b > o.total + (Math.random() < 0.3 ? 4 : 0)) || 50; startReact(o, level, stars, { oid: o.id, total: o.total, paid: bill, owed: bill - o.total, given: 0 }); return true; }
  const REACT = { thrilled: { word: 'THRILLED!', col: '#22c55e', mood: 'excited', lines: ['This is the best burger in all of Meru!', 'I am telling EVERYONE about this place!', 'Wow. Just wow.'] }, happy: { word: 'HAPPY', col: '#7dd3fc', mood: 'happy', lines: ['Delicious, thank you!', 'Just how I like it.', 'Great service!'] }, neutral: { word: 'NEUTRAL', col: '#e6b45a', mood: 'neutral', lines: ['It is fine. Took a while.', 'Okay. Thanks.', 'Hm. Not bad.'] }, unhappy: { word: 'UNHAPPY', col: '#ff9a8a', mood: 'sad', lines: ['Half my order is missing...', 'This is not what I asked for.', 'I waited for this?'] }, insulted: { word: 'INSULTED!', col: '#ec3013', mood: 'angry', lines: ['That is NOT my order!', 'Do I look like I ordered that?', 'Are you even listening?'] } };
  function startReact(o, level, stars, pay) { const R = REACT[level]; o.f.userData.mood = R.mood; o.f.userData.lineMood = R.mood; if (level === 'thrilled') o.f.userData.hop = 1; S.react = { o, level, stars, pay, t: 0, word: R.word, col: R.col, line: pick(R.lines), who: CUSTOMERS[o.ci].name, tip: o.tip || 0 }; S.focus = 'all';
    tone(level === 'insulted' ? 180 : level === 'unhappy' ? 300 : 880, 0.18, 0.05, level === 'insulted' || level === 'unhappy' ? 'sawtooth' : 'triangle'); if (level === 'thrilled') { setTimeout(() => tone(1175, 0.1, 0.05), 110); setTimeout(() => tone(1568, 0.16, 0.05), 220); for (let i = 0; i < 10; i++) puff(o.f.position.x + rr(-0.4, 0.4), rr(1.4, 2.2), o.f.position.z + rr(-0.2, 0.2), 0xffd23a, 1); } }
  function reactDone() { const r = S.react; S.react = null; r.o.f.userData.lineMood = null; if (r.pay) { S.pay = r.pay; payProps(r.pay); S.payOut = null; tone(880, 0.1, 0.05); audio.burst && audio.burst(0.2, 3200, 0.08); } else { bagMesh.visible = true; bagMesh.position.set(K.bagStand.x, K.top + 0.06, K.bagStand.z); r.o.pat = Math.max(4, r.o.pat - 6); } }
  // ---------- REGISTER close-up: drawer, the customer's bill, coins you count out, a live display ----------
  const REG = V3(K.register.x, K.top, K.register.z - 0.62), RG = registerKit(ST, REG, { open: "SIZZLE'S  ·  OPEN" }), { DISH, regDisp, drawer, regDraw, billTex, coinsOut, payProps, coinDrop } = RG;
  function giveCoin(v) { const P = S.pay; if (!P) return; P.given += v; coinDrop(v); regDraw(P); tone(1400 + v * 40, 0.05, 0.03); if (P.given === P.owed) payDone(); else if (P.given > P.owed) { flash('TOO MUCH · TRY AGAIN', '#ec3013'); P.given = 0; tone(220, 0.2, 0.04, 'sawtooth'); coinsOut.forEach(c => scene.remove(c)); coinsOut.length = 0; regDraw(P); } }
  function payDone() { const P = S.pay, o = orders.find(q => q.id === P.oid); S.pay = null; S.payOut = { t: 0, o }; regDraw({ ...P, given: P.owed }); if (!o) return; const pts = o.total + o.tip; S.earned += o.total; S.tips += o.tip; S.served++; S.starList.push(o.stars); S.combo = o.stars === 3 ? S.combo + 1 : 0;
    flash((o.stars === 3 ? '★★★' : o.stars === 2 ? '★★' : '★') + ' +' + pts + 'g' + (o.tip ? ' (TIP ' + o.tip + ')' : ''), '#ffd23a', 1.8); tone(1046, 0.1, 0.05); setTimeout(() => tone(1568, 0.12, 0.05), 90); o.st = 'leave'; o.t = 0; }

  // ---------- input: tap stations, drag pieces ----------
  const ray = new THREE.Raycaster(), ndc = new THREE.Vector2(), plane = new THREE.Plane(new THREE.Vector3(0, 1, 0), -(K.top + 0.15)), hit = V3();
  const scr = p => { const v = p.clone().project(camera); return { x: (v.x + 1) / 2 * CW(), y: (1 - v.y) / 2 * CHh() }; };
  const TARGETS = () => { const t = [];
    for (const [k, b] of Object.entries(K.bins)) t.push({ kind: 'bin', k, p: V3(b.x, K.top + 0.1, b.z), r: 40 });
    t.push({ kind: 'cutBoard', p: V3(K.chop.x, K.top + 0.08, K.chop.z), r: 80 });
    t.push({ kind: 'patBox', p: V3(K.patBox.x, K.top + 0.12, K.patBox.z), r: 40 });
    grill.forEach((g, i) => g && t.push({ kind: 'patty', i, p: g.m.position.clone(), r: 34 }));
    t.push({ kind: 'friesBox', p: V3(K.friesBox.x, K.top + 0.15, K.friesBox.z), r: 40 });
    fryer.forEach((f, i) => f && t.push({ kind: 'basket', i, p: f.g.position.clone().setY(K.top + 0.12), r: 34 }));
    for (const tap of K.taps) if (SIDES[tap.k].day <= S.day) t.push({ kind: 'tap', tap, p: V3(tap.x, K.top + 0.5, tap.z + 0.15), r: 40 });
    cups.forEach((c, i) => t.push({ kind: 'cup', i, p: c.g.position.clone().setY(c.g.position.y + 0.1), r: 30 }));
    t.push({ kind: 'board', p: V3(K.board.x, K.top + 0.06, K.board.z), r: 70 });
    t.push({ kind: 'bagStand', p: V3(K.bagStand.x, K.top + 0.12, K.bagStand.z), r: 42 }); if (tray.burgers.length) t.push({ kind: 'tray', p: V3(K.tray.x, K.top + 0.1, K.tray.z), r: 44 });
    if (bag) t.push({ kind: 'bag', p: bagMesh.position.clone().setY(K.top + 0.15), r: 44 });
    orders.forEach(o => o.st === 'wait' && t.push({ kind: 'cust', o, p: V3(o.f.position.x, 1.45, o.f.position.z), r: 70 })); return t; };
  const scale = () => Math.min(1.6, Math.max(0.85, Math.min(CW(), CHh()) / 420));
  function pickAt(x, y, kinds) { let best = null, bd = 1e9; for (const t of TARGETS()) { if (kinds && !kinds.includes(t.kind)) continue; const s = scr(t.p), d = Math.hypot(s.x - x, s.y - y); if (d < t.r * scale() && d < bd) { bd = d; best = t; } } return best; }
  const local = e => { const r = renderer.domElement.getBoundingClientRect(); return { x: e.clientX - r.left, y: e.clientY - r.top }; };
  function dragStart(kind, mesh, data) { drag = { kind, mesh, data }; scene.add(mesh); }
  const STATION = { cutBoard: 'cut', tray: 'fryer', bin: 'board', board: 'board', patBox: 'grill', patty: 'grill', friesBox: 'fryer', basket: 'fryer', tap: 'drinks', cup: 'drinks', bagStand: 'bag', bag: 'bag', cust: 'bag' };
  function onDown(e) { audio.init && audio.init(); S.lastInput = performance.now(); if (S.pourShot && !DM.on) S.pourShot = null; if (S.phase !== 'shift' || S.pay || DM.on || S.reveal || S.react) return; const { x, y } = local(e); const t = pickAt(x, y); if (!t && !(S.focus === 'cut' && S.cut)) return; e.preventDefault(); if (S.focus === 'cut' && S.cut) { S.stroke = { x, y }; strokeMove(x, y); return; }
    if (S.focus === 'all' && t.kind !== 'bin' && t.kind !== 'patty' && t.kind !== 'bag') setFocus(STATION[t.kind]);
    if (t.kind === 'cutBoard') { if (!S.cut) flash('NOTHING TO CUT RIGHT NOW', '#ffffff', 1); else { setFocus('cut'); S.stroke = { x, y }; } }
    else if (t.kind === 'bin') { if (VEG[t.k] && stock[t.k] <= 0) { flash('OUT OF ' + VEG[t.k] + ' · CUT MORE', '#ec3013', 1.4); needCut(t.k); setFocus('cut'); return; } if (VEG[t.k]) setStock(t.k, stock[t.k] - 1); const m = pieceMesh(t.k); dragStart('ing', m, { k: t.k, fromBin: true }); }
    else if (t.kind === 'patty') { const g = grill[t.i]; if (g.st === 'burnt') { dropPatty(g); flash('BURNT · IN THE BIN', '#ec3013', 1.2); tone(160, 0.2, 0.04); return; } if (g.flipT > 0) return; g.press = true; S.press = { g, x0: x, y0: y, t0: performance.now() }; return; }
    else if (t.kind === 'patBox') { const n = upg('grill4') ? 4 : 3, slot = Array.from({ length: n }, (_, i) => i).find(i => !grill[i]); if (slot == null) flash('GRILL IS FULL', '#ffffff', 0.9); else addPatty(slot); }
    else if (t.kind === 'friesBox') { const i = fryer.findIndex(f => !f); if (i < 0) flash('FRYER IS FULL', '#ffffff', 0.9); else if (!sidesAvail().includes('fries')) flash('FRIES FROM DAY 2', '#ffffff', 1); else addFries(i); }
    else if (t.kind === 'basket') { const f = fryer[t.i]; if (f.st === 'cook') { flash('NOT GOLDEN YET', '#ffffff', 0.9); return; } scene.remove(f.g); fryer[t.i] = null; if (f.st === 'burnt') { flash('BURNT FRIES · BIN', '#ec3013', 1.2); return; } tray.fries++; rebuildTray(); tone(990, 0.08, 0.04); }
    else if (t.kind === 'tap') { if (cups.some(c => c.tap === t.tap)) return; addCup(t.tap); }
    else if (t.kind === 'cup') { const c = cups[t.i]; if (c.fill < 1) { flash('STILL POURING', '#ffffff', 0.9); return; } scene.remove(c.g); if (c.stream) scene.remove(c.stream); cups.splice(t.i, 1); tray.drinks.push(c.k); rebuildTray(); tone(990, 0.08, 0.04); }
    else if (t.kind === 'board') { if (board.length) { board.pop(); rebuildBoard(); tone(400, 0.06, 0.03); } }
    else if (t.kind === 'bagStand') { if (bag) return; if (!tray.burgers.length && !tray.fries && !tray.drinks.length) { flash('TRAY IS EMPTY', '#ffffff', 0.9); return; } bag = { burgers: tray.burgers.slice(), fries: tray.fries, drinks: tray.drinks.slice() }; tray.burgers = []; tray.fries = 0; tray.drinks = []; rebuildTray(); bagMesh.visible = true; bagMesh.position.set(K.bagStand.x, K.top + 0.06, K.bagStand.z); tone(700, 0.08, 0.04); audio.burst && audio.burst(0.15, 3000, 0.08); }
    else if (t.kind === 'tray') { const b = tray.burgers.pop(); rebuildTray(); flash(RECIPES.find(r => r.id === bid(b)).name + ' BINNED', '#ec3013', 1.1); tone(160, 0.2, 0.04); }
    else if (t.kind === 'bag') { dragStart('bag', bagMesh, {}); }
    else if (t.kind === 'cust') { if (bag) { const o = t.o; serve(o); } else flash(CUSTOMERS[t.o.ci].name + ' · DRAG THE BAG HERE', '#ffffff', 1.2); }
    if (drag) onMove(e); }
  function onMove(e) { if (S.stroke) { const { x, y } = local(e); strokeMove(x, y); return; }
    if (S.press) { const { x, y } = local(e), P = S.press; if (Math.hypot(x - P.x0, y - P.y0) > 18) { const g = P.g; g.press = false; S.press = null; if (g.st === 'raw') { flash('STILL RAW · HOLD IT TO GRILL', '#ffffff', 1.1); return; } dropPatty(g); dragStart('ing', g.m, { k: 'patty', dn: g.st }); } else return; }
    if (!drag) return; const { x, y } = local(e); ndc.set(x / CW() * 2 - 1, -(y / CHh()) * 2 + 1); ray.setFromCamera(ndc, camera); if (ray.ray.intersectPlane(plane, hit)) drag.mesh.position.set(hit.x, K.top + 0.18, hit.z); }
  function onUp(e) { if (S.stroke) { S.stroke = null; knife.visible = false; return; }
    if (S.press) { const P = S.press, g = P.g; g.press = false; S.press = null; if (performance.now() - P.t0 < 220 && g.flipT === 0) { g.flipT = 0.001; if (!g.flipped && g.d > 0.3) flash('FLIP!', '#ffd23a', 0.7); } return; }
    if (!drag) return; const { x, y } = local(e), d = drag; drag = null;
    if (d.kind === 'ing') { const t = pickAt(x, y, ['board']); scene.remove(d.mesh); if (t) addToBoard(d.data); else if (d.data.fromBin && VEG[d.data.k]) setStock(d.data.k, stock[d.data.k] + 1); else if (d.data.k === 'patty') { flash('PATTY DROPPED · BIN', '#ec3013', 1); } }
    else if (d.kind === 'bag') { const t = pickAt(x, y, ['cust']); if (t) serve(t.o); if (bag) { bagMesh.position.set(K.bagStand.x, K.top + 0.06, K.bagStand.z); } } }
  function addToBoard({ k, st, dn }) { if (!board.length && k !== 'bunB') { flash('BOTTOM BUN FIRST', '#ffffff', 1); return; } if (board.length && board[board.length - 1].k === 'bunT') return; if (k === 'bunB' && board.length) { flash('ONE BOTTOM BUN', '#ffffff', 0.9); return; }
    board.push({ k, st, dn, rot: rr(-0.3, 0.3) }); rebuildBoard(); tone(600 + board.length * 60, 0.05, 0.03); puff(K.board.x, K.top + 0.2, K.board.z, 0xfff3d0, 1);
    if (k === 'bunT') { const id0 = burgerMatches(board), pdn = (board.find(p => p.k === 'patty') || {}).dn, id = id0 && id0 !== 'custom' ? id0 + '|' + pdn : id0; if (!id0 || id0 === 'custom') { flash(id0 ? 'NOT ON THE MENU · TAP THE BOARD TO UNDO' : 'RAW PATTY!', '#ec3013', 1.6); return; } S.reveal = { id, t: 0, ...revealInfo(id) }; S.flash = null; tone(1175, 0.1, 0.05); setTimeout(() => tone(1568, 0.14, 0.05), 120); for (let i = 0; i < 6; i++) puff(K.board.x + rr(-0.2, 0.2), K.top + rr(0.1, 0.35), K.board.z + rr(-0.15, 0.15), 0xffe7a0, 1); } }
  // which order wants this burger, and would it complete that order?
  function revealInfo(full) { const id = bid(full), dn = bdn(full), want = orders.filter(o => o.st === 'wait').sort((a, b) => a.pat - b.pat); for (const o of want) { const still = o.burgers.map((b, i) => ({ id: b.id, dn: o.dns[i] })); tray.burgers.forEach(x => { const i = still.findIndex(s => s.id === bid(x)); if (i >= 0) still.splice(i, 1); }); const hitI = still.findIndex(s => s.id === id && s.dn === dn) >= 0 ? still.findIndex(s => s.id === id && s.dn === dn) : still.findIndex(s => s.id === id); if (hitI >= 0) { const wantDn = still[hitI].dn; still.splice(hitI, 1); const sides = tray.fries >= o.fries && o.drinks.every(k => tray.drinks.filter(d => d === k).length >= o.drinks.filter(d => d === k).length); return { oid: o.id, who: CUSTOMERS[o.ci].name, dn, wantDn, dnOk: wantDn === dn, completes: !still.length && sides, missing: [...still.map(b => RECIPES.find(r => r.id === b.id).name), ...(tray.fries < o.fries ? ['FRIES'] : []), ...o.drinks.filter(k => tray.drinks.filter(d => d === k).length < o.drinks.filter(d => d === k).length).map(k => SIDES[k].name)] }; } } return { oid: null, who: null, dn, completes: false, missing: [] }; }
  function revealDone(choice = 'tray') { const r = S.reveal, id = r.id; if (!S.ranOut && !DM.noRunOut) { S.ranOut = true; const on = [...new Set(avail().flatMap(rc => rc.stack))].filter(k => VEG[k]), k = pick(on.length ? on : ['tomato']); setTimeout(() => { setStock(k, 0); needCut(k, true); }, 900); } S.reveal = null; boardGroup.rotation.y = 0; boardGroup.scale.setScalar(1); board = []; rebuildBoard();
    if (choice === 'bin') { flash('BURGER BINNED', '#ec3013', 1); tone(160, 0.2, 0.04); return; }
    tray.burgers.push(id); rebuildTray(); tone(990, 0.08, 0.04);
    if (choice === 'serve') { const o = orders.find(q => q.id === r.oid && q.st === 'wait'); if (!o) return; bag = { burgers: tray.burgers.slice(), fries: tray.fries, drinks: tray.drinks.slice() }; tray.burgers = []; tray.fries = 0; tray.drinks = []; rebuildTray(); serve(o); } }
  renderer.domElement.addEventListener('pointerdown', onDown); addEventListener('pointermove', onMove); addEventListener('pointerup', onUp);

  // ---------- flow ----------
  function startShift() { if (S.phase !== 'intro' && S.phase !== 'done') return; S.payOut = null; payProps(null); S.ranOut = false; if (S.cut) { scene.remove(S.cut.mesh); S.cut = null; } slices.forEach(s2 => scene.remove(s2)); slices.length = 0; Object.keys(stock).forEach(k => setStock(k, STOCK0)); S.reveal = null; S.react = null; if (!S.demo && DM.on) demoStop(); audio.init && audio.init(); Object.assign(S, { phase: 'glide', t: 0, earned: 0, tips: 0, served: 0, lost: 0, starList: [], next: 2.5, done: null, pay: null, combo: 0 });
    grill.forEach(g => g && (scene.remove(g.m), scene.remove(g.ring), scene.remove(g.gauge))); S.press = null; spat.visible = false; grill.length = 0; fryer.forEach((f, i) => { if (f) scene.remove(f.g); fryer[i] = null; }); cups.forEach(c => { scene.remove(c.g); if (c.stream) scene.remove(c.stream); }); cups.length = 0; S.pourShot = null; orders.forEach(o => o.f.visible = false); orders.length = 0; board = []; bag = null; bagMesh.visible = false; tray.burgers = []; tray.fries = 0; tray.drinks = []; rebuildBoard(); rebuildTray();
    S.focus = 'all'; ben.position.set(-2.6, 0, K.z - 0.55); ben.rotation.y = 0.35; setUniform(!!save.flag('burgerUniform')); sizzle.visible = false; glideTo(workShot(), 1.6); say('SIZZLE: "Grill on the right, fryer and drinks on the left, bags far right. Go go go!"', 6); ben.visible = false; S.glideT = 1.65; }
  function endShift() { S.phase = 'done'; const avg = S.starList.length ? S.starList.reduce((a, b) => a + b, 0) / S.starList.length : 0, eod = S.served >= 5 + S.day && avg >= 2.4, wage = 10 + S.day * 2, total = wage + S.earned + S.tips;
    let newDay = false, unlock = []; try { save.addGold(total); save.best(SAVE.best, total); if (S.served >= 3 + S.day) { const nd = S.day + 1; save.setStat(SAVE.day, nd); newDay = true; unlock = [...RECIPES.filter(r => r.day === nd).map(r => r.name), ...Object.entries(SIDES).filter(([, v]) => v.day === nd).map(([, v]) => v.name)]; } if (!save.flag('burgerUniform') && S.served >= 3) { save.setFlag('burgerUniform'); setUniform(true); unlock.push('BURGERS UNIFORM (cap + apron)'); } if (eod) save.setStat('meru.burgers.stars', save.stat('meru.burgers.stars', 0) + 1); } catch (e) {}
    S.done = { day: S.day, served: S.served, lost: S.lost, avg: Math.round(avg * 10) / 10, wage, earned: S.earned, tips: S.tips, total, eod, newDay, unlock, stars: save.stat('meru.burgers.stars', 0), gold: save.data.gold };
    if (newDay) S.day += 1; glideTo(wideShot(), 1.4); say(eod ? 'SIZZLE: "EMPLOYEE OF THE DAY! Look at you!"' : S.served >= 3 ? 'SIZZLE: "Good shift. Same time tomorrow?"' : 'SIZZLE: "Rough one. Tomorrow will be better."', 6); orders.forEach(o => { o.st = 'leave'; o.t = 0; }); }
  function buyUpgrade(id) { const u = UPGRADES.find(q => q.id === id); if (!u || upg(id)) return false; if (!save.spend(u.cost)) { flash('NOT ENOUGH GOLD', '#ec3013'); return false; } save.setStat(SAVE.upg + id, 1); flash(u.name + ' · INSTALLED', '#22c55e', 1.6); tone(1320, 0.1, 0.05); if (S.done) S.done.gold = save.data.gold; return true; }

  // ---------- DEMO: an autopilot plays a real shift with captions (nothing is saved) ----------
  const DM = { on: false, cd: 0, cap: '', key: '', seen: {}, served: 0, anim: null, day0: 1 };
  const hand = new THREE.Sprite(new THREE.SpriteMaterial({ map: glowTex, color: 0xffd23a, transparent: true, depthWrite: false, depthTest: false, blending: THREE.AdditiveBlending })); hand.scale.setScalar(0.32); hand.visible = false; hand.renderOrder = 20; scene.add(hand);
  const handTo = (p, f) => { hand.visible = true; hand.position.copy(p); hand.scale.setScalar(0.5); if (f) setFocus(f); DM.hint = { p: p.clone().setY(Math.max(K.top, p.y - 0.15)), r: 0.18 }; };
  const cap = (id, key, text) => { if (DM.seen[id]) return; DM.seen[id] = true; DM.cap = text; DM.key = key; DM.cd = Math.max(DM.cd, 1.6); };
  function slide(mesh, from, to, dur, done) { scene.add(mesh); mesh.position.copy(from); DM.anim = { mesh, from: from.clone(), to: to.clone(), t: 0, dur, done }; }
  const boardTop = () => V3(K.board.x, K.top + 0.18, K.board.z);
  function demoAct() { grill.forEach(g => g && (g.press = false)); const o = orders.find(q => q.st === 'wait'); if (S.pay) { const P = S.pay, left = P.owed - P.given, v = [10, 5, 2, 1].find(c => c <= left); if (!DM.seen['pay']) { cap('pay', 'COINS', 'THEY PAID ' + P.paid + 'g FOR A ' + P.total + 'g BILL. TAP COINS TO GIVE ' + P.owed + 'g CHANGE'); return 1.8; } DM.cap = 'GIVE ' + P.owed + 'g CHANGE · ' + (P.given + v) + ' / ' + P.owed + 'g'; DM.key = v + 'g'; giveCoin(v); if (!S.pay) { DM.served++; DM.cap = 'EXACT CHANGE! COINS GO TO THE CUSTOMER'; DM.key = '✓'; return 1.6; } return 0.85; }
    if (!o) return 0.4; const need = { patty: 0 }; o.burgers.forEach(b => b.stack.forEach(k => { if (k === 'patty') need.patty++; }));
    const onBoard = board.filter(p => p.k === 'patty').length, cooking = grill.filter(Boolean).length, TF = trayFor(o), made = TF.made;
    // bag + hand over when the tray matches
    const ready = made >= o.burgers.length && tray.fries >= o.fries && o.drinks.every(k => tray.drinks.filter(d => d === k).length >= o.drinks.filter(d => d === k).length);
    if (bag) { cap('hand', 'DRAG', 'DRAG THE BAG ONTO THE CUSTOMER WHO ORDERED IT'); const to = V3(o.f.position.x, 1.3, o.f.position.z); handTo(to, 'bag'); bagMesh.visible = false; const m = bagMesh.clone(); m.visible = true; slide(m, bagMesh.position.clone(), to, 0.7, () => { scene.remove(m); bagMesh.visible = true; serve(o); }); return 1.0; }
    if (ready) { cap('bag', 'TAP', 'TRAY READY? TAP THE BAG STAND TO BAG IT'); handTo(V3(K.bagStand.x, K.top + 0.15, K.bagStand.z), 'bag'); bag = { burgers: tray.burgers.slice(), fries: tray.fries, drinks: tray.drinks.slice() }; tray.burgers = []; tray.fries = 0; tray.drinks = []; rebuildTray(); bagMesh.visible = true; bagMesh.position.set(K.bagStand.x, K.top + 0.06, K.bagStand.z); tone(700, 0.08, 0.04); return 0.8; }
    // collect finished sides
    const fi = fryer.findIndex(f => f && f.st === 'done'); if (fi >= 0 && tray.fries < o.fries) { cap('fries2', 'TAP', 'GOLDEN FRIES? TAP THE BASKET'); handTo(fryer[fi].g.position.clone().setY(K.top + 0.2), 'fryer'); scene.remove(fryer[fi].g); fryer[fi] = null; tray.fries++; rebuildTray(); tone(990, 0.08, 0.04); return 0.6; }
    const ci = cups.findIndex(c => c.fill >= 1); if (ci >= 0) { cap('cup2', 'TAP', 'LID + STRAW ON = FULL. TAP THE CUP TO PUT IT ON THE TRAY'); handTo(cups[ci].g.position.clone().setY(K.top + 0.2), 'drinks'); scene.remove(cups[ci].g); tray.drinks.push(cups[ci].k); cups.splice(ci, 1); rebuildTray(); tone(990, 0.08, 0.04); return 0.6; }
    // start things that take time
    if (cooking + onBoard < need.patty * (o.burgers.length - made > 0 ? 1 : 0) && made < o.burgers.length) { const slot = [0, 1, 2].find(i => !grill[i]); if (slot != null) { cap('grill', 'TAP', 'TAP THE PATTY BOX: A PATTY GOES ON THE GRILL'); handTo(V3(K.patBox.x, K.top + 0.2, K.patBox.z), 'grill'); addPatty(slot); return 0.7; } }
    if (o.fries > tray.fries && !fryer.some(Boolean)) { cap('fries', 'TAP', 'TAP THE FRIES BOX: A BASKET DROPS IN THE FRYER'); handTo(V3(K.friesBox.x, K.top + 0.2, K.friesBox.z), 'fryer'); addFries(0); return 0.7; }
    for (const k of o.drinks) { const have = tray.drinks.filter(d => d === k).length + cups.filter(c => c.k === k).length, want = o.drinks.filter(d => d === k).length; if (have < want) { const tap = K.taps.find(tp => tp.k === k); if (!cups.some(c => c.tap === tap)) { cap('drink', 'TAP', 'TAP A BUTTON ON THE DRINK MACHINE: WATCH IT POUR'); handTo(V3(tap.x, K.top + 0.36, tap.z), 'drinks'); addCup(tap); return upg('fastPour') ? 1.4 : 2.6; } } }
    if (S.cut) { cap('cut', 'SWIPE', 'OUT OF ' + VEG[S.cut.k] + '! SWIPE ACROSS IT ON THE CUTTING BOARD TO CUT MORE'); handTo(V3(K.chop.x + 0.06, K.top + 0.12, K.chop.z), 'cut'); knife.visible = true; knife.position.set(K.chop.x - 0.06 + (S.cut.cuts % 2 ? 0.12 : -0.12), K.top + 0.14, K.chop.z); knife.rotation.set(0, 0.3, -0.25); cutOnce(); if (!S.cut) knife.visible = false; return 0.4; }
    // build the burger, piece by piece (dragged)
    if (TF.next >= 0) { const rec = o.burgers[TF.next], seq = ['bunB', ...rec.stack, 'bunT'], next = seq[board.length];
      if (next === 'patty') { const want = o.dns[TF.next], g = grill.find(q => q && q.st !== 'burnt'); if (!g) return 0.3; g.want = want; const mid = (DN[want][0] + DN[want][1]) / 2;
        if (g.d < mid) { if (!g.flipped && g.d > 0.42 && g.flipT === 0) { g.press = false; cap('flip', 'TAP', 'QUICK TAP = FLIP IT'); g.flipT = 0.001; return 0.6; } cap('press', 'HOLD', 'HOLD THE PATTY TO GRILL IT. LET GO IN THE ' + DN_NAME[want] + ' ZONE'); handTo(g.m.position.clone(), 'grill'); g.press = true; return 0.08; }
        g.press = false; cap('patty', 'DRAG', DN_NAME[want] + '! NOW DRAG THE PATTY ONTO THE BUN'); dropPatty(g); handTo(g.m.position.clone(), 'grill'); scene.add(g.m); const dn = g.st; slide(g.m, g.m.position.clone(), boardTop(), 0.5, () => { scene.remove(g.m); addToBoard({ k: 'patty', dn }); }); return 0.75; }
      if (next) { if (next === 'bunB') cap('bun', 'DRAG', 'DRAG A BOTTOM BUN ONTO THE BOARD, THEN THE TOPPINGS'); if (next === 'bunT') cap('top', 'DRAG', 'TOP BUN LAST: THE BURGER GOES ON THE TRAY'); const b = K.bins[next], from = V3(b.x, K.top + 0.15, b.z); handTo(from, 'board'); slide(pieceMesh(next), from, boardTop(), 0.45, () => addToBoard({ k: next })); return 0.7; } }
    return 0.3; }
  function demoStep(dt) { if (DM.anim) { const a = DM.anim; a.t += dt / a.dur; const k = Math.min(1, a.t), p = a.from.clone().lerp(a.to, smooth(0, 1, k)); p.y += Math.sin(k * Math.PI) * 0.25; a.mesh.position.copy(p); hand.position.copy(p); if (k >= 1) { DM.anim = null; a.done && a.done(); } return; }
    hand.scale.setScalar(Math.max(0.3, hand.scale.x - dt * 0.6)); if (S.phase !== 'shift' || S.reveal || S.react || S.pourShot || S.payOut) return; DM.cd -= dt; if (DM.cd > 0) return; const f0 = S.focus; DM.cd = demoAct(); if (S.focus !== f0) DM.cd += 0.5;
    if (DM.served >= 3 || S.t > 120) { DM.cap = 'YOUR TURN! TAP PUT ME TO WORK'; DM.key = 'GO'; DM.cd = 99; setTimeout(() => DM.on && demoStop(), 2600); } }
  function demoStart() { if (DM.on) return; audio.init && audio.init(); DM.on = true; DM.seen = {}; DM.served = 0; DM.anim = null; DM.cd = 2.2; DM.day0 = S.day; S.day = Math.max(S.day, 3); DM.cap = 'WATCH A SHIFT AT SIZZLE\'S'; DM.key = ''; S.phase = 'intro'; S.done = null; S.demo = true; startShift(); S.next = 0.8; }
  function demoStop() { if (!DM.on) return; S.payOut = null; payProps(null); DM.on = false; S.demo = false; hand.visible = false; if (DM.anim) { scene.remove(DM.anim.mesh); DM.anim = null; } S.day = DM.day0; S.pay = null; S.phase = 'intro'; S.done = null; grill.forEach(g => g && (scene.remove(g.m), scene.remove(g.ring), scene.remove(g.gauge))); S.press = null; spat.visible = false; grill.length = 0; fryer.forEach((f, i) => { if (f) scene.remove(f.g); fryer[i] = null; }); cups.forEach(c => { scene.remove(c.g); if (c.stream) scene.remove(c.stream); }); cups.length = 0; S.pourShot = null; orders.forEach(o => o.f.visible = false); orders.length = 0; board = []; bag = null; bagMesh.visible = false; tray.burgers = []; tray.fries = 0; tray.drinks = []; rebuildBoard(); rebuildTray(); ben.visible = true; sizzle.visible = true; ben.position.set(-1.0, 0, K.z + 3.5); ben.rotation.y = 0.3; glideTo(wideShot(), 1.2); }

  // ---------- NEXT-STEP HINT: a bobbing arrow + a pulsing ring over the next thing to do ----------
  const RINGS = hintRings(ST), { arrow, pulse, pulse2 } = RINGS;
  function nextHint() { if (S.phase !== 'shift' || S.pay) return null; const o = orders.filter(q => q.st === 'wait').sort((a, b) => a.pat - b.pat)[0]; if (!o) return null;
    const P3 = (x, z, y = K.top) => V3(x, y, z), H = (p, station, text, r = 0.16) => ({ p, station, text, r });
    const burnt = grill.find(g => g && g.st === 'burnt'); if (burnt) return H(burnt.m.position.clone().setY(K.top), 'grill', 'BURNT PATTY: TAP IT TO BIN IT');
    if (bag) return H(P3(o.f.position.x, o.f.position.z, 0.02), 'bag', 'DRAG THE BAG TO ' + CUSTOMERS[o.ci].name, 0.45);
    const TF = trayFor(o), made = TF.made, ready = made >= o.burgers.length && tray.fries >= o.fries && o.drinks.every(k => tray.drinks.filter(d => d === k).length >= o.drinks.filter(d => d === k).length);
    if (ready) return H(P3(K.bagStand.x, K.bagStand.z), 'bag', TF.extra.length ? 'TAP THE BAG STAND (EXTRA BURGERS ARE FINE)' : 'TAP THE BAG STAND', 0.22);
    const fd = fryer.find(f => f && f.st === 'done'); if (fd && tray.fries < o.fries) return H(fd.g.position.clone().setY(K.top), 'fryer', 'FRIES ARE GOLDEN: TAP THE BASKET');
    const cf = cups.find(c => c.fill >= 1 && o.drinks.includes(c.k)); if (cf) return H(cf.g.position.clone().setY(K.top), 'drinks', 'DRINK IS FULL: TAP THE CUP', 0.1);
    if (TF.next >= 0) grill.forEach(q => q && (q.want = o.dns[TF.next])); const needPat = TF.next >= 0 ? o.burgers[TF.next].stack.filter(k => k === 'patty').length - board.filter(p => p.k === 'patty').length : 0;
    if (needPat > grill.filter(Boolean).length) return H(P3(K.patBox.x, K.patBox.z), 'grill', 'TAP THE PATTY BOX', 0.22);
    if (o.fries > tray.fries && !fryer.some(Boolean)) return H(P3(K.friesBox.x, K.friesBox.z), 'fryer', 'TAP THE FRIES BOX', 0.2);
    if (S.cut) { const needIt = TF.next >= 0 && o.burgers[TF.next].stack.includes(S.cut.k); if (needIt || S.focus === 'cut') return H(P3(K.chop.x + 0.06, K.chop.z), 'cut', 'SWIPE ACROSS THE ' + VEG[S.cut.k] + ' TO CUT · ' + S.cut.cuts + ' / ' + CUTS, 0.22); }
    if (TF.next >= 0) { const rec = o.burgers[TF.next], seq = ['bunB', ...rec.stack, 'bunT'], ok = board.every((p, i) => p.k === seq[i] || (seq.slice(1, -1).includes(p.k) && i > 0 && i < seq.length - 1)), next = ok ? seq.find((k, i) => i >= board.length && !(i > 0 && i < seq.length - 1 && board.filter(p => p.k === k).length >= seq.slice(1, i + 1).filter(q => q === k).length && false)) || seq[board.length] : null;
      if (!ok) return H(P3(K.board.x, K.board.z), 'board', 'WRONG PIECE: TAP THE BOARD TO UNDO', 0.36);
      const nk = seq[board.length]; if (nk === 'patty') { const want = o.dns[TF.next], who = CUSTOMERS[o.ci].name; grill.forEach(q => q && (q.want = want)); const g = grill.find(q => q && q.st === want); if (g) return H(g.m.position.clone().setY(K.top), 'grill', DN_NAME[want] + '! DRAG THE PATTY ONTO THE BUN'); const c = grill.find(q => q && q.d < DN[want][0]); if (c) return H(c.m.position.clone().setY(K.top), 'grill', 'HOLD THE PATTY TO GRILL · ' + who + ' WANTS ' + DN_NAME[want]); return H(P3(K.patBox.x, K.patBox.z), 'grill', 'TAP THE PATTY BOX', 0.22); }
      if (nk) { const b = K.bins[nk]; return H(P3(b.x, b.z), 'board', 'DRAG THE ' + ING[nk].name + ' ONTO THE BOARD', 0.15); } }
    for (const k of o.drinks) { const have = tray.drinks.filter(d => d === k).length + cups.filter(c => c.k === k).length; if (have < o.drinks.filter(d => d === k).length) { const tap = K.taps.find(tp => tp.k === k); if (!cups.some(c => c.tap === tap)) return H(P3(tap.x, tap.z, K.top + 0.02), 'drinks', 'TAP THE ' + SIDES[k].name + ' TAP', 0.12); } }
    const ff = fryer.find(f => f && f.st === 'cook'); if (ff) return H(ff.g.position.clone().setY(K.top), 'fryer', 'FRIES ARE FRYING · WAIT');
    const cc = cups.find(c => c.fill < 1); if (cc) return H(cc.g.position.clone().setY(K.top), 'drinks', 'POURING · WAIT', 0.1);
    return null; }
  function trayFor(o) { const pool = tray.burgers.slice(), covered = o.burgers.map(() => false); o.burgers.forEach((b, j) => { let i = pool.indexOf(b.id + '|' + o.dns[j]); if (i < 0) i = pool.findIndex(x => bid(x) === b.id); if (i >= 0) { covered[j] = true; pool.splice(i, 1); } }); return { covered, made: covered.filter(Boolean).length, next: covered.indexOf(false), extra: pool }; }
  // ---------- CUTTING: veggie bins run out; swipe (touch or mouse drag) across the whole veggie on the cutting board ----------
  const VEG = { lettuce: 'LETTUCE', tomato: 'TOMATOES', pickle: 'PICKLES', onion: 'ONIONS' }, STOCK0 = 8, CUTS = 5, stock = { lettuce: STOCK0, tomato: STOCK0, pickle: STOCK0, onion: STOCK0 };
  const outT = canvasTex(128, 64, c => { c.fillStyle = '#ec3013'; c.fillRect(0, 0, 128, 64); c.fillStyle = '#fff'; c.font = '900 40px Archivo, Arial'; c.textAlign = 'center'; c.textBaseline = 'middle'; c.fillText('OUT', 64, 34); });
  const outTags = {}; for (const k of Object.keys(VEG)) { const s = new THREE.Sprite(new THREE.SpriteMaterial({ map: outT, depthTest: false })); s.scale.set(0.22, 0.11, 1); s.position.set(K.bins[k].x, K.top + 0.28, K.bins[k].z); s.renderOrder = 26; s.visible = false; scene.add(s); outTags[k] = s; }
  const setStock = (k, n) => { stock[k] = n; (K.binPiles[k] || []).forEach((m, i) => m.visible = n > i * 2); outTags[k].visible = n <= 0; };
  const { wholeVeg, knife } = vegArt(ST);
  const slices = []; function needCut(k, why) { if (S.cut) return; const m = wholeVeg(k); m.position.set(K.chop.x + 0.06, K.top + 0.04, K.chop.z); scene.add(m); S.cut = { k, cuts: 0, mesh: m, last: 0 }; if (why) { say('SIZZLE: "MORNING SHIFT forgot to cut the ' + VEG[k] + ' we need more right away!"', 6); flash('OUT OF ' + VEG[k] + '!', '#ec3013', 2); tone(330, 0.2, 0.05, 'square'); setTimeout(() => tone(260, 0.25, 0.05, 'square'), 180); } }
  function cutOnce() { const C = S.cut; const now = performance.now() / 1000; if (!C || now - C.last < 0.08) return; C.last = now; C.cuts++; tone(1800 + C.cuts * 120, 0.04, 0.05, 'square'); audio.burst && audio.burst(0.08, 4000, 0.1);
    const s = makeIng(THREE, toon, C.k, null, addOutline); s.scale.setScalar(0.55); s.position.set(K.chop.x - 0.2 + (C.cuts % 3) * 0.05, K.top + 0.045 + Math.floor(C.cuts / 3) * 0.015, K.chop.z - 0.08 + (C.cuts % 2) * 0.12); s.rotation.y = rr(0, 6); scene.add(s); slices.push(s); C.mesh.scale.x = Math.max(0.25, 1 - C.cuts / CUTS * 0.75); C.mesh.position.x = K.chop.x + 0.06 + C.cuts * 0.02; puff(K.chop.x, K.top + 0.15, K.chop.z, 0xffffff, 2);
    if (C.cuts >= CUTS) { scene.remove(C.mesh); slices.forEach(s2 => scene.remove(s2)); slices.length = 0; setStock(C.k, STOCK0); flash(VEG[C.k] + ' READY · +' + STOCK0, '#22c55e', 1.6); tone(1175, 0.1, 0.05); setTimeout(() => tone(1568, 0.12, 0.05), 100); S.cut = null; knife.visible = false; if (S.focus === 'cut') S.focus = 'board'; } }
  function strokeMove(x, y) { const C = S.cut, st = S.stroke; if (!C || !st) return; const v = scr(V3(K.chop.x + 0.06, K.top + 0.1, K.chop.z)), R = 70 * scale(), sxa = st.x - v.x, sxb = x - v.x, sya = st.y - v.y, syb = y - v.y;
    if ((sxa * sxb < 0 && Math.abs(y - v.y) < R) || (sya * syb < 0 && Math.abs(x - v.x) < R)) cutOnce(); st.x = x; st.y = y;
    ndc.set(x / CW() * 2 - 1, -(y / CHh()) * 2 + 1); ray.setFromCamera(ndc, camera); if (ray.ray.intersectPlane(plane, hit)) { knife.visible = true; knife.position.set(hit.x - 0.12, K.top + 0.14, hit.z); knife.rotation.set(0, 0.3, -0.25); } }
  let HINT = null, hintT = 0;
  function autoFollow() { if (DM.on || !HINT || !HINT.station || S.focus === 'all' || S.focus === HINT.station) return; if (drag || S.press || S.stroke || S.reveal || S.react || S.pay || S.pourShot) return; const busy = { drinks: cups.some(c => c.fill < 1), fryer: fryer.some(f => f && f.st === 'cook'), grill: grill.some(g => g && g.press) }; if (busy[S.focus]) return; const idle = (performance.now() - (S.lastInput || 0)) / 1000; if (idle > 0.9 && performance.now() - (S.userFocusT || 0) > 2500) S.focus = HINT.station; }
  function updHint(dt) { hintT += dt; HINT = DM.on ? (DM.hint && !DM.anim ? DM.hint : null) : nextHint(); RINGS.place(HINT && !S.reveal && !S.react ? HINT : null, hintT, dt); }

  // ---------- per-frame ----------
  const clock = new THREE.Clock(); let raf = 0, hudT = 0, PAUSE = false;
  function step(dt) {
    if (S.reveal) { S.reveal.t += dt; const r = S.reveal, sh = shotFor('reveal', () => { const b = K.board, T = K.top; return [V3(b.x - 0.2, T, b.z - 0.2), V3(b.x + 0.2, T, b.z + 0.2), V3(b.x - 0.2, T + 0.42, b.z), V3(b.x + 0.2, T + 0.42, b.z)]; }, 0.62, 0.18, 0.12); camera.position.lerp(sh.pos, Math.min(1, dt * 6)); CAM.look.lerp(sh.look, Math.min(1, dt * 6)); boardGroup.rotation.y += dt * 1.6; boardGroup.scale.setScalar(1 + Math.sin(Math.min(1, r.t / 0.35) * Math.PI) * 0.12); if (DM.on && r.t > 1.8) revealDone(r.completes ? 'serve' : r.oid ? 'tray' : 'bin'); }
    else if (S.pourShot && (DM.on || S.focus === 'drinks')) { const ps = S.pourShot, c = cups.find(q => q.tap === ps.tap); ps.t += dt; if (!c || c.fill >= 1 || ps.t > 3.2) S.pourShot = null; else { const cp = c.g.position, sh = shotFor('pour' + K.taps.indexOf(ps.tap), () => [V3(cp.x - 0.12, cp.y, cp.z - 0.1), V3(cp.x + 0.12, cp.y, cp.z + 0.1), V3(cp.x, K.top + 0.42, K.drinks.z - 0.2), V3(cp.x, cp.y + 0.24, cp.z)], 0.5, -0.15, 0.14); camera.position.lerp(sh.pos, Math.min(1, dt * 5)); CAM.look.lerp(sh.look, Math.min(1, dt * 5)); } }
    else if (S.pay || S.payOut) { const port = CW() < CHh(), sh = shotFor('pay', () => [V3(REG.x - 0.24, REG.y, REG.z - 0.38), V3(REG.x + 0.24, REG.y + 0.1, REG.z + 0.05), V3(DISH.x - 0.14, DISH.y, DISH.z - 0.14), V3(DISH.x + 0.14, DISH.y, DISH.z + 0.14), V3(REG.x + 0.52, REG.y, REG.z - 0.5), V3(REG.x - 0.24, REG.y + 0.5, REG.z - 0.05), V3(REG.x + 0.24, REG.y + 0.5, REG.z - 0.05)], 1.0, 0.25, 0.07); camera.position.lerp(sh.pos, Math.min(1, dt * 5)); CAM.look.lerp(sh.look, Math.min(1, dt * 5)); regDisp.scale.set(port ? 0.36 : 0.46, port ? 0.133 : 0.17, 1); }
    else if (S.react) { S.react.t += dt; const o = S.react.o, f = o.f.position, sh = shotFor('react' + o.spot, () => [V3(f.x - 0.45, 1.25, f.z), V3(f.x + 0.45, 1.25, f.z), V3(f.x, 2.35, f.z), V3(f.x, 1.55, f.z - 0.3)], 0.12, 0.12, 0.1); camera.position.lerp(sh.pos, Math.min(1, dt * 5)); CAM.look.lerp(sh.look, Math.min(1, dt * 5)); if (S.react.t > (DM.on ? 2.0 : 2.4)) reactDone(); }
    else if (CAM.t < 1 && CAM.from) { CAM.t = Math.min(1, CAM.t + dt / CAM.dur); const k = smooth(0, 1, CAM.t); camera.position.lerpVectors(CAM.from.pos, CAM.to.pos, k); CAM.look.lerpVectors(CAM.from.look, CAM.to.look, k); } else if ((S.phase === 'intro' || S.phase === 'done') && !DM.on) { const w = wideShot(); camera.position.lerp(w.pos, Math.min(1, dt * 4)); CAM.look.lerp(w.look, Math.min(1, dt * 4)); }
    else if ((S.phase === 'intro' || S.phase === 'done') && !DM.on) { const w = wideShot(); camera.position.lerp(w.pos, Math.min(1, dt * 4)); CAM.look.lerp(w.look, Math.min(1, dt * 4)); }
    else if (S.phase === 'shift' || S.phase === 'glide') { const w = workShot(); camera.position.lerp(w.pos, Math.min(1, dt * 3.2)); CAM.look.lerp(w.look, Math.min(1, dt * 3.2)); }
    { const hide = S.phase === 'intro' || S.phase === 'done'; K.front.forEach(m => m.visible = !hide); K.booths.forEach(m => m.visible = !hide); }
    camera.lookAt(CAM.look);
    { const want = 0; if ((camera.view && camera.view.offsetY) !== -want) { if (want) camera.setViewOffset(CW(), CHh(), 0, -want, CW(), CHh()); else camera.clearViewOffset(); } }
    S.flashT -= dt; if (S.flashT <= 0) S.flash = null; S.sayT -= dt; if (S.sayT <= 0) S.say = '';
    for (const p of smokeS) { if (p.life <= 0) { p.s.material.opacity = 0; continue; } p.life -= dt * 0.8; p.s.position.addScaledVector(p.v, dt); p.s.material.opacity = 0.45 * p.life; p.s.scale.setScalar(0.18 + (1 - p.life) * 0.3); }
    lampGl.forEach((s, i) => s.material.opacity = 0.5 + Math.sin(clock.elapsedTime * 2 + i) * 0.04);
    if (S.phase === 'glide') { S.glideT -= dt; if (S.glideT <= 0) S.phase = 'shift'; }
    { const hide = (S.phase === 'shift' || S.phase === 'glide') && (CAM.t > 0.35 || !CAM.from); K.cut.forEach(m => m.visible = !hide); lampGl.forEach(s => s.visible = !hide); }
    const work = S.phase === 'shift';
    if (work) { S.t += dt; if (S.t >= BURGERS.shift && !DM.on) endShift(); }
    if (DM.on) demoStep(dt);
    updHint(dt); if (S.phase === 'shift') autoFollow();
    regDisp.visible = !!(S.pay || S.payOut);
    drawer.position.z = damp(drawer.position.z, REG.z - 0.05 - (S.pay ? 0.26 : 0), 10, dt);
    for (const m of coinsOut) { if (m.userData.t < 1) { m.userData.t = Math.min(1, m.userData.t + dt / 0.35); const k = m.userData.t, a = V3(drawer.position.x, drawer.position.y + 0.08, drawer.position.z); m.position.lerpVectors(a, m.userData.target, k); m.position.y += Math.sin(k * Math.PI) * 0.12; m.rotation.x = k * 6; if (k >= 1) { m.rotation.x = 0; tone(2400 + Math.random() * 400, 0.04, 0.03, 'square'); } } }
    if (S.payOut) { S.payOut.t += dt; const k = Math.min(1, S.payOut.t / 0.7), o = S.payOut.o; if (o) { const to = V3(o.f.position.x, K.pass.y + 0.03, K.pass.z); coinsOut.forEach(m => m.position.lerp(to, Math.min(1, dt * 4))); if (RG.bill()) RG.bill().position.lerp(V3(REG.x, REG.y + 0.02, REG.z - 0.2), Math.min(1, dt * 6)); } if (S.payOut.t > 1.1) { S.payOut = null; payProps(null); } }
    // grill
    let pressing = null; for (const g of grill) { if (!g) continue; g.t += dt; const rate = g.press ? 0.17 : (upg('warmer') && g.d > 0.9 ? 0 : 0.03); g.d = Math.min(1.25, g.d + rate * dt); const z = dnOf(g.d); g.st = z;
      if (z !== g.lastZ) { g.lastZ = z; { const np = pieceMesh('patty', z); np.position.copy(g.m.position); np.rotation.copy(g.m.rotation); np.scale.copy(g.m.scale); scene.remove(g.m); scene.add(np); g.m = np; } g.ring.material.color.setHex(ZONE_COL[z]); if (z === 'burnt') tone(220, 0.25, 0.04, 'sawtooth'); else if (z !== 'raw' && z === g.want) tone(1320, 0.08, 0.04); } g.ring.material.opacity = (g.want && z === g.want) || z === 'burnt' ? 0.55 + Math.sin(clock.elapsedTime * 9) * 0.4 : 0.35;
      if (Math.abs(g.d - g.lastD) > 0.008) { g.lastD = g.d; gaugeTex(g); } if (Math.random() < dt * (g.press ? 22 : 5)) puff(g.m.position.x, K.top + 0.1, g.m.position.z, z === 'burnt' ? 0x3a3836 : 0xffffff, 1);
      if (g.flipT > 0) { g.flipT = Math.min(1, g.flipT + dt / 0.45); g.m.position.y = K.top + 0.07 + Math.sin(g.flipT * Math.PI) * 0.22; g.m.rotation.x = g.flipT * Math.PI; if (g.flipT >= 1) { g.flipT = 0; g.m.rotation.x = 0; g.flipped = true; tone(700, 0.06, 0.04); } }
      g.m.scale.y = damp(g.m.scale.y, g.press ? 0.7 : 1, 14, dt); if (g.press) pressing = g; }
    spat.visible = !!pressing; if (pressing) { spat.position.set(pressing.m.position.x, K.top + 0.11 + Math.sin(clock.elapsedTime * 30) * 0.004, pressing.m.position.z); if (Math.random() < dt * 8) audio.burst && audio.burst(0.05, 3200, 0.05); }
    // fryer
    fryer.forEach(f => { if (!f) return; f.t += dt; const burnAt = FRY_DONE + (upg('bell') ? 10 : 6); if (f.st === 'cook' && f.t > FRY_DONE) { f.st = 'done'; f.g.userData.ff.children.forEach(c => c.material = toon('#f7c948')); tone(1568, 0.15, 0.05); f.g.position.y = K.top + 0.16; } if (f.st === 'done' && f.t > burnAt) { f.st = 'burnt'; f.g.userData.ff.children.forEach(c => c.material = toon('#5a3a1a')); tone(220, 0.25, 0.04, 'sawtooth'); } if (f.st === 'cook') { f.g.position.y = K.top - 0.04 + Math.sin(clock.elapsedTime * 20) * 0.004; if (Math.random() < dt * 5) puff(f.g.position.x, K.top + 0.2, f.g.position.z, 0xfff3d0, 1); } });
    // cups
    for (const c of cups) { if (c.fill >= 1) { if (c.stream) { scene.remove(c.stream); c.stream = null; } continue; } c.t += dt; c.fill = Math.min(1, c.t / (upg('fastPour') ? 1.2 : 2.4)); scene.remove(c.g); const p = c.g.position.clone(); c.g = cupMesh(c.k, c.fill); c.g.position.copy(p); scene.add(c.g);
      if (c.stream) { const top = K.top + 0.25, bot = p.y + 0.06 + 0.1 * c.fill, h = Math.max(0.02, top - bot); c.stream.scale.set(1 + Math.sin(clock.elapsedTime * 40) * 0.12, h, 1); c.stream.position.set(p.x, bot + h / 2, p.z); if (Math.random() < dt * 5) puff(p.x + rr(-0.03, 0.03), bot + 0.02, p.z, 0xffffff, 1); }
      if (c.fill >= 1) { tone(1320, 0.08, 0.04); setTimeout(() => tone(1760, 0.1, 0.04), 90); if (c.stream) { scene.remove(c.stream); c.stream = null; } puff(p.x, p.y + 0.22, p.z, 0xffffff, 3); flash(SIDES[c.k].name + ' READY', '#22c55e', 1); } }
    // customers
    if (work) { S.next -= dt; const maxQ = Math.min(3, 1 + Math.ceil(S.day / 2)); if (S.next <= 0 && orders.filter(o => o.st !== 'leave').length < maxQ && S.t < BURGERS.shift - 12) { newOrder(); S.next = Math.max(7, 15 - S.day * 1.5) * rr(0.8, 1.2); } }
    for (let i = orders.length - 1; i >= 0; i--) { const o = orders[i], sp = K.spots[o.spot]; o.t = (o.t || 0) + dt; kit.animFox && kit.animFox(o.f, dt, o.st === 'walk' || o.st === 'leave' ? 2 : 0);
      if (o.st === 'walk') { o.f.position.x = damp(o.f.position.x, sp.x, 2.2, dt); o.f.position.z = damp(o.f.position.z, sp.z, 2.2, dt); o.f.rotation.y = Math.PI; if (Math.abs(o.f.position.x - sp.x) < 0.08) { o.st = 'wait'; say(CUSTOMERS[o.ci].name + ': "' + o.line + '"', 3); tone(1046, 0.06, 0.03); } }
      else if (o.st === 'wait' && work) { o.pat -= DM.on ? 0 : dt; o.f.userData.mood = o.pat / o.patMax < 0.3 ? 'angry' : o.pat / o.patMax < 0.6 ? 'neutral' : 'happy'; if (o.pat <= 0) { o.st = 'leave'; o.t = 0; S.lost++; S.combo = 0; flash(CUSTOMERS[o.ci].name + ' LEFT · ' + pick(LINES.angry), '#ec3013', 1.8); tone(180, 0.3, 0.05, 'sawtooth'); } }
      else if (o.st === 'leave') { o.f.rotation.y = Math.PI / 2 + Math.PI; o.f.position.x += dt * 2.4; if (o.t > 3.5) { o.f.visible = false; orders.splice(i, 1); } } }
    const greet = S.phase === 'intro' || S.phase === 'done'; ben.rotation.y = damp(ben.rotation.y, greet ? 0.3 : drag ? -0.2 : 0.35, 4, dt); ben.userData.mood = greet ? 'excited' : 'happy'; kit.animFox && (kit.animFox(ben, dt, 0), kit.animFox(sizzle, dt, 0));
    if (greet && BP.arms && BP.arms[0]) { const w = performance.now() / 1000, arm = BP.arms[0]; arm.rotation.set(-0.25, 0, -2.55 + Math.sin(w * 7) * 0.32); }
  }
  function frame() { raf = requestAnimationFrame(frame); const dt = Math.min(0.05, clock.getDelta()); if (!PAUSE) step(dt); renderer.render(scene, camera); hudT -= dt; if (hudT <= 0) { hudT = 0.1; emit(); } }
  function onRs() { renderer.setSize(CW(), CHh()); camera.aspect = CW() / CHh(); camera.updateProjectionMatrix(); } addEventListener('resize', onRs); const ro = new ResizeObserver(onRs); ro.observe(container);
  function hud() { const n = upg('grill4') ? 4 : 3;
    const ticket = o => { const sp = scr(V3(o.f.position.x, 2.35, o.f.position.z)); return { id: o.id, name: CUSTOMERS[o.ci].name, role: CUSTOMERS[o.ci].role, burgers: o.burgers.map((b, j) => ({ name: b.name, dn: DN_NAME[o.dns[j]], stack: ['bunB', ...b.stack, 'bunT'].map(k => ({ k, name: ING[k].name, col: ING[k].col })) })), fries: o.fries, drinks: o.drinks.map(k => SIDES[k].name), total: o.total, pat: Math.max(0, o.pat / o.patMax), waiting: o.st === 'wait', sx: sp.x, sy: sp.y }; };
    return { phase: S.phase, day: S.day, left: Math.max(0, BURGERS.shift - S.t), earned: S.earned, tips: S.tips, served: S.served, lost: S.lost, stars: S.starList.length ? Math.round(S.starList.reduce((a, b) => a + b, 0) / S.starList.length * 10) / 10 : 0, combo: S.combo,
      orders: orders.filter(o => o.st === 'wait' || o.st === 'walk').sort((a, b) => a.spot - b.spot).map(ticket), tray: { burgers: tray.burgers.map(x => RECIPES.find(r => r.id === bid(x)).name + ' (' + DN_NAME[bdn(x)] + ')'), fries: tray.fries, drinks: tray.drinks.map(k => SIDES[k].name) }, bag: !!bag,
      board: board.map(p => ING[p.k].name), grillFree: n - grill.filter(Boolean).length, pay: S.pay ? { ...S.pay } : null, flash: S.flash, say: S.say, done: S.done, gold: save.data.gold, uniform: !!save.flag('burgerUniform'),
      upgrades: UPGRADES.map(u => ({ ...u, owned: upg(u.id) })), menu: avail().map(r => ({ name: r.name, stack: r.stack.map(k => ING[k].name), price: r.price })), sides: sidesAvail().map(k => SIDES[k].name), demo: DM.on ? { cap: DM.cap, key: DM.key, n: DM.served, of: 3 } : null, focus: S.focus, press: S.press ? { d: S.press.g.d, zone: DN_NAME[S.press.g.st], want: DN_NAME[S.press.g.want] || '' } : null,
      hint: HINT && HINT.text && !S.reveal && !S.react ? { text: HINT.text, station: HINT.station } : null,
      reveal: S.reveal ? { dn: DN_NAME[S.reveal.dn] || '', wantDn: DN_NAME[S.reveal.wantDn] || '', dnOk: !!S.reveal.dnOk, name: (RECIPES.find(r => r.id === bid(S.reveal.id)) || {}).name, who: S.reveal.who, completes: S.reveal.completes, missing: S.reveal.missing, ok: !!S.reveal.oid } : null,
      react: S.react ? { word: S.react.word, col: S.react.col, line: S.react.line, who: S.react.who, stars: S.react.stars, tip: S.react.tip } : null,
      cut: S.cut ? { name: VEG[S.cut.k], cuts: S.cut.cuts, of: CUTS } : null, stock: { ...stock },
      badges: { cut: S.cut ? S.cut.cuts + ' / ' + CUTS : '', grill: grill.some(g => g && g.st === 'burnt') ? 'BURNING' : grill.some(g => g && g.press) ? 'SIZZLE' : grill.some(g => g && g.want && g.st === g.want) ? 'READY' : grill.some(Boolean) ? 'HOLD' : '', board: board.length ? board.length + ' ON' : '', fryer: fryer.some(f => f && f.st === 'burnt') ? 'BURNT' : fryer.some(f => f && f.st === 'done') ? 'READY' : fryer.some(Boolean) ? 'FRYING' : '', drinks: cups.some(c => c.fill >= 1) ? 'READY' : cups.length ? 'POURING' : '', bag: bag ? 'BAG!' : (tray.burgers.length || tray.fries || tray.drinks.length) ? 'TRAY' : '', all: orders.filter(o => o.st === 'wait').length ? orders.filter(o => o.st === 'wait').length + ' WAIT' : '' } }; }
  function emit() { onState(hud()); }
  frame();
  return { setSafe(top, bottom, left = 0) { if (Math.abs(SAFE.top - top) > 3 || Math.abs(SAFE.bottom - bottom) > 3 || Math.abs(SAFE.left - left) > 3) { SAFE.top = top; SAFE.bottom = bottom; SAFE.left = left; } }, revealChoice: c => S.reveal && revealDone(c), setFocus, demoStart, demoStop, startShift, endShift, giveCoin, buyUpgrade, hud, setPaused(v) { PAUSE = !!v; }, toIntro() { S.phase = 'intro'; S.done = null; setUniform(true); ben.visible = true; sizzle.visible = true; ben.position.set(-1.0, 0, K.z + 3.5); ben.rotation.y = 0.3; glideTo(wideShot(), 1); }, _pump(n = 1, dt = 1 / 30) { for (let i = 0; i < n; i++) step(dt); renderer.render(scene, camera); emit(); }, _skip(t) { S.t = Math.max(S.t, BURGERS.shift - t); }, _cutPos: () => { const r = renderer.domElement.getBoundingClientRect(), s = scr(V3(K.chop.x + 0.06, K.top + 0.1, K.chop.z)); return { x: r.left + s.x, y: r.top + s.y }; }, _state: () => S,
    _auto() { return { orders, grill, fryer, cups, tray, board, K, addToBoard, addPatty, addFries, addCup, serve: o => serve(o), bagIt: () => { bag = { burgers: tray.burgers.slice(), fries: tray.fries, drinks: tray.drinks.slice() }; tray.burgers = []; tray.fries = 0; tray.drinks = []; rebuildTray(); bagMesh.visible = true; bagMesh.position.set(K.bagStand.x, K.top + 0.06, K.bagStand.z); }, takeFries: i => { const f = fryer[i]; scene.remove(f.g); fryer[i] = null; tray.fries++; rebuildTray(); }, takeCup: i => { const c = cups[i]; scene.remove(c.g); cups.splice(i, 1); tray.drinks.push(c.k); rebuildTray(); } }; },
    destroy() { cancelAnimationFrame(raf); removeEventListener('resize', onRs); ro.disconnect(); removeEventListener('pointermove', onMove); removeEventListener('pointerup', onUp); renderer.dispose(); renderer.domElement.remove(); try { audio.ctx && audio.ctx.close(); } catch (e) {} } };
}
