// 8 GATES — JIDDA · SUBMARINE [jSubSchool] + [jSubMission]. JIB's yellow + red sub (8 crest both sides, clear bubble cockpit) on the Deep Dive seabed.
// SUB SCHOOL: 5 lessons (steer · dive · sonar · grab · dock). THE MISSION: find the sunken chest, free 3 trapped divers, fight off the giant squid, dock home.
// Buttons: TAP 1 = arm (grab / whack a creature / ZAP the squid) · else SONAR · HOLD 1 = torpedo (always armed, homing; red crates +4) · creatures: pufferfish, crabs, angler fish · 2 DOWN 8 m · 3 UP 8 m. Desktop extra: R sonar, F torpedo.
// Easy by design: hull empty = JIB tows you back (+15 s), nothing is lost; docking under the boat repairs the hull.
import * as THREE from '../../vendor/three/three.module.js';
import { rr, pick, clamp, damp, makeGradient, glowTexture, Ambience, smooth } from '../../village-game.js';
import { crestTex, canvasTex } from '../../meru-game.js';
import { foxKit, PLAYER_MALE } from '../../fox-kit.js';
import { castKit } from '../../engine/cast.js';
import { save } from '../../engine/save.js';

export const PLACES = [
  { id: 'school', name: 'SUB SCHOOL', room: 'jSubSchool', built: true, target: 180, goal: '5 lessons with JIB', line: 'JIB teaches you the sub: steer through rings, dive and climb, ping the sonar, work the grabber arm, and park her back in the dock.' },
  { id: 'mission', name: 'THE MISSION', room: 'jSubMission', built: true, target: 300, goal: 'Treasure · divers · squid', line: 'Find the sunken chest, free the three trapped divers, then fight off the giant squid with torpedoes and bring the chest home.' }];
export const SUB = { SPEED: 7, DRAG: 1.7, STEP: 8, VY: 5, HULL: 100, PING_CD: 1.4, PING_R: 55, TORPS: 10, REACH: 3.8, SQUID_HP: 8, TOW: 15 };
const sstep = (e0, e1, x) => { const t = clamp((x - e0) / (e1 - e0), 0, 1); return t * t * (3 - 2 * t); };
const lerp = (a, b, k) => a + (b - a) * k;

export async function createSub({ container, onState = () => {} }) {
  const touch = matchMedia('(pointer: coarse)').matches, CW = () => container.clientWidth || 1, CHh = () => container.clientHeight || 1;
  const renderer = new THREE.WebGLRenderer({ antialias: !touch }); renderer.setPixelRatio(Math.min(devicePixelRatio, touch ? 1.5 : 2)); renderer.setSize(CW(), CHh());
  renderer.domElement.style.cssText = 'display:block;width:100%;height:100%;touch-action:none;outline:none'; container.appendChild(renderer.domElement);
  const scene = new THREE.Scene(); scene.background = new THREE.Color(0x2a9fc0); scene.fog = new THREE.Fog(0x2a9fc0, 4, 60);
  const camera = new THREE.PerspectiveCamera(60, CW() / CHh(), 0.1, 1200);
  const grad = makeGradient(), glowTex = glowTexture(), cache = new Map(), V3 = (x = 0, y = 0, z = 0) => new THREE.Vector3(x, y, z);
  const toon = (c, extra) => { const k = c + (extra ? JSON.stringify(extra) : ''); if (!cache.has(k)) cache.set(k, new THREE.MeshToonMaterial({ color: c, gradientMap: grad, ...extra })); return cache.get(k); };
  const outlineMat = new THREE.MeshBasicMaterial({ color: 0x1a1626, side: THREE.BackSide });
  function addOutline(mesh, t = 0.04, radius) { const g = mesh.geometry; g.computeBoundingBox(); const s = V3(); g.boundingBox.getSize(s); const o = new THREE.Mesh(g, outlineMat); if (radius) o.scale.setScalar(1 + t / radius); else o.scale.set(1 + 2 * t / Math.max(s.x, 0.01), 1 + 2 * t / Math.max(s.y, 0.01), 1 + 2 * t / Math.max(s.z, 0.01)); mesh.add(o); return mesh; }
  const WORLD = new THREE.Group(); scene.add(WORLD);
  function M(geo, mat, x = 0, y = 0, z = 0, parent, outline = 0.04, radius) { const m = new THREE.Mesh(geo, mat); m.position.set(x, y, z); if (outline) addOutline(m, outline, radius); (parent || WORLD).add(m); return m; }
  const kit = foxKit({ THREE, scene, toon, M, grad, outlineMat, crestTex, rr, pick, clamp, smooth, damp }), cast = castKit({ THREE, M, toon, makeFox: kit.makeFox });
  const audio = new Ambience();
  const hemi = new THREE.HemisphereLight(0xcff4ff, 0x0b3a52, 1.1), sunL = new THREE.DirectionalLight(0xe8fbff, 1.6); sunL.position.set(10, 40, -10); scene.add(hemi, sunL);
  const ink = toon('#201e1d'), white = toon('#f3f2f2'), red = toon('#ec3013'), yel = toon('#ffd23a'), steel = toon('#7d8790');
  const glowMat = (c, o = 0.8) => new THREE.SpriteMaterial({ map: glowTex, color: c, transparent: true, depthWrite: false, opacity: o, fog: false });

  // ---------- FX ----------
  const SPN = touch ? 70 : 120, sprays = []; let spI = 0;
  for (let i = 0; i < SPN; i++) { const m = new THREE.Sprite(new THREE.SpriteMaterial({ map: glowTex, color: 0xffffff, transparent: true, depthWrite: false, opacity: 0 })); m.visible = false; scene.add(m); sprays.push({ m, v: V3(), life: 0, max: 1, s: 1, g: 9 }); }
  function spray(p, n, spd, size = 1, life = 0.9, col = 0xffffff, g = -2.5) { for (let k = 0; k < n; k++) { const s = sprays[spI = (spI + 1) % SPN]; s.m.position.copy(p); s.m.position.x += rr(-0.3, 0.3); s.m.position.z += rr(-0.3, 0.3); s.v.set(rr(-1, 1) * spd * 0.5, rr(0.3, 1) * spd, rr(-1, 1) * spd * 0.5); s.life = s.max = life * rr(0.7, 1.2); s.s = size * rr(0.7, 1.3); s.g = g; s.m.material.color.setHex(col); s.m.visible = true; } }
  const bubbles = (p, n = 3) => spray(p, n, 0.6, 0.3, 1.4, 0xdff6ff, -3);
  function fxStep(dt) { for (const s of sprays) { if (s.life <= 0) continue; s.life -= dt; if (s.life <= 0) { s.m.visible = false; continue; } s.v.y -= s.g * dt; s.m.position.addScaledVector(s.v, dt); const u = 1 - s.life / s.max; s.m.material.opacity = 0.8 * (1 - u); s.m.scale.setScalar(s.s * (0.7 + u * 0.6)); } }
  const bangTex = canvasTex(64, 64, g => { g.fillStyle = '#ec3013'; g.fillRect(4, 4, 56, 56); g.strokeStyle = '#ffffff'; g.lineWidth = 5; g.strokeRect(6, 6, 52, 52); g.fillStyle = '#fff'; g.font = '900 46px Archivo, sans-serif'; g.textAlign = 'center'; g.textBaseline = 'middle'; g.fillText('!', 32, 35); });
  const mkBang = (parent, y, s = 0.8) => { const b = new THREE.Sprite(new THREE.SpriteMaterial({ map: bangTex, transparent: true, depthWrite: false, depthTest: false })); b.scale.set(s, s, 1); b.position.y = y; b.visible = false; b.renderOrder = 5; parent.add(b); return b; };
  const signTex = (txt, bg, fg) => canvasTex(256, 96, g => { g.fillStyle = bg; g.fillRect(0, 0, 256, 96); g.strokeStyle = '#201e1d'; g.lineWidth = 8; g.strokeRect(4, 4, 248, 88); g.fillStyle = fg; let fs = 52; g.font = '900 ' + fs + 'px Archivo, sans-serif'; const tw = g.measureText(txt).width; if (tw > 220) { fs = Math.floor(fs * 220 / tw); g.font = '900 ' + fs + 'px Archivo, sans-serif'; } g.textBaseline = 'middle'; g.fillText(txt, 18, 52); });
  const sign = (txt, x, y, z, bg = '#ffd23a', fg = '#201e1d', parent, w = 3.4) => { const sp = new THREE.Sprite(new THREE.SpriteMaterial({ map: signTex(txt, bg, fg), transparent: true, depthWrite: false, fog: false })); sp.scale.set(w, w * 0.375, 1); sp.position.set(x, y, z); (parent || WORLD).add(sp); return sp; };

  // ---------- THE SEABED (same as THE DEEP): shelf by the boat → slope → the trench ----------
  const floor = (x, z) => { const shelf = -9 - 2 * Math.sin(x * 0.12) * Math.sin(z * 0.1), slope = -26 - 3 * Math.sin(x * 0.09 + z * 0.05), abyss = -54 - 4 * Math.sin(x * 0.07) - 6 * sstep(25, 55, Math.abs(x)) * -1; let y = lerp(shelf, slope, sstep(30, 60, z)); y = lerp(y, abyss, sstep(100, 125, z)); y += 10 * sstep(28, 60, Math.abs(x)) * sstep(90, 120, z); return y; };
  { const n = touch ? 90 : 130, g = new THREE.PlaneGeometry(160, 260, n, n); g.rotateX(-Math.PI / 2); g.translate(0, 0, 80); const p = g.attributes.position, col = new Float32Array(p.count * 3), sand = new THREE.Color('#e3cf9a'), mid = new THREE.Color('#6f8f86'), deep = new THREE.Color('#2b3b4a'), tc = new THREE.Color();
    for (let i = 0; i < p.count; i++) { const x = p.getX(i), z = p.getZ(i), y = floor(x, z); p.setY(i, y); tc.copy(sand).lerp(mid, sstep(-10, -28, y)).lerp(deep, sstep(-28, -55, y)); const k = 0.05 * Math.sin(x * 1.1) * Math.sin(z * 0.9); col[i * 3] = tc.r + k; col[i * 3 + 1] = tc.g + k; col[i * 3 + 2] = tc.b + k; }
    g.setAttribute('color', new THREE.BufferAttribute(col, 3)); g.computeVertexNormals(); WORLD.add(new THREE.Mesh(g, new THREE.MeshToonMaterial({ vertexColors: true, gradientMap: grad }))); }
  const surf = new THREE.Mesh(new THREE.PlaneGeometry(600, 600), new THREE.MeshBasicMaterial({ color: 0x9fe6f2, transparent: true, opacity: 0.55, side: THREE.DoubleSide, depthWrite: false, fog: false })); surf.rotation.x = -Math.PI / 2; scene.add(surf);
  const shafts = []; for (let i = 0; i < (touch ? 8 : 14); i++) { const s = new THREE.Mesh(new THREE.PlaneGeometry(2.4, 24), new THREE.MeshBasicMaterial({ map: glowTex, color: 0xdff6ff, transparent: true, opacity: 0.12, depthWrite: false, side: THREE.DoubleSide, blending: THREE.AdditiveBlending })); s.position.set(rr(-30, 30), -11, rr(-10, 60)); s.rotation.z = 0.2; scene.add(s); shafts.push(s); }
  const boat = new THREE.Group(); scene.add(boat); M(new THREE.BoxGeometry(3, 1.2, 7), white, 0, 0.1, 0, boat, 0.05); M(new THREE.BoxGeometry(3.1, 0.25, 7.1), red, 0, 0.75, 0, boat, 0.03); M(new THREE.BoxGeometry(2, 1.4, 2), toon('#38bdf8'), 0, 1.4, -1.5, boat, 0.04); M(new THREE.ConeGeometry(1.5, 2.2, 4), white, 0, 0.1, 4.4, boat, 0.04).rotation.x = Math.PI / 2;
  const jib = kit.makeFox({ key: 'jib', torso: ['#fff4e2', '#38bdf8', '#1e6f9a'], outfit: 'vest', look: { ...PLAYER_MALE, fur: '#e8b277', furDark: '#8a5a2b', tailMid: '#f3e2c4', tailTip: '#ffffff', armorAccent: '#38bdf8' }, mood: 'neutral' }); jib.scale.setScalar(1.3); jib.position.set(0, 0.85, 1.4); boat.add(jib);
  // THE DOCK: an open steel cage hanging under JIB's boat, open toward the sea (+z)
  const DOCK = { x: 0, y: -4.5, z: -6, hx: 2.9, hy: 2.6, hz: 4 };
  { const d = DOCK; for (const sx of [-1, 1]) for (const sz of [-1, 1]) M(new THREE.BoxGeometry(0.3, d.hy * 2 + 4.5, 0.3), steel, d.x + sx * d.hx, d.y + 2.2, d.z + sz * d.hz, null, 0.03); for (const sx of [-1, 1]) M(new THREE.BoxGeometry(0.3, 0.3, d.hz * 2), steel, d.x + sx * d.hx, d.y + d.hy, d.z, null, 0.03); M(new THREE.BoxGeometry(d.hx * 2, 0.3, 0.3), steel, d.x, d.y + d.hy, d.z - d.hz, null, 0.03); M(new THREE.BoxGeometry(d.hx * 2 + 0.3, 0.25, d.hz * 2), toon('#3a3f44'), d.x, d.y - d.hy, d.z, null, 0.03);
    DOCK.lights = []; for (const sx of [-1, 1]) for (let k = 0; k < 3; k++) { const s = new THREE.Sprite(glowMat(0xffd23a, 0.9)); s.scale.setScalar(1.1); s.position.set(d.x + sx * (d.hx - 0.1), d.y - d.hy + 0.4, d.z + d.hz - k * 3.6); scene.add(s); DOCK.lights.push(s); }
    DOCK.sign = sign('DOCK', d.x, d.y + d.hy + 1.2, d.z + d.hz, '#ffd23a', '#201e1d', null, 3); }
  const inDock = s => Math.abs(s.x - DOCK.x) < DOCK.hx - 0.4 && Math.abs(s.z - DOCK.z) < DOCK.hz && Math.abs(s.y - DOCK.y) < DOCK.hy;

  // ---------- KEY PLACES (rocks keep clear of them) ----------
  const RINGS = { steer: [[0, -4, 14], [9, -4, 24], [-6, -4, 34], [3, -4, 44]], dive: [[0, -12, 54, 'DOWN · 2'], [0, -20, 64, 'DOWN · 2'], [0, -12, 78, 'UP · 3']] };
  const BEACONS = [[-16, 70], [18, 84], [-6, 96]], CRATES = [[10, 102], [-12, 106], [2, 112]], CHEST = [-3, 148], WRECK = [-8, 151], DIVERS = [[16, 122], [-20, 114], [9, 136]], AMMO = [[-10, 24], [14, 50], [-18, 80], [20, 96], [-4, 122], [-14, 158], [14, 146]], SQUID_HOME = [0, 172];
  const keyPts = [...RINGS.steer, ...RINGS.dive].map(r => [r[0], r[2]]).concat(BEACONS, CRATES, [CHEST, WRECK], DIVERS, AMMO, [[0, -6], [0, 0]]);
  const clear = (x, z, r) => keyPts.every(([kx, kz]) => Math.hypot(x - kx, z - kz) > r + 5) && Math.abs(x) > 4;

  // ---------- DECOR ----------
  const cc = ['#f472b6', '#ffd23a', '#ec3013', '#a78bfa', '#5ec97e', '#fb923c'];
  for (let i = 0; i < (touch ? 50 : 90); i++) { const x = rr(-45, 45), z = rr(-15, 55), y = floor(x, z), c = toon(pick(cc)); if (Math.random() < 0.5) M(new THREE.ConeGeometry(rr(0.25, 0.5), rr(0.8, 1.8), 6), c, x, y + 0.5, z, null, 0.03); else M(new THREE.SphereGeometry(rr(0.4, 0.8), 8, 6), c, x, y + 0.2, z, null, 0.03).scale.y = 0.6; }
  const rocks = [];
  const rock = (x, z, r) => { const y = floor(x, z) + r * 0.4, m = M(new THREE.DodecahedronGeometry(r, 0), toon(pick(['#5f6b73', '#4f5a62', '#6b7680'])), x, y, z, null, 0.06); m.rotation.set(rr(0, 3), rr(0, 3), 0); rocks.push({ x, y, z, r: r * 0.92 }); };
  for (let i = 0, n = 0; i < 200 && n < 22; i++) { const x = rr(-44, 44), z = rr(10, 170), r = rr(1.4, 3.2); if (clear(x, z, r)) { rock(x, z, r); n++; } }
  for (const [x, z] of [[-28, 44], [26, 96]]) { const y0 = floor(x, z); for (const s of [-1, 1]) for (let k = 0; k < 3; k++) { const r = 1.5 - k * 0.15, px = x + s * 4, py = y0 + 1 + k * 2.4; M(new THREE.DodecahedronGeometry(r, 0), toon('#55606a'), px, py, z, null, 0.05); rocks.push({ x: px, y: py, z, r }); } for (let k = -2; k <= 2; k++) { const px = x + k * 2, py = y0 + 8 - Math.abs(k) * 0.4; M(new THREE.DodecahedronGeometry(1.4, 0), toon('#55606a'), px, py, z, null, 0.05); rocks.push({ x: px, y: py, z, r: 1.3 }); } }
  const kelpM = []; for (const k of [{ x: 30, z: 30, r: 8 }, { x: -32, z: 64, r: 8 }]) for (let i = 0; i < (touch ? 20 : 34); i++) { const a = rr(0, 6.28), r = rr(0, k.r), x = k.x + Math.cos(a) * r, z = k.z + Math.sin(a) * r, y = floor(x, z), h = rr(5, 10), s = M(new THREE.CylinderGeometry(0.06, 0.16, h, 4), toon(pick(['#3f8f3a', '#2f6f3a', '#5c9a43'])), x, y + h / 2, z, null, 0); s.userData.ph = rr(0, 6); kelpM.push(s); }
  const snowN = touch ? 500 : 900, snowG = new THREE.BufferGeometry(), snowP = new Float32Array(snowN * 3); for (let i = 0; i < snowN; i++) { snowP[i * 3] = rr(-25, 25); snowP[i * 3 + 1] = rr(-25, 25); snowP[i * 3 + 2] = rr(-25, 25); } snowG.setAttribute('position', new THREE.BufferAttribute(snowP, 3)); const snow = new THREE.Points(snowG, new THREE.PointsMaterial({ color: 0xdff6ff, size: 0.08, transparent: true, opacity: 0.6, depthWrite: false })); scene.add(snow);
  const fishes = [], dm = new THREE.Object3D();
  function fishSchool(cx, cy, cz, n, col, r = 6) { const im = new THREE.InstancedMesh(new THREE.ConeGeometry(0.14, 0.5, 5), toon(col), n); im.frustumCulled = false; WORLD.add(im); fishes.push({ im, cx, cy, cz, n, r, ph: Array.from({ length: n }, () => [rr(0, 6.28), rr(0.6, 1), rr(-0.8, 0.8)]) }); }
  [[-14, -5, 20, '#ffd23a'], [16, -7, 38, '#38bdf8'], [-8, -16, 72, '#fb923c'], [14, -24, 104, '#a78bfa']].forEach(([x, y, z, c]) => fishSchool(x, y, z, touch ? 14 : 22, c));
  const jellies = []; for (let i = 0; i < 9; i++) { let x = 0, z = 0; for (let k = 0; k < 20; k++) { x = rr(-30, 30); z = rr(20, 160); if (clear(x, z, 2)) break; } const y = rr(floor(x, z) + 4, -4), g = new THREE.Group(); g.add(new THREE.Mesh(new THREE.SphereGeometry(0.6, 12, 8, 0, 6.3, 0, 1.6), new THREE.MeshToonMaterial({ color: pick(['#f472b6', '#a78bfa', '#7dd3fc']), gradientMap: grad, transparent: true, opacity: 0.8, emissive: new THREE.Color('#5a2a6a'), emissiveIntensity: 0.4 }))); for (let k = 0; k < 6; k++) { const t = new THREE.Mesh(new THREE.CylinderGeometry(0.03, 0.02, 1.3, 4), toon('#f9b4d4')); t.position.set(Math.cos(k * 1.05) * 0.3, -0.65, Math.sin(k * 1.05) * 0.3); g.add(t); } WORLD.add(g); jellies.push({ g, x, y, z, hx: x, hy: y, hz: z, ph: rr(0, 6) }); }

  // ---------- SCHOOL: rings, sonar beacons, practice crates ----------
  const ringMat = new THREE.MeshBasicMaterial({ color: 0xffd23a, transparent: true, opacity: 1 }), ringMatDim = new THREE.MeshBasicMaterial({ color: 0xffd23a, transparent: true, opacity: 0.25, depthWrite: false });
  const rings = {}; for (const set of ['steer', 'dive']) { rings[set] = RINGS[set].map(([x, y, z, hint], i, a) => { const m = new THREE.Mesh(new THREE.TorusGeometry(2.8, 0.24, 8, 32), ringMat); m.position.set(x, y, z); const n = a[i + 1] || [x, y, z + 10]; m.lookAt(n[0], y, n[2]); scene.add(m); const lb = sign(hint || 'RING ' + (i + 1), x, y + 3.9, z, '#ffd23a', '#201e1d', null, 3); return { x, y, z, hint, m, lb, done: false }; }); }
  const beacons = BEACONS.map(([x, z]) => { const y = floor(x, z) + 1, g = new THREE.Group(); g.position.set(x, y, z); WORLD.add(g); M(new THREE.CylinderGeometry(0.35, 0.5, 1.4, 8), toon('#3a3f44'), 0, 0, 0, g, 0.03); const tip = M(new THREE.SphereGeometry(0.3, 10, 8), new THREE.MeshBasicMaterial({ color: 0x7dd3fc }), 0, 0.9, 0, g, 0); const gl = new THREE.Sprite(glowMat(0x7dd3fc, 0.9)); gl.scale.setScalar(4); gl.position.y = 0.9; g.add(gl); const lb = sign('BEACON', 0, 3.2, 0, '#7dd3fc', '#201e1d', g, 3); return { x, y, z, g, gl, tip, lb, seen: false, found: false }; });
  const crateMat = toon('#e6b45a');
  const mkCrate = (x, z, col = crateMat, txt) => { const y = floor(x, z) + 0.6, g = new THREE.Group(); g.position.set(x, y, z); g.rotation.y = rr(0, 3); WORLD.add(g); M(new THREE.BoxGeometry(1.2, 1.2, 1.2), col, 0, 0, 0, g, 0.04); M(new THREE.BoxGeometry(1.26, 0.18, 1.26), ink, 0, 0.3, 0, g, 0); M(new THREE.BoxGeometry(1.26, 0.18, 1.26), ink, 0, -0.3, 0, g, 0); M(new THREE.TorusGeometry(0.22, 0.06, 6, 10), steel, 0, 0.72, 0, g, 0).rotation.x = Math.PI / 2; const gl = new THREE.Sprite(glowMat(0xffd23a, 0.5)); gl.scale.setScalar(2.6); g.add(gl); const lb = txt ? sign(txt, 0, 2, 0, '#ec3013', '#ffffff', g, 2.6) : null; return { x, y, z, hy: y, g, gl, lb, held: 0, taken: false }; };
  const crates = CRATES.map(([x, z]) => mkCrate(x, z));

  // ---------- MISSION: the wreck + chest, trapped divers, ammo crates ----------
  { const [x, z] = WRECK, y = floor(x, z), g = new THREE.Group(); g.position.set(x, y + 1.2, z); g.rotation.set(0.15, 0.6, 0.35); WORLD.add(g); const wood = toon('#6b4a2a'), dark = toon('#4a321c');
    M(new THREE.BoxGeometry(3.6, 2.4, 13), wood, 0, 0, 0, g, 0.06); M(new THREE.BoxGeometry(3.8, 0.4, 13.2), dark, 0, 1.2, 0, g, 0.03); M(new THREE.BoxGeometry(2.6, 1.6, 3), dark, 0, 2, -4.4, g, 0.04); const mast = M(new THREE.CylinderGeometry(0.22, 0.28, 9, 6), dark, 0, 5, 1, g, 0.03); mast.rotation.z = 0.9; M(new THREE.ConeGeometry(1.9, 3, 4), wood, 0, 0, 7.8, g, 0.04).rotation.x = Math.PI / 2; for (let k = 0; k < 3; k++) M(new THREE.TorusGeometry(0.36, 0.08, 6, 12), toon('#2b2a33'), 1.85, 0.2, -3 + k * 3, g, 0).rotation.y = Math.PI / 2;
    rocks.push({ x, y: y + 1.2, z, r: 3.2 }, { x: x + 3, y: y + 1.6, z: z + 4.5, r: 2.4 }, { x: x - 3, y: y + 0.8, z: z - 4.5, r: 2.4 }); }
  const chest = (() => { const [x, z] = CHEST, y = floor(x, z) + 0.5, g = new THREE.Group(); g.position.set(x, y, z); g.rotation.y = 0.4; WORLD.add(g); M(new THREE.BoxGeometry(1.6, 0.9, 1), toon('#7a4f2a'), 0, 0, 0, g, 0.04); const lid = M(new THREE.CylinderGeometry(0.5, 0.5, 1.6, 10, 1, false, 0, Math.PI), toon('#8a5a2b'), 0, 0.45, 0, g, 0.03); lid.rotation.z = Math.PI / 2; for (const s of [-0.55, 0.55]) M(new THREE.BoxGeometry(0.14, 1.5, 1.06), yel, s, 0.2, 0, g, 0); M(new THREE.BoxGeometry(0.24, 0.3, 0.08), yel, 0, 0.2, 0.52, g, 0); const gl = new THREE.Sprite(glowMat(0xffd23a, 0.0)); gl.scale.setScalar(5); gl.position.y = 0.6; g.add(gl); const lb = sign('TREASURE', 0, 2.6, 0, '#ffd23a', '#201e1d', g, 3); lb.visible = false; return { x, y, z, hy: y, g, gl, lb, seen: false, held: false }; })();
  const divers = DIVERS.map(([x, z], i) => { const y = floor(x, z), cols = [['#ffd23a', '#ec3013'], ['#38bdf8', '#201e1d'], ['#5ec97e', '#ffd23a']][i];
    const f = kit.makeFox({ key: 'diver' + i, torso: ['#fff4e2', cols[0], cols[1]], outfit: 'vest', look: { ...PLAYER_MALE, fur: ['#d9822b', '#c8a27a', '#9a6b3f'][i], armorAccent: cols[0] }, mood: 'sad' }); f.position.set(x, y, z); f.rotation.y = rr(0, 6); WORLD.add(f);
    M(new THREE.CylinderGeometry(0.2, 0.2, 0.8, 10), yel, 0, 1.3, -0.4, f, 0.02);
    const net = new THREE.Mesh(new THREE.SphereGeometry(1.9, 12, 8, 0, 6.3, 0, 1.7), new THREE.MeshBasicMaterial({ color: 0x2f4a2a, wireframe: true, transparent: true, opacity: 0.85 })); net.position.set(x, y, z); WORLD.add(net);
    for (let k = 0; k < 4; k++) M(new THREE.SphereGeometry(0.22, 6, 5), steel, x + Math.cos(k * 1.57) * 1.8, y + 0.1, z + Math.sin(k * 1.57) * 1.8, null, 0);
    const lb = sign('HELP!', x, y + 4.4, z, '#ec3013', '#ffffff', null, 2.6), balloon = M(new THREE.SphereGeometry(0.9, 12, 10), yel, 0, 4.3, 0, f, 0.04); balloon.visible = false; balloon.scale.y = 1.2;
    return { x, y, z, hy: y, f, net, lb, balloon, freed: false, up: 0 }; });
  const ammos = AMMO.map(([x, z]) => Object.assign(mkCrate(x, z, toon('#ec3013'), 'TORPEDOES'), { ammo: true, back: 0 }));
  // ---------- CREATURES: hit them with the arm (tap 1) or a torpedo (hold 1) ----------
  const critters = [], eyeW = toon('#ffffff');
  const eyes = (g, x, y, z, r = 0.12) => { for (const s of [-1, 1]) { M(new THREE.SphereGeometry(r, 8, 6), eyeW, s * x, y, z, g, 0.02); M(new THREE.SphereGeometry(r * 0.55, 6, 5), ink, s * (x + 0.02), y, z + r * 0.7, g, 0); } };
  function mkPuffer(x, y, z) { const g = new THREE.Group(), b = new THREE.Group(); g.add(b); M(new THREE.SphereGeometry(0.55, 14, 10), toon('#f5a623'), 0, 0, 0, b, 0.04, 0.55); M(new THREE.SphereGeometry(0.5, 12, 8, 0, 6.3, 1.7, 1.4), toon('#fff1c9'), 0, -0.04, 0, b, 0); for (let k = 0; k < 14; k++) { const a = k * 2.4, e = Math.acos(1 - 2 * (k + 0.5) / 14), d = V3(Math.sin(e) * Math.cos(a), Math.cos(e), Math.sin(e) * Math.sin(a)), sp = new THREE.Mesh(new THREE.ConeGeometry(0.07, 0.3, 4), toon('#8a4b12')); sp.position.copy(d).multiplyScalar(0.6); sp.lookAt(d.clone().multiplyScalar(2)); sp.rotateX(Math.PI / 2); b.add(sp); } eyes(b, 0.22, 0.15, 0.42); const t1 = M(new THREE.ConeGeometry(0.22, 0.36, 4), toon('#f5a623'), 0, 0, -0.66, b, 0.02); t1.rotation.x = -Math.PI / 2; WORLD.add(g); return { kind: 'puffer', name: 'PUFFERFISH', g, b, x, y, z, hx: x, hy: y, hz: z, hp: 1, max: 1, r: 0.8, pts: 80, dmg: 6, ph: rr(0, 6) }; }
  function mkCrab(x, z) { const y = floor(x, z) + 0.35, g = new THREE.Group(), b = new THREE.Group(); g.add(b); const sh = toon('#e0452b'), dk = toon('#9e2a18'); const bd = M(new THREE.SphereGeometry(0.62, 14, 8), sh, 0, 0, 0, b, 0.04, 0.62); bd.scale.set(1.3, 0.5, 1); for (const s of [-1, 1]) { for (let k = 0; k < 3; k++) { const lg = M(new THREE.CylinderGeometry(0.04, 0.05, 0.6, 4), dk, s * 0.8, -0.1, -0.25 + k * 0.25, b, 0); lg.rotation.z = s * 1.0; } const cl = M(new THREE.SphereGeometry(0.22, 8, 6), sh, s * 0.7, 0.1, 0.62, b, 0.03); cl.scale.set(1, 0.7, 1.3); M(new THREE.ConeGeometry(0.1, 0.3, 4), dk, s * 0.62, 0.12, 0.85, b, 0).rotation.x = Math.PI / 2; } for (const s of [-1, 1]) M(new THREE.CylinderGeometry(0.03, 0.03, 0.3, 4), dk, s * 0.18, 0.4, 0.35, b, 0); eyes(b, 0.18, 0.58, 0.36, 0.09); g.position.set(x, y, z); WORLD.add(g); return { kind: 'crab', name: 'CRAB', g, b, x, y, z, hx: x, hy: y, hz: z, hp: 1, max: 1, r: 0.9, pts: 60, dmg: 4, ph: rr(0, 6) }; }
  function mkAngler(x, y, z) { const g = new THREE.Group(), b = new THREE.Group(); g.add(b); const sk = toon('#4a3a5e'); M(new THREE.SphereGeometry(0.95, 14, 10), sk, 0, 0, 0, b, 0.05, 0.95); const jaw = M(new THREE.SphereGeometry(0.85, 14, 8, 0, 6.3, 1.6, 1.2), toon('#2a2036'), 0, -0.12, 0.25, b, 0); for (let k = 0; k < 7; k++) { const a = -1 + k / 6 * 2, tt = M(new THREE.ConeGeometry(0.06, 0.24, 4), eyeW, Math.sin(a) * 0.62, -0.18, 0.7 + Math.cos(a) * 0.15, b, 0); tt.rotation.x = Math.PI; } eyes(b, 0.35, 0.42, 0.62, 0.15); const t1 = M(new THREE.ConeGeometry(0.5, 0.8, 4), sk, 0, 0, -1.2, b, 0.03); t1.rotation.x = -Math.PI / 2; const st = M(new THREE.CylinderGeometry(0.03, 0.03, 1.2, 4), sk, 0, 1.25, 0.5, b, 0); st.rotation.x = 0.7; const lure = new THREE.Sprite(glowMat(0x9effc8, 0.95)); lure.scale.setScalar(1.3); lure.position.set(0, 1.6, 1.0); b.add(lure); M(new THREE.SphereGeometry(0.1, 8, 6), new THREE.MeshBasicMaterial({ color: 0xd8ffe8 }), 0, 1.6, 1.0, b, 0); WORLD.add(g); return { kind: 'angler', name: 'ANGLER FISH', g, b, x, y, z, hx: x, hy: y, hz: z, hp: 2, max: 2, r: 1.3, pts: 150, dmg: 8, ph: rr(0, 6), cd: 0 }; }
  const spot = (z0, z1, r = 2) => { for (let k = 0; k < 40; k++) { const x = rr(-30, 30), z = rr(z0, z1); if (clear(x, z, r) && Math.hypot(x, z + 6) > 14) return [x, z]; } return [rr(-30, 30), rr(z0, z1)]; };
  for (let i = 0; i < 8; i++) { const [x, z] = spot(14, 150), fy = floor(x, z); critters.push(mkPuffer(x, rr(fy + 3, Math.min(-4, fy + 10)), z)); }
  for (let i = 0; i < 7; i++) { const [x, z] = spot(10, 115); critters.push(mkCrab(x, z)); }
  for (let i = 0; i < 3; i++) { const [x, z] = spot(112, 168, 3); critters.push(mkAngler(x, floor(x, z) + rr(4, 7), z)); }
  function hitCritter(c, how) { c.hp--; c.hitT = 0.35; spray(V3(c.x, c.y, c.z), 12, 3, 0.6, 0.7, 0xffd9a0, 0); audio.tone(how === 'arm' ? 340 : 200, 0.15, 0.06, 'square', 0.6); if (c.hp > 0) return flash(c.name + ' · ONE MORE HIT', '#ffd23a'); c.dead = 30; c.g.visible = false; spray(V3(c.x, c.y, c.z), 22, 4, 0.9, 1, 0xdff6ff, -2); award(c.name + (how === 'arm' ? ' · ARM WHACK' : ' · TORPEDO'), c.pts, '#ffd23a'); }
  function critterStep(dt, live) { for (const c of critters) { if (c.dead > 0) { c.dead -= dt; if (c.dead <= 0) { c.hp = c.max; c.x = c.hx; c.y = c.hy; c.z = c.hz; c.g.visible = true; } continue; } c.hitT = Math.max(0, (c.hitT || 0) - dt); c.cd = Math.max(0, (c.cd || 0) - dt); const dx = sub.x - c.x, dy = sub.y - c.y, dz = sub.z - c.z, d = Math.hypot(dx, dy, dz) || 1; let sc = 1;
      if (c.kind === 'puffer') { const a = TT * 0.35 + c.ph; c.x = lerp(c.x, c.hx + Math.cos(a) * 4, dt * 0.8); c.z = lerp(c.z, c.hz + Math.sin(a) * 4, dt * 0.8); c.y = c.hy + Math.sin(TT * 1.3 + c.ph) * 0.5; c.puff = damp(c.puff || 0, d < 7 ? 1 : 0, 4, dt); sc = 1 + c.puff * 0.7; c.g.rotation.y = Math.atan2(Math.cos(a + 1.57), -Math.sin(a + 1.57)) * 0 + a + Math.PI; }
      else if (c.kind === 'crab') { c.x = c.hx + Math.sin(TT * 0.7 + c.ph) * 3; c.y = floor(c.x, c.z) + 0.35; c.b.position.y = Math.abs(Math.sin(TT * 9)) * 0.05; c.g.rotation.y = c.ph; }
      else if (c.kind === 'angler') { const chase = live && d < 18 && c.cd <= 0, tx = chase ? sub.x : c.hx, ty = chase ? sub.y : c.hy, tz = chase ? sub.z : c.hz, mx = tx - c.x, my = ty - c.y, mz = tz - c.z, md = Math.hypot(mx, my, mz); if (md > 0.3) { const s = Math.min(md, (chase ? 2.6 : 1.5) * dt); c.x += mx / md * s; c.y += my / md * s; c.z += mz / md * s; } c.y = Math.max(c.y, floor(c.x, c.z) + 1.5); c.g.lookAt(chase ? sub.x : c.x + mx, c.y, chase ? sub.z : c.z + mz); }
      c.g.position.set(c.x, c.y, c.z); c.b.scale.setScalar(sc * (c.hitT > 0 ? 1.25 : 1));
      if (live && d < c.r * sc + 1.3) { if (hurt(c.dmg, c.name)) { sub.vx += dx / d * 5; sub.vz += dz / d * 5; c.cd = 3; if (c.kind === 'angler') { c.x -= dx / d * 3; c.z -= dz / d * 3; } } } } }

  // ---------- THE GIANT SQUID ----------
  const SQ = (() => { const g = new THREE.Group(); WORLD.add(g); const skin = toon('#c8394a'), dark = toon('#8e2433');
    M(new THREE.SphereGeometry(2.3, 16, 12), skin, 0, 0, 0, g, 0.08).scale.set(1, 0.9, 1.1);
    const mantle = M(new THREE.ConeGeometry(2.3, 9, 14), skin, 0, 0.3, -5.6, g, 0.08); mantle.rotation.x = -Math.PI / 2;
    for (const s of [-1, 1]) { const fin = M(new THREE.BoxGeometry(2.6, 0.18, 2.2), dark, s * 1.6, 0.3, -9, g, 0.04); fin.rotation.z = s * 0.2; }
    for (let k = 0; k < 7; k++) M(new THREE.SphereGeometry(rr(0.2, 0.4), 6, 5), dark, rr(-1.3, 1.3), rr(0.6, 1.6), rr(-8, -3), g, 0);
    const pupils = []; for (const s of [-1, 1]) { M(new THREE.SphereGeometry(0.85, 14, 10), white, s * 1.95, 0.5, 0.7, g, 0.04); pupils.push(M(new THREE.SphereGeometry(0.48, 12, 8), ink, s * 2.5, 0.5, 1.1, g, 0)); }
    const arms = []; for (let k = 0; k < 8; k++) { const a = k / 8 * 6.28, root = new THREE.Group(); root.position.set(Math.cos(a) * 1.3, Math.sin(a) * 1.1 - 0.2, 1.8); g.add(root); let p = root; const segs = []; for (let s = 0; s < 3; s++) { const sg = new THREE.Group(); sg.position.z = s ? 1.9 : 0; p.add(sg); const r0 = 0.5 - s * 0.14, mm = M(new THREE.CylinderGeometry(r0 - 0.12, r0, 2, 7), skin, 0, 0, 1, sg, 0.03); mm.rotation.x = Math.PI / 2; segs.push(sg); p = sg; } arms.push({ root, segs, a }); }
    const lashG = new THREE.CylinderGeometry(0.22, 0.42, 1, 7); lashG.translate(0, 0.5, 0); lashG.rotateX(Math.PI / 2); const lash = new THREE.Group(); scene.add(lash); const lm = new THREE.Mesh(lashG, skin); lash.add(lm); const club = M(new THREE.SphereGeometry(0.9, 10, 8), dark, 0, 0, 1, lash, 0.04); club.scale.set(1, 0.6, 1.6); lash.visible = false;
    const mark = new THREE.Mesh(new THREE.RingGeometry(2.8, 3.8, 32), new THREE.MeshBasicMaterial({ color: 0xec3013, transparent: true, opacity: 0.8, side: THREE.DoubleSide, depthWrite: false, depthTest: false })); mark.renderOrder = 6; scene.add(mark); mark.visible = false;
    const sq = { g, arms, lash, lm, club, mark, pupils, x: SQUID_HOME[0], y: -60, z: SQUID_HOME[1], hp: SUB.SQUID_HP, st: 'off', t: 0, cd: 3, stun: 0, mp: V3(), side: 1, on: false, hurtT: 0 }; sq.bang = mkBang(g, 3.6, 1.4); g.visible = false; return sq; })();

  // ---------- THE SUB (yellow, JIB's) with the player in the conning tower ----------
  const subG = new THREE.Group(); scene.add(subG); const body = new THREE.Group(); subG.add(body);
  const SUBFX = { pods: [], beacon: null };
  { const lb = red, gold = toon('#c8922e'), yelD = toon('#e6a800'), prof = [[0, -3.0], [0.34, -2.92], [0.62, -2.55], [0.86, -2.0], [1.04, -1.4], [1.1, -0.95], [1.1, 1.0], [1.075, 1.5], [0.98, 1.95], [0.8, 2.35], [0.5, 2.66], [0, 2.8]].map(([r, z]) => new THREE.Vector2(r, z));
    const hg = new THREE.LatheGeometry(prof, touch ? 22 : 30); hg.rotateX(Math.PI / 2); M(hg, yel, 0, 0, 0, body, 0.06);
    const belly = M(new THREE.CylinderGeometry(1.115, 1.115, 2.2, 22, 1, true, Math.PI * 0.62, Math.PI * 0.76), yelD, 0, 0, -0.05, body, 0); belly.rotation.x = Math.PI / 2; belly.material = toon('#e6a800', { side: THREE.DoubleSide });
    M(new THREE.TorusGeometry(1.105, 0.085, 6, 28), lb, 0, 0, 1.15, body, 0); M(new THREE.TorusGeometry(1.09, 0.085, 6, 28), lb, 0, 0, -1.1, body, 0);
    { const rv = new THREE.InstancedMesh(new THREE.SphereGeometry(0.035, 5, 4), gold, 64), o = new THREE.Object3D(); let n = 0; for (const [z, r] of [[1.32, 1.1], [0.98, 1.11], [-0.92, 1.11], [-1.28, 1.08]]) for (let k = 0; k < 16; k++) { const a = k / 16 * Math.PI * 2; o.position.set(Math.cos(a) * r, Math.sin(a) * r, z); o.updateMatrix(); rv.setMatrixAt(n++, o.matrix); } body.add(rv); }
    M(new THREE.BoxGeometry(0.22, 0.14, 4.2), lb, 0, -1.08, -0.1, body, 0.03);
    const deck = M(new THREE.CylinderGeometry(1.06, 1.15, 0.34, 24), yel, 0, 0.92, 0.2, body, 0.05); deck.scale.z = 1.25; M(new THREE.CylinderGeometry(0.98, 1.05, 0.24, 20), red, 0, 1.12, 0.2, body, 0.04);
    M(new THREE.TorusGeometry(1.0, 0.05, 6, 28), gold, 0, 1.25, 0.2, body, 0).rotation.x = Math.PI / 2;
    const dome = new THREE.Mesh(new THREE.SphereGeometry(0.86, 24, 16, 0, Math.PI * 2, 0, Math.PI / 2), new THREE.MeshToonMaterial({ color: '#bfeaff', emissive: new THREE.Color('#2a7fa8'), emissiveIntensity: 0.35, gradientMap: grad, transparent: true, opacity: 0.38, depthWrite: false, side: THREE.DoubleSide })); dome.position.set(0, 1.22, 0.2); dome.scale.setScalar(1.18); dome.renderOrder = 3; body.add(dome);
    { const rim = new THREE.Mesh(dome.geometry, new THREE.MeshBasicMaterial({ color: 0x1a1626, side: THREE.BackSide, transparent: true, opacity: 0.9 })); rim.scale.setScalar(1.05); dome.add(rim); for (const a of [0, Math.PI / 2]) { const fr = M(new THREE.TorusGeometry(0.87, 0.035, 6, 32, Math.PI), red, 0, 0, 0, null, 0); fr.rotation.y = a; dome.add(fr); } }
    const shine = new THREE.Mesh(new THREE.SphereGeometry(0.87, 16, 10, 0.4, 0.7, 0.35, 0.5), new THREE.MeshBasicMaterial({ color: 0xffffff, transparent: true, opacity: 0.75, depthWrite: false })); shine.position.copy(dome.position); shine.scale.setScalar(1.18); shine.renderOrder = 4; body.add(shine);
    const crestM = new THREE.MeshToonMaterial({ map: crestTex('8', '#ec3013'), gradientMap: grad, transparent: true, polygonOffset: true, polygonOffsetFactor: -2 }); for (const s of [-1, 1]) { const cg = new THREE.CylinderGeometry(1.112, 1.112, 1.2, 16, 1, true, (s > 0 ? Math.PI / 2 : Math.PI * 1.5) - 0.54, 1.08); cg.rotateX(Math.PI / 2); const cm = new THREE.Mesh(cg, crestM); cm.position.z = -0.55; body.add(cm); }
    { const ah = M(new THREE.CylinderGeometry(0.035, 0.05, 1.5, 5), steel, 0, 1.6, -1.15, body, 0); ah.rotation.x = -0.25; const bm = M(new THREE.SphereGeometry(0.12, 10, 8), new THREE.MeshBasicMaterial({ color: 0xec3013 }), 0, 2.32, -1.34, body, 0.02); const bg = new THREE.Sprite(glowMat(0xec3013, 0.9)); bg.scale.setScalar(1.1); bm.add(bg); SUBFX.beacon = bg; }
    M(new THREE.CylinderGeometry(0.05, 0.05, 0.9, 5), steel, 0.55, 1.5, -0.7, body, 0); M(new THREE.BoxGeometry(0.1, 0.12, 0.34), ink, 0.55, 1.95, -0.6, body, 0.02);
    for (const s of [-1, 1]) for (let k = 0; k < 2; k++) { const pz = 1.05 - k * 0.6; M(new THREE.TorusGeometry(0.2, 0.06, 6, 16), gold, s * 1.07, 0.2, pz, body, 0).rotation.y = Math.PI / 2; const gl = new THREE.Mesh(new THREE.CircleGeometry(0.18, 14), new THREE.MeshBasicMaterial({ color: 0x9fe6f2 })); gl.position.set(s * 1.1, 0.2, pz); gl.rotation.y = s * Math.PI / 2; body.add(gl); const sh = new THREE.Mesh(new THREE.CircleGeometry(0.06, 8), new THREE.MeshBasicMaterial({ color: 0xffffff })); sh.position.set(s * 1.112, 0.27, pz + s * 0.05); sh.rotation.y = s * Math.PI / 2; body.add(sh); }
    { const nr = M(new THREE.TorusGeometry(0.5, 0.07, 6, 20), lb, 0, 0, 2.62, body, 0); for (const s of [-1, 1]) { const hl = M(new THREE.CylinderGeometry(0.17, 0.2, 0.22, 12), ink, s * 0.55, 0.35, 2.32, body, 0.02); hl.rotation.x = Math.PI / 2; hl.rotation.z = -s * 0.25; const lens = new THREE.Mesh(new THREE.CircleGeometry(0.14, 12), new THREE.MeshBasicMaterial({ color: 0xfff4d6 })); lens.position.set(s * 0.57, 0.35, 2.44); body.add(lens); const g2 = new THREE.Sprite(glowMat(0xfff4d6, 0.85)); g2.scale.setScalar(1.3); g2.position.set(s * 0.57, 0.35, 2.5); body.add(g2); } }
    for (const s of [-1, 1]) { const pl = M(new THREE.BoxGeometry(0.9, 0.07, 0.45), lb, s * 1.4, -0.1, 1.55, body, 0.03); pl.rotation.z = s * -0.08; M(new THREE.BoxGeometry(0.06, 0.2, 0.47), ink, s * 1.85, -0.1, 1.55, body, 0); }
    for (const s of [-1, 1]) { const pod = new THREE.Group(); pod.position.set(s * 1.12, -0.6, -1.75); body.add(pod); M(new THREE.BoxGeometry(0.5, 0.12, 0.3), steel, -s * 0.2, 0, 0, pod, 0.02); const pc = M(new THREE.CapsuleGeometry(0.22, 0.7, 4, 12), yel, 0, 0, 0, pod, 0.04, 0.22); pc.rotation.x = Math.PI / 2; M(new THREE.SphereGeometry(0.23, 12, 8), lb, 0, 0, 0.5, pod, 0.03); M(new THREE.TorusGeometry(0.27, 0.05, 6, 16), ink, 0, 0, -0.62, pod, 0); const pp = new THREE.Group(); pp.position.z = -0.62; pod.add(pp); for (let k = 0; k < 3; k++) { const bl = new THREE.Mesh(new THREE.BoxGeometry(0.07, 0.42, 0.03), steel); bl.position.y = 0.12; const q = new THREE.Group(); q.rotation.z = k * 2.09; q.add(bl); pp.add(q); } SUBFX.pods.push(pp); }
    for (const s of [-1, 1]) { M(new THREE.CylinderGeometry(0.05, 0.05, 2.8, 6), steel, s * 0.6, -1.32, -0.1, body, 0.02).rotation.x = Math.PI / 2; for (const z of [-0.9, 0.7]) { const st = M(new THREE.BoxGeometry(0.06, 0.4, 0.06), ink, s * 0.5, -1.15, z, body, 0); st.rotation.z = s * 0.4; } }
    for (const rz of [0, Math.PI / 2]) { const fin = new THREE.Mesh(new THREE.BoxGeometry(2.3, 0.09, 0.7), lb); addOutline(fin, 0.03); fin.position.z = -2.45; fin.rotation.z = rz; body.add(fin); for (const s of [-1, 1]) { const tip = new THREE.Mesh(new THREE.BoxGeometry(0.12, 0.12, 0.78), ink); tip.position.set(Math.cos(rz) * s * 1.15, Math.sin(rz) * s * 1.15, -2.45); body.add(tip); } }
    M(new THREE.CylinderGeometry(0.62, 0.62, 0.5, 20, 1, true), toon('#ec3013', { side: THREE.DoubleSide }), 0, 0, -3.05, body, 0).rotation.x = Math.PI / 2; M(new THREE.TorusGeometry(0.62, 0.06, 6, 22), ink, 0, 0, -2.8, body, 0); M(new THREE.TorusGeometry(0.62, 0.06, 6, 22), ink, 0, 0, -3.3, body, 0);
    for (const s of [-1, 1]) M(new THREE.CylinderGeometry(0.16, 0.16, 0.9, 10), ink, s * 0.55, -0.7, 1.9, body, 0.02).rotation.x = Math.PI / 2;
  }
  const prop = new THREE.Group(); prop.position.set(0, 0, -3.05); body.add(prop); M(new THREE.SphereGeometry(0.18, 8, 6), steel, 0, 0, 0, prop, 0); for (let k = 0; k < 3; k++) { const b = M(new THREE.BoxGeometry(0.2, 0.52, 0.05), toon('#3a3f44'), 0, 0.3, 0, null, 0); const p = new THREE.Group(); p.rotation.z = k * 2.09; p.add(b); prop.add(p); b.rotation.y = 0.5; }
  // the grabber arm under the nose: shoulder → forearm → two claw fingers
  const arm = new THREE.Group(); arm.position.set(0, -0.95, 1.4); body.add(arm); M(new THREE.SphereGeometry(0.22, 8, 6), ink, 0, 0, 0, arm, 0); const fore = new THREE.Group(); arm.add(fore); M(new THREE.BoxGeometry(0.16, 0.16, 1.4), steel, 0, 0, 0.7, fore, 0.02); const hand = new THREE.Group(); hand.position.z = 1.4; fore.add(hand); const fingers = []; for (const s of [-1, 1]) { const f = new THREE.Group(); f.position.x = s * 0.12; hand.add(f); M(new THREE.BoxGeometry(0.08, 0.08, 0.5), red, 0, 0, 0.25, f, 0.02); fingers.push(f); }
  const pilot = cast.make('player', { gear: 'none' }); pilot.scale.setScalar(0.45); pilot.position.set(0, 0.62, 0.2); body.add(pilot);
  const lamp = new THREE.SpotLight(0xfff4d6, 0, 34, 0.6, 0.5, 1.1); lamp.position.set(0, 0.3, 2.6); subG.add(lamp); const lampT = new THREE.Object3D(); lampT.position.set(0, -2, 12); subG.add(lampT); lamp.target = lampT;
  const ping = new THREE.Mesh(new THREE.SphereGeometry(1, 28, 16), new THREE.MeshBasicMaterial({ color: 0x7dd3fc, transparent: true, opacity: 0, wireframe: true, depthWrite: false, fog: false })); scene.add(ping); ping.visible = false;
  const sub = { x: 0, y: -4, z: -6, vx: 0, vz: 0, vy: 0, yaw: 0, inv: 0, armX: 0, claw: V3() };
  const torps = []; for (let i = 0; i < 6; i++) { const g = new THREE.Group(); const c = M(new THREE.CapsuleGeometry(0.18, 0.9, 4, 8), steel, 0, 0, 0, g, 0.02); c.rotation.x = Math.PI / 2; M(new THREE.SphereGeometry(0.19, 8, 6), red, 0, 0, 0.62, g, 0); g.visible = false; scene.add(g); torps.push({ g, on: false, v: V3(), life: 0 }); }

  // ---------- STATE ----------
  const G = { phase: 'ready', board: true, place: 'school', stage: 0, ri: 0, t: 0, pen: 0, pts: 0, hull: SUB.HULL, ty: -4, pingCd: 0, pingT: 0, ink: 0, held: 0, torps: 0, armed: false, banner: '', bannerT: 0, radio: '', radioWho: 'JIB', radioT: 0, flash: null, flashT: 0, flashId: 0, done: null, count: 0, prompt: null, tows: 0, hits: 0, tok: 0, coins: 0, freed: 0, stowed: 0, found: 0, hintT: 0, chk: null };
  const say = (s, t = 2.4) => { G.banner = s; G.bannerT = t; };
  const radio = (s, who = 'JIB', t = 6) => { G.radio = s; G.radioWho = who; G.radioT = t; };
  const flash = (txt, col = '#ffd23a') => { G.flash = { txt, col, id: ++G.flashId }; G.flashT = 1.6; };
  const award = (name, v, col) => { G.pts += v; flash(name + '  +' + v, col); audio.tone(880 + Math.min(900, v), 0.12, 0.04, 'triangle', 1.4); return v; };
  const hint = s => { if (G.hintT > 0) return; G.hintT = 2.6; flash(s, '#7dd3fc'); };
  const hurt = (n, why) => { if (sub.inv > 0 || DM.on) return false; G.hull = Math.max(0, G.hull - n); sub.inv = 1.0; G.hits++; flash(why + ' · HULL -' + n, '#ec3013'); audio.tone(160, 0.3, 0.08, 'sawtooth', 0.5); bubbles(V3(sub.x, sub.y + 0.4, sub.z), 12); camShake = 0.5; return true; };
  const zone = y => y > -14 ? 'REEF' : y > -32 ? 'TWILIGHT' : 'ABYSS';
  let TT = 0, camShake = 0, PAUSE = false;

  // ---------- STAGES ----------
  const STAGES = {
    school: [
      { id: 'steer', name: 'LESSON 1 · STEER', quest: 'Steer through the 4 rings', radio: 'Welcome aboard. Push the stick and she goes that way. Take her out of the dock and through the four yellow rings.' },
      { id: 'dive', name: 'LESSON 2 · DIVE', quest: '2 to go down, 3 to come up', radio: 'Now depth. Tap 2 and she sinks 8 metres. Tap 3 and she climbs 8. Go down through the rings, then back up.' },
      { id: 'sonar', name: 'LESSON 3 · SONAR', quest: 'Ping the sonar (1), find 3 beacons', radio: 'I dropped three beacons on the slope. You will not see them in the dark. Tap 1 to ping the sonar and they light up.' },
      { id: 'grab', name: 'LESSON 4 · GRABBER ARM', quest: 'Pick up 3 crates with the arm', radio: 'The arm sits under the nose. Get close to a crate and tap 1 to grab it. Hold 1 any time to fire a torpedo. Bonk a crab or a pufferfish if they get cheeky.' },
      { id: 'dock', name: 'LESSON 5 · DOCKING', quest: 'Park in the dock under my boat', radio: 'Last one. Bring her home and ease her into the dock under my boat. Slow at the end.' }],
    mission: [
      { id: 'chest', name: 'PART 1 · THE TREASURE', quest: 'Find the sunken chest by the wreck', radio: 'An old ship went down in the deep, past the slope. Ping near the wreck and the sonar will find the chest. Grab it with the arm.' },
      { id: 'divers', name: 'PART 2 · THE DIVERS', quest: 'Free the 3 trapped divers', radio: 'Mayday on the radio. Three divers are caught in nets near the trench. Get close and tap 1: the arm cuts the net and clips a balloon on.' },
      { id: 'squid', name: 'PART 3 · THE GIANT SQUID', quest: 'Fight off the giant squid', radio: 'Something big is coming up out of the trench. Hold 1 to fire torpedoes, they find it on their own. Swim out of the red ring when it lifts a tentacle.' },
      { id: 'home', name: 'HOME', quest: 'Bring the chest back to the dock', radio: 'It is gone. Bring the chest home to the dock and I will put the kettle on.' }] };
  const stg = () => STAGES[G.place][G.stage] || {};
  function stageEnter() { const s = stg(); G.ri = 0; say(s.name, 3); radio(s.radio, 'JIB', 9); if (s.id === 'squid') { G.torps = Math.max(G.torps, SUB.TORPS); SQ.on = true; SQ.st = 'rise'; SQ.t = 0; SQ.hp = SUB.SQUID_HP; SQ.x = SQUID_HOME[0]; SQ.z = SQUID_HOME[1]; SQ.y = floor(SQ.x, SQ.z) + 2; G.chk = { x: 0, y: -26, z: 128 }; audio.tone(55, 2, 0.12, 'sawtooth', 0.6); } }
  function advance() { const s = stg(); award(s.id === 'home' ? 'HOME' : s.name.split(' · ')[0] + ' DONE', 100, '#5ec97e'); G.stage++; if (G.stage >= STAGES[G.place].length) return finish(); stageEnter(); }

  function reset() { Object.assign(sub, { x: 0, y: -4, z: -5, vx: 0, vz: 0, vy: 0, yaw: 0, inv: 0, armX: 0 }); Object.assign(G, { stage: 0, ri: 0, t: 0, pen: 0, pts: 0, hull: SUB.HULL, ty: -4, pingCd: 0, pingT: 0, ink: 0, held: 0, torps: 8, armed: true, done: null, tows: 0, hits: 0, tok: 0, coins: 0, freed: 0, stowed: 0, found: 0, chk: null, carry: null, chestDone: false });
    for (const k in rings) for (const r of rings[k]) r.done = false; for (const b of beacons) { b.seen = b.found = false; } for (const c of crates) { c.taken = false; c.held = 0; c.g.visible = true; c.g.position.set(c.x, c.hy, c.z); }
    chest.seen = false; chest.held = false; chest.g.visible = true; chest.g.position.set(chest.x, chest.hy, chest.z); chest.lb.visible = false;
    for (const d of divers) { d.freed = false; d.up = 0; d.f.position.set(d.x, d.hy, d.z); d.f.visible = d.net.visible = d.lb.visible = true; d.balloon.visible = false; }
    for (const a of ammos) { a.taken = false; a.back = 0; a.g.visible = true; a.held = 0; a.g.position.set(a.x, a.hy, a.z); } for (const c of critters) { c.dead = 0; c.hp = c.max; c.x = c.hx; c.y = c.hy; c.z = c.hz; c.g.visible = true; }
    Object.assign(SQ, { on: false, st: 'off', hp: SUB.SQUID_HP, stun: 0 }); SQ.g.visible = false; SQ.lash.visible = SQ.mark.visible = false; for (const t of torps) { t.on = false; t.g.visible = false; } for (const it of items) { it.on = true; it.g.visible = true; } cam.cut = true; }
  function rollOut(id = G.place) { audioOn(); reset(); G.place = PLACES.some(p => p.id === id) ? id : 'school'; G.board = false; G.phase = 'count'; G.count = 3.2; PAUSE = false; say(G.place === 'school' ? 'SUB SCHOOL' : 'THE MISSION', 3); emit(); }
  function tow() { G.tows++; G.pen += SUB.TOW; const c = G.chk || { x: 0, y: -4, z: 4 }; sub.x = c.x; sub.y = c.y; sub.z = c.z; G.ty = c.y; sub.vx = sub.vz = 0; sub.yaw = 0; G.hull = SUB.HULL; G.held = 0; if (SQ.st === 'hold') { SQ.st = 'fight'; SQ.cd = 3; } cam.cut = true; flash('HULL GONE · JIB TOWED YOU · +' + SUB.TOW + ' S', '#ec3013'); radio('Got you. Hull is patched. Off you go again.', 'JIB', 4); }
  function finish() { if (DM.on) return; const pd = PLACES.find(p => p.id === G.place), t = G.t + G.pen, tb = Math.max(0, Math.round((pd.target - t) * 15)), total = Math.round(G.pts + tb), key = 'jidda.sub.' + G.place + '.best'; let nb = false, best = total; try { nb = save.best(key, total); best = save.stat(key, total); save.setFlag(G.place === 'school' ? 'subSchool' : 'subMission'); save.addGold && save.addGold(Math.round(total / 100)); } catch (e) {}
    const th = G.place === 'school' ? [3000, 2400, 1800, 1200] : [4200, 3400, 2600, 1800], grade = total >= th[0] ? 'S' : total >= th[1] ? 'A' : total >= th[2] ? 'B' : total >= th[3] ? 'C' : 'D';
    const stat = G.place === 'school' ? [['Lessons passed', '5 / 5'], ['Hits · tows', G.hits + ' · ' + G.tows]] : [['Chest', 'HOME'], ['Divers freed', G.freed + ' / 3'], ['Squid', 'DRIVEN OFF'], ['Hits · tows', G.hits + ' · ' + G.tows]];
    G.done = { id: G.place, name: pd.name, title: G.place === 'school' ? 'Sub school passed' : 'Mission complete', next: G.place === 'school' ? 'mission' : null, time: t, pen: G.pen, target: pd.target, tok: G.tok, coins: G.coins, pts: Math.round(G.pts), tb, total, grade, newBest: nb, best, gold: Math.round(total / 100), stat }; G.phase = 'done';
    radio(G.place === 'school' ? 'You can drive her. Ready for a real job?' : 'Treasure, three divers home and a squid with a headache. Best day this boat has had.', 'JIB', 8); }

  // ---------- tokens + coins (same spots as THE DEEP) ----------
  const tokTex = canvasTex(128, 128, g => { g.fillStyle = '#e6b45a'; g.beginPath(); g.arc(64, 64, 62, 0, 7); g.fill(); g.lineWidth = 8; g.strokeStyle = '#a8792e'; g.stroke(); g.fillStyle = '#201e1d'; g.font = '900 78px Archivo, sans-serif'; g.textAlign = 'center'; g.textBaseline = 'middle'; g.fillText('8', 64, 68); });
  const tokMat = new THREE.MeshToonMaterial({ map: tokTex, gradientMap: grad, emissive: new THREE.Color('#6a4500'), emissiveIntensity: 0.6 }), tokEdge = toon('#c8922e'), items = [];
  const addItem = (kind, x, y, z) => { const g = new THREE.Group(), c = new THREE.Mesh(kind === 'tok' ? new THREE.CylinderGeometry(0.75, 0.75, 0.18, 20) : new THREE.CylinderGeometry(0.4, 0.4, 0.1, 14), [tokEdge, tokMat, tokMat]); c.rotation.x = Math.PI / 2; if (kind === 'tok') addOutline(c, 0.05); g.add(c); g.position.set(x, y, z); WORLD.add(g); items.push({ kind, g, x, y, z, on: true }); };
  [[-12, -4, 12], [14, -4, 30], [-20, -12, 50], [6, -12, 70], [-10, -20, 86], [20, -24, 104], [0, -36, 130], [-14, -44, 160]].forEach(p => addItem('tok', ...p));
  for (const [x0, y0, z0] of [[-4, -4, 20], [6, -12, 58], [-8, -20, 76], [6, -28, 116], [-6, -40, 140]]) for (let j = 0; j < 6; j++) addItem('coin', x0 + j * 1.3, y0, z0 + j * 1.0);

  // ---------- CAMERA ----------
  const VIEWS = ['BEHIND', 'HIGH', 'LOW'];
  const cam = { vi: 0, pos: V3(0, 2, -16), look: V3(0, -4, 6), cut: true, yawOff: 0, pitchOff: 0, drag: false, zoom: 1, dir: V3(0, 0, 1), tp: V3(), tl: V3() };
  function camStep(dt) { const port = CHh() > CW() * 1.05, Z = cam.zoom * (port ? 1.4 : 1), tp = cam.tp, tl = cam.tl;
    if (G.phase === 'ready') { const a = TT * 0.08; tp.set(Math.cos(a) * 16, -1, 4 + Math.sin(a) * 16); tl.set(sub.x, sub.y, sub.z); }
    else { const sp = Math.hypot(sub.vx, sub.vz), d = cam.dir; if (sp > 0.8) { d.x = damp(d.x, sub.vx / sp, 1.6, dt); d.z = damp(d.z, sub.vz / sp, 1.6, dt); } const dl = Math.hypot(d.x, d.z) || 1, fx = d.x / dl, fz = d.z / dl, v = VIEWS[cam.vi], dist = (v === 'HIGH' ? 13 : v === 'LOW' ? 8 : 10) * Z, hgt = (v === 'HIGH' ? 8 : v === 'LOW' ? 0.6 : 3.4) * Z;
      tp.set(sub.x - fx * dist, sub.y + hgt, sub.z - fz * dist); tl.set(sub.x + fx * 5, sub.y - 0.6, sub.z + fz * 5);
      if (SQ.on && (SQ.st === 'tell' || SQ.st === 'lash' || SQ.st === 'hold')) { tl.lerp(V3(SQ.x, SQ.y, SQ.z), 0.25); } }
    if (cam.yawOff || cam.pitchOff) { const dx = tp.x - tl.x, dz = tp.z - tl.z, r = Math.hypot(dx, dz), a = Math.atan2(dx, dz) + cam.yawOff; tp.x = tl.x + Math.sin(a) * r; tp.z = tl.z + Math.cos(a) * r; tp.y += cam.pitchOff * r; }
    if (!cam.drag) { cam.yawOff = damp(cam.yawOff, 0, 3, dt); cam.pitchOff = damp(cam.pitchOff, 0, 3, dt); }
    if (cam.cut) { cam.pos.copy(tp); cam.look.copy(tl); cam.cut = false; } else { cam.pos.lerp(tp, Math.min(1, dt * 3.5)); cam.look.lerp(tl, Math.min(1, dt * 5)); }
    cam.pos.y = Math.max(cam.pos.y, floor(cam.pos.x, cam.pos.z) + 1); for (const r of rocks) { const dx = cam.pos.x - r.x, dy = cam.pos.y - r.y, dz = cam.pos.z - r.z, d = Math.hypot(dx, dy, dz), mm = r.r + 0.8; if (d < mm && d > 0.01) cam.pos.set(r.x + dx / d * mm, r.y + dy / d * mm, r.z + dz / d * mm); } if (G.phase !== 'ready' && cam.pos.y > -0.5) cam.pos.y = -0.5;
    camera.position.copy(cam.pos); if (camShake > 0) camera.position.add(V3(rr(-1, 1), rr(-1, 1), rr(-1, 1)).multiplyScalar(camShake * 0.4)); camera.lookAt(cam.look); camera.fov = damp(camera.fov, port ? 68 : 60, 4, dt); camera.updateProjectionMatrix();
    const cy = camera.position.y, k = sstep(0, -45, cy), above = cy > 0, fc = above ? new THREE.Color(0xbfe6f2) : new THREE.Color().setHSL(0.56, 0.7, lerp(0.42, 0.04, Math.pow(k, 0.8)));
    scene.background.copy(fc); scene.fog.color.copy(fc); scene.fog.near = above ? 60 : lerp(4, 2, k); scene.fog.far = above ? 400 : lerp(70, 34, k);
    hemi.intensity = lerp(1.1, 0.3, k); sunL.intensity = lerp(1.6, 0.12, k); lamp.intensity = lerp(4, 70, sstep(-4, -24, sub.y)); surf.position.set(camera.position.x, 0, camera.position.z);
    snow.position.copy(camera.position); for (const s of shafts) { s.material.opacity = 0.12 * (1 - k * 2); s.lookAt(camera.position.x, s.position.y, camera.position.z); } }

  // ---------- INPUT ----------
  const keys = new Set(), STK = { x: 0, y: 0 };
  const kx = () => (keys.has('KeyD') || keys.has('ArrowRight') ? 1 : 0) - (keys.has('KeyA') || keys.has('ArrowLeft') ? 1 : 0), ky = () => (keys.has('KeyW') || keys.has('ArrowUp') ? 1 : 0) - (keys.has('KeyS') || keys.has('ArrowDown') ? 1 : 0);
  const onKD = e => { if (e.target && /INPUT|TEXTAREA/.test(e.target.tagName)) return; if (keys.has(e.code)) return; keys.add(e.code); if (e.code === 'Digit1' || e.code === 'KeyJ') down1(); if (e.code === 'Digit2' || e.code === 'KeyK' || e.code === 'KeyQ') press(2); if (e.code === 'Space' || e.code === 'KeyE') { e.preventDefault(); press(3); } if (e.code === 'KeyR') doPing(); if (e.code === 'KeyF') fire(); };
  const onKU = e => { keys.delete(e.code); if (e.code === 'Digit1' || e.code === 'KeyJ') up1(); }; addEventListener('keydown', onKD); addEventListener('keyup', onKU);
  const stickWorld = (sx, sy) => { const fx = cam.look.x - cam.pos.x, fz = cam.look.z - cam.pos.z, l = Math.hypot(fx, fz) || 1, ux = fx / l, uz = fz / l; return { x: ux * sy - uz * sx, z: uz * sy + ux * sx }; };
  const near = (o, y) => Math.hypot(o.x - sub.claw.x, (y ?? o.y) - sub.claw.y, o.z - sub.claw.z);
  function grabTarget() { if (G.phase !== 'run') return null; const s = stg().id;
    if (G.held > 0 && SQ.st === 'hold') return { label: 'ZAP THE SQUID', act: zap };
    let best = null, bd = SUB.REACH; const consider = (o, y, label, act) => { const d = near(o, y); if (d < bd) { bd = d; best = { label, act }; } };
    if (s === 'grab') for (const c of crates) if (!c.taken && !c.held) consider(c, c.hy, 'GRAB THE CRATE', () => { c.held = 1; sub.armX = 1; audio.tone(600, 0.15, 0.06, 'square', 0.8); });
    if (G.place === 'mission' && !chest.held && (s === 'chest' || s === 'divers')) consider(chest, chest.hy, 'GRAB THE CHEST', () => { chest.held = true; chest.seen = true; sub.armX = 1; G.carry = 'chest'; say('GOT THE TREASURE', 2.5); award('TREASURE', 300, '#ffd23a'); spray(V3(chest.x, chest.hy + 1, chest.z), 20, 3, 1, 1, 0xffd23a, -1); radio(G.freed >= 3 ? 'Got it. Now the divers are safe too.' : 'Got it! Now, about that mayday.', 'JIB', 5); if (s === 'chest') advance(); });
    if (G.place === 'mission' && s !== 'squid' && s !== 'home') for (const d of divers) if (!d.freed) consider(d, d.hy + 1, 'CUT THE NET · FREE THE DIVER', () => freeDiver(d));
    for (const a of ammos) if (!a.taken) consider(a, a.hy, 'GRAB · +4 TORPEDOES', () => takeAmmo(a));
    for (const c of critters) if (!(c.dead > 0)) consider(c, c.y, 'ARM WHACK · ' + c.name, () => { sub.armX = 1; hitCritter(c, 'arm'); });
    return best; }
  function takeAmmo(a) { a.taken = true; a.back = 25; a.g.visible = false; G.torps += 4; sub.armX = 1; award('+4 TORPEDOES · ' + G.torps, 40, '#ec3013'); }
  function freeDiver(d) { d.freed = true; d.net.visible = false; d.lb.visible = false; d.balloon.visible = true; G.freed++; sub.armX = 1; award('DIVER FREE · ' + G.freed + ' / 3', 200, '#5ec97e'); spray(V3(d.x, d.hy + 1, d.z), 16, 2, 0.6, 1.2, 0xdff6ff, -3); radio(['Thank you! I was out of ideas down there.', 'Oh, that is much better. Thank you, sub!', 'Last one! You are a hero.'][G.freed - 1], 'DIVER', 4); if (G.freed >= 3 && stg().id === 'divers') setTimeout(() => stg().id === 'divers' && advance(), 1200); }
  function zap() { G.held = 0; SQ.st = 'fight'; SQ.stun = 2; SQ.cd = 3; const dx = SQ.x - sub.x, dz = SQ.z - sub.z, d = Math.hypot(dx, dz) || 1; SQ.x += dx / d * 7; SQ.z += dz / d * 7; award('ZAP! IT LET GO', 60, '#7dd3fc'); spray(V3(sub.x, sub.y, sub.z), 24, 6, 0.6, 0.5, 0x7dd3fc, 0); audio.tone(2600, 0.3, 0.06, 'sawtooth', 2); }
  function doPing() { if (G.phase !== 'run') return; if (G.pingCd > 0) return flash('SONAR RECHARGING', '#8a847e'); G.pingCd = SUB.PING_CD; G.pingT = 1.3; ping.visible = true; ping.position.set(sub.x, sub.y, sub.z); audio.tone(1250, 1.1, 0.06, 'sine', 0.4);
    let n = 0; for (const b of beacons) if (!b.found && !b.seen && Math.hypot(b.x - sub.x, b.z - sub.z) < SUB.PING_R) { b.seen = true; n++; } if (G.place === 'mission' && !chest.seen && Math.hypot(chest.x - sub.x, chest.z - sub.z) < SUB.PING_R) { chest.seen = true; n++; radio('There! The sonar has it. Look for the gold light.', 'JIB', 5); }
    setTimeout(() => { if (n) { flash('SONAR · ' + n + ' FOUND', '#7dd3fc'); audio.tone(1650, 0.3, 0.05, 'sine', 0.6); } else flash('PING · NOTHING CLOSE', '#7dd3fc'); }, 500); }
  function aimAt(px, py, pz, fx, fz) { let best = null, bd = 34; const cand = o => { const dx = o.x - px, dz = o.z - pz, d = Math.hypot(dx, o.y - py, dz); if (d < bd && (dx * fx + dz * fz) / (Math.hypot(dx, dz) || 1) > 0.35) { bd = d; best = o; } }; if (SQ.on && SQ.st !== 'flee' && SQ.st !== 'rise') cand(SQ); for (const c of critters) if (!(c.dead > 0)) cand(c); return best; }
  function fire() { if (G.phase !== 'run') return; if (G.torps <= 0) return flash('NO TORPEDOES · FIND A RED CRATE', '#ec3013'); const t = torps.find(q => !q.on); if (!t) return; G.torps--; t.on = true; t.life = 2.6; const fx = Math.sin(sub.yaw), fz = Math.cos(sub.yaw); t.g.position.set(sub.x + fx * 2.8, sub.y - 0.6, sub.z + fz * 2.8); t.v.set(fx, 0, fz); t.tg = aimAt(t.g.position.x, t.g.position.y, t.g.position.z, fx, fz); if (t.tg) t.v.lerp(V3(t.tg.x - t.g.position.x, t.tg.y - t.g.position.y, t.tg.z - t.g.position.z).normalize(), 0.6).normalize(); t.g.visible = true; audio.burst(0.4, 500, 0.12); bubbles(t.g.position, 6); }
  const H1 = { on: false, t: 0, fired: false, last: 0 };
  function down1() { audioOn(); if (G.board || PAUSE || G.phase !== 'run') return; H1.on = true; H1.t = 0; H1.fired = false; }
  function up1() { if (!H1.on) return; H1.on = false; if (!H1.fired) press(1); }
  function press(n) { audioOn(); if (G.board || PAUSE || G.phase !== 'run') return;
    if (n === 1) { const g = grabTarget(); if (g) return g.act(); return doPing(); }
    const fl = floor(sub.x, sub.z) + 1.8; if (n === 2) { if (G.ty - SUB.STEP < fl - 0.5 && G.ty <= fl + 0.5) return flash('SEABED · CAN\'T GO LOWER', '#ffffff'); G.ty = Math.max(fl, G.ty - SUB.STEP); bubbles(V3(sub.x, sub.y + 1, sub.z), 6); audio.tone(300, 0.2, 0.04, 'sine', 0.5); }
    else { G.ty = Math.min(-2, G.ty + SUB.STEP); bubbles(V3(sub.x, sub.y - 1, sub.z), 6); audio.tone(520, 0.2, 0.04, 'sine', 1.6); } }
  function useItem(id) { if (G.phase !== 'run') return; if (id === 'repairKit' || id === 'erToGo' || id === 'healingCharges' || id === 'splint' || id === 'amber') { try { save.take(id); } catch (e) {} G.hull = Math.min(SUB.HULL, G.hull + 50); flash('HULL +50', '#5ec97e'); return; } if (id === 'energyPod') { try { save.take(id); } catch (e) {} if (G.armed) G.torps += 6; G.hull = SUB.HULL; flash('HULL FULL' + (G.armed ? ' · +6 TORPEDOES' : ''), '#38bdf8'); return; } flash('SAVE IT FOR THE BOAT', '#ffffff'); }

  // ---------- STEP ----------
  function squidStep(dt) { const q = SQ; if (!q.on) { q.g.visible = false; return; } q.g.visible = true; q.t += dt; q.cd -= dt; q.stun = Math.max(0, q.stun - dt); q.hurtT = Math.max(0, q.hurtT - dt); const live = G.phase === 'run';
    const dx = sub.x - q.x, dy = sub.y - q.y, dz = sub.z - q.z, d = Math.hypot(dx, dy, dz) || 1, fl = floor(q.x, q.z) + 4;
    q.arms.forEach((a, i) => a.segs.forEach((s, k) => { s.rotation.x = Math.sin(TT * 2.4 + i + k * 0.7) * 0.28 + (q.st === 'hold' ? 0.5 : 0); s.rotation.y = Math.cos(TT * 1.9 + i * 1.3 + k) * 0.22; }));
    const moveTo = (tx, ty, tz, sp) => { const mx = tx - q.x, my = ty - q.y, mz = tz - q.z, md = Math.hypot(mx, my, mz); if (md > 0.1) { const s = Math.min(md, sp * dt); q.x += mx / md * s; q.y += my / md * s; q.z += mz / md * s; } };
    if (q.st === 'rise') { moveTo(q.x, Math.max(fl, sub.y), q.z, 5); if (q.t > 2.2) { q.st = 'fight'; q.cd = 2.5; say('THE GIANT SQUID', 2.5); } }
    else if (q.st === 'fight') { if (!q.stun) { const ox = -dx / d, oz = -dz / d, sa = q.side * 0.6 * Math.sin(TT * 0.4), tx = sub.x + (ox * Math.cos(sa) - oz * Math.sin(sa)) * 14, tz = sub.z + (oz * Math.cos(sa) + ox * Math.sin(sa)) * 14; moveTo(tx, Math.max(fl, sub.y + 1), tz, d > 26 ? 9 : 4.5); }
      if (q.cd <= 0 && !q.stun && live && d < 30) { const r = Math.random(); if (d < 12 && r < 0.3) { q.st = 'grab'; q.t = 0; } else if (r < 0.5 && q.hp < SUB.SQUID_HP) { q.st = 'ink'; q.t = 0; } else { q.st = 'tell'; q.t = 0; q.mp.set(sub.x, sub.y, sub.z); q.bang.visible = true; audio.tone(220, 0.6, 0.06, 'square', 0.6); } } }
    else if (q.st === 'tell') { q.mark.visible = true; q.mark.position.copy(q.mp); q.mark.lookAt(camera.position); q.mark.material.opacity = 0.5 + 0.4 * Math.sin(TT * 18); q.mark.scale.setScalar(1 + (1.3 - q.t) * 0.2); if (q.t > 1.3) { q.bang.visible = false; q.st = 'lash'; q.t = 0; q.res = false; } }
    else if (q.st === 'lash') { const L = q.mp.distanceTo(V3(q.x, q.y, q.z)); q.lash.visible = true; q.lash.position.set(q.x, q.y, q.z); q.lash.lookAt(q.mp); const k = q.t < 0.2 ? q.t / 0.2 : q.t < 0.45 ? 1 : Math.max(0, 1 - (q.t - 0.45) / 0.3); q.lm.scale.set(1, 1, Math.max(0.01, L * k)); q.club.position.z = L * k; if (q.t >= 0.2 && !q.res) { q.res = true; spray(q.mp, 14, 4, 1, 0.8, 0xdff6ff, -1); audio.burst(0.6, 120, 0.25); if (sub.claw && Math.hypot(sub.x - q.mp.x, sub.y - q.mp.y, sub.z - q.mp.z) < 3.8) hurt(15, 'TENTACLE SLAM'); else if (live) award('DODGED', 40, '#ffffff'); } if (q.t > 0.75) { q.lash.visible = false; q.mark.visible = false; q.st = 'fight'; q.cd = 3.4 - (SUB.SQUID_HP - q.hp) * 0.12; q.side = -q.side; } }
    else if (q.st === 'grab') { moveTo(sub.x, sub.y + 1, sub.z, 10); if (d < 5.5 && live) { q.st = 'hold'; q.t = 0; G.held = 5; flash('THE SQUID HAS YOU · TAP 1 TO ZAP', '#ec3013'); audio.burst(0.5, 300, 0.16); } else if (q.t > 2.5) { q.st = 'fight'; q.cd = 2; } }
    else if (q.st === 'hold') { const ox = -dx / d, oz = -dz / d; q.x = lerp(q.x, sub.x + ox * 4.8, dt * 6); q.y = lerp(q.y, sub.y + 1.2, dt * 6); q.z = lerp(q.z, sub.z + oz * 4.8, dt * 6); if (live) G.hull = Math.max(0, G.hull - 5 * dt); camShake = Math.max(camShake, 0.15); if (G.held <= 0) { q.st = 'fight'; q.cd = 2.5; q.stun = 1; } }
    else if (q.st === 'ink') { if (q.t < dt * 1.5) { spray(V3(q.x, q.y, q.z), 30, 4, 2.4, 2, 0x140f18, -0.5); if (d < 22) { G.ink = 1.8; flash('INK!', '#c7a6ff'); } q.side = -q.side; } moveTo(q.x + q.side * 12, q.y, q.z, 9); if (q.t > 1) { q.st = 'fight'; q.cd = 2.6; } }
    else if (q.st === 'flee') { q.y -= 7 * dt; q.z += 5 * dt; if (q.t > 3.5) { q.on = false; q.g.visible = false; } }
    if (q.st !== 'flee') { q.y = Math.max(q.y, fl); q.g.lookAt(sub.x, sub.y, sub.z); } q.g.position.set(q.x, q.y, q.z); q.g.scale.setScalar(q.hurtT > 0 ? 1 + q.hurtT * 0.15 : 1);
    if (q.st !== 'flee' && d < 5 && q.st !== 'hold') { sub.x = q.x + dx / d * 5; sub.z = q.z + dz / d * 5; } }
  function squidHit() { const q = SQ; q.hp--; q.hurtT = 0.5; q.stun = Math.max(q.stun, 0.4); spray(V3(q.x, q.y, q.z), 18, 5, 1.2, 0.8, 0xffd9a0, 0); audio.burst(0.9, 180, 0.3); if (q.hp > 0) { award('HIT · SQUID ' + q.hp + ' LEFT', 60, '#ffd23a'); if (q.st === 'hold') { G.held = 0; } } else { q.st = 'flee'; q.t = 0; q.mark.visible = q.lash.visible = false; q.bang.visible = false; G.held = 0; award('THE SQUID SWIMS OFF', 600, '#5ec97e'); G.chk = { x: 0, y: -4, z: 4 }; setTimeout(() => stg().id === 'squid' && advance(), 1400); } }

  function step(dt) { TT += dt; demoStep(dt);
    if (H1.on) { H1.t += dt; if (H1.t >= 0.3 && (!H1.fired || H1.t - H1.last >= 0.5)) { fire(); H1.fired = true; H1.last = H1.t; } if (G.phase !== 'run') H1.on = false; }
    if (G.phase === 'count') { G.count -= dt; if (G.count <= 0) { G.phase = 'run'; say('GO!', 1.2); audio.tone(990, 0.3, 0.08, 'square', 1.2); stageEnter(); } }
    const live = G.phase === 'run'; if (live) G.t += dt;
    G.pingCd = Math.max(0, G.pingCd - dt); G.ink = Math.max(0, G.ink - dt); G.held = Math.max(0, G.held - dt); sub.inv = Math.max(0, sub.inv - dt); G.hintT = Math.max(0, G.hintT - dt); camShake = Math.max(0, camShake - dt * 1.5);
    const sx = live ? STK.x + kx() : 0, sy = live ? STK.y + ky() : 0, w = stickWorld(sx, sy), m = Math.min(1, Math.hypot(sx, sy)), wl = Math.hypot(w.x, w.z) || 1, slow = G.held > 0 ? 0.15 : 1;
    sub.vx += (w.x / wl * m * SUB.SPEED * slow - sub.vx) * SUB.DRAG * dt; sub.vz += (w.z / wl * m * SUB.SPEED * slow - sub.vz) * SUB.DRAG * dt; sub.x += sub.vx * dt; sub.z += sub.vz * dt;
    if (G.phase === 'count') { sub.x = 0; sub.z = -5; sub.vx = sub.vz = 0; }
    sub.x = clamp(sub.x, -60, 60); sub.z = clamp(sub.z, -20, 185);
    const fl = floor(sub.x, sub.z) + 1.8; G.ty = Math.max(G.ty, fl); const py = sub.y; sub.y += clamp(G.ty - sub.y, -SUB.VY * dt, SUB.VY * dt); sub.y = Math.max(sub.y, fl); sub.vy = (sub.y - py) / Math.max(dt, 1e-4);
    const spd = Math.hypot(sub.vx, sub.vz);
    for (const r of rocks) { const dx = sub.x - r.x, dy = sub.y - r.y, dz = sub.z - r.z, d = Math.hypot(dx, dy, dz), mm = r.r + 1.4; if (d < mm && d > 0.01) { sub.x = r.x + dx / d * mm; sub.y = r.y + dy / d * mm; sub.z = r.z + dz / d * mm; const vn = (sub.vx * dx + sub.vz * dz) / d; if (vn < 0) { sub.vx -= dx / d * vn * 1.4; sub.vz -= dz / d * vn * 1.4; } if (live && spd > 5.5 && vn < -4) hurt(4, 'BUMP · EASY ON THE ROCKS'); } }
    // dock frame: the posts are solid
    if (!inDock(sub)) { const d = DOCK; for (const sx2 of [-1, 1]) { const px = d.x + sx2 * d.hx; if (Math.abs(sub.z - d.z) < d.hz + 0.6 && Math.abs(sub.x - px) < 1.4 && Math.abs(sub.y - d.y) < d.hy + 1) sub.x = px + Math.sign(sub.x - px || sx2) * 1.4; } }
    if (spd > 0.6) { const want = Math.atan2(sub.vx, sub.vz), dd = Math.atan2(Math.sin(want - sub.yaw), Math.cos(want - sub.yaw)); sub.yaw += clamp(dd, -2.4 * dt, 2.4 * dt); sub.turn = damp(sub.turn || 0, clamp(dd, -1, 1), 4, dt); } else sub.turn = damp(sub.turn || 0, 0, 4, dt);
    subG.position.set(sub.x, sub.y + Math.sin(TT * 1.3) * 0.08, sub.z); subG.rotation.set(0, sub.yaw, 0); body.rotation.x = damp(body.rotation.x, clamp(-sub.vy * 0.08, -0.35, 0.35), 4, dt); body.rotation.z = damp(body.rotation.z, -sub.turn * 0.25, 4, dt);
    prop.rotation.z += dt * (2 + spd * 3); for (const pp of SUBFX.pods) pp.rotation.z -= dt * (3 + spd * 2.5 + Math.abs(sub.vy) * 3); if (SUBFX.beacon) SUBFX.beacon.material.opacity = (TT * 1.5) % 1 < 0.25 ? 1 : 0.15; if (spd > 1 && Math.random() < 0.4) bubbles(subG.localToWorld(V3(0, 0, -3.5)), 1);
    // grabber arm: reaches down + forward when it works, holds what it carries
    sub.armX = Math.max(chest.held || crates.some(c => c.held) ? 0.6 : 0, sub.armX - dt * 1.2); arm.rotation.x = lerp(0.9, 0.35, sub.armX); fore.rotation.x = lerp(0.6, 0.1, sub.armX); fingers.forEach((f, i) => f.rotation.y = (i ? -1 : 1) * (sub.armX > 0.8 ? 0.05 : 0.35));
    subG.updateMatrixWorld(true); hand.getWorldPosition(sub.claw); sub.claw.y -= 0.4;
    pilot.visible = true; try { kit.animFox(pilot, dt, 0, false); } catch (e) {}
    if (G.pingT > 0) { G.pingT -= dt; const u = 1 - G.pingT / 1.3; ping.scale.setScalar(2 + u * SUB.PING_R); ping.material.opacity = 0.5 * (1 - u); if (G.pingT <= 0) ping.visible = false; }
    // stage checks
    const s = stg().id;
    if (live && (s === 'steer' || s === 'dive')) { const set = rings[s], r = set[G.ri]; if (r) { const hd = Math.hypot(sub.x - r.x, sub.z - r.z), dy = sub.y - r.y; if (hd < 3 && Math.abs(dy) < 2.8) { r.done = true; G.ri++; award('RING ' + G.ri + ' / ' + set.length, 50, '#ffd23a'); audio.tone(1320, 0.2, 0.05, 'triangle', 1.6); if (G.ri >= set.length) advance(); } else if (hd < 6 && Math.abs(dy) > 2.8) hint(dy > 0 ? 'RING IS BELOW · TAP 2' : 'RING IS ABOVE · TAP 3'); } }
    for (const k in rings) rings[k].forEach((r, i) => { const on = live && s === k && !r.done && i >= G.ri && i <= G.ri + 1; r.m.visible = on || (G.phase === 'ready' && k === 'steer'); r.m.material = i === G.ri ? ringMat : ringMatDim; r.lb.visible = on && i === G.ri; if (on && i === G.ri) r.m.scale.setScalar(1 + 0.05 * Math.sin(TT * 5)); });
    for (const b of beacons) { const vis = b.seen && !b.found; b.g.visible = vis || (s === 'sonar' && Math.hypot(b.x - sub.x, b.z - sub.z) < 9); b.gl.material.opacity = vis ? 0.6 + 0.3 * Math.sin(TT * 5) : 0.15; b.lb.visible = vis; if (live && s === 'sonar' && !b.found) { const hd = Math.hypot(b.x - sub.x, b.z - sub.z), dy = sub.y - b.y; if (hd < 5 && dy < 7) { b.found = true; b.seen = true; G.found++; award('BEACON ' + G.found + ' / 3', 80, '#7dd3fc'); if (G.found >= 3) advance(); } else if (hd < 7 && dy >= 7) hint('BEACON IS BELOW · TAP 2'); } }
    for (const c of crates) { c.g.visible = !c.taken && (s === 'grab' || G.place === 'school'); if (c.held) { c.held += dt; c.g.position.lerp(sub.claw, Math.min(1, dt * 10)); if (c.held > 1.2) { c.held = 0; c.taken = true; G.stowed++; award('CRATE ' + G.stowed + ' / 3', 60, '#ffd23a'); if (G.stowed >= 3 && stg().id === 'grab') advance(); } } else if (live && s === 'grab' && !c.taken && Math.hypot(c.x - sub.x, c.z - sub.z) < 5 && sub.y - c.hy > 4) hint('CRATE IS BELOW · TAP 2'); c.gl.material.opacity = 0.35 + 0.2 * Math.sin(TT * 4); }
    if (live && s === 'dock' || live && s === 'home') { if (inDock(sub)) { if (spd < 3.2) { award(spd < 1.5 ? 'SOFT DOCKING' : 'DOCKED', spd < 1.5 ? 150 : 80, '#5ec97e'); sub.vx = sub.vz = 0; if (s === 'home' && chest.held) { chest.held = false; chest.g.visible = false; G.carry = null; } advance(); } else hint('TOO FAST · EASE OFF'); } }
    if (live && inDock(sub) && G.hull < SUB.HULL) { G.hull = Math.min(SUB.HULL, G.hull + 30 * dt); if (!G.repT) { G.repT = 2; flash('DOCK · REPAIRING THE HULL', '#5ec97e'); } } G.repT = Math.max(0, (G.repT || 0) - dt);
    DOCK.lights.forEach((l, i) => l.material.opacity = (s === 'dock' || s === 'home') ? (Math.floor(TT * 4 - i * 0.5) % 2 ? 1 : 0.3) : 0.6); DOCK.sign.visible = true;
    // mission pieces
    chest.gl.material.opacity = chest.seen && !chest.held ? 0.5 + 0.3 * Math.sin(TT * 4) : 0; chest.lb.visible = chest.seen && !chest.held && G.place === 'mission'; if (chest.held) { chest.g.position.lerp(sub.claw, Math.min(1, dt * 10)); chest.g.rotation.y = sub.yaw; }
    if (G.place === 'mission' && live && s === 'chest' && !chest.held && Math.hypot(chest.x - sub.x, chest.z - sub.z) < 6 && sub.y - chest.hy > 4) hint('THE CHEST IS BELOW · TAP 2');
    for (const d of divers) { d.f.visible = G.place === 'mission' || G.phase === 'ready' ? d.up < 30 : false; d.net.visible = d.f.visible && !d.freed; d.lb.visible = d.net.visible; if (d.freed && d.up < 30) { d.up += dt * 2.6; d.f.position.y = d.hy + d.up; d.balloon.scale.setScalar(Math.min(1, d.up / 2)); d.balloon.scale.y *= 1.2; } try { kit.animFox(d.f, dt, d.freed ? 0 : 0.4, false); } catch (e) {} d.lb.material.opacity = 0.6 + 0.4 * Math.sin(TT * 6); if (live && !d.freed && G.place === 'mission' && s !== 'squid' && s !== 'home' && Math.hypot(d.x - sub.x, d.z - sub.z) < 6 && sub.y - d.hy > 5) hint('DIVER IS BELOW · TAP 2'); }
    for (const a of ammos) { a.g.visible = !a.taken; if (a.taken) { a.back -= dt; if (a.back <= 0) a.taken = false; } else { a.g.position.y = a.hy + Math.sin(TT * 2 + a.x) * 0.15; a.g.rotation.y += dt * 0.6; if (live && Math.hypot(a.x - sub.x, a.hy - sub.y, a.z - sub.z) < 2.6) takeAmmo(a); } }
    critterStep(dt, live);
    squidStep(dt);
    for (const t of torps) { if (!t.on) continue; t.life -= dt; const tg = t.tg; if (tg && !(tg.dead > 0) && (tg !== SQ || (SQ.on && SQ.st !== 'flee'))) { const to = V3(tg.x - t.g.position.x, tg.y - t.g.position.y, tg.z - t.g.position.z); to.normalize(); if (to.dot(t.v) > 0.1) t.v.lerp(to, Math.min(1, dt * 3)).normalize(); } if (SQ.on && SQ.st !== 'flee' && SQ.st !== 'rise' && t.g.position.distanceTo(V3(SQ.x, SQ.y, SQ.z)) < 4.8) { t.on = false; t.g.visible = false; squidHit(); continue; } { const hc = critters.find(c => !(c.dead > 0) && Math.hypot(c.x - t.g.position.x, c.y - t.g.position.y, c.z - t.g.position.z) < c.r + 1); if (hc) { t.on = false; t.g.visible = false; hitCritter(hc, 'torp'); continue; } } t.g.position.addScaledVector(t.v, 24 * dt); t.g.lookAt(t.g.position.clone().add(t.v)); if (Math.random() < 0.6) bubbles(t.g.position, 1); if (t.life <= 0 || t.g.position.y < floor(t.g.position.x, t.g.position.z) + 0.3) { t.on = false; t.g.visible = false; spray(t.g.position, 10, 3, 1, 0.6, 0xffd9a0, 0); } }
    for (const j of jellies) { j.x = lerp(j.x, j.hx + Math.cos(TT * 0.3 + j.ph) * 3, dt * 0.4); j.z = lerp(j.z, j.hz + Math.sin(TT * 0.25 + j.ph) * 3, dt * 0.4); const pu = Math.sin(TT * 2.2 + j.ph); j.y = j.hy + pu * 0.4; j.g.scale.set(1 + pu * 0.08, 1 - pu * 0.1, 1 + pu * 0.08); j.g.position.set(j.x, j.y, j.z); if (live && Math.hypot(sub.x - j.x, sub.y - j.y, sub.z - j.z) < 2.2) { if (hurt(5, 'JELLYFISH')) { j.hx += (j.x - sub.x) * 2; j.hz += (j.z - sub.z) * 2; } } }
    if (live && G.hull <= 0) tow();
    for (const k of kelpM) k.rotation.z = Math.sin(TT * 1.1 + k.userData.ph) * 0.12;
    for (const f of fishes) { for (let i = 0; i < f.n; i++) { const [p0, k, yo] = f.ph[i], a = p0 + TT * 0.6, r = f.r * k; dm.position.set(f.cx + Math.cos(a) * r, f.cy + yo, f.cz + Math.sin(a) * r); dm.rotation.set(0, -a, Math.PI / 2); dm.updateMatrix(); f.im.setMatrixAt(i, dm.matrix); } f.im.instanceMatrix.needsUpdate = true; }
    if (live) for (const it of items) { if (!it.on) continue; it.g.rotation.y += dt * 3; if (Math.hypot(sub.x - it.x, sub.y - it.y, sub.z - it.z) < (it.kind === 'tok' ? 2.6 : 2.0)) { it.on = false; it.g.visible = false; if (it.kind === 'tok') { G.tok++; award('TOKEN ' + G.tok + ' / 8', 60, '#e6b45a'); if (G.tok === 8) setTimeout(() => award('ALL 8 TOKENS', 400, '#e6b45a'), 500); } else { G.coins++; G.pts += 25; audio.tone(1500 + (G.coins % 6) * 120, 0.08, 0.04, 'triangle', 1.3); } } }
    boat.position.y = Math.sin(TT * 1.2) * 0.12; boat.rotation.z = Math.sin(TT * 0.9) * 0.04; kit.animFox(jib, dt, 0, false);
    const gt = grabTarget(); G.prompt = gt ? gt.label : null;
    fxStep(dt);
    G.bannerT = Math.max(0, G.bannerT - dt); if (G.bannerT <= 0) G.banner = ''; G.radioT = Math.max(0, G.radioT - dt); if (G.radioT <= 0) G.radio = ''; G.flashT = Math.max(0, G.flashT - dt); if (G.flashT <= 0) G.flash = null;
    camStep(dt); }
  let last = performance.now(), raf = 0, hudT = 0, miniC = null, miniT = 0;
  function frame(now) { raf = requestAnimationFrame(frame); const rdt = Math.min(0.05, (now - last) / 1000); last = now; if (!PAUSE) step(rdt); renderer.render(scene, camera); hudT -= rdt; if (hudT <= 0) { hudT = 0.1; emit(); } miniT -= rdt; if (miniT <= 0 && miniC) { miniT = 0.25; drawMini(); } }
  function onRs() { renderer.setSize(CW(), CHh()); camera.aspect = CW() / CHh(); camera.updateProjectionMatrix(); } addEventListener('resize', onRs); const ro = new ResizeObserver(onRs); ro.observe(container);
  let audioReady = false; function audioOn() { if (audioReady) return; audioReady = true; try { audio.init(); } catch (e) {} }

  // ---------- HUD ----------
  const _pv = V3(), fmtT = t => { const m = Math.floor(t / 60), s = t - m * 60; return m + ':' + (s < 10 ? '0' : '') + s.toFixed(1); };
  const nearest = (list, f = () => true) => { let b = null, bd = 1e9; for (const o of list) if (f(o)) { const d = Math.hypot(o.x - sub.x, o.z - sub.z); if (d < bd) { bd = d; b = o; } } return b; };
  function nextGoal() { const s = stg().id, D = { x: DOCK.x, y: DOCK.y, z: DOCK.z + DOCK.hz + 3, label: 'DOCK' };
    if (G.hull < 30 && s !== 'squid') return { ...D, label: 'DOCK · REPAIR' };
    if (s === 'steer' || s === 'dive') { const r = rings[s][G.ri]; return r ? { x: r.x, y: r.y, z: r.z, label: r.hint || 'RING ' + (G.ri + 1) } : null; }
    if (s === 'sonar') { const b = nearest(beacons, q => q.seen && !q.found); return b ? { x: b.x, y: b.y, z: b.z, label: 'BEACON' } : { x: 0, y: -18, z: 80, label: 'SLOPE · PING (1)' }; }
    if (s === 'grab') { const c = nearest(crates, q => !q.taken && !q.held); return c ? { x: c.x, y: c.hy, z: c.z, label: 'CRATE' } : null; }
    if (s === 'dock' || s === 'home') return D;
    if (s === 'chest') return chest.seen ? { x: chest.x, y: chest.hy, z: chest.z, label: 'TREASURE' } : { x: WRECK[0], y: floor(WRECK[0], WRECK[1]) + 4, z: WRECK[1], label: 'WRECK · PING (1)' };
    if (s === 'divers') { const d = nearest(divers, q => !q.freed); return d ? { x: d.x, y: d.hy + 1, z: d.z, label: 'DIVER' } : null; }
    if (G.torps <= 0) { const a = nearest(ammos, q => !q.taken); if (a) return { x: a.x, y: a.hy, z: a.z, label: 'TORPEDOES' }; }
    if (s === 'squid' && SQ.on) return G.torps <= 0 ? (() => { const a = nearest(ammos, q => !q.taken); return a ? { x: a.x, y: a.hy, z: a.z, label: 'AMMO' } : null; })() : { x: SQ.x, y: SQ.y, z: SQ.z, label: 'SQUID' };
    return null; }
  function progress() { const s = stg(), id = s.id, P = G.place === 'school' ? 'LESSON ' + (G.stage + 1) + '/5' : 'PART ' + Math.min(G.stage + 1, 4) + '/4';
    const x = id === 'steer' || id === 'dive' ? 'RING ' + Math.min(G.ri + 1, rings[id].length) + '/' + rings[id].length : id === 'sonar' ? 'BEACONS ' + G.found + '/3' : id === 'grab' ? 'CRATES ' + G.stowed + '/3' : id === 'divers' ? 'DIVERS ' + G.freed + '/3' : id === 'squid' ? 'SQUID ' + Math.max(0, SQ.hp) + '/' + SUB.SQUID_HP : id === 'chest' ? (chest.seen ? 'CHEST FOUND' : 'FIND THE CHEST') : 'DOCK HER';
    return P + ' · ' + x; }
  function hud() { const pd = PLACES.find(p => p.id === G.place), live = G.phase === 'run'; let goal = null; if (live) { const n = nextGoal(); if (n) { const dd = Math.hypot(sub.x - n.x, sub.y - n.y, sub.z - n.z); if (dd > 6) { _pv.set(n.x, n.y + 0.5, n.z).project(camera); goal = { nx: _pv.x, ny: _pv.y, behind: _pv.z > 1, label: n.label, dist: Math.round(dd) }; } } }
    const bests = PLACES.map(p => { try { return save.stat('jidda.sub.' + p.id + '.best', 0); } catch (e) { return 0; } }), hl = Math.round(G.hull), cr = hl < 20 ? 3 : hl < 45 ? 2 : hl < 70 ? 1 : 0;
    const armTxt = G.held > 0 && SQ.st === 'hold' ? 'TAP 1 · ZAP' : 'HOLD 1 · TORPEDOES ' + G.torps;
    return { state: G.phase === 'ready' ? 'ready' : 'run', phase: G.phase, board: G.board, done: G.done, place: G.place, placeName: pd.name, room: pd.room, target: pd.target, time: fmtT(G.t + G.pen), over: G.t + G.pen > pd.target,
      breath: hl, under: true, depth: Math.max(0, -sub.y).toFixed(0), zone: zone(sub.y), tok: G.tok || 0, coins: G.coins || 0, pts: Math.round(G.pts), stage: stg().name || '',
      progress: progress(), cracks: cr, crackURL: crackURLs[cr] || '', gauge: clamp(-sub.y / 60, 0, 1), prompt: G.prompt, ink: G.ink, held: G.held > 0, banner: G.banner, radio: G.radio, radioWho: G.radioWho, flash: G.flash, count: G.phase === 'count' ? Math.ceil(G.count) : null,
      view: VIEWS[cam.vi], goal, bests, armTxt, armCol: G.torps > 0 ? '#ec3013' : '#8a847e', torps: G.torps, quest: (stg().quest || pd.goal), demo: DM.on ? { cap: DM.cap, key: (DEMO[DM.i] || {}).key || '', n: DM.i + 1, of: DEMO.length } : null }; }
  function emit() { onState({ course: hud() }); }
  const crackURLs = ['']; { const cv = document.createElement('canvas'); cv.width = 800; cv.height = 800; const g = cv.getContext('2d'); g.lineCap = 'round'; for (const [hx, hy] of [[130, 170], [680, 590], [190, 670]]) { for (let k = 0; k < 9; k++) { let x = hx, y = hy, a = k / 9 * 6.28 + rr(-0.2, 0.2); g.beginPath(); g.moveTo(x, y); const L = rr(90, 240); for (let q = 0; q < L; q += 18) { a += rr(-0.4, 0.4); x += Math.cos(a) * 18; y += Math.sin(a) * 18; g.lineTo(x, y); } g.strokeStyle = 'rgba(255,255,255,0.85)'; g.lineWidth = 2.4; g.stroke(); g.strokeStyle = 'rgba(20,30,40,0.4)'; g.lineWidth = 0.9; g.stroke(); } crackURLs.push(cv.toDataURL('image/png')); } }
  function drawMini() { const c = miniC; if (!c.isConnected) { miniC = null; return; } const dpr = Math.min(2, devicePixelRatio || 1), w = Math.round(c.clientWidth * dpr), h = Math.round(c.clientHeight * dpr); if (!w || !h) return; if (c.width !== w) c.width = w; if (c.height !== h) c.height = h;
    const x = c.getContext('2d'), k = Math.min(w / 140, h / 220), X = px => w / 2 - px * k, Y = pz => h - 10 - (pz + 20) * k, dot = (px, pz, r, col) => { x.fillStyle = col; x.beginPath(); x.arc(X(px), Y(pz), r * dpr, 0, 7); x.fill(); }; x.fillStyle = '#0c3a52'; x.fillRect(0, 0, w, h); [['#2a9fc0', -20, 30], ['#145a7a', 30, 100], ['#062a3e', 100, 190]].forEach(([cl, a, b]) => { x.fillStyle = cl; x.fillRect(0, Y(b), w, (b - a) * k); });
    x.fillStyle = '#ffd23a'; x.fillRect(X(DOCK.x) - 4 * dpr, Y(DOCK.z) - 5 * dpr, 8 * dpr, 10 * dpr); const n = nextGoal(); if (n) dot(n.x, n.z, 4, '#ffd23a'); if (SQ.on) dot(SQ.x, SQ.z, 6, '#ec3013'); dot(sub.x, sub.z, 5, '#ffffff'); dot(sub.x, sub.z, 3, '#ec3013'); }

  // ---------- JIB'S SUB SHEET ----------
  function drawBoard(g, P = false) {
    const W = P ? 900 : 1600, H = P ? 1600 : 900, J = (n = 1.6) => (Math.random() - 0.5) * n * 2;
    g.fillStyle = '#7a4f2a'; g.fillRect(0, 0, W, H); g.strokeStyle = 'rgba(40,24,10,0.35)'; g.lineWidth = 2; for (let i = 0; i < 40; i++) { g.beginPath(); const y = Math.random() * H; g.moveTo(0, y); g.bezierCurveTo(W * 0.3, y + J(8), W * 0.6, y + J(8), W, y + J(6)); g.stroke(); }
    const x0 = 34, y0 = 34, w = W - 68, h = H - 98; g.fillStyle = '#1f2b27'; g.fillRect(x0, y0, w, h);
    for (let i = 0; i < 70; i++) { g.fillStyle = `rgba(255,255,255,${Math.random() * 0.03})`; g.beginPath(); g.ellipse(x0 + Math.random() * w, y0 + Math.random() * h, 60 + Math.random() * 200, 20 + Math.random() * 60, Math.random() * 3, 0, 7); g.fill(); }
    const CH = '#f2f1e8', YL = '#f5e08a', RD = '#ff9a8a', BL = '#9fd8f5';
    const txt = (s, x, y, size, col = CH, wt = 800, fam = 'Archivo, sans-serif') => { g.font = `${wt} ${size}px ${fam}`; g.textBaseline = 'alphabetic'; g.fillStyle = col; g.globalAlpha = 0.92; g.fillText(s, x, y); g.globalAlpha = 0.28; g.fillText(s, x + 1.6, y - 1.2); g.globalAlpha = 1; };
    const HF = '"Caveat", "Segoe Print", "Bradley Hand", cursive', hw = (s, x, y, size, col = YL) => txt(String(s).toUpperCase(), x, y, size, col, 700, HF);
    const ln = (pts, col = CH, wd = 5, close) => { g.strokeStyle = col; g.lineWidth = wd; g.lineCap = 'round'; g.lineJoin = 'round'; g.globalAlpha = 0.9; g.beginPath(); pts.forEach(([x, y], i) => i ? g.lineTo(x + J(), y + J()) : g.moveTo(x + J(), y + J())); if (close) g.closePath(); g.stroke(); g.globalAlpha = 1; };
    const circ = (x, y, r, col = CH, wd = 5, a0 = 0, a1 = Math.PI * 2) => { g.strokeStyle = col; g.lineWidth = wd; g.globalAlpha = 0.9; g.beginPath(); g.arc(x + J(), y + J(), r, a0, a1); g.stroke(); g.globalAlpha = 1; };
    const arrow = (x1, y1, x2, y2, col = YL) => { ln([[x1, y1], [(x1 + x2) / 2 + 12, (y1 + y2) / 2 - 10], [x2, y2]], col, 4); const an = Math.atan2(y2 - y1, x2 - x1); ln([[x2 - Math.cos(an - 0.5) * 22, y2 - Math.sin(an - 0.5) * 22], [x2, y2], [x2 - Math.cos(an + 0.5) * 22, y2 - Math.sin(an + 0.5) * 22]], col, 4); };
    txt('THE SUB', 86, 160, P ? 100 : 112, CH, 900); txt("JIDDA  ·  JIB'S SUB", 90, 214, 32, YL, 800); ln([[88, 238], [760, 234]], CH, 4);
    g.save(); if (P) { g.translate(-590, 250); g.scale(0.92, 0.92); } else g.translate(0, 90);
    // the sub, side view, nose to the right
    { const cx = 1200, cy = 350, L = 230, R = 62, pts = []; for (let k = 0; k <= 16; k++) { const an = -Math.PI / 2 + k / 16 * Math.PI; pts.push([cx + L + Math.cos(an) * R, cy + Math.sin(an) * R]); } for (let k = 0; k <= 16; k++) { const an = Math.PI / 2 + k / 16 * Math.PI; pts.push([cx - L + Math.cos(an) * R, cy + Math.sin(an) * R]); } ln(pts, YL, 6, true); }
    ln([[1090, 288], [1090, 352 + 58], [1090, 412]], RD, 4); ln([[1330, 288], [1330, 412]], RD, 4);
    for (let k = 0; k < 2; k++) { circ(1250 + k * 50, 335, 14, CH, 4); circ(1250 + k * 50, 335, 6, RD, 3); } circ(1160, 352, 34, RD, 5); circ(1160, 352, 27, CH, 2); g.font = '900 40px Archivo, sans-serif'; g.textAlign = 'center'; g.fillStyle = CH; g.fillText('8', 1160, 366); g.textAlign = 'left';
    ln([[1120, 289], [1280, 289]], RD, 7); circ(1200, 286, 74, BL, 4, Math.PI, Math.PI * 2); circ(1200, 286, 62, BL, 2, Math.PI * 1.15, Math.PI * 1.4);
    circ(1200, 240, 18, CH, 4); ln([[1186, 230], [1188, 210], [1197, 224]], CH, 3); ln([[1203, 224], [1212, 210], [1214, 230]], CH, 3); g.fillStyle = CH; g.fillRect(1193, 237, 4, 4); g.fillRect(1204, 237, 4, 4);
    ln([[1110, 289], [1110, 170], [1080, 170]], CH, 4);
    ln([[925, 350], [895, 350]], CH, 4); ln([[895, 305], [895, 395]], CH, 6); ln([[960, 300], [925, 270], [975, 290]], RD, 5); ln([[960, 400], [925, 430], [975, 410]], RD, 5);
    for (let k = 0; k < 3; k++) circ(860 - k * 28, 330 - k * 26, 10 + k * 5, '#cfd8d4', 3);
    ln([[1380, 408], [1405, 455], [1465, 462]], CH, 5); ln([[1465, 462], [1495, 448]], RD, 5); ln([[1465, 462], [1495, 478]], RD, 5);
    ln([[1496, 372], [1512, 372]], CH, 4); ln([[1518, 364], [1546, 364], [1555, 372], [1546, 380], [1518, 380]], RD, 4, true);
    { g.font = `700 32px ${HF}`; hw('Tap 1 grab · hold 1 torpedo', 1150, 530, 32); } arrow(1360, 500, 1440, 475);
    hw('2  Down', 975, 512, 40, BL); arrow(945, 450, 945, 520, BL);
    hw('3  Up', 1335, 262, 40); arrow(1305, 268, 1305, 190);
    hw('8 m a tap', 1335, 205, 30, CH);
    g.restore();
    g.save(); if (P) { g.translate(-10, 470); g.scale(1.12, 1.12); }
    const rows = [['STICK', 'WASD', 'Steer', CH], ['1', 'J  ·  R SONAR  ·  F TORPEDO', 'Tap: grab · sonar   Hold: torpedo', RD], ['2', 'K / Q', 'Down 8 m', BL], ['3', 'SPACE / E', 'Up 8 m', YL], ['EYE', 'HOLD FOR 360 VIEW AND TAP FOR POV', 'Look around', CH]];
    rows.forEach(([k, kb, d, col], i) => { const y = 330 + i * 104, cx = 150, cy = y - 14;
      if (k === 'STICK') { circ(cx, cy, 31, CH, 4); g.globalAlpha = 0.5; g.fillStyle = CH; g.beginPath(); g.arc(cx + 6, cy - 9, 14, 0, 7); g.fill(); g.globalAlpha = 1; circ(cx + 6, cy - 9, 14, CH, 4); for (const [ax, ay, rot] of [[0, -44, 0], [0, 44, Math.PI], [-44, 0, -Math.PI / 2], [44, 0, Math.PI / 2]]) { const s = Math.sin(rot), c = Math.cos(rot), Q = (px, py) => [cx + ax + px * c - py * s, cy + ay + px * s + py * c]; ln([Q(-7, 5), Q(0, -3), Q(7, 5)], CH, 3); } }
      else if (k === 'EYE') { circ(cx, cy, 30, CH, 4); ln([[cx - 19, cy], [cx - 9, cy - 8], [cx, cy - 10], [cx + 9, cy - 8], [cx + 19, cy], [cx + 9, cy + 8], [cx, cy + 10], [cx - 9, cy + 8]], CH, 3, true); g.globalAlpha = 0.9; g.fillStyle = CH; g.beginPath(); g.arc(cx, cy, 4.5, 0, 7); g.fill(); g.globalAlpha = 1; }
      else { g.globalAlpha = 0.9; g.strokeStyle = col; g.lineWidth = 9; g.beginPath(); g.arc(cx, cy, 30, 0, 7); g.stroke(); g.globalAlpha = 1; circ(cx, cy, 22, CH, 2); g.font = '900 34px Archivo, sans-serif'; g.textAlign = 'center'; g.fillStyle = CH; g.fillText(k, cx, cy + 12); g.textAlign = 'left'; }
      txt(kb, 230, y - 24, 18, '#b9c4bf', 800); txt(d, 230, y + 4, 32, CH, 700); });
    g.restore();
    { const s = 'School · treasure · divers · squid'; if (P) { const avail = 760; let sz = 52; g.font = `700 ${sz}px ${HF}`; let w1 = g.measureText(s.toUpperCase()).width; if (w1 > avail) { sz = Math.floor(sz * avail / w1); g.font = `700 ${sz}px ${HF}`; w1 = g.measureText(s.toUpperCase()).width; } hw(s, (900 - w1) / 2, 1400, sz); const s2 = 'Hull hit? Dock to repair'; g.font = `700 40px ${HF}`; hw(s2, (900 - g.measureText(s2.toUpperCase()).width) / 2, 1480, 40, '#a8e6b8'); } else { const cap = 960, right = 1440, by = 778; let sz = 50; g.font = `700 ${sz}px ${HF}`; let wd = g.measureText(s.toUpperCase()).width; if (wd > cap) { sz = Math.floor(sz * cap / wd); g.font = `700 ${sz}px ${HF}`; wd = g.measureText(s.toUpperCase()).width; } hw(s, right - wd, by, sz); } }
    g.fillStyle = '#5e3c1f'; g.fillRect(0, H - 64, W, 64); g.fillStyle = '#7a4f2a'; g.fillRect(0, H - 64, W, 10); for (let k = 0; k < 4; k++) { g.fillStyle = ['#f2f1e8', '#f5e08a', '#ff9a8a', '#f2f1e8'][k]; g.fillRect(260 + k * 120, H - 48, 70, 16); } }
  const boardCv = document.createElement('canvas'); boardCv.width = 1600; boardCv.height = 900; const boardCvP = document.createElement('canvas'); boardCvP.width = 900; boardCvP.height = 1600;
  const paintBoards = () => { drawBoard(boardCv.getContext('2d')); drawBoard(boardCvP.getContext('2d'), true); course.boardURL = boardCv.toDataURL('image/jpeg', 0.9); course.boardURLP = boardCvP.toDataURL('image/jpeg', 0.9); emit(); };
  try { if (!document.getElementById('font-caveat')) { const lk = document.createElement('link'); lk.id = 'font-caveat'; lk.rel = 'stylesheet'; lk.href = 'https://fonts.googleapis.com/css2?family=Caveat:wght@700&display=swap'; document.head.appendChild(lk); } } catch (e) {}

  // ---------- DEMO ----------
  const DM = { on: false, i: 0, t: 0, cap: '' };
  const steerTo = (tx, tz) => { const fx = cam.look.x - cam.pos.x, fz = cam.look.z - cam.pos.z, l = Math.hypot(fx, fz) || 1, ux = fx / l, uz = fz / l, dx = tx - sub.x, dz = tz - sub.z, d = Math.hypot(dx, dz); if (d < 0.8) { STK.x = STK.y = 0; return d; } const k = Math.min(1, d / 3), wx = dx / d * k, wz = dz / d * k; STK.y = wx * ux + wz * uz; STK.x = -wx * uz + wz * ux; return d; };
  const tpTo = (x, y, z, yaw = 0) => { sub.x = x; sub.y = y; sub.z = z; G.ty = y; sub.vx = sub.vz = 0; sub.yaw = yaw; cam.dir.set(Math.sin(yaw), 0, Math.cos(yaw)); cam.cut = true; };
  const at = (a, b) => DM.t > a && DM.t - DM.dt <= a;
  const toStage = (place, id) => { if (G.place !== place) { reset(); G.place = place; } G.phase = 'run'; G.stage = STAGES[place].findIndex(s => s.id === id); stageEnter(); G.radio = ''; };
  const DEMO = [
    { d: 4.2, key: 'STICK', cap: 'STEER WITH THE STICK (WASD). GO THROUGH THE YELLOW RINGS', on() { rollOut('school'); G.count = 0.01; }, tick() { const r = rings.steer[G.ri] || rings.steer[3]; steerTo(r.x, r.z + 2); } },
    { d: 4, key: '2', cap: 'TAP 2 TO GO DOWN 8 M. THE RING LABEL TELLS YOU WHICH WAY', on() { toStage('school', 'dive'); tpTo(0, -4, 42); }, tick() { steerTo(0, 60); if (at(0.4)) press(2); } },
    { d: 3.6, key: '3', cap: 'TAP 3 TO COME BACK UP 8 M', on() { G.ri = 2; rings.dive[0].done = rings.dive[1].done = true; tpTo(0, -20, 68); }, tick() { steerTo(0, 82); if (at(0.3)) press(3); } },
    { d: 4, key: '1', cap: 'IN THE DARK? TAP 1 TO PING THE SONAR. HIDDEN THINGS LIGHT UP', on() { toStage('school', 'sonar'); tpTo(-10, -18, 56); }, tick() { if (at(0.4)) press(1); if (DM.t > 1.6) { const b = beacons[0]; steerTo(b.x, b.z); G.ty = b.y + 2; } } },
    { d: 4, key: '1', cap: 'GET THE ARM CLOSE TO A CRATE AND TAP 1 TO GRAB IT', on() { toStage('school', 'grab'); const c = crates[0]; tpTo(c.x, c.hy + 2.2, c.z - 6); }, tick() { const c = crates[0]; steerTo(c.x, c.z - 2.6); if (!c.held && !c.taken && grabTarget()) press(1); } },
    { d: 4.4, key: 'DOCK', cap: 'EASE HER INTO THE DOCK UNDER JIB\'S BOAT. SLOW AT THE END', on() { toStage('school', 'dock'); tpTo(0, -4, 10, Math.PI); }, tick() { steerTo(0, -5); } },
    { d: 4.4, key: '1', cap: 'THE MISSION: PING BY THE WRECK, THEN GRAB THE CHEST', on() { toStage('mission', 'chest'); tpTo(chest.x + 1, chest.hy + 2.2, chest.z - 9); }, tick() { if (at(0.3)) press(1); if (DM.t > 1.2) steerTo(chest.x, chest.z - 2.4); if (DM.t > 1.2 && !chest.held && grabTarget()) press(1); } },
    { d: 3.6, key: '1', cap: 'FREE THE TRAPPED DIVERS: GET CLOSE AND TAP 1', on() { const d = divers[0]; tpTo(d.x, d.hy + 2.6, d.z - 7); }, tick() { const d = divers[0]; steerTo(d.x, d.z - 2.4); if (!d.freed && grabTarget()) press(1); } },
    { d: 4.4, key: '1', cap: 'HOLD 1 TO FIRE TORPEDOES. THEY HOME IN. RED CRATES GIVE YOU MORE', on() { toStage('mission', 'squid'); SQ.st = 'fight'; SQ.x = 0; SQ.y = -34; SQ.z = 160; SQ.cd = 9; tpTo(0, -34, 142); }, tick() { steerTo(SQ.x, SQ.z - 14); sub.yaw = Math.atan2(SQ.x - sub.x, SQ.z - sub.z); if (at(1) || at(2) || at(3)) fire(); } },
    { d: 3.8, key: '!', cap: 'RED RING = A TENTACLE IS COMING. SWIM OUT OF IT', on() { SQ.st = 'tell'; SQ.t = 0; SQ.mp.set(sub.x, sub.y, sub.z); SQ.bang.visible = true; }, tick() { steerTo(sub.x + 10, sub.z); SQ.cd = 9; } },
    { d: 3.4, key: 'GO', cap: 'HULL GONE? JIB TOWS YOU BACK. NOTHING IS LOST. HAVE FUN', on() {}, tick() { STK.x = STK.y = 0; SQ.cd = 9; } }];
  function demoStep(dt) { if (!DM.on) return; const s = DEMO[DM.i]; DM.dt = dt; DM.t += dt; if (s.tick) s.tick(dt); G.radio = ''; sub.inv = 1; if (DM.t >= s.d) { DM.i++; DM.t = 0; if (DM.i >= DEMO.length) return demoStop(); const n = DEMO[DM.i]; DM.cap = n.cap; n.on && n.on(); } }
  function demoStart() { DM.on = true; DM.i = 0; DM.t = 0; DM.cap = DEMO[0].cap; G.board = false; PAUSE = false; DEMO[0].on(); emit(); }
  function demoStop() { DM.on = false; DM.cap = ''; STK.x = STK.y = 0; reset(); G.place = 'school'; G.done = null; G.board = true; PAUSE = true; G.phase = 'ready'; emit(); }

  // ---------- API ----------
  const course = { boardURL: '', boardURLP: '', hud, say, rollOut, useItem, demoStart, demoStop,
    openBoard() { G.board = true; PAUSE = true; if (G.phase === 'done') G.done = null; emit(); }, closeBoard() { G.board = false; PAUSE = false; emit(); }, preview() {},
    _tp(x, y, z) { tpTo(x, y, z); }, _stage(place, id) { G.board = false; PAUSE = false; toStage(place, id); }, _win() { finish(); }, _dbg: () => ({ phase: G.phase, place: G.place, stage: stg().id, x: sub.x, y: sub.y, z: sub.z, hull: G.hull, squid: SQ.st, hp: SQ.hp }) };
  const api = { course: () => course,
    start() { rollOut(); }, talk() {}, choose() {}, closeDialog() {}, nextLine() {}, clearToast() {}, closeWheel() {}, skipTime() {}, cycleWeather() {}, useItem, setHudPad() {},
    toggleSound() { audio.setMuted(!audio.muted); return audio.muted; },
    melee() { down1(); }, meleeUp() { up1(); }, range() { press(2); }, jump() { press(3); },
    setPaused(v) { PAUSE = !!v || G.board; }, setStick(x, y) { STK.x = x; STK.y = y; },
    eyeLook(dx, dy) { cam.drag = true; cam.yawOff -= dx * 0.006; cam.pitchOff = clamp(cam.pitchOff - dy * 0.004, -0.6, 0.9); }, eyeRelease() { cam.drag = false; }, togglePov() { cam.vi = (cam.vi + 1) % VIEWS.length; flash('VIEW · ' + VIEWS[cam.vi], '#ffffff'); return cam.vi !== 0; },
    lookBy(dx, dy) { api.eyeLook(dx, dy); }, zoomBy(k) { cam.zoom = clamp(cam.zoom * k, 0.6, 1.8); }, getCam() { return { dist: cam.zoom * 10, pitch: cam.pitchOff }; }, setCam(d, p) { if (d != null) cam.zoom = clamp(d / 10, 0.6, 1.8); if (p != null) cam.pitchOff = p; },
    mapData() { return { p: [sub.x, sub.z, sub.yaw], indoor: false, b: [], f: [], e: SQ.on ? [[SQ.x, SQ.z]] : [], q: null }; }, setMinimap(c) { miniC = c || null; },
    reset() {}, _pump(n = 1, dt = 1 / 30) { for (let i = 0; i < n; i++) step(dt); renderer.render(scene, camera); emit(); },
    destroy() { cancelAnimationFrame(raf); removeEventListener('keydown', onKD); removeEventListener('keyup', onKU); removeEventListener('resize', onRs); ro.disconnect(); renderer.dispose(); renderer.domElement.remove(); try { audio.ctx && audio.ctx.close(); } catch (e) {} } };
  reset(); G.phase = 'ready';
  setTimeout(paintBoards, 30); setTimeout(paintBoards, 1400);
  raf = requestAnimationFrame(frame);
  return api;
}
