// 8 GATES — KYOTO THEATRE [kyotoTheatre] · THE FOX WIFE (the 2D game's `noh` minigame, rebuilt in 3D). Ben · Sumo is the actor on the mark.
// Source of truth: GAYA.noh in the 2D Gaya file (copied to minigames/kyoto/fox-wife-2d.json): 3 masks, 22 lines, every number below comes from it.
// Rule: the chorus names who is speaking — put that face on before the drum. The rack is down while you listen (first 35% of a line); a change takes a moment and
// if the drum lands mid-change you are "a man holding a mask". THE HOUSE (needs 60 to pass, 90 = great) · THEY NOTICE (100 = caught: THE WATER IS HONEST).
// Game HUD vehicle "kabuki": 1 WIFE · 2 FARMER · 3 FOX. Save: flags kyotoTheatrePlayed / kyotoTheatrePlayedWell, stat kyoto.theatre.best.
import * as THREE from '../../vendor/three/three.module.js';
import { rr, clamp, damp } from '../../village-game.js';
import { canvasTex } from '../../meru-game.js';
import { save } from '../../engine/save.js';
import { createStage } from '../../engine/restaurant-kit.js';
import { humanKit, HUMAN_PRESETS, SKINS } from '../../engine/human-kit.js';
import { theatreAudio } from './theatre-audio.js';

const SY = 0.9, KEYS = ['girl', 'old', 'fox'];
const ss = t => t * t * (3 - 2 * t);
function lerpP(a, b, t) { const o = {}; for (const k in b) { const va = a && a[k], vb = b[k]; if (Array.isArray(vb)) o[k] = Array.isArray(va) ? vb.map((v, i) => va[i] + (v - va[i]) * t) : vb.slice(); else if (typeof vb === 'number') o[k] = typeof va === 'number' ? va + (vb - va) * t : vb; else o[k] = vb; } return o; }

export async function createFoxWife({ container, onState = () => {}, opts = {} }) {
  const C = await (await fetch(new URL('./fox-wife-2d.json', import.meta.url))).json();
  const ST = createStage(container, { bg: '#120a08' }), { CW, CHh, renderer, scene, camera, V3, toon, M, audio, tone, glowTex, touch } = ST;
  const HK = humanKit({ THREE, grad: ST.grad }); let OPT = { speed: 1, ...opts };
  camera.fov = 42; camera.far = 80; camera.updateProjectionMatrix(); scene.fog = new THREE.Fog(0x120a08, 18, 40);
  scene.children.filter(o => o.isHemisphereLight).forEach(h => { h.color.set(0xffeedd); h.groundColor.set(0x3a2418); h.intensity = 0.62; });
  const sun = ST.sun; sun.position.set(0.5, 9, 6); sun.intensity = 0.9; Object.assign(sun.shadow.camera, { left: -6, right: 6, top: 6, bottom: -6 }); sun.shadow.camera.updateProjectionMatrix();
  const spot = new THREE.SpotLight(0xffe4c0, 3.2, 0, 0.42, 0.5, 0); spot.position.set(0, 9, 5); spot.target.position.set(0, SY, 0.4); scene.add(spot, spot.target);
  const flat = (w, d, col, y, x = 0, z = 0, map) => { const m = new THREE.Mesh(new THREE.PlaneGeometry(w, d), map ? new THREE.MeshToonMaterial({ map, gradientMap: ST.grad }) : toon(col)); m.rotation.x = -Math.PI / 2; m.position.set(x, y, z); m.receiveShadow = true; scene.add(m); return m; };
  // ---------- the house ----------
  { const fT = canvasTex(256, 256, c => { for (let i = 0; i < 8; i++) { c.fillStyle = ['#2a1810', '#24140c', '#2e1c12', '#20120a'][i % 4]; c.fillRect(0, i * 32, 256, 32); } }); fT.wrapS = fT.wrapT = THREE.RepeatWrapping; fT.repeat.set(8, 8); flat(40, 40, '#2a1810', 0, 0, 6, fT);
    const pT = canvasTex(512, 256, c => { for (let i = 0; i < 16; i++) { c.fillStyle = ['#d9a86a', '#cf9d5f', '#e0b074', '#c8955a'][i % 4]; c.fillRect(0, i * 16, 512, 16); c.fillStyle = 'rgba(90,50,20,0.25)'; c.fillRect(0, i * 16, 512, 1); } c.fillStyle = 'rgba(255,240,210,0.08)'; c.fillRect(0, 0, 512, 256); }); pT.wrapS = pT.wrapT = THREE.RepeatWrapping; pT.repeat.set(2, 2);
    const st = new THREE.Mesh(new THREE.BoxGeometry(13, SY, 7.6), [toon('#3a2214'), toon('#3a2214'), new THREE.MeshToonMaterial({ map: pT, gradientMap: ST.grad }), toon('#3a2214'), toon('#2a180e'), toon('#2a180e')]); st.position.set(0, SY / 2, -0.3); st.receiveShadow = true; scene.add(st);
    M(new THREE.BoxGeometry(13.2, 0.12, 0.2), toon('#141210'), 0, SY, 3.5, scene, 0.01);
    const lac = toon('#141210'), red = toon('#8a1c1c'), gld = toon('#c9a227');
    for (const sx of [-1, 1]) { M(new THREE.BoxGeometry(0.5, 7.5, 0.5), lac, sx * 6.6, 3.75, 3.3, scene, 0.012); M(new THREE.BoxGeometry(0.56, 0.3, 0.56), gld, sx * 6.6, 7.4, 3.3, scene, 0); }
    M(new THREE.BoxGeometry(14, 0.6, 0.5), lac, 0, 7.3, 3.3, scene, 0.012); M(new THREE.BoxGeometry(14, 0.12, 0.52), gld, 0, 6.95, 3.3, scene, 0);
    { const vT = canvasTex(512, 64, c => { c.fillStyle = '#8a1c1c'; c.fillRect(0, 0, 512, 64); c.fillStyle = '#c9a227'; for (let i = 0; i < 8; i++) { c.beginPath(); c.arc(32 + i * 64, 30, 16, 0, 7); c.fill(); c.fillStyle = '#8a1c1c'; c.beginPath(); c.arc(32 + i * 64, 30, 9, 0, 7); c.fill(); c.fillStyle = '#c9a227'; } }); const v = new THREE.Mesh(new THREE.PlaneGeometry(13, 0.8), new THREE.MeshBasicMaterial({ map: vT })); v.position.set(0, 6.6, 3.2); scene.add(v); }
    for (const sx of [-1, 1]) { const w = new THREE.Mesh(new THREE.PlaneGeometry(1.6, 7), toon('#1a120c')); w.position.set(sx * 5.9, 3.5, 3.1); scene.add(w); }
    const back = new THREE.Mesh(new THREE.PlaneGeometry(40, 18), toon('#140c08')); back.position.set(0, 9, -6); scene.add(back);
    for (const sx of [-1, 1]) { const w = new THREE.Mesh(new THREE.PlaneGeometry(30, 18), toon('#1c120c')); w.position.set(sx * 14, 9, 6); w.rotation.y = -sx * Math.PI / 2; scene.add(w); }
    // hanamichi: the flower path from stage left out through the house
    M(new THREE.BoxGeometry(1.4, SY * 0.95, 14), new THREE.MeshToonMaterial({ map: pT, gradientMap: ST.grad }), -7.6, SY * 0.475, 10, scene, 0.01); }
  // joshiki-maku: the black · persimmon · green striped curtain, two halves that draw open
  const curT = canvasTex(256, 64, c => { const cols = ['#141210', '#c2501e', '#2f5a3a']; for (let i = 0; i < 12; i++) { c.fillStyle = cols[i % 3]; c.fillRect(i * 256 / 12, 0, 256 / 12 + 1, 64); } });
  const curtain = [-1, 1].map(sx => { const g = new THREE.PlaneGeometry(6.6, 6.6, 24, 1), p = g.attributes.position; for (let i = 0; i < p.count; i++) p.setZ(i, Math.sin(p.getX(i) * 4.5) * 0.08); g.computeVertexNormals(); const m = new THREE.Mesh(g, new THREE.MeshToonMaterial({ map: curT, gradientMap: ST.grad, side: THREE.DoubleSide })); m.position.set(sx * 3.3, SY + 3.3, 3.0); scene.add(m); return { m, sx }; });
  // footlights + hall lanterns
  { const fl = []; for (let i = 0; i < 9; i++) { const x = -5 + i * 1.25; M(new THREE.CylinderGeometry(0.12, 0.12, 0.26, 10), toon('#f3e6c8', { emissive: 0x8a6a3a }), x, SY + 0.13, 3.35, scene, 0.008); const s = new THREE.Sprite(new THREE.SpriteMaterial({ map: glowTex, color: 0xffc070, transparent: true, depthWrite: false, blending: THREE.AdditiveBlending, opacity: 0.6 })); s.position.set(x, SY + 0.2, 3.35); s.scale.setScalar(0.8); scene.add(s); fl.push(s); }
    for (let i = 0; i < 8; i++) { const sx = i % 2 ? 1 : -1, z = 5 + Math.floor(i / 2) * 3.2, x = sx * 10.5; M(new THREE.CylinderGeometry(0.28, 0.28, 0.7, 12), toon(i % 4 < 2 ? '#c0392b' : '#f3e6c8', { emissive: i % 4 < 2 ? 0x6a1a10 : 0x8a6a3a }), x, 4.2, z, scene, 0.01); const s = new THREE.Sprite(new THREE.SpriteMaterial({ map: glowTex, color: 0xffa860, transparent: true, depthWrite: false, blending: THREE.AdditiveBlending, opacity: 0.6 })); s.position.set(x, 4.2, z); s.scale.setScalar(1.6); scene.add(s); }
    for (const [x, z] of touch ? [[0, 8]] : [[-6, 9], [6, 9]]) { const pl = new THREE.PointLight(0xffa060, 1.0, 16); pl.position.set(x, 5, z); scene.add(pl); } }
  // audience (instanced, seated, facing the stage) + the man in red in his box
  const seats = []; { const keep = touch ? 0.45 : 0.75; for (let r = 0; r < 9; r++) { const z = 5.6 + r * 1.05, y = r * 0.18; for (let i = 0; i < 22; i++) { const x = -9.5 + i * 0.85 + (r % 2) * 0.4; if (x < -6.6 && x > -8.6) continue; if (Math.random() > keep) continue; seats.push({ x, y, z, ph: Math.random() * 6 }); } } }
  const CRC = ['#1f2a44', '#7a2a2a', '#3a5a8a', '#e6e4de', '#5a6a4a', '#8a5ab0', '#201e1d', '#c9a06a', '#3a3836', '#2f7a6a'];
  const crB = new THREE.InstancedMesh(new THREE.CapsuleGeometry(0.19, 0.2, 3, 8).scale(1.15, 1, 0.8), new THREE.MeshToonMaterial({ gradientMap: ST.grad }), seats.length), crH = new THREE.InstancedMesh(new THREE.SphereGeometry(0.13, 10, 7), new THREE.MeshToonMaterial({ gradientMap: ST.grad }), seats.length), crHair = new THREE.InstancedMesh(new THREE.SphereGeometry(0.138, 10, 5, 0, Math.PI * 2, 0, Math.PI * 0.55), new THREE.MeshToonMaterial({ gradientMap: ST.grad, color: 0x1a1210 }), seats.length), dm = new THREE.Object3D(), cc = new THREE.Color();
  seats.forEach((p, i) => { crB.setColorAt(i, cc.set(CRC[i % CRC.length])); crH.setColorAt(i, cc.set(SKINS[i % 6 + 1])); });
  const placeCrowd = (lean = 0, t = 0) => { seats.forEach((p, i) => { const j = lean ? Math.max(0, Math.sin(t * 9 + p.ph)) * lean * 0.08 : 0; dm.position.set(p.x, p.y + 0.3 + j, p.z); dm.rotation.set(-lean * 0.15, Math.PI, 0); dm.scale.set(1, 0.85, 1); dm.updateMatrix(); crB.setMatrixAt(i, dm.matrix); dm.scale.set(1, 1, 1); dm.position.y += 0.34; dm.position.z -= lean * 0.06; dm.updateMatrix(); crH.setMatrixAt(i, dm.matrix); dm.position.y += 0.02; dm.updateMatrix(); crHair.setMatrixAt(i, dm.matrix); }); crB.instanceMatrix.needsUpdate = crH.instanceMatrix.needsUpdate = crHair.instanceMatrix.needsUpdate = true; };
  placeCrowd(); scene.add(crB, crH, crHair);
  M(new THREE.BoxGeometry(2.4, 0.15, 2.2), toon('#3a2214'), 9.6, 2.2, 5.2, scene, 0.01); M(new THREE.BoxGeometry(2.4, 0.7, 0.12), toon('#8a1c1c'), 9.6, 2.6, 4.1, scene, 0.008);
  // ---------- THE SHADOW PLAY: a lit paper screen across the back of the stage, the story told in silhouette line by line (the 2D game's sets + props, animated) ----------
  const SW = 1024, SH2 = 512, G = 446, scv = document.createElement('canvas'); scv.width = SW; scv.height = SH2; let sx = scv.getContext('2d'); const MAINX = sx, ink = document.createElement('canvas'); ink.width = SW; ink.height = SH2; const IX = ink.getContext('2d'), prevCv = document.createElement('canvas'); prevCv.width = SW; prevCv.height = SH2; const PX = prevCv.getContext('2d');
  const FIB = (() => { const c = document.createElement('canvas'); c.width = SW; c.height = SH2; const g = c.getContext('2d'); for (let i = 0; i < 2600; i++) { g.strokeStyle = Math.random() < 0.5 ? 'rgba(255,250,235,0.10)' : 'rgba(90,60,30,0.07)'; g.lineWidth = 1; const x = Math.random() * SW, y = Math.random() * SH2, a = Math.random() * 6.28, l = 4 + Math.random() * 18; g.beginPath(); g.moveTo(x, y); g.quadraticCurveTo(x + Math.cos(a + 0.6) * l * 0.5, y + Math.sin(a + 0.6) * l * 0.5, x + Math.cos(a) * l, y + Math.sin(a) * l); g.stroke(); } const v = g.createRadialGradient(SW / 2, SH2 * 0.52, SH2 * 0.3, SW / 2, SH2 * 0.52, SW * 0.62); v.addColorStop(0, 'rgba(20,10,4,0)'); v.addColorStop(1, 'rgba(20,10,4,0.55)'); g.fillStyle = v; g.fillRect(0, 0, SW, SH2); return c; })(); const scTex = new THREE.CanvasTexture(scv); scTex.colorSpace = THREE.SRGBColorSpace;
  const screen = new THREE.Mesh(new THREE.PlaneGeometry(12.4, 6.2), new THREE.MeshBasicMaterial({ map: scTex })); screen.position.set(0, SY + 3.1, -3.9); scene.add(screen);
  const glowS = new THREE.Sprite(new THREE.SpriteMaterial({ map: glowTex, color: 0xffd8a0, transparent: true, depthWrite: false, blending: THREE.AdditiveBlending, opacity: 0.18 })); glowS.position.set(0, SY + 3, -3.6); glowS.scale.set(14, 7, 1); scene.add(glowS);
  const PAPER = { gate: ['#7a8cb0', '#36425f'], house: ['#f7cf8a', '#d99540'], field: ['#fae09a', '#e9a24a'], door: ['#f2c27a', '#c98538'], wood: ['#a8c4a4', '#4d6b55'], dawn: ['#7a5a9a', '#f4a066'] };
  const SHD = 'rgba(22,13,8,0.9)', SHL = 'rgba(22,13,8,0.45)';
  const bgCache = {}; function bg(key) { if (bgCache[key]) return bgCache[key]; const c = document.createElement('canvas'); c.width = SW; c.height = SH2; const g = c.getContext('2d'), [t0, t1] = PAPER[key] || PAPER.house, gr = g.createLinearGradient(0, 0, 0, SH2); gr.addColorStop(0, t0); gr.addColorStop(1, t1); g.fillStyle = gr; g.fillRect(0, 0, SW, SH2);
      const rg = g.createRadialGradient(SW / 2, SH2 * 0.55, 40, SW / 2, SH2 * 0.55, SW * 0.6); rg.addColorStop(0, 'rgba(255,250,230,0.35)'); rg.addColorStop(1, 'rgba(255,250,230,0)'); g.fillStyle = rg; g.fillRect(0, 0, SW, SH2);
      g.fillStyle = SHL; if (key === 'gate') { for (const x0 of [690, 860]) g.fillRect(x0, 150, 22, G - 150); g.fillRect(650, 132, 270, 22); g.fillRect(670, 176, 230, 12); g.beginPath(); g.moveTo(630, 134); g.quadraticCurveTo(785, 112, 940, 134); g.lineTo(940, 128); g.quadraticCurveTo(785, 100, 630, 128); g.fill(); g.fillStyle = 'rgba(240,248,255,0.5)'; g.beginPath(); g.arc(200, 90, 34, 0, 7); g.fill(); }
      if (key === 'house' || key === 'door') { g.fillRect(0, 40, SW, 18); g.fillRect(0, G - 6, SW, 10); for (const x0 of [60, 950]) g.fillRect(x0, 40, 16, G - 40); g.fillRect(470, 58, 4, 70); g.beginPath(); g.ellipse(472, 142, 26, 18, 0, 0, 7); g.fill(); }
      if (key === 'door') { const dg = g.createLinearGradient(0, 90, 0, G); dg.addColorStop(0, '#1a2338'); dg.addColorStop(1, '#2a3550'); g.fillStyle = dg; g.fillRect(120, 90, 170, G - 90); g.fillStyle = SHD; g.fillRect(112, 84, 186, 10); g.fillRect(112, 84, 10, G - 84); g.fillRect(288, 84, 10, G - 84); g.fillStyle = 'rgba(230,240,255,0.7)'; g.beginPath(); g.arc(240, 150, 14, 0, 7); g.fill(); }
      if (key === 'field') { g.beginPath(); g.moveTo(0, 300); g.lineTo(180, 200); g.lineTo(330, 280); g.lineTo(520, 180); g.lineTo(720, 270); g.lineTo(880, 210); g.lineTo(1024, 260); g.lineTo(1024, 330); g.lineTo(0, 330); g.fill(); g.fillStyle = 'rgba(255,250,220,0.7)'; g.beginPath(); g.arc(800, 110, 50, 0, 7); g.fill(); g.fillStyle = SHL; g.fillRect(860, 300, 70, 46); g.beginPath(); g.moveTo(848, 302); g.lineTo(895, 268); g.lineTo(942, 302); g.fill(); }
      if (key === 'wood') { const band = (n, col, w0, a0) => { g.fillStyle = col; for (let i = 0; i < n; i++) { const x = (i * 131.7 * n) % SW, w = w0 * (0.7 + ((i * 37) % 10) / 15); g.fillRect(x - w / 2, 0, w, G + 10); } }; band(14, 'rgba(22,13,8,0.22)', 14); band(9, 'rgba(22,13,8,0.4)', 22); band(5, 'rgba(22,13,8,0.75)', 38); g.fillStyle = 'rgba(240,250,240,0.55)'; g.beginPath(); g.arc(820, 90, 30, 0, 7); g.fill(); }
      if (key === 'dawn') { g.beginPath(); g.moveTo(0, 360); g.lineTo(200, 270); g.lineTo(360, 340); g.lineTo(560, 250); g.lineTo(760, 330); g.lineTo(1024, 280); g.lineTo(1024, G); g.lineTo(0, G); g.fill(); }
      g.fillStyle = SHD; g.fillRect(0, G, SW, SH2 - G);
      g.strokeStyle = 'rgba(40,24,10,0.35)'; g.lineWidth = 3; for (let x = 128; x < SW; x += 128) { g.beginPath(); g.moveTo(x, 0); g.lineTo(x, SH2); g.stroke(); } for (let y = 128; y < SH2; y += 128) { g.beginPath(); g.moveTo(0, y); g.lineTo(SW, y); g.stroke(); } g.lineWidth = 10; g.strokeStyle = 'rgba(30,18,8,0.8)'; g.strokeRect(5, 5, SW - 10, SH2 - 10);
      bgCache[key] = c; return c; }
  // silhouette puppets (screen space, feet on y = G, ~150 px tall)
  const P2 = { farmer(x, o = {}) { const c = sx, ph = o.walk || 0, bend = o.bend || 0, sit = o.sit || 0, y0 = G - sit * 46 + Math.sin(S.t * 1.6 + x * 0.01) * 1.5; c.fillStyle = o.col || SHD; c.strokeStyle = o.col || SHD; c.lineCap = 'round';
      if (!sit) { c.lineWidth = 11; for (const s2 of [-1, 1]) { c.beginPath(); c.moveTo(x, G - 64); c.lineTo(x + Math.sin(ph) * 16 * s2, G); c.stroke(); } } else { c.beginPath(); c.ellipse(x + 14, G - 14, 34, 16, 0, 0, 7); c.fill(); }
      c.beginPath(); c.moveTo(x - 22 + bend * 26, y0 - 122); c.lineTo(x + 20 + bend * 30, y0 - 120); c.lineTo(x + 28, y0 - 54); c.lineTo(x - 28, y0 - 54); c.closePath(); c.fill();
      const hx = x + bend * 40 + (o.headDown ? 10 : 0), hy = y0 - 136 + (o.headDown ? 14 : 0) + bend * 18; c.beginPath(); c.arc(hx, hy, 14, 0, 7); c.fill();
      if (o.hat !== false) { c.beginPath(); c.moveTo(hx - 40, hy + 2); c.lineTo(hx, hy - 28); c.lineTo(hx + 40, hy + 2); c.closePath(); c.fill(); }
      c.lineWidth = 9; const ax = o.arm || 0; c.beginPath(); c.moveTo(x + 14 + bend * 28, y0 - 112); c.lineTo(x + 30 + Math.cos(-ax) * 34 + bend * 30, y0 - 100 + Math.sin(-ax) * 34); c.stroke();
      if (o.staff) { c.lineWidth = 4; c.beginPath(); c.moveTo(x + 36, y0 - 128); c.lineTo(x + 44, G); c.stroke(); }
      if (o.sickle) { c.lineWidth = 4; const tx = x + 56 + bend * 30, ty = y0 - 70; c.beginPath(); c.moveTo(tx - 12, ty - 8); c.lineTo(tx, ty); c.stroke(); c.beginPath(); c.arc(tx + 8, ty - 4, 12, Math.PI, Math.PI * 1.9); c.stroke(); }
      if (o.baby) { c.beginPath(); c.ellipse(x + 40 + bend * 30, y0 - 132 - (o.lift || 0) * 50, 18, 11, 0.3, 0, 7); c.fill(); c.beginPath(); c.arc(x + 54 + bend * 30, y0 - 138 - (o.lift || 0) * 50, 8, 0, 7); c.fill(); }
      if (o.mino) { c.beginPath(); for (let q = 0; q <= 14; q++) { const fx = x - 34 + bend * 26 + q * 5, fy = y0 - 122 + q * 0.6; c.moveTo(fx, fy); c.lineTo(fx - 4 + Math.sin(S.t * 3 + q) * 2, y0 - 58 + (q % 3) * 6); } c.lineWidth = 4; c.stroke(); }
      { const hx2 = x + 30 + Math.cos(-ax) * 34 + bend * 30, hy2 = y0 - 100 + Math.sin(-ax) * 34; c.save(); c.globalAlpha *= 0.5; c.lineWidth = 2.2; c.beginPath(); c.moveTo(hx2, hy2); c.lineTo(hx2 + 40, SH2); c.moveTo(x, y0 - 80); c.lineTo(x - 10, SH2); c.stroke(); c.restore(); }
      if (o.cup) { c.lineWidth = 7; for (const s2 of [-1, 1]) { c.beginPath(); c.moveTo(hx + s2 * 10, hy + 26); c.lineTo(hx + 22, hy + 4); c.stroke(); } } },
    wife(x, o = {}) { const c = sx, bow = o.bow || 0, kn = o.kneel || 0, y0 = G - kn * 40 + Math.sin(S.t * 1.4 + x * 0.013) * 1.4, al = o.alpha == null ? 1 : o.alpha; c.save(); c.globalAlpha = al; c.fillStyle = o.col || SHD;
      if (o.tails) { for (let i = 0; i < o.tails; i++) { const a2 = -0.95 - i * 0.28 + Math.sin(S.t * 2 + i) * 0.08; c.save(); c.translate(x - 18, y0 - 46); c.rotate(a2); c.beginPath(); c.moveTo(0, -8); c.quadraticCurveTo(46, -26, 104 * (o.tailK || 1), -6); c.quadraticCurveTo(52, 12, 0, 10); c.closePath(); c.fill(); c.restore(); } }
      c.beginPath(); c.moveTo(x - 10 + bow * 18, y0 - 124 + bow * 20); c.quadraticCurveTo(x - 30, y0 - 70, x - 40 - kn * 10, G); c.lineTo(x + 34 + kn * 10, G); c.quadraticCurveTo(x + 26, y0 - 70, x + 12 + bow * 22, y0 - 124 + bow * 20); c.closePath(); c.fill();
      c.fillRect(x - 24 + bow * 8, y0 - 92 + bow * 10, 48, 14); c.beginPath(); c.ellipse(x - 30 + bow * 6, y0 - 86 + bow * 10, 14, 10, 0, 0, 7); c.fill();
      for (const s2 of [-1, 1]) { const sw = Math.sin(S.t * 1.8 + s2) * 4, sx0 = x + s2 * 22 + bow * 14, sy0 = y0 - 116 + bow * 18; c.beginPath(); c.moveTo(sx0, sy0); c.quadraticCurveTo(sx0 + s2 * 26, sy0 + 10, sx0 + s2 * 24 + sw, sy0 + 62); c.quadraticCurveTo(sx0 + s2 * 8 + sw, sy0 + 70, sx0 - s2 * 2, sy0 + 40); c.closePath(); c.fill(); }
      const hx = x + 2 + bow * 34, hy = y0 - 138 + bow * 30; c.beginPath(); c.arc(hx, hy, 13, 0, 7); c.fill(); c.beginPath(); c.moveTo(hx - 10, hy - 6); c.quadraticCurveTo(hx - 26, hy + 30, hx - 22, y0 - 70); c.lineTo(hx - 12, y0 - 72); c.quadraticCurveTo(hx - 12, hy + 20, hx + 2, hy - 2); c.fill(); c.beginPath(); c.ellipse(hx - 6, hy - 14, 10, 7, 0, 0, 7); c.fill();
      { const hx3 = x + 2 + bow * 34, hy3 = y0 - 138 + bow * 30; c.save(); c.strokeStyle = o.col || SHD; c.lineWidth = 2; c.beginPath(); c.moveTo(hx3 - 4, hy3 - 18); c.lineTo(hx3 + 16, hy3 - 34); c.moveTo(hx3 - 8, hy3 - 16); c.lineTo(hx3 - 22, hy3 - 30); c.stroke(); c.beginPath(); c.arc(hx3 + 17, hy3 - 35, 3.5, 0, 7); c.fill(); for (let q = 0; q < 3; q++) { c.beginPath(); c.moveTo(hx3 - 22, hy3 - 30); c.lineTo(hx3 - 26 - q * 3, hy3 - 16 + q * 2); c.stroke(); } c.restore(); }
      if (o.ears) { const e = o.ears; for (const s2 of [-1, 1]) { c.beginPath(); c.moveTo(hx + s2 * 6, hy - 10); c.lineTo(hx + s2 * 14, hy - 10 - 22 * e); c.lineTo(hx + s2 * 18, hy - 4); c.closePath(); c.fill(); } }
      if (o.point) { c.strokeStyle = o.col || SHD; c.lineWidth = 8; c.lineCap = 'round'; c.beginPath(); c.moveTo(hx, y0 - 110); c.lineTo(hx + 60 * o.point, y0 - 120 - 10 * o.point); c.stroke(); }
      if (o.baby) { c.beginPath(); c.ellipse(x + 24, y0 - 100, 20, 12, -0.3, 0, 7); c.fill(); c.beginPath(); c.arc(x + 40, y0 - 108, 8, 0, 7); c.fill(); }
      c.save(); c.strokeStyle = o.col || SHD; c.globalAlpha *= 0.5; c.lineWidth = 2.2; c.beginPath(); c.moveTo(x + 26 + bow * 14, y0 - 66 + bow * 18); c.lineTo(x + 66, SH2); c.moveTo(x - 4, y0 - 60); c.lineTo(x - 18, SH2); c.stroke(); c.restore();
      c.restore(); },
    fox(x, y, o = {}) { const c = sx, sc = o.sc || 1, ph = o.run || 0; c.save(); c.translate(x, y); c.scale(sc * (o.flip ? -1 : 1), sc); c.fillStyle = o.col || SHD;
      for (let i = 0; i < (o.tails || 1); i++) { c.save(); c.translate(-40, -26); c.rotate(-0.5 - i * 0.3 + Math.sin(S.t * 3 + i) * 0.1); c.beginPath(); c.moveTo(0, -6); c.quadraticCurveTo(-40, -30, -90, -12); c.quadraticCurveTo(-46, 12, 0, 8); c.fill(); c.restore(); }
      c.beginPath(); c.moveTo(-46, -30); c.bezierCurveTo(-44, -54, 30, -54, 44, -34); c.bezierCurveTo(48, -20, 20, -12, -10, -14); c.bezierCurveTo(-36, -14, -48, -18, -46, -30); c.fill(); c.beginPath(); c.moveTo(34, -40); c.lineTo(58, -60); c.lineTo(62, -76); c.lineTo(70, -60); c.lineTo(92, -48); c.lineTo(64, -32); c.fill();
      c.strokeStyle = o.col || SHD; c.lineWidth = 7; c.lineCap = 'round'; for (const [lx, p0] of [[-30, 0], [-16, Math.PI], [22, Math.PI], [34, 0]]) { c.beginPath(); c.moveTo(lx, -24); c.lineTo(lx + Math.sin(ph + p0) * 14, 0); c.stroke(); } c.globalAlpha *= 0.45; c.lineWidth = 2.2 / Math.max(0.5, sc); c.beginPath(); c.moveTo(0, -28); c.lineTo(10, 400); c.stroke(); c.restore(); },
    dog(x, o = {}) { const c = sx, b = o.bark || 0; c.fillStyle = SHD; c.beginPath(); c.ellipse(x, G - 44, 48, 22, 0, 0, 7); c.fill(); c.beginPath(); c.ellipse(x + 44, G - 70 - b * 6, 22, 17, 0.2, 0, 7); c.fill(); c.beginPath(); c.moveTo(x + 58, G - 72 - b * 6); c.lineTo(x + 88, G - 66 - b * 10); c.lineTo(x + 58, G - 56 - b * 2); c.fill(); for (const s2 of [-1, 1]) { c.beginPath(); c.moveTo(x + 36 + s2 * 4, G - 84 - b * 6); c.lineTo(x + 32 + s2 * 8, G - 104); c.lineTo(x + 50 + s2 * 6, G - 86); c.fill(); } for (const lx of [-34, -12, 18, 36]) c.fillRect(x + lx - 5, G - 30, 10, 30); c.beginPath(); c.moveTo(x - 46, G - 52); c.quadraticCurveTo(x - 82, G - 70 - (o.wag || 0) * 20, x - 80, G - 96); c.quadraticCurveTo(x - 66, G - 64, x - 42, G - 40); c.fill();
      if (b > 0.5) { c.strokeStyle = SHD; c.lineWidth = 3; for (let q = 1; q <= 3; q++) { c.beginPath(); c.arc(x + 92, G - 68, q * 10, -0.6, 0.6); c.stroke(); } } },
    child(x) { const c = sx; c.fillStyle = SHD; c.beginPath(); c.ellipse(x, G - 14, 48, 16, 0, 0, 7); c.fill(); c.beginPath(); c.arc(x + 44, G - 24, 12, 0, 7); c.fill(); c.fillRect(x - 60, G - 4, 120, 6); },
    lamp(x, y, r = 120) { const c = sx, g = c.createRadialGradient(x, y, 4, x, y, r); g.addColorStop(0, 'rgba(255,236,190,0.65)'); g.addColorStop(1, 'rgba(255,220,160,0)'); c.fillStyle = g; c.fillRect(x - r, y - r, r * 2, r * 2); c.fillStyle = SHD; c.fillRect(x - 10, y - 14, 20, 28); c.fillRect(x - 2, y + 14, 4, G - y - 14); },
    bowl(x, glow) { const c = sx; if (glow) { const g = c.createRadialGradient(x, G - 24, 4, x, G - 24, 90); g.addColorStop(0, 'rgba(190,230,255,' + (0.7 * glow) + ')'); g.addColorStop(1, 'rgba(190,230,255,0)'); c.fillStyle = g; c.fillRect(x - 90, G - 114, 180, 180); } c.fillStyle = SHD; c.beginPath(); c.moveTo(x - 34, G - 24); c.quadraticCurveTo(x, G + 6, x + 34, G - 24); c.closePath(); c.fill(); },
    note(x, y) { const c = sx; c.fillStyle = SHD; c.beginPath(); c.ellipse(x, y, 7, 5, -0.4, 0, 7); c.fill(); c.fillRect(x + 5, y - 26, 3, 26); c.fillRect(x + 5, y - 26, 12, 4); },
    eyes(x, y, open) { if (!open) return; const c = sx, g = c.createRadialGradient(x, y, 1, x, y, 30); g.addColorStop(0, 'rgba(255,214,120,0.6)'); g.addColorStop(1, 'rgba(255,214,120,0)'); c.fillStyle = g; c.fillRect(x - 30, y - 30, 60, 60); c.fillStyle = '#ffd23a'; for (const s2 of [-1, 1]) { c.beginPath(); c.ellipse(x + s2 * 9, y, 6, 3, 0, 0, 7); c.fill(); } },
    rain(n = 90) { const c = sx; c.strokeStyle = 'rgba(225,238,255,0.55)'; c.lineWidth = 2; for (let i = 0; i < n; i++) { const sd = i * 97.13, rx = (sd * 7 + S.t * 180) % SW, ry = (sd * 13 + S.t * 520) % G; c.beginPath(); c.moveTo(rx, ry); c.lineTo(rx - 7, ry + 22); c.stroke(); } },
    rice(h) { const c = sx; c.strokeStyle = SHD; c.lineWidth = 4; for (let i = 0; i < 60; i++) { const rx = (i + 0.5) * SW / 60, lean = Math.sin(i * 1.7 + S.t * 1.2) * 8, top = G - (70 + 30 * Math.sin(i * 2.3)) * h; c.beginPath(); c.moveTo(rx, G); c.quadraticCurveTo(rx + lean * 0.4, (G + top) / 2, rx + lean, top); c.stroke(); c.fillStyle = SHD; c.beginPath(); c.ellipse(rx + lean, top, 4, 8 * h, lean * 0.02, 0, 7); c.fill(); } },
    sun(y) { const c = sx, g = c.createRadialGradient(512, y, 10, 512, y, 160); g.addColorStop(0, 'rgba(255,240,190,1)'); g.addColorStop(0.3, 'rgba(255,220,140,0.8)'); g.addColorStop(1, 'rgba(255,200,120,0)'); c.fillStyle = g; c.fillRect(352, y - 160, 320, 320); } };
  // one tableau per line of THE FOX WIFE (index = line), u = 0..1 through the line
  const ease = v => ss(clamp(v, 0, 1)), walk = (u, a, b) => a + (b - a) * ease(u / 0.75);
  const SCENES = [
    u => { P2.rain(); P2.wife(770, { bow: 0.15 }); P2.farmer(walk(u, 120, 470), { walk: S.t * 7 * (u < 0.75 ? 1 : 0), staff: true, mino: true }); },
    u => { P2.rain(60); P2.wife(700, { bow: Math.sin(ease(u * 1.4) * Math.PI) * 0.6 }); P2.farmer(470, { hat: false, arm: 0.4 * ease(u * 2), staff: true, mino: true }); sx.save(); sx.translate(560, G - 150 - 10 * ease(u * 2)); sx.fillStyle = SHD; sx.beginPath(); sx.moveTo(-40, 6); sx.lineTo(0, -22); sx.lineTo(40, 6); sx.fill(); sx.restore(); },
    u => { P2.lamp(470, 260, 180); P2.farmer(300, { sit: 1, hat: false }); P2.wife(640, { kneel: 1, bow: 0.3 + Math.sin(S.t * 2) * 0.05 }); },
    u => { P2.lamp(860, 250, 260); P2.farmer(230, { sit: 1, hat: false, headDown: true }); const k = ease(u * 1.3); P2.wife(560, { tails: Math.round(k * 4), tailK: 0.6 + k * 0.6, ears: k * 0.8 }); sx.save(); sx.globalAlpha = 0.35 * k; sx.translate(560, 0); sx.scale(1.5, 1.5); sx.translate(-560, -G + G / 1.5); P2.wife(560, { tails: 4, ears: 1, col: SHL }); sx.restore(); },
    u => { P2.rice(0.4 + ease(u) * 0.9); P2.farmer(walk(u, 300, 420), { bend: 0.6 + Math.sin(S.t * 5) * 0.15, sickle: true, hat: true }); },
    u => { P2.lamp(500, 240, 170); P2.wife(560, { kneel: 1, baby: true, bow: 0.15 }); P2.farmer(330, { sit: 1, hat: false, bend: 0.3 * ease(u * 2) }); },
    u => { P2.lamp(500, 240, 170); P2.farmer(420, { hat: false, baby: true, lift: ease(u * 1.4) }); P2.wife(640, { kneel: 1 }); },
    u => { P2.lamp(820, 300, 140); P2.child(420); P2.wife(600, { kneel: 1, ears: 0.6 + Math.sin(S.t * 1.5) * 0.1, tails: 1 + Math.floor(ease(u) * 3) }); for (let q = 0; q < 4; q++) { const t2 = (S.t * 0.6 + q * 0.25) % 1; P2.note(640 + t2 * 160 + Math.sin(t2 * 9) * 12, G - 150 - t2 * 180); } },
    u => { P2.lamp(600, 240, 160); P2.farmer(560, { hat: false, arm: -0.2 }); P2.dog(walk(u, 360, 210) - 160 + 160, { bark: Math.max(0, Math.sin(S.t * 9)) }); },
    u => { P2.lamp(600, 240, 160); P2.wife(560, { point: ease(u * 2) }); P2.dog(200 + ease((u - 0.4) * 2) * 260 - ease((u - 0.4) * 2) * 520, { wag: -1 }); },
    u => { P2.farmer(560, { hat: false, arm: 0.5 * ease(u * 2) + 0.2 }); P2.wife(800, {}); P2.bowl(400, 0.4); },
    u => { const k = ease((u - 0.15) * 1.6); P2.wife(walk(u, 760, 470), { bow: k * 0.9 }); P2.bowl(400, 0.6 + k * 0.6); P2.fox(400, G - 40 - k * 70, { sc: 0.6 + k * 0.4, tails: 4, col: 'rgba(170,220,255,' + (0.85 * k) + ')' }); },
    u => { P2.wife(560, { ears: 1, tails: 4 }); P2.farmer(300, { hat: false }); P2.bowl(400, 0.3); },
    u => { P2.farmer(380, { sit: 1, hat: false, headDown: true }); P2.wife(640, { ears: 1, tails: 4, alpha: 1 - ease(u) * 0.4 }); },
    u => { const k = ease(u * 1.2); if (k < 0.35) P2.wife(620, { ears: 1, tails: 4, alpha: 1 - k / 0.35 }); P2.fox(620 - Math.max(0, k - 0.2) * 620, G, { sc: 1.1, tails: 4, run: S.t * 14, flip: true, col: 'rgba(22,13,8,' + Math.min(0.9, k * 3) + ')' }); P2.farmer(820, { sit: 1, hat: false, headDown: true }); sx.fillStyle = SHD; for (let q = 0; q < 6; q++) { if (k * 6 < q) continue; sx.beginPath(); sx.ellipse(560 - q * 70, G + 12 + (q % 2) * 10, 7, 9, 0.2, 0, 7); sx.fill(); } },
    u => { P2.farmer(walk(u, 100, 520), { walk: S.t * 6 * (u < 0.75 ? 1 : 0), staff: true, bend: 0.25 }); },
    u => { P2.farmer(520, { staff: true, cup: true }); sx.strokeStyle = SHL; sx.lineWidth = 4; for (let q = 1; q <= 3; q++) { const r = ((S.t * 80 + q * 40) % 140); sx.beginPath(); sx.arc(540, G - 130, r, -0.7, 0.7); sx.stroke(); } },
    u => { P2.farmer(walk(u, 300, 600), { walk: S.t * 5 * (u < 0.75 ? 1 : 0), staff: true }); for (const [ex, ey, p0] of [[180, 300, 0], [860, 330, 2.1], [740, 250, 4]]) P2.eyes(ex + walk(u, 0, 260) * (ex < 500 ? 1 : 0.3), ey, ((S.t * 0.9 + p0) % 4) > 0.3); },
    u => { P2.farmer(560, { staff: true }); P2.wife(300, { alpha: 0.32 + Math.sin(S.t * 2) * 0.06, col: 'rgba(250,250,255,0.9)' }); },
    u => { P2.farmer(560, { staff: true, headDown: true }); P2.wife(300, { alpha: 0.32 * (1 - ease(u)), col: 'rgba(250,250,255,0.9)' }); },
    u => { P2.farmer(560, { staff: true, hat: false }); },
    u => { P2.sun(G - 40 - ease(u) * 200); P2.farmer(520, { sit: 1, hat: false, staff: false }); } ];
  const SP = { acc: 1 };
  function drawShadow() { const L = LINES[S.i], key = S.mode === 'play' && S.phase === 'lines' && L ? S.set : S.mode === 'done' ? (S.done && S.done.over === 'caught' ? 'door' : 'dawn') : 'gate', mx = MAINX;
    mx.globalAlpha = 1; mx.globalCompositeOperation = 'source-over'; if (S.was && S.setT < 1) { mx.drawImage(bg(S.was), 0, 0); mx.globalAlpha = S.setT; } mx.drawImage(bg(key), 0, 0); mx.globalAlpha = 1;
    // the lamp behind the paper breathes and drifts
    const fl = 0.85 + 0.1 * Math.sin(S.t * 7.3) + 0.05 * Math.sin(S.t * 17.1), lx = SW / 2 + Math.sin(S.t * 0.4) * 70, ly = SH2 * 0.5 + Math.cos(S.t * 0.31) * 24; mx.globalCompositeOperation = 'lighter'; const hg = mx.createRadialGradient(lx, ly, 20, lx, ly, SW * 0.42); hg.addColorStop(0, 'rgba(255,226,170,' + (0.2 * fl).toFixed(3) + ')'); hg.addColorStop(1, 'rgba(255,210,150,0)'); mx.fillStyle = hg; mx.fillRect(0, 0, SW, SH2); mx.globalCompositeOperation = 'source-over';
    // puppets on their own sheet, then pressed onto the paper: a soft far echo + a crisp shadow with a warm penumbra
    IX.clearRect(0, 0, SW, SH2); sx = IX;
    if (S.mode === 'intro' || (S.mode === 'play' && S.phase === 'intro')) { P2.rain(50); P2.fox(512, G - 20, { sc: 1.6, tails: 4 }); P2.wife(220, { alpha: 0.5 }); P2.farmer(820, { staff: true, mino: true }); }
    else if (S.mode === 'play' && L && SCENES[S.i]) SCENES[S.i](clamp(S.lineT / S.lineOf, 0, 1));
    else if ((S.mode === 'play' && S.over === 'caught') || (S.mode === 'done' && S.done && S.done.over === 'caught')) { P2.fox(512, G, { sc: 3.2, tails: 4 }); P2.bowl(512, 1); }
    else if ((S.mode === 'play' && S.over) || S.mode === 'done') { P2.sun(G - 200); P2.farmer(420, { sit: 1, hat: false }); P2.wife(620, { alpha: 0.4, col: 'rgba(255,255,255,0.8)', ears: 1, tails: 1 }); }
    sx = MAINX;
    mx.save(); mx.globalAlpha = 0.18 * fl; mx.drawImage(ink, -SW * 0.02 + (lx - SW / 2) * -0.05, -SH2 * 0.045, SW * 1.04, SH2 * 1.045); mx.restore();
    mx.save(); mx.shadowColor = 'rgba(70,30,8,0.55)'; mx.shadowBlur = touch ? 7 : 12; mx.globalAlpha = 0.96; mx.drawImage(ink, 0, 0); mx.restore();
    if (S.xf > 0) { mx.globalAlpha = S.xf; mx.drawImage(prevCv, 0, 0); mx.globalAlpha = 1; }
    mx.drawImage(FIB, 0, 0); mx.fillStyle = 'rgba(25,12,4,' + (0.06 + (1 - fl) * 0.5).toFixed(3) + ')'; mx.fillRect(0, 0, SW, SH2);
    scTex.needsUpdate = true; }
  // the 3D bowl of still water downstage (the zoom goes to it on "the water is honest")
  const PROPS = {};
  { const bowl = new THREE.Group(); bowl.position.set(1.3, SY, 1.4); const bw = M(new THREE.CylinderGeometry(0.34, 0.22, 0.2, 20, 1, true), toon('#3a2214'), 0, 0.1, 0, bowl, 0.008); bw.material = toon('#3a2214').clone(); bw.material.side = THREE.DoubleSide; M(new THREE.CylinderGeometry(0.2, 0.2, 0.04, 16), toon('#2a1810'), 0, 0.02, 0, bowl, 0);
    const foxFace = canvasTex(128, 128, c => { c.fillStyle = '#9ad8ff'; c.fillRect(0, 0, 128, 128); c.fillStyle = 'rgba(255,170,80,0.95)'; c.beginPath(); c.moveTo(64, 104); c.lineTo(30, 54); c.lineTo(34, 18); c.lineTo(50, 40); c.lineTo(78, 40); c.lineTo(94, 18); c.lineTo(98, 54); c.closePath(); c.fill(); c.fillStyle = '#141210'; c.beginPath(); c.ellipse(50, 60, 6, 3, 0.4, 0, 7); c.ellipse(78, 60, 6, 3, -0.4, 0, 7); c.fill(); });
    const water = new THREE.Mesh(new THREE.CircleGeometry(0.31, 24), new THREE.MeshBasicMaterial({ color: 0x6a9ac0, transparent: true, opacity: 0.85 })); water.rotation.x = -Math.PI / 2; water.position.y = 0.17; bowl.add(water); const refl = new THREE.Mesh(new THREE.CircleGeometry(0.3, 24), new THREE.MeshBasicMaterial({ map: foxFace, transparent: true, opacity: 0, depthWrite: false })); refl.rotation.x = -Math.PI / 2; refl.position.y = 0.175; bowl.add(refl); const glow = new THREE.Sprite(new THREE.SpriteMaterial({ map: glowTex, color: 0x9ad8ff, transparent: true, depthWrite: false, blending: THREE.AdditiveBlending, opacity: 0 })); glow.position.y = 0.4; glow.scale.setScalar(1.4); bowl.add(glow);
    bowl.visible = false; scene.add(bowl); PROPS.bowl = { o: bowl, refl, glow }; }
  // Ben's own shadow on the lit boards: a fox, with as many tails as the house has noticed (2D: nohTails)
  const shCv = document.createElement('canvas'); shCv.width = 512; shCv.height = 256; const shTex = new THREE.CanvasTexture(shCv);
  const benShadow = new THREE.Mesh(new THREE.PlaneGeometry(3.2, 1.6), new THREE.MeshBasicMaterial({ map: shTex, transparent: true, depthWrite: false })); benShadow.rotation.x = -Math.PI / 2; benShadow.position.set(-0.3, SY + 0.012, -0.6); benShadow.renderOrder = 1; scene.add(benShadow);
  const pool = new THREE.Mesh(new THREE.CircleGeometry(2.0, 32), new THREE.MeshBasicMaterial({ map: glowTex, color: 0xffd6a0, transparent: true, opacity: 0.35, depthWrite: false, blending: THREE.AdditiveBlending })); pool.rotation.x = -Math.PI / 2; pool.position.set(0, SY + 0.008, 0.2); scene.add(pool);
  let shTails = -1; function drawBenShadow(n) { if (n === shTails) return; shTails = n; const c = shCv.getContext('2d'); c.clearRect(0, 0, 512, 256); c.fillStyle = 'rgba(20,10,6,0.55)'; c.save(); c.translate(256, 150); for (let i = 0; i < n; i++) { c.save(); c.rotate(-0.4 - (i - (n - 1) / 2) * 0.3); c.beginPath(); c.moveTo(-10, -8); c.quadraticCurveTo(-70, -40, -150, -14); c.quadraticCurveTo(-80, 18, -6, 12); c.fill(); c.restore(); } c.beginPath(); c.ellipse(30, 0, 70, 46, 0, 0, 7); c.fill(); c.beginPath(); c.arc(100, -20, 30, 0, 7); c.fill(); for (const s2 of [-1, 1]) { c.beginPath(); c.moveTo(96 + s2 * 12, -40); c.lineTo(104 + s2 * 20, -80); c.lineTo(122 + s2 * 6, -40); c.fill(); } c.restore(); shTex.needsUpdate = true; }
  const rain = []; { const rm = new THREE.MeshBasicMaterial({ color: 0xb8d0f0, transparent: true, opacity: 0.35 }); for (let i = 0; i < (touch ? 40 : 90); i++) { const m = new THREE.Mesh(new THREE.PlaneGeometry(0.012, 0.35), rm); m.position.set(rr(-6, 6), rr(SY, SY + 6), rr(-3.5, 2.5)); m.rotation.z = 0.25; m.visible = false; scene.add(m); rain.push(m); } }
  // ---------- people ----------
  const people = [];
  function mkW(cfg) { const g = HK.make(cfg); g.rotation.order = 'YXZ'; scene.add(g); g.traverse(m => { if (m.isMesh) m.castShadow = !touch; }); const U = g.userData.H, w = { g, cfg, U, L: U.L, k: U.L.H / 1.75, R0: HK.restPose(g), P: null, x: 0, y: 0, z: 0, yaw: 0, anim: 'stand' }; w.P = w.R0; people.push(w); return w; }
  const ben = mkW({ ...HUMAN_PRESETS.bensumoClothes1, top: '#141210', bottom: '#141210', accent: '#2a2826', whiteTrim: false, crest: false, pads: false, theme8: false, masks: KEYS, wearing: 'old' }); ben.x = 0; ben.y = SY; ben.z = 0.5;
  const maskImg = {}; for (const k of KEYS) { try { ben.U.J.masks[k].children[0].material.map.image.toBlob(b => { if (b) maskImg[k] = URL.createObjectURL(b); }, 'image/png'); } catch (e) { maskImg[k] = ''; } }
  const handMasks = {}; for (const k of KEYS) { const src = ben.U.J.masks[k], cl = src.clone(true); cl.visible = false; cl.position.set(0, -ben.L.H * 0.06, ben.L.H * 0.04); cl.rotation.set(-1.35, 0, 0); cl.scale.setScalar(0.85); ben.U.J.handR.add(cl); handMasks[k] = cl; }
  const chorus = [[4.6, -0.2], [4.6, -1.2]].map(([x, z]) => { const w = mkW({ name: 'CHORUS', height: 1.7, build: 1.0, outfit: 'kimono', top: '#201e1d', bottom: '#201e1d', accent: '#9a948c', hair: 'short', hairCol: '#1a1410', mood: 'neutral', skin: SKINS[3], age: 0.6 }); w.x = x; w.y = SY; w.z = z; w.yaw = -Math.PI / 2; w.anim = 'kneel'; return w; });
  const drummer = mkW({ name: 'DRUM', height: 1.7, build: 1.05, outfit: 'kimono', top: '#2a3a5a', bottom: '#141a2a', accent: '#e6b45a', hair: 'short', hairCol: '#141210', mood: 'focus', skin: SKINS[2], age: 0.45 }); drummer.x = 3.4; drummer.y = SY; drummer.z = -2.4; drummer.yaw = -0.5; drummer.anim = 'drum';
  const drum = new THREE.Group(); drum.position.set(3.05, SY, -1.95); scene.add(drum); M(new THREE.CylinderGeometry(0.42, 0.42, 0.5, 20), toon('#7a2a1a'), 0, 0.55, 0, drum, 0.01).rotation.x = Math.PI / 2; for (const zz of [-0.25, 0.25]) M(new THREE.CylinderGeometry(0.44, 0.44, 0.03, 20), toon('#e6dcc8'), 0, 0.55, zz, drum, 0).rotation.x = Math.PI / 2; for (const sx of [-1, 1]) M(new THREE.BoxGeometry(0.06, 0.6, 0.06), toon('#3a2214'), sx * 0.3, 0.3, 0, drum, 0.006); drum.rotation.y = -0.5 + Math.PI / 2;
  const actor = mkW({ ...HUMAN_PRESETS.oldActor }); actor.x = -5.2; actor.y = SY; actor.z = -1.0; actor.yaw = 1.0; actor.anim = 'stand';
  const general = mkW({ ...HUMAN_PRESETS.general, helmet: false }); general.x = 9.6; general.y = 2.28; general.z = 5.4; general.yaw = Math.PI + 0.55; general.anim = 'sit';
  // the house crest is PAINTED on the curtain: each half carries half of the fox mask, so it splits down the middle when the curtain draws open
  { const fx = ben.U.J.masks.fox.children[0].material.map.image, cols = ['#141210', '#c2501e', '#2f5a3a'];
    curtain.forEach(c => { const cv = document.createElement('canvas'); cv.width = 512; cv.height = 512; const g = cv.getContext('2d'); for (let i = 0; i < 12; i++) { g.fillStyle = cols[i % 3]; g.fillRect(i * 512 / 12, 0, 512 / 12 + 1, 512); }
      for (let i = 0; i < 12; i++) { g.fillStyle = 'rgba(0,0,0,0.18)'; g.fillRect(i * 512 / 12 + 512 / 12 - 6, 0, 6, 512); }
      const mh = 300, mw = mh * fx.width / fx.height, cx = c.sx < 0 ? 512 : 0, cy = 70; g.save(); g.shadowColor = 'rgba(0,0,0,0.5)'; g.shadowBlur = 18; g.drawImage(fx, cx - mw / 2, cy, mw, mh); g.restore();
      g.fillStyle = 'rgba(0,0,0,0.16)'; for (let i = 0; i < 12; i++) g.fillRect(i * 512 / 12 + 512 / 12 - 6, 0, 6, 512);
      const t = new THREE.CanvasTexture(cv); t.colorSpace = THREE.SRGBColorSpace; c.m.material.map = t; c.m.material.needsUpdate = true; }); }
  const curtainGlow = new THREE.Sprite(new THREE.SpriteMaterial({ map: glowTex, color: 0xffd8a0, transparent: true, depthWrite: false, blending: THREE.AdditiveBlending, opacity: 0.3 })); curtainGlow.position.set(0, SY + 4.2, 3.12); curtainGlow.scale.setScalar(4.4); scene.add(curtainGlow);
  const rack = new THREE.Group(); rack.position.set(-2.0, SY, -0.4); scene.add(rack); M(new THREE.BoxGeometry(1.7, 0.08, 0.3), toon('#3a2214'), 0, 1.25, 0, rack, 0.006); for (const sx2 of [-1, 1]) M(new THREE.BoxGeometry(0.08, 1.25, 0.08), toon('#3a2214'), sx2 * 0.82, 0.62, 0, rack, 0.006);
  const rackMasks = {}; KEYS.forEach((k, i) => { const cl = ben.U.J.masks[k].clone(true); cl.position.set(-0.52 + i * 0.52, 0.74, 0.08); cl.rotation.set(0, 0, 0); cl.scale.setScalar(0.5); cl.visible = true; rack.add(cl); rackMasks[k] = cl; });
  // ---------- state ----------
  const S = { mode: 'intro', t: 0, i: -1, lineT: 0, lineOf: 1, house: C.house0, slip: 0, wearing: 'old', into: null, swap: 0, hit: 0, miss: 0, foxes: 0, scene: '', sceneT: 0, mark: null, over: null, overT: 0, shake: 0, warned: false, set: 'gate', setT: 1, prop: '', stamped: false, cheer: 0, demo: false, done: null, curtain: 1, look: V3(0, SY + 1.5, 0.5) };
  const HEAD = { x: 0, y: 0, sx: 0, sy: 0, keys: new Set(), roll: 0, life: 0 };
  const LIFE = { girl: { amp: 0.16, sp: 0.9, nod: 0.05, sway: 0.03 }, old: { amp: 0.1, sp: 0.6, nod: 0.09, sway: 0.02 }, fox: { amp: 0.26, sp: 1.45, nod: 0.06, sway: 0.06 } };
  let PAUSE = false, raf = 0, hudT = 0; const clock = new THREE.Clock(), SAFE = { top: 0, bottom: 0 };
  const LINES = C.lines, MASKS = C.masks, mOf = k => MASKS.find(m => m.key === k) || {};
  const AU = theatreAudio(audio);
  const sfx = { drum: ok => AU.taiko(ok), swap: () => AU.rustle(), flute: () => { AU.hyoshigi(2); AU.flute(AU.HIRA[0] * 2, 2.6, 0.07); }, good: () => AU.ooh(undefined, 0.07), fox: () => { AU.gasp(undefined, 0.12); setTimeout(() => AU.ooh(undefined, 0.11), 260); setTimeout(() => AU.applause(1.1, 26, 0.07), 450); }, miss: () => AU.cough(), between: () => { AU.cough(); setTimeout(() => AU.gasp(undefined, 0.08), 200); }, stamp: () => AU.stamp(), koto: () => {} };
  const listening = () => S.mode === 'play' && !S.over && S.i >= 0 && S.lineT < S.lineOf * C.listen;
  const showing = () => S.swap > 0 ? null : S.wearing;
  function wear(key) { if (S.mode !== 'play' || S.over || S.i < 0) return false; try { AU.init(); } catch (e) {} if (listening()) return false; if (S.swap > 0 || S.wearing === key || !KEYS.includes(key)) return false; S.into = key; S.swap = C.swap / 60 * 1.25; S.swapOf = S.swap; sfx.swap(); return true; }
  function setTo(set, prop) { if (set && set !== S.set) { S.was = S.set; S.set = set; S.setT = 0; } S.prop = prop || ''; S.propT = 0; }
  function start(demo = false) { S.tilts = 0; try { AU.init(); AU.hyoshigi(14, true); } catch (e) {} Object.assign(S, { mode: 'play', t: 0, i: -1, lineT: 0, lineOf: 2, house: C.house0, slip: 0, wearing: 'old', into: null, swap: 0, hit: 0, miss: 0, foxes: 0, scene: '', sceneT: 0, mark: null, over: null, overT: 0, shake: 0, warned: false, prop: '', demo, done: null, curtain: 1, phase: 'intro', phaseT: 0 }); HK.setMask(ben.g, 'old'); setTo('gate', ''); S.setT = 1; }
  function next() { if (S.i >= 0) { PX.clearRect(0, 0, SW, SH2); PX.drawImage(scv, 0, 0); S.xf = 1; } S.i++; const L = LINES[S.i]; if (!L) { finish(); return; } S.lineT = 0; S.lineOf = (L.frames || C.frames) / 60 / OPT.speed; S.stamped = false; S.demoT = rr(0.08, 0.3); S.demoErr = Math.random() < 0.06; setTo(L.set, L.prop); if (L.scene) { S.scene = L.scene; S.sceneT = 2.2; sfx.flute(); } }
  function beat() { const L = LINES[S.i]; if (!L) { finish(); return; } const sh = showing(), fox = L.mask === C.foxMask; sfx.drum(sh === L.mask); S.drumHit = 0.25;
    if (sh === null) { S.house += C.between; S.slip += C.betweenSlip; S.miss++; S.mark = { kind: 'between', t: 1.6, text: C.betweenCall }; S.shake = 0.3; sfx.between(); }
    else if (sh === L.mask) { S.hit++; S.house += fox ? C.foxHouse : C.house; S.slip -= C.cool; const wantUp = L.act === 'terasu', wantDn = L.act === 'kumorasu', tilted = wantUp ? HEAD.y > 0.35 : wantDn ? HEAD.y < -0.35 : false; if (tilted) { S.house += 3; S.tilts = (S.tilts || 0) + 1; AU.ooh(undefined, 0.1); } if (fox) { S.foxes++; S.mark = { kind: 'fox', t: 1.6, text: tilted ? (wantUp ? 'THE MASK SMILES · ' : 'THE MASK WEEPS · ') + C.foxCall : C.foxCall }; sfx.fox(); S.cheer = 1.2; S.foxZoom = 1.4; } else { S.mark = { kind: 'good', t: 1.2, text: tilted ? (wantUp ? 'THE MASK SMILES' : 'THE MASK WEEPS') : C.goodCall }; sfx.good(); S.cheer = 0.6; } }
    else { S.house += C.wrong; S.slip += C.wrongSlip; S.miss++; S.mark = fox ? { kind: 'miss', t: 1.6, text: C.foxMissCall } : { kind: 'miss', t: 1.2, text: C.missCall }; S.shake = 0.2; sfx.miss(); }
    S.house = clamp(S.house, 0, 100); S.slip = Math.max(0, S.slip);
    if (!S.warned && S.slip >= C.slipMax * C.warnAt) { S.warned = true; S.mark = { kind: 'between', t: 2, text: C.warnCall }; }
    if (S.slip >= C.slipMax) { S.slip = C.slipMax; S.over = 'caught'; S.overT = 0; S.shake = 0.8; S.mark = null; AU.gasp(undefined, 0.25); for (let q = 0; q < 6; q++) setTimeout(() => AU.taiko(false, 0.5 - q * 0.05), 120 + q * 150); AU.flute(AU.HIRA[1], 3.5, 0.06); return; } next(); }
  function finish() { if (S.over) return; S.over = S.house >= C.pass ? 'won' : 'thin'; S.overT = 0; S.mark = null; if (S.over === 'won') { AU.hyoshigi(2); AU.taiko(true, 0.7); setTimeout(() => AU.applause(S.house >= C.great ? 5 : 3.2, S.house >= C.great ? 70 : 45, 0.13), 300); S.cheer = 3; } else { AU.applause(1.4, 10, 0.06); setTimeout(() => AU.cough(), 600); } }
  function pay() { const d = { over: S.over, house: Math.round(S.house), hit: S.hit, miss: S.miss, foxes: S.foxes, lines: LINES.length, gold: 0, xp: 0, great: false, best: save.stat('kyoto.theatre.best', 0), newBest: false, demo: S.demo };
    if (S.over === 'won' && !S.demo) { d.gold = Math.round(S.house * C.goldPer); d.xp = C.xp; save.addGold(d.gold); save.addXp(d.xp); save.setFlag('kyotoTheatrePlayed'); if (S.house >= C.great) { d.great = true; save.setFlag('kyotoTheatrePlayedWell'); } } else if (S.over === 'won') { d.great = S.house >= C.great; }
    if (!S.demo) { d.newBest = save.best('kyoto.theatre.best', Math.round(S.house)); d.best = save.stat('kyoto.theatre.best', 0); }
    d.title = S.over === 'won' ? C.wonTitle : S.over === 'thin' ? C.thinTitle : C.caughtTitle; d.note = S.over === 'caught' ? C.caughtNote : S.over === 'thin' ? C.thinNote : d.great ? C.greatNote : C.note; d.body = S.over === 'caught' ? C.caughtBody : d.note.body; S.done = d; S.mode = 'done';
    if (S.demo) setTimeout(() => { if (S.demo) toIntro(); }, 3500); }
  function toIntro() { S.mode = 'intro'; S.demo = false; S.done = null; S.over = null; S.mark = null; S.curtain = 1; S.i = -1; HK.setMask(ben.g, 'old'); S.wearing = 'old'; setTo('gate', ''); }
  // ---------- poses ----------
  function poseOf(w) { const L = w.L, k = w.k, sy = L.hipY + L.torsoL * 0.93, B = w.R0, fy = L.footH, J = w.U.J, f = J.heavy ? (J.bellyR || 0.3) * 1.15 : 0.2 * k;
    if (w.anim === 'kneel') return { ...B, hip: [0, -L.hipY * 0.6, -0.18 * k], lean: 0.06, fL: [0.13 * k, fy, -0.42 * k], fR: [-0.13 * k, fy, -0.42 * k], kL: [0.2 * k, L.hipY * 0.3, 1.5], kR: [-0.2 * k, L.hipY * 0.3, 1.5], hL: [0.17 * k, L.hipY * 0.5, 0.18 * k], hR: [-0.17 * k, L.hipY * 0.5, 0.18 * k], eL: [1, L.hipY * 0.8, 0], eR: [-1, L.hipY * 0.8, 0], pitch: 0.08, mouth: w.sing || 0 };
    if (w.anim === 'drum') { const hit = S.drumHit > 0 ? S.drumHit / 0.25 : 0; return { ...B, hip: [0, -L.hipY * 0.6, -0.18 * k], fL: [0.13 * k, fy, -0.42 * k], fR: [-0.13 * k, fy, -0.42 * k], kL: [0.2 * k, L.hipY * 0.3, 1.5], kR: [-0.2 * k, L.hipY * 0.3, 1.5], lean: 0.12, hR: [-0.2 * k, sy - 0.2 * k + hit * 0.25 * k, 0.4 * k], eR: [-1, sy, 0], hL: [0.2 * k, sy - 0.25 * k, 0.35 * k], eL: [1, sy, 0] }; }
    if (w.anim === 'sit') return { ...B, hip: [0, -L.hipY * 0.45, -0.1], fL: [0.2 * k, fy, 0.25 * k], fR: [-0.2 * k, fy, 0.25 * k], kL: [0.3, L.hipY, 1], kR: [-0.3, L.hipY, 1], hL: [0.25 * k, L.hipY * 0.75, 0.3 * k], hR: [-0.25 * k, L.hipY * 0.75, 0.3 * k], yaw: Math.sin(S.t * 0.2) * 0.2 - 0.35, mood: 'angry' };
    if (w !== ben) return { ...B, hip: [Math.sin(S.t * 0.7) * 0.006, 0, 0], yaw: 0.2 + Math.sin(S.t * 0.3) * 0.15, hL: [B.hL[0], B.hL[1], 0.12], hR: [-0.08 * k, sy - 0.32 * k, 0.24 * k], eR: [-1, sy - 0.5, -0.3] };
    // BEN: the kata for this line, then the mask change on top
    const Lx = LINES[S.i], act = S.mode === 'play' && Lx && !S.over ? Lx.act : 'stand', u = S.lineOf ? clamp(S.lineT / S.lineOf, 0, 1) : 0, e = ss(clamp(u / 0.5, 0, 1));
    const base = { ...B, hip: [0, -0.08 * k, 0], lean: 0.05, fL: [B.fL[0] + 0.05, fy, 0.08 * k], fR: [B.fR[0] - 0.05, fy, -0.04 * k], mood: null };
    let P = base; const arm = (side, x, y, z) => ({ [side > 0 ? 'hL' : 'hR']: [x, y, z], [side > 0 ? 'eL' : 'eR']: [side * 1.2, sy - 0.4, -0.3] });
    if (act === 'sashi') P = { ...base, lean: 0.12, ...arm(-1, -0.2 * k, sy + 0.05 * k * e, f + 0.55 * k * e) };
    else if (act === 'hiraki') P = { ...base, lean: -0.05, hip: [0, -0.12 * k, 0], ...arm(1, 0.55 * k * e + 0.3 * k * (1 - e), sy - 0.05 * k, f * 0.6), ...arm(-1, -0.55 * k * e - 0.3 * k * (1 - e), sy - 0.05 * k, f * 0.6) };
    else if (act === 'shikake') P = { ...base, lean: 0.15, hip: [0, -0.12 * k, 0.08 * k * e], fR: [B.fR[0] - 0.05, fy, 0.16 * k * e], ...arm(-1, -0.15 * k, sy - 0.25 * k, f + 0.4 * k * e) };
    else if (act === 'kake') P = { ...base, twist: Math.sin(u * Math.PI) * 0.4, ...arm(-1, -0.45 * k, sy - 0.15 * k + Math.sin(u * Math.PI) * 0.2 * k, f + 0.25 * k) };
    else if (act === 'terasu') P = { ...base, pitch: -0.28 * e, lean: -0.08 * e };
    else if (act === 'kumorasu') P = { ...base, pitch: 0.38 * e, lean: 0.12 * e };
    else if (act === 'shiori') P = { ...base, pitch: 0.2 * e, ...arm(1, 0.06 * k, sy + 0.22 * k * e, f + 0.18 * k) };
    else if (act === 'mawari') P = { ...base, hip: [0, -0.1 * k, 0] };
    else if (act === 'stamp') { const lift = u > 0.38 && u < 0.56 ? Math.sin((u - 0.38) / 0.18 * Math.PI / 2) : u >= 0.56 && u < 0.62 ? 1 - (u - 0.56) / 0.06 : 0; P = { ...base, hip: [0.04 * k * lift, -0.14 * k, 0], side: 0.12 * lift, fR: [B.fR[0] - 0.05, fy + lift * 0.3 * k, 0.04], kR: [-0.6, L.hipY * 1.1, 1] }; }
    else if (act === 'ori') P = { ...base, hip: [0, -L.hipY * 0.55 * e, -0.1 * k * e], fL: [0.15 * k, fy, -0.3 * k * e], fR: [-0.15 * k, fy, -0.3 * k * e], kL: [0.3, L.hipY * 0.3, 1.5], kR: [-0.3, L.hipY * 0.3, 1.5], pitch: 0.3 * e, lean: 0.1 };
    if (S.over === 'won' && S.overT > 0.5) P = { ...base, lean: 0.55 * ss(clamp((S.overT - 0.5) / 0.8, 0, 1)), pitch: 0.4 };
    else { P = { ...P, yaw: (P.yaw || 0) + HEAD.x * 0.75 + HEAD.lifeYaw, pitch: (P.pitch || 0) - HEAD.y * 0.42 + HEAD.lifeNod, twist: (P.twist || 0) + HEAD.x * 0.12, side: (P.side || 0) + HEAD.lifeSway }; }
    if (S.swap > 0) { const v = 1 - S.swap / S.swapOf, h = Math.sin(v * Math.PI), from = P.hR || B.hR, to = [-0.05 * k, sy + 0.4 * k, f + 0.34 * k]; P = { ...P, hR: from.map((a, i) => a + (to[i] - a) * h), eR: [-1.1, sy - 0.1, -0.4] }; }
    return P; }
  // ---------- camera ----------
  function camShot() { const asp = CW() / CHh(), H = CHh(), tv = Math.tan(camera.fov * Math.PI / 360), th = tv * asp, yT = 1 - 2 * SAFE.top / H, yB = -1 + 2 * SAFE.bottom / H, frac = Math.max(0.25, (yT - yB) / 2), yc = clamp((yT + yB) / 2, -0.6, 0.6);
    if (S.mode === 'intro') { const a = Math.sin(S.t * 0.08) * 0.12, port = asp < 0.8, d = port ? 13 : 12, ox = port ? 0 : -clamp(2.6 * (1.6 / asp), 1.2, 2.6), oy = port ? -1.0 : 0; return { pos: V3(ox + Math.sin(a) * d, SY + 3.9, 3 + Math.cos(a) * d), look: V3(ox, SY + 3.4 + oy, 3) }; }
    const wide = asp >= 0.8, hNeed = wide ? 3.0 : 2.7, span = wide ? 5.6 : 2.6, d = clamp(Math.max((span / 2) / th, (hNeed / 2) / (frac * tv)) * 1.04, 4, 15), cy = SY + (wide ? 2.0 : ben.L.H * 0.62);
    const base = { pos: V3(ben.x * 0.5, cy + d * 0.12, ben.z + d), look: V3(ben.x * 0.5, cy - yc * d * tv, ben.z) }, zw = ss(clamp(S.zw || 0, 0, 1)); if (zw < 0.001 || !S.ztLast) return base;
    let z; if (S.ztLast === 'face') { const hp = ben.U.J.head.getWorldPosition(V3()); hp.y += ben.L.rH * 0.9; const dz = clamp((ben.L.rH * (asp < 0.8 ? 7 : 5) / 2) / (frac * tv), 1.4, 5); z = { pos: V3(hp.x + 0.15, hp.y + 0.05, hp.z + dz), look: V3(hp.x, hp.y - yc * dz * tv, hp.z) }; }
    else if (S.ztLast === 'bowl') { const bp = PROPS.bowl.o.position.clone(); bp.y += 0.2; z = { pos: V3(bp.x - 0.3, bp.y + 1.3, bp.z + 1.6), look: V3(bp.x, bp.y - yc * 0.6, bp.z) }; }
    else { const tp = V3(0, SY + 3.0, -3.9), dz = clamp(Math.max((wide ? 9 : 7.2) / 2 / th, 3.2 / 2 / (frac * tv)), 3, 11); z = { pos: V3(0, tp.y + 2.9, tp.z + dz), look: V3(0, tp.y - 0.25 - yc * dz * tv, tp.z) }; }
    return { pos: base.pos.lerp(z.pos, zw), look: base.look.lerp(z.look, zw) }; }
  // ---------- step ----------
  function step(dt) { S.t += dt;
    AU.tick(dt, S.mode === 'play' && S.phase === 'lines' && !S.over ? S.set : 'intro', S.mode === 'play' && S.phase === 'lines' && !S.over ? clamp(S.lineT / S.lineOf, 0, 1) : null, S.mode === 'play' && S.phase === 'lines' && !S.over); AU.swell(S.mode === 'play' ? (S.over ? 0.2 : clamp(S.house / 100, 0, 1) * 0.5 + (S.slip / C.slipMax) * 0.8) : 0.25);
    if (S.mode === 'play') { if (S.phase === 'intro') { S.phaseT += dt; S.curtain = Math.max(0, 1 - ss(clamp((S.phaseT - 0.6) / 1.6, 0, 1))); if (S.phaseT > C.intro / 60 + 0.6) { S.phase = 'lines'; next(); } }
      else if (!S.over) { S.lineT += dt; const L = LINES[S.i];
        if (S.demo && L && !listening() && S.lineT > S.lineOf * C.listen + S.demoT) { const want = S.demoErr ? KEYS[(KEYS.indexOf(L.mask) + 1) % 3] : L.mask; if (S.wearing !== want && !S.swap) wear(want); }
        if (L && L.act === 'stamp' && !S.stamped && S.lineT > S.lineOf * 0.56) { S.stamped = true; S.shake = 0.35; sfx.stamp(); }
        if (S.lineT >= S.lineOf) beat(); }
      else { S.overT += dt; if (S.over === 'caught' && S.overT > 0.4) { S.curtain = Math.min(1, S.curtain + dt * 0.5); } if (S.overT > (S.over === 'caught' ? 2.6 : 2.4)) pay(); } }
    { const K = HEAD.keys; let tx = HEAD.sx, ty = HEAD.sy; if (K.has('KeyA') || K.has('ArrowLeft')) tx = -1; if (K.has('KeyD') || K.has('ArrowRight')) tx = 1; if (K.has('KeyW') || K.has('ArrowUp')) ty = 1; if (K.has('KeyS') || K.has('ArrowDown')) ty = -1;
      if (S.demo) { const Ld = LINES[S.i]; tx = Math.sin(S.t * 0.7) * 0.3; ty = Ld && !listening() && Ld.act === 'terasu' ? 1 : Ld && !listening() && Ld.act === 'kumorasu' ? -1 : Math.sin(S.t * 0.5) * 0.15; }
      HEAD.x = damp(HEAD.x, clamp(tx, -1, 1), 7, dt); HEAD.y = damp(HEAD.y, clamp(ty, -1, 1), 7, dt);
      { const lf = LIFE[S.wearing] || LIFE.old, on = S.mode === 'play' && S.phase === 'lines' && !S.over && S.swap <= 0 ? 1 : S.mode === 'intro' ? 0.6 : 0.3; HEAD.life = damp(HEAD.life, on, 3, dt); const t2 = S.t * lf.sp, L2 = LINES[S.i], u2 = S.lineOf ? clamp(S.lineT / S.lineOf, 0, 1) : 0;
        // a slow look about + a quicker tilt left and right; the fox drifts off the beat, the farmer nods along, the wife barely moves; and every mask leans toward the drum near the end of a line
        const sway = Math.sin(t2 * 1.1) * 0.6 + Math.sin(t2 * 2.3 + 1.3) * 0.4, look = Math.sin(t2 * 0.47 + 0.6), toDrum = L2 && u2 > 0.82 ? Math.sin((u2 - 0.82) / 0.18 * Math.PI) : 0;
        const tgtRoll = (sway * lf.amp + HEAD.x * -0.22 + (S.wearing === 'fox' ? Math.sin(S.t * 0.53) * 0.08 : 0)) * HEAD.life, tgtYaw = (look * lf.amp * 0.9) * HEAD.life, tgtNod = (Math.sin(t2 * 1.7) * lf.nod + toDrum * 0.12) * HEAD.life, tgtSw = (Math.sin(t2 * 0.8) * lf.sway) * HEAD.life;
        HEAD.roll = damp(HEAD.roll, tgtRoll, 5, dt); HEAD.lifeYaw = damp(HEAD.lifeYaw || 0, tgtYaw, 4, dt); HEAD.lifeNod = damp(HEAD.lifeNod || 0, tgtNod, 4, dt); HEAD.lifeSway = damp(HEAD.lifeSway || 0, tgtSw, 3, dt);
        for (const k of KEYS) { const mg = ben.U.J.masks[k]; mg.rotation.z = HEAD.roll; mg.rotation.y = HEAD.roll * -0.25; } }
      const lit = clamp(1 + HEAD.y * 0.28, 0.62, 1.3); for (const k of KEYS) ben.U.J.masks[k].traverse(m => { if (m.isMesh && m.material && m.material.map && m.material.isMeshToonMaterial) m.material.color.setScalar(lit); }); }
    let face = S.wearing, inHand = null; if (S.swap > 0) { S.swap -= dt; const v = 1 - Math.max(0, S.swap) / S.swapOf; if (v >= 0.5 && S.into) { S.from = S.wearing; S.wearing = S.into; S.into = null; } if (v < 0.3) face = S.into ? S.wearing : S.from; else if (v < 0.5) { face = null; inHand = S.into ? S.wearing : S.from; } else if (v < 0.72) { face = null; inHand = S.wearing; } else face = S.wearing; if (S.swap <= 0) { S.swap = 0; face = S.wearing; } }
    if (face !== S.faceShown) { S.faceShown = face; HK.setMask(ben.g, face); if (face) HEAD.roll += (Math.random() < 0.5 ? -1 : 1) * 0.22; } for (const k of KEYS) { handMasks[k].visible = inHand === k; rackMasks[k].visible = k !== S.wearing; }
    if (S.mark) { S.mark.t -= dt; if (S.mark.t <= 0) S.mark = null; } if (S.sceneT > 0) S.sceneT -= dt; if (S.drumHit > 0) S.drumHit -= dt;
    S.setT = Math.min(1, (S.setT || 0) + dt / 0.5); if (S.xf > 0) S.xf = Math.max(0, S.xf - dt / 0.45); S.propT = (S.propT || 0) + dt; SP.acc += dt; if (SP.acc > (touch ? 1 / 24 : 1 / 40)) { SP.acc = 0; drawShadow(); }
    { const p = PROPS.bowl, inDoor = S.mode === 'play' && S.phase === 'lines' && S.set === 'door', lit = inDoor && S.i === 11; p.o.visible = inDoor || (S.mode === 'done' && S.done && S.done.over === 'caught') || (S.over === 'caught'); p.refl.material.opacity = damp(p.refl.material.opacity, lit || S.over === 'caught' ? 0.85 : 0, 3, dt); p.glow.material.opacity = damp(p.glow.material.opacity, lit || S.over === 'caught' ? 0.5 + Math.sin(S.t * 6) * 0.15 : 0, 4, dt); }
    drawBenShadow(S.mode === 'play' && S.phase === 'lines' ? Math.max(1, Math.min(4, 1 + Math.floor((S.slip / C.slipMax) * 4))) : 1); benShadow.visible = S.mode !== 'intro';
    // ZOOMS: the shadow play on scene starts + the fox's own lines (while you listen), the bowl on "the water is honest", the mask after a right fox line, the bow at the end
    { let zt = null; const Lz = LINES[S.i]; if (S.mode === 'play' && S.phase === 'lines' && !S.over && Lz) { if (S.i === 11) zt = 'bowl'; else if (listening() && (Lz.scene || Lz.mask === 'fox')) zt = 'screen'; if (S.foxZoom > 0) zt = 'face'; } if (S.over === 'won' && S.overT > 0.4) zt = 'face'; if (S.over === 'caught') zt = 'screen'; if (S.foxZoom > 0) S.foxZoom -= dt; if (zt) S.ztLast = zt; S.zw = damp(S.zw || 0, zt ? 1 : 0, zt === 'face' ? 4 : 2.6, dt); }
    rain.forEach(r => { r.visible = S.set === 'gate' && S.mode === 'play'; if (r.visible) { r.position.y -= dt * 7; r.position.x -= dt * 1.8; if (r.position.y < SY) { r.position.y = SY + 6; r.position.x = rr(-6, 6); } } });
    curtain.forEach(c => { c.m.position.x = c.sx * (3.3 + (1 - S.curtain) * 3.6); c.m.scale.x = 0.5 + S.curtain * 0.5; });
    { const k = clamp((S.curtain - 0.6) / 0.4, 0, 1); curtainGlow.visible = k > 0.01; curtainGlow.material.opacity = 0.26 * k * (0.85 + 0.15 * Math.sin(S.t * 2)); }
    chorus.forEach(c => { c.sing = S.mode === 'play' && !S.over && S.i >= 0 && S.lineT < S.lineOf * 0.8 ? 0.25 + Math.abs(Math.sin(S.t * 11 + c.x)) * 0.35 : 0; });
    if (S.cheer > 0) { S.cheer -= dt * 0.8; placeCrowd(Math.min(1, S.cheer), S.t); if (S.cheer <= 0) placeCrowd(); }
    // mawari: a full slow turn in place
    const Lc = LINES[S.i]; ben.yaw = S.mode === 'play' && Lc && Lc.act === 'mawari' && !S.over ? ss(clamp(S.lineT / S.lineOf / 0.85, 0, 1)) * Math.PI * 2 : 0;
    for (const w of people) { const tgt = poseOf(w); w.P = lerpP(w.P, tgt, 1 - Math.exp(-(w === ben ? 10 : 8) * dt)); w.g.position.set(w.x, w.y, w.z); w.g.rotation.set(0, w.yaw, 0); HK.update(w.g, w.P, dt); }
    const sh = camShot(); if (S.snap !== false) { camera.position.copy(sh.pos); S.look.copy(sh.look); S.snap = false; } const kL = Math.min(1, dt * 2.5); camera.position.lerp(sh.pos, kL); S.look.lerp(sh.look, kL); camera.lookAt(S.look);
    if (S.shake > 0) { S.shake -= dt; camera.position.x += rr(-0.04, 0.04) * S.shake * 4; camera.position.y += rr(-0.04, 0.04) * S.shake * 4; } }
  function frame() { raf = requestAnimationFrame(frame); { const pr = renderer.getPixelRatio(); if (Math.abs(renderer.domElement.width - Math.round(CW() * pr)) > 1 || Math.abs(renderer.domElement.height - Math.round(CHh() * pr)) > 1) onRs(); } const dt = Math.min(0.05, clock.getDelta()); if (!PAUSE) step(dt); renderer.render(scene, camera); hudT -= dt; if (hudT <= 0) { hudT = 0.1; onState(hud()); } }
  function onRs() { renderer.setSize(CW(), CHh(), false); renderer.domElement.style.width = '100%'; renderer.domElement.style.height = '100%'; camera.aspect = CW() / CHh(); camera.updateProjectionMatrix(); } addEventListener('resize', onRs); const ro = new ResizeObserver(onRs); ro.observe(container);
  const KM = { Digit1: 'girl', Digit2: 'old', Digit3: 'fox', KeyJ: 'girl', KeyK: 'old', KeyL: 'fox' }, onKD = e => { if (KM[e.code]) { e.preventDefault(); if (!e.repeat && !S.demo) wear(KM[e.code]); return; } if (/^(Key[WASD]|Arrow)/.test(e.code)) { HEAD.keys.add(e.code); e.preventDefault(); } }, onKU = e => HEAD.keys.delete(e.code); addEventListener('keydown', onKD); addEventListener('keyup', onKU); addEventListener('blur', () => HEAD.keys.clear());
  function hud() { const L = LINES[S.i], lis = listening(), play = S.mode === 'play' && S.phase === 'lines' && !S.over;
    return { mode: S.mode, phase: S.phase, over: S.over, house: S.house, slip: S.slip / C.slipMax, pass: C.pass, great: C.great, line: L && play ? { n: S.i + 1, of: LINES.length, text: L.text, cue: L.cue, mask: L.mask, col: mOf(L.mask).col, u: clamp(S.lineT / S.lineOf, 0, 1), act: L.act } : null, headY: HEAD.y, headX: HEAD.x, tilts: S.tilts || 0, maskImg, listening: lis, changing: S.swap > 0, wearing: S.wearing, wearingLabel: mOf(S.wearing).label, wearingCol: mOf(S.wearing).col,
      scene: S.sceneT > 0 ? S.scene : '', mark: S.mark ? { kind: S.mark.kind, text: S.mark.text } : null, done: S.done, demo: S.demo, title: C.title, sub: C.sub, masks: MASKS.map(m => ({ key: m.key, label: m.label, col: m.col })), best: save.stat('kyoto.theatre.best', 0), playedWell: save.flag('kyotoTheatrePlayedWell'), played: save.flag('kyotoTheatrePlayed'), gold: save.data.gold,
      swap: play ? KEYS.map(k => [k === 'girl' ? 'mwife' : k === 'old' ? 'mfarmer' : 'mfox', (S.wearing === k ? '● ' : '') + (k === 'girl' ? 'WIFE' : k === 'old' ? 'FARMER' : 'FOX')]) : null }; }
  frame();
  return { start: () => start(false), demoStart: () => start(true), demoStop: toIntro, toIntro, wear, setOpts(o) { OPT = { ...OPT, ...o }; }, setSafe(o) { Object.assign(SAFE, o); },
    melee() { if (!S.demo) wear('girl'); }, range() { if (!S.demo) wear('old'); }, jump() { if (!S.demo) wear('fox'); }, meleeUp() {}, rangeUp() {}, jumpUp() {},
    setStick(x, y) { HEAD.sx = x; HEAD.sy = y; }, setPaused(v) { PAUSE = !!v; }, setHudPad() {}, talk() {}, choose() {}, closeDialog() {}, nextLine() {}, clearToast() {}, useItem() {}, closeWheel() {}, skipTime() {}, eyeLook() {}, eyeRelease() {}, togglePov() { return false; }, lookBy() {}, zoomBy() {}, getCam() { return { dist: 9, pitch: 0.2 }; }, setCam() {}, setMinimap() {}, toggleSound() { AU.setMuted(!AU._m); AU._m = !AU._m; }, cycleWeather() {},
    mapData() { return { p: [0, 0.5, 0], b: [['STAGE', 0, 0]], f: [], e: [], q: null }; }, hud, _sim(n, cb, dt = 1 / 30) { for (let i = 0; i < n; i++) { step(dt); if (cb && cb(S, i) === false) break; } renderer.render(scene, camera); onState(hud()); }, _state: () => S, C,
    destroy() { cancelAnimationFrame(raf); removeEventListener('resize', onRs); ro.disconnect(); removeEventListener('keydown', onKD); removeEventListener('keyup', onKU); renderer.dispose(); renderer.domElement.remove(); try { audio.ctx && audio.ctx.close(); } catch (e) {} } };
}
