// 8 GATES — KYOTO · SUMO HALL [kyotoSumoHall] · SUMO STREAK. Game HUD vehicle "sumo": 1 PUSH · 2 SLAP · 3 GRAB (gripping: 1 DRIVE · 2 LET GO · 3 THROW).
// Ben's spec (BUILD_PLAN "KYOTO SUMO HALL"): real-time brawl in the ring, joystick moves/circles. Win by push-out (OSHIDASHI), slap-out (TSUKIDASHI), belt carry (YORIKIRI), throw (UWATENAGE).
// One endless streak: opponents grow each win, one loss ends it. Ceremony every bout: ring entry, salt, shiko (tap to stomp), gyoji HAKKEYOI! / NOKOTTA, zabuton on an upset.
// Save: stats kyoto.sumo.streak.best / kyoto.sumo.wins / kyoto.sumo.bouts, relic kyotoSumoTrophy + flag mawashiSky at 5 wins in one streak.
import * as THREE from '../../vendor/three/three.module.js';
import { rr, clamp, damp } from '../../village-game.js';
import { canvasTex } from '../../meru-game.js';
import { save } from '../../engine/save.js';
import { createStage } from '../../engine/restaurant-kit.js';
import { humanKit, HUMAN_PRESETS, SKINS } from '../../engine/human-kit.js';

const DY = 0.6, R = 2.3, HALF = 3.4, SKY = '#7dd3fc';
export const KIMARITE = { OSHIDASHI: 'Pushed out', TSUKIDASHI: 'Slapped out', YORIKIRI: 'Carried out by the belt', UWATENAGE: 'Overarm belt throw', SHITATENAGE: 'Underarm belt throw', TSUKITAOSHI: 'Shoved down', HATAKIKOMI: 'Slapped down', ISAMIASHI: 'Stepped out' };
const NAMES = ['HAYATE', 'IWAGUMO', 'KAZEYAMA', 'TETSUUMI', 'ONIZAKURA', 'KUROSHIO', 'FUJIMARU', 'ARASHIYAMA', 'TAKIGAWA', 'SHIROGANE', 'YAMAKAZE', 'OTORIUMI', 'GINRYU', 'KUMAGATAKE', 'RAIZAN', 'KOTONAMI'];
const RANKS = ['JONOKUCHI', 'JONIDAN', 'SANDANME', 'MAKUSHITA', 'JURYO', 'MAEGASHIRA', 'KOMUSUBI', 'SEKIWAKE', 'OZEKI', 'YOKOZUNA'];
const MAW = ['#7a2a2a', '#1f2a44', '#3a7a4a', '#8a5ab0', '#e6b45a', '#201e1d', '#9a948c', '#ec3013', '#5a6a4a', '#3a5a8a'];
const SK = { best: 'kyoto.sumo.streak.best', wins: 'kyoto.sumo.wins', bouts: 'kyoto.sumo.bouts' };
const CROWD = ['#1f2a44', '#7a2a2a', '#3a5a8a', '#e6e4de', '#5a6a4a', '#8a5ab0', '#201e1d', '#c9a06a', '#d9534f', '#3a3836', '#2f7a6a'];
const rng = s => () => { s = (s * 16807) % 2147483647; return (s - 1) / 2147483646; };
const ss = t => t * t * (3 - 2 * t);
const dampA = (a, b, l, dt) => { const d = ((b - a + Math.PI) % (Math.PI * 2) + Math.PI * 2) % (Math.PI * 2) - Math.PI; return a + d * (1 - Math.exp(-l * dt)); };
function lerpP(a, b, t) { const o = {}; for (const k in b) { const va = a && a[k], vb = b[k]; if (Array.isArray(vb)) o[k] = Array.isArray(va) ? vb.map((v, i) => va[i] + (v - va[i]) * t) : vb.slice(); else if (typeof vb === 'number') o[k] = typeof va === 'number' ? va + (vb - va) * t : vb; else o[k] = vb; } return o; }

export function oppFor(n, seed = 1) { const r = rng(seed * 97 + n * 131 + 7), name = NAMES[(seed + n * 5) % NAMES.length], col = MAW[(seed + n * 3) % MAW.length];
  const cfg = { ...HUMAN_PRESETS.sumo, name, height: Math.min(2.22, 1.76 + n * 0.045), build: Math.min(2, 1.55 + n * 0.07), belly: Math.min(1, 0.6 + n * 0.06), shoulders: 1.1 + Math.min(n, 8) * 0.03, skin: SKINS[1 + Math.floor(r() * 6)], hair: n < 2 ? 'topknot' : 'oicho', hairCol: '#141210', top: col, bottom: col, mood: 'determined', apron: false, eyeShape: r() < 0.5 ? 'almond' : 'round', age: Math.min(0.6, 0.15 + n * 0.05) };
  return { cfg, name, rank: RANKS[Math.min(n, RANKS.length - 1)], mass: Math.min(1.9, 0.8 + n * 0.07 + Math.max(0, n - 5) * 0.04), sc: 1 + Math.max(0, n - 8) * 0.03 }; }
const brainFor = n => ({ drive: Math.min(1, 0.5 + 0.06 * n), react: Math.max(0.28, 0.8 - 0.05 * n), aggr: Math.min(0.85, 0.35 + 0.06 * n), throwP: Math.min(0.4, 0.04 + 0.03 * n), edge: Math.min(0.85, 0.25 + 0.07 * n), wind: Math.max(0.16, 0.34 - 0.02 * n), tdelay: Math.max(0.1, 0.5 - 0.04 * n), spd: 1.05 + Math.min(n, 10) * 0.04, mix: [0.45, 0.75] });
const BOT = { drive: 1, react: 0.32, aggr: 0.9, throwP: 0.3, edge: 0.85, wind: 0, tdelay: 0.15, spd: 1.5, mix: [0.5, 0.72] };

export async function createSumo({ container, onState = () => {}, opts = {} }) {
  const ST = createStage(container, { bg: '#140c08' }), { CW, CHh, renderer, scene, camera, V3, toon, M, audio, tone, glowTex, touch } = ST;
  const HK = humanKit({ THREE, grad: ST.grad }); let OPT = { apronInBout: false, normal: false, ...opts };
  camera.far = 90; camera.fov = 46; camera.updateProjectionMatrix(); scene.fog = new THREE.Fog(0x1a0f0a, 28, 62);
  scene.children.filter(o => o.isHemisphereLight).forEach(h => { h.color.set(0xfff0dc); h.groundColor.set(0x5a3a2a); h.intensity = 0.72; });
  const sun = ST.sun; sun.position.set(0.6, 13, 2.2); sun.intensity = 1.25;
  { const sp = new THREE.SpotLight(0xfff1dc, 2.3, 0, 0.6, 0.55, 0); sp.position.set(0, 13.5, 0); sp.target.position.set(0, DY, 0); scene.add(sp, sp.target); const rim = new THREE.DirectionalLight(0x9ab8ff, 0.6); rim.position.set(-4, 6, -9); scene.add(rim); } Object.assign(sun.shadow.camera, { left: -5, right: 5, top: 5, bottom: -5 }); sun.shadow.camera.updateProjectionMatrix();
  const flat = (w, d, col, y, x = 0, z = 0, map) => { const m = new THREE.Mesh(new THREE.PlaneGeometry(w, d), map ? new THREE.MeshToonMaterial({ map, gradientMap: ST.grad }) : toon(col)); m.rotation.x = -Math.PI / 2; m.position.set(x, y, z); m.receiveShadow = true; scene.add(m); return m; };
  // ---------- hall ----------
  { const fT = canvasTex(256, 256, c => { for (let i = 0; i < 8; i++) { c.fillStyle = ['#3a2416', '#341f12', '#40291a', '#2e1b10'][i % 4]; c.fillRect(0, i * 32, 256, 32); c.fillStyle = 'rgba(0,0,0,0.35)'; c.fillRect(0, i * 32, 256, 2); } }); fT.wrapS = fT.wrapT = THREE.RepeatWrapping; fT.repeat.set(10, 10); flat(48, 48, '#3a2416', 0, 0, 0, fT);
    const masT = canvasTex(128, 128, c => { c.fillStyle = '#6a2a24'; c.fillRect(0, 0, 128, 128); c.strokeStyle = '#2a140e'; c.lineWidth = 6; c.strokeRect(3, 3, 122, 122); }); masT.wrapS = masT.wrapT = THREE.RepeatWrapping; masT.repeat.set(14, 14); const mas = flat(21, 21, '#6a2a24', 0.01, 0, 0, masT); mas.renderOrder = 1;
    flat(11.2, 11.2, '#2a1a12', 0.02);
    const wallM = toon('#24150e'); for (let s = 0; s < 4; s++) { const w = new THREE.Mesh(new THREE.PlaneGeometry(46, 16), wallM); const a = s * Math.PI / 2; w.position.set(Math.sin(a) * 22, 8, Math.cos(a) * 22); w.rotation.y = a + Math.PI; scene.add(w); }
    const ceil = new THREE.Mesh(new THREE.PlaneGeometry(46, 46), toon('#120a06')); ceil.rotation.x = Math.PI / 2; ceil.position.y = 15; scene.add(ceil);
    const seatT = canvasTex(128, 64, c => { c.fillStyle = '#3a1a12'; c.fillRect(0, 0, 128, 64); c.fillStyle = '#7a2420'; for (let i = 0; i < 4; i++) c.fillRect(i * 32 + 3, 4, 26, 30); c.fillStyle = '#9a3a2c'; for (let i = 0; i < 4; i++) c.fillRect(i * 32 + 3, 4, 26, 4); c.fillStyle = '#c9a06a'; c.fillRect(0, 56, 128, 8); }); seatT.wrapS = THREE.RepeatWrapping;
    for (let r = 0; r < 7; r++) { const D = 11.5 + r, h = 0.7 + r * 0.6, L = 2 * D + 1, t = seatT.clone(); t.needsUpdate = true; t.repeat.set(L / 1.3, 1); const fm = new THREE.MeshToonMaterial({ map: t, gradientMap: ST.grad }), tm = toon(r % 2 ? '#4a2a1a' : '#3e2216'); for (let s = 0; s < 4; s++) { const a = s * Math.PI / 2, b = new THREE.Mesh(new THREE.BoxGeometry(L, h, 1), [tm, tm, tm, tm, fm, tm]); b.position.set(Math.sin(a) * D, h / 2, Math.cos(a) * D); b.rotation.y = a + Math.PI; scene.add(b); } }
    const khT = canvasTex(128, 32, c => { for (let i = 0; i < 4; i++) { c.fillStyle = i % 2 ? '#f3f2f2' : '#c0392b'; c.fillRect(i * 32, 0, 32, 32); } }); khT.wrapS = THREE.RepeatWrapping; khT.repeat.set(30, 1);
    for (let s = 0; s < 4; s++) { const a = s * Math.PI / 2, kh = new THREE.Mesh(new THREE.PlaneGeometry(40, 0.9), new THREE.MeshToonMaterial({ map: khT, gradientMap: ST.grad })); kh.position.set(Math.sin(a) * 18.6, 5.15, Math.cos(a) * 18.6); kh.rotation.y = a + Math.PI; scene.add(kh); M(new THREE.BoxGeometry(40, 0.18, 0.3), toon('#2a1a12'), Math.sin(a) * 18.55, 5.65, Math.cos(a) * 18.55, scene, 0).rotation.y = a;
      for (let i = -2; i <= 2; i++) { const p = M(new THREE.BoxGeometry(0.6, 15, 0.6), toon('#2e1c12'), Math.sin(a) * 21.4 + Math.cos(a) * i * 9, 7.5, Math.cos(a) * 21.4 - Math.sin(a) * i * 9, scene, 0); p.castShadow = p.receiveShadow = false; } }
    { const bars = [], sp = 1.25; for (let x = -10.6; x <= 10.6; x += sp) for (let z = -10.6; z <= 10.6; z += sp) { const m = Math.max(Math.abs(x), Math.abs(z)); if (m < 5.5 || m > 10.7) continue; bars.push([x, z, 0], [x, z, 1]); }
      const bm = new THREE.InstancedMesh(new THREE.BoxGeometry(sp, 0.14, 0.07), toon('#5a3420'), bars.length), o = new THREE.Object3D(); bars.forEach(([x, z, r], i) => { o.position.set(x + (r ? 0 : sp / 2), 0.07, z + (r ? sp / 2 : 0)); o.rotation.set(0, r ? Math.PI / 2 : 0, 0); o.updateMatrix(); bm.setMatrixAt(i, o.matrix); }); scene.add(bm); }
    { const rig = new THREE.Group(); rig.position.y = 13.6; scene.add(rig); const bmm = toon('#1a1210'); for (const [x, z, w, d] of [[0, 4.2, 9, 0.3], [0, -4.2, 9, 0.3], [4.2, 0, 0.3, 9], [-4.2, 0, 0.3, 9], [0, 0, 9, 0.2], [0, 0, 0.2, 9]]) { const b = new THREE.Mesh(new THREE.BoxGeometry(w, 0.3, d), bmm); b.position.set(x, 0, z); rig.add(b); }
      const lm = new THREE.MeshBasicMaterial({ color: 0xfff4dc }); for (let i = 0; i < 4; i++) for (let j = 0; j < 4; j++) { const x = -3.15 + i * 2.1, z = -3.15 + j * 2.1, l = new THREE.Mesh(new THREE.BoxGeometry(0.7, 0.12, 0.7), lm); l.position.set(x, -0.2, z); rig.add(l); const g = new THREE.Sprite(new THREE.SpriteMaterial({ map: glowTex, color: 0xffe2b0, transparent: true, depthWrite: false, blending: THREE.AdditiveBlending, opacity: 0.55 })); g.position.set(x, -0.35, z); g.scale.setScalar(2.2); rig.add(g); } }
    { const shT = canvasTex(4, 256, c => { const g = c.createLinearGradient(0, 0, 0, 256); g.addColorStop(0, 'rgba(255,255,255,0)'); g.addColorStop(0.55, 'rgba(255,255,255,0.55)'); g.addColorStop(1, 'rgba(255,255,255,1)'); c.fillStyle = g; c.fillRect(0, 0, 4, 256); });
      const cone = new THREE.Mesh(new THREE.ConeGeometry(4.9, 13, 40, 1, true), new THREE.MeshBasicMaterial({ color: 0xffe6c0, alphaMap: shT, transparent: true, opacity: 0.075, blending: THREE.AdditiveBlending, depthWrite: false, side: THREE.DoubleSide, fog: false })); cone.position.y = 13.5 - 6.5; cone.renderOrder = 5; scene.add(cone); } }
  const motes = []; for (let i = 0; i < (touch ? 18 : 40); i++) { const m = new THREE.Sprite(new THREE.SpriteMaterial({ map: glowTex, color: 0xffe8c8, transparent: true, depthWrite: false, blending: THREE.AdditiveBlending, opacity: 0 })); const a = Math.random() * 7, r = Math.random() * 3.6; m.position.set(Math.cos(a) * r, DY + 0.5 + Math.random() * 7, Math.sin(a) * r); m.scale.setScalar(0.05 + Math.random() * 0.05); m.userData.ph = Math.random() * 7; scene.add(m); motes.push(m); }
  // crowd (instanced, phone budget) — masu boxes on the floor + 7 stand rows, aisles (hanamichi) on east + west
  const seats = []; { const keep = touch ? 0.36 : 0.62, row = (D, y, sit) => { for (let s = 0; s < 4; s++) { const nn = Math.floor(2 * D / 0.74); for (let i = 0; i < nn; i++) { const u = -D + (i + 0.5) * (2 * D / nn); let x, z; if (s === 0) { x = u; z = D; } else if (s === 1) { x = D; z = -u; } else if (s === 2) { x = -u; z = -D; } else { x = -D; z = u; } if ((s === 1 || s === 3) && Math.abs(z) < 1.2) continue; if (Math.random() > keep) continue; seats.push({ x: x + rr(-0.08, 0.08), y, z: z + rr(-0.08, 0.08), a: Math.atan2(-x, -z), sit, ph: Math.random() * 6 }); } } };
    for (let r = 0; r < 4; r++) row(6.1 + r * 1.1, 0, true); for (let r = 0; r < 7; r++) row(11.5 + r, 0.7 + r * 0.6, false); }
  const crB = new THREE.InstancedMesh(new THREE.CapsuleGeometry(0.19, 0.24, 3, 8).scale(1.15, 1, 0.8), new THREE.MeshToonMaterial({ gradientMap: ST.grad }), seats.length), crH = new THREE.InstancedMesh(new THREE.SphereGeometry(0.13, 10, 7), new THREE.MeshToonMaterial({ gradientMap: ST.grad }), seats.length), crHair = new THREE.InstancedMesh(new THREE.SphereGeometry(0.138, 10, 5, 0, Math.PI * 2, 0, Math.PI * 0.55), new THREE.MeshToonMaterial({ gradientMap: ST.grad, color: 0x1a1210 }), seats.length), dm = new THREE.Object3D(), cc = new THREE.Color();
  seats.forEach((p, i) => { crB.setColorAt(i, cc.set(CROWD[i % CROWD.length])); crH.setColorAt(i, cc.set(SKINS[i % 6 + 1])); });
  const crCush = new THREE.InstancedMesh(new THREE.BoxGeometry(0.46, 0.07, 0.46), new THREE.MeshToonMaterial({ gradientMap: ST.grad }), seats.length); seats.forEach((p, i) => { p.s = 0.9 + ((p.ph * 977) % 1) * 0.18; crCush.setColorAt(i, cc.set(['#5a2a6a', '#7a2a2a', '#3a2a5a'][i % 3])); dm.position.set(p.x, p.sit ? 0.045 : -5, p.z); dm.rotation.set(0, p.a, 0); dm.updateMatrix(); crCush.setMatrixAt(i, dm.matrix); }); scene.add(crCush);
  const placeCrowd = (jump = 0, t = 0) => { seats.forEach((p, i) => { const j = jump ? Math.max(0, Math.sin(t * 13 + p.ph)) * jump * 0.28 : 0, by = p.y + (p.sit ? 0.32 : 0.42) * p.s + j; dm.position.set(p.x, by, p.z); dm.rotation.set(jump ? Math.sin(t * 9 + p.ph) * 0.12 * jump : 0.06, p.a, 0); dm.scale.set(p.s, (p.sit ? 0.82 : 1) * p.s, p.s); dm.updateMatrix(); crB.setMatrixAt(i, dm.matrix); dm.scale.setScalar(p.s); dm.rotation.set(0, p.a, 0); dm.position.y = by + (p.sit ? 0.3 : 0.36) * p.s; dm.updateMatrix(); crH.setMatrixAt(i, dm.matrix); dm.position.y += 0.02; dm.updateMatrix(); crHair.setMatrixAt(i, dm.matrix); }); crB.instanceMatrix.needsUpdate = crH.instanceMatrix.needsUpdate = crHair.instanceMatrix.needsUpdate = true; };
  placeCrowd(); scene.add(crB, crH, crHair);
  // nobori banners + lanterns
  { const phr = ['満員御礼', '八門場所', '京都場所', '大相撲', '千秋楽', '八門'], cols = [['#f3f2f2', '#201e1d'], ['#1f2a44', '#f3f2f2'], ['#ec3013', '#f3f2f2'], ['#e6b45a', '#201e1d'], ['#3a7a4a', '#f3f2f2'], ['#8a5ab0', '#f3f2f2']];
    for (let i = 0; i < 16; i++) { const s = i % 4, u = (Math.floor(i / 4) - 1.5) * 8, D = 19.2, a = s * Math.PI / 2, [bg, fg] = cols[i % cols.length], txt = phr[(i * 5) % phr.length];
      const t = canvasTex(128, 512, c => { c.fillStyle = bg; c.fillRect(0, 0, 128, 512); c.fillStyle = fg; c.fillRect(0, 0, 128, 18); c.fillRect(0, 494, 128, 18); c.font = '900 84px "Hiragino Mincho ProN","Yu Mincho","MS Mincho",serif'; c.textAlign = 'center'; c.textBaseline = 'middle'; const ch = [...txt], step = Math.min(110, 440 / ch.length); ch.forEach((k, j) => c.fillText(k, 64, 256 - (ch.length - 1) * step / 2 + j * step)); });
      const b = new THREE.Mesh(new THREE.PlaneGeometry(1.1, 4.4), new THREE.MeshToonMaterial({ map: t, gradientMap: ST.grad, side: THREE.DoubleSide })); b.position.set(Math.sin(a) * D + Math.cos(a) * u, 7.6, Math.cos(a) * D - Math.sin(a) * u); b.rotation.y = a + Math.PI; scene.add(b); }
    for (let i = 0; i < 12; i++) { const a = i / 12 * Math.PI * 2 + 0.26, x = Math.cos(a) * 11, z = Math.sin(a) * 11; M(new THREE.CylinderGeometry(0.22, 0.22, 0.55, 10), toon(i % 2 ? '#f3e6c8' : '#c0392b', { emissive: i % 2 ? 0x8a6a3a : 0x6a1a10 }), x, 3.9, z, scene, 0.012); const s = new THREE.Sprite(new THREE.SpriteMaterial({ map: glowTex, color: 0xffb060, transparent: true, depthWrite: false, blending: THREE.AdditiveBlending, opacity: 0.7 })); s.position.set(x, 3.9, z); s.scale.setScalar(1.4); scene.add(s); }
    for (const [x, z] of touch ? [[0, 7]] : [[6, 6], [-6, -6]]) { const pl = new THREE.PointLight(0xffa860, 1.1, 18); pl.position.set(x, 6, z); scene.add(pl); } }
  // ---------- the dohyo ----------
  { const sideT = canvasTex(256, 64, c => { c.fillStyle = '#b07e52'; c.fillRect(0, 0, 256, 64); for (let i = 0; i < 6; i++) { c.fillStyle = i % 2 ? 'rgba(90,50,24,0.22)' : 'rgba(230,190,140,0.18)'; c.fillRect(0, i * 10 + Math.random() * 4, 256, 3 + Math.random() * 4); } for (let i = 0; i < 500; i++) { c.fillStyle = 'rgba(70,40,20,0.25)'; c.fillRect(Math.random() * 256, Math.random() * 64, 2, 2); } c.fillStyle = '#7a4e2e'; c.fillRect(0, 56, 256, 8); }); sideT.wrapS = THREE.RepeatWrapping; sideT.repeat.set(4, 1);
    const plat = new THREE.Mesh(new THREE.CylinderGeometry(HALF * Math.SQRT2, (HALF + 0.55) * Math.SQRT2, DY, 4, 1), new THREE.MeshToonMaterial({ map: sideT, gradientMap: ST.grad })); plat.rotation.y = Math.PI / 4; plat.position.y = DY / 2; plat.receiveShadow = true; scene.add(plat);
    const s = 512 / (HALF * 2), topT = canvasTex(512, 512, c => { c.fillStyle = '#c9a06c'; c.fillRect(0, 0, 512, 512); c.fillStyle = '#d6b07c'; c.beginPath(); c.arc(256, 256, (R + 0.35) * s, 0, 7); c.fill(); c.fillStyle = '#cfa572'; c.beginPath(); c.arc(256, 256, (R - 0.05) * s, 0, 7); c.fill();
      for (let i = 0; i < 1400; i++) { c.fillStyle = i % 2 ? 'rgba(120,80,40,0.18)' : 'rgba(255,240,210,0.16)'; c.fillRect(Math.random() * 512, Math.random() * 512, 2, 2); } c.strokeStyle = 'rgba(255,240,210,0.16)'; c.lineWidth = 2; for (let i = 0; i < 26; i++) { c.beginPath(); c.arc(256, 256, (R + 0.13 + i * 0.012) * s, 0, 7); c.stroke(); } c.fillStyle = 'rgba(0,0,0,0.08)'; c.beginPath(); c.arc(256, 256, (R - 0.05) * s, 0, 7); c.arc(256, 256, (R - 0.4) * s, 0, 7, true); c.fill(); c.fillStyle = '#f3f2f2'; for (const sx of [-1, 1]) c.fillRect(256 + sx * 0.7 * s - 0.035 * s, 256 - 0.45 * s, 0.07 * s, 0.9 * s); });
    flat(HALF * 2, HALF * 2, '#c9a06c', DY + 0.004, 0, 0, topT);
    const strawT = (w, h, along) => canvasTex(w, h, c => { c.fillStyle = '#d6bc76'; c.fillRect(0, 0, w, h); for (let i = 0; i < 260; i++) { c.fillStyle = i % 3 ? 'rgba(140,110,50,0.35)' : 'rgba(255,245,200,0.4)'; if (along) c.fillRect(Math.random() * w, Math.random() * h, 1 + Math.random() * 1.5, 18 + Math.random() * 40); else c.fillRect(Math.random() * w, Math.random() * h, 18 + Math.random() * 40, 1 + Math.random() * 1.5); } c.fillStyle = '#7a5a2a'; for (let k = 0; k < 8; k++) { if (along) c.fillRect(0, k * h / 8, w, 5); else c.fillRect(k * w / 8, 0, 5, h); } });
    const tT = strawT(512, 64, false); tT.wrapS = tT.wrapT = THREE.RepeatWrapping; tT.repeat.set(3, 1); const straw = new THREE.MeshToonMaterial({ map: tT, gradientMap: ST.grad }), ring = M(new THREE.TorusGeometry(R, 0.11, 8, 96), straw, 0, DY + 0.03, 0, scene, 0.012, 0.11); ring.rotation.x = Math.PI / 2;
    const cT = strawT(64, 512, true); cT.wrapS = cT.wrapT = THREE.RepeatWrapping; cT.repeat.set(1, 1.3); const straw2 = new THREE.MeshToonMaterial({ map: cT, gradientMap: ST.grad });
    for (let i = 0; i < 4; i++) { const a = i * Math.PI / 2, c2 = M(new THREE.CylinderGeometry(0.09, 0.09, 2 * HALF - 0.5, 10), straw2, Math.sin(a) * (HALF - 0.25), DY + 0.04, Math.cos(a) * (HALF - 0.25), scene, 0.01, 0.09); c2.rotation.set(i % 2 ? Math.PI / 2 : 0, 0, i % 2 ? 0 : Math.PI / 2); }
    for (const sx of [-1, 1]) { M(new THREE.BoxGeometry(0.6, 0.3, 1.0), toon('#a8784e'), sx * (HALF + 0.75), 0.15, 0, scene, 0.012); M(new THREE.BoxGeometry(0.42, 0.34, 0.42), toon('#8a5a32'), sx * (HALF - 0.5), DY + 0.17, sx * (HALF - 0.5), scene, 0.01); flat(0.36, 0.36, '#f6f4ee', DY + 0.345, sx * (HALF - 0.5), sx * (HALF - 0.5)); M(new THREE.CylinderGeometry(0.2, 0.18, 0.42, 12), toon('#7a4a2a'), sx * (HALF - 0.5), DY + 0.21, -sx * (HALF - 0.5), scene, 0.01, 0.2); } }
  // tsuriyane: the hanging shrine roof, purple curtain + 4 tassels
  { const rf = new THREE.Group(); rf.position.y = DY + 5.8; scene.add(rf);
    const curT = canvasTex(512, 64, c => { c.fillStyle = '#4a1f5c'; c.fillRect(0, 0, 512, 64); c.fillStyle = '#e6b45a'; for (let i = 0; i < 4; i++) { c.beginPath(); c.arc(64 + i * 128, 30, 17, 0, 7); c.fill(); } c.fillStyle = '#2a1034'; c.fillRect(0, 56, 512, 8); }), cm = new THREE.MeshToonMaterial({ map: curT, gradientMap: ST.grad }), pm = toon('#3a1748');
    const cur = new THREE.Mesh(new THREE.BoxGeometry(7.2, 0.7, 7.2), [cm, cm, pm, pm, cm, cm]); rf.add(cur);
    M(new THREE.BoxGeometry(7.8, 0.28, 7.8), toon('#2a1a12'), 0, 0.5, 0, rf, 0.02);
    const sh = new THREE.Shape(); sh.moveTo(-4.3, 0); sh.lineTo(4.3, 0); sh.lineTo(0, 2.0); sh.closePath(); const rg = new THREE.ExtrudeGeometry(sh, { depth: 7.4, bevelEnabled: false }); rg.translate(0, 0, -3.7); M(rg, toon('#3a3330'), 0, 0.64, 0, rf, 0.03);
    const gold = toon('#d9b45a'); M(new THREE.BoxGeometry(0.3, 0.22, 7.6), gold, 0, 2.66, 0, rf, 0.012); for (let i = 0; i < 5; i++) M(new THREE.CylinderGeometry(0.11, 0.11, 0.9, 10), toon('#3a3330'), 0, 2.86, -2.8 + i * 1.4, rf, 0.01, 0.11).rotation.z = Math.PI / 2;
    for (const z of [-3.75, 3.75]) for (const s of [-1, 1]) { const ch = M(new THREE.BoxGeometry(0.14, 1.4, 0.1), toon('#3a3330'), s * 0.28, 2.9, z, rf, 0.01); ch.rotation.z = s * 0.55; }
    const TAS = [[3.5, -3.5, '#2f7a6a'], [3.5, 3.5, '#c0392b'], [-3.5, 3.5, '#f3f2f2'], [-3.5, -3.5, '#201e1d']]; for (const [x, z, c] of TAS) { M(new THREE.SphereGeometry(0.16, 10, 8), toon(c), x, -0.55, z, rf, 0.01, 0.16); M(new THREE.CylinderGeometry(0.07, 0.24, 1.15, 10), toon(c), x, -1.2, z, rf, 0.012, 0.2); }
    for (const [x, z] of [[2.6, 2.6], [-2.6, 2.6], [2.6, -2.6], [-2.6, -2.6]]) M(new THREE.CylinderGeometry(0.02, 0.02, 7, 4), toon('#2a1a12'), x, 4.2, z, rf, 0); }
  // ---------- people ----------
  const people = [];
  function mkW(cfg, sc = 1) { const g = HK.make(cfg); g.rotation.order = 'YXZ'; g.scale.setScalar(sc); const U = g.userData.H, R0 = HK.restPose(g); HK.update(g, R0, 0.016); g.updateMatrixWorld(true); const bb = new THREE.Box3().setFromObject(g), front = Math.max(0.2, bb.max.z / sc);
    scene.add(g); g.traverse(m => { if (m.isMesh) { m.castShadow = !touch; } }); const w = { g, cfg, U, L: U.L, k: U.L.H / 1.75, R0, P: R0, front, rad: front * sc * 0.92, sc, x: 0, y: DY, z: 0, vy: 0, vx: 0, vz: 0, kx: 0, kz: 0, mx: 0, mz: 0, yaw: 0, pitch: 0, roll: 0, mass: 1, spd: 1.5, bal: 100, st: 100, act: null, stun: 0, stumble: 0, boost: 0, charge: 0, tq: 1, fall: null, mood: null, think: 0, pivot: 0, anim: 'stand', ph: 0, at: 0, sk: null, stomps: 0, lastHit: null, out: false };
    if (touch) { const b = new THREE.Mesh(new THREE.PlaneGeometry(1.3 * sc * w.k, 1.3 * sc * w.k), new THREE.MeshBasicMaterial({ map: blobT, transparent: true, depthWrite: false })); b.rotation.x = -Math.PI / 2; b.renderOrder = 2; scene.add(b); w.blob = b; } people.push(w); return w; }
  const blobT = canvasTex(64, 64, c => { const g = c.createRadialGradient(32, 32, 2, 32, 32, 32); g.addColorStop(0, 'rgba(0,0,0,0.55)'); g.addColorStop(1, 'rgba(0,0,0,0)'); c.fillStyle = g; c.fillRect(0, 0, 64, 64); });
  function dropW(w) { if (!w) return; if (w.blob) scene.remove(w.blob); scene.remove(w.g); w.g.traverse(m => { if (m.isMesh && m.geometry) m.geometry.dispose(); }); const i = people.indexOf(w); if (i >= 0) people.splice(i, 1); }
  const benCfg = () => ({ ...HUMAN_PRESETS.bensumo, ...(save.flag('mawashiSky') ? { top: SKY, bottom: SKY } : {}) });
  let ben = mkW(benCfg()), benSky = save.flag('mawashiSky'), opp = null; ben.mass = 1; ben.spd = 1.5;
  const gyoji = mkW({ name: 'GYOJI', height: 1.66, build: 0.9, outfit: 'kimono', top: '#5a2a7a', bottom: '#3a1a4a', accent: '#e6b45a', hair: 'short', hairCol: '#141210', mood: 'neutral', skin: SKINS[2], age: 0.5 });
  { const J = gyoji.U.J, L = gyoji.L; const hat = M(new THREE.CylinderGeometry(0.07, 0.12, 0.26, 10), toon('#141210'), 0, L.rH * 2.05, -L.rH * 0.1, J.head, 0.01, 0.1); hat.rotation.x = -0.2;
    const fan = new THREE.Group(); J.handR.add(fan); M(new THREE.CylinderGeometry(0.018, 0.018, 0.2, 6), toon('#2a1a12'), 0, -0.1, 0, fan, 0.006, 0.02); const pad = M(new THREE.CylinderGeometry(0.16, 0.16, 0.025, 20), toon('#1a1a1a'), 0, -0.34, 0, fan, 0.008, 0.16); pad.rotation.x = Math.PI / 2; pad.scale.set(1, 1, 1.25); M(new THREE.CylinderGeometry(0.11, 0.11, 0.03, 20), toon('#e6b45a'), 0, -0.34, 0.004, fan, 0, 0.11).rotation.x = Math.PI / 2; }
  const judges = [[0, -(HALF + 1.4)], [HALF + 1.4, 1.8]].map(([x, z]) => { const j = mkW({ name: 'JUDGE', height: 1.72, build: 1.1, outfit: 'kimono', top: '#201e1d', bottom: '#201e1d', accent: '#9a948c', hair: 'short', hairCol: '#2a2420', mood: 'neutral', skin: SKINS[3], age: 0.7 }); j.x = x; j.z = z; j.y = 0; j.yaw = Math.atan2(-x, -z); j.anim = 'kneel'; return j; });
  // ---------- effects ----------
  const salt = []; for (let i = 0; i < 40; i++) { const s = new THREE.Sprite(new THREE.SpriteMaterial({ map: glowTex, color: 0xffffff, transparent: true, depthWrite: false, opacity: 0 })); s.scale.setScalar(0.09); scene.add(s); salt.push({ s, v: V3(), life: 0 }); } let saltI = 0;
  const throwSalt = w => { const p = w.U.J.handR.getWorldPosition(V3()), dir = V3(-w.x, 0, -w.z).normalize(); for (let i = 0; i < 18; i++) { const q = salt[saltI = (saltI + 1) % salt.length]; q.s.position.copy(p); q.v.set(dir.x * rr(1.4, 2.6) + rr(-0.5, 0.5), rr(1.8, 3), dir.z * rr(1.4, 2.6) + rr(-0.5, 0.5)); q.life = 1.4; } audio.burst && audio.burst(0.25, 5000, 0.12); };
  const dust = (x, z, n = 6) => { for (let i = 0; i < n; i++) ST.puff(x + rr(-0.2, 0.2), DY + 0.05, z + rr(-0.2, 0.2), 0xc9a06c, 1); };
  const zab = []; { const cols = ['#6a2a5a', '#8a2a2a', '#c9a06a', '#3a5a8a']; for (let i = 0; i < (touch ? 16 : 28); i++) { const m = M(new THREE.BoxGeometry(0.5, 0.07, 0.55), toon(cols[i % 4]), 0, -5, 0, scene, 0.008); m.visible = false; zab.push({ m, t: 0, p0: V3(), p1: V3(), spin: V3() }); } }
  const throwZabuton = () => { zab.forEach((z, i) => { const p = seats[Math.floor(Math.random() * seats.length)]; z.p0.set(p.x, p.y + 1, p.z); const a = Math.random() * 7, r = rr(1, HALF + 2); z.p1.set(Math.cos(a) * r, r < HALF ? DY + 0.04 : 0.04, Math.sin(a) * r); z.t = -i * 0.06 - Math.random() * 0.3; z.spin.set(rr(-8, 8), rr(-8, 8), rr(-8, 8)); z.m.visible = true; }); };
  // ---------- state ----------
  const S = { mode: 'intro', ph: 'idle', t: 0, phT: 0, streak: 0, n: 0, seed: 1 + Math.floor(Math.random() * 999), first: true, lock: null, tachi: null, flash: null, call: '', callT: 0, nokT: 0, done: null, res: null, cheer: 0, shake: 0, bot: false, demo: false, prompt: '', camDir: V3(0, 0, 1), look: V3(0, DY + 1, 0), snap: true, oppInfo: null, P: brainFor(0), contactT: -9, edgeT: 0 };
  const SAFE = { top: 0, bottom: 0 }; let PAUSE = false, raf = 0, hudT = 0; const clock = new THREE.Clock(), stick = { x: 0, y: 0 }, keys = new Set();
  const flash = (txt, col = '#ffd23a', d = 1.2) => { S.flash = { txt, col, t: S.t + d }; };
  const call = (txt, d = 1.4) => { S.call = txt; S.callT = S.t + d; tone(540, 0.22, 0.1, 'triangle', 1.3); };
  const cheer = (v = 1) => { S.cheer = Math.max(S.cheer, v); audio.burst && audio.burst(0.9 * v, 1600, 0.22 * v); };
  const thud = (v = 1) => { tone(85, 0.2, 0.35 * v, 'sine', 0.6); audio.burst && audio.burst(0.08, 900, 0.25 * v); };
  const other = w => w === ben ? opp : ben;
  const groundY = (x, z) => { const m = Math.max(Math.abs(x), Math.abs(z)); return m <= HALF ? DY : m >= HALF + 0.55 ? 0 : DY * (1 - (m - HALF) / 0.55); };
  const sideOf = w => w === ben ? -1 : 1;
  function resetW(w) { Object.assign(w, { vx: 0, vz: 0, kx: 0, kz: 0, mx: 0, mz: 0, vy: 0, pitch: 0, roll: 0, bal: 100, st: 100, act: null, stun: 0, stumble: 0, boost: 0, charge: 0, tq: 1, fall: null, mood: null, sk: null, stomps: 0, lastHit: null, out: false, path: null }); }
  function setOpp(n) { dropW(opp); const o = oppFor(OPT.normal ? n + 2 : n, S.seed); opp = mkW(o.cfg, o.sc); opp.mass = o.mass; opp.info = o; S.P = brainFor(OPT.normal ? n + 2 : n); opp.spd = S.P.spd; S.oppInfo = o; }
  function newBout() { S.mode = 'bout'; S.lock = null; S.tachi = null; S.res = null; S.done = null; S.flash = null; S.call = ''; S.prompt = ''; S.n = S.streak; setOpp(S.n);
    if (save.flag('mawashiSky') !== benSky) { benSky = save.flag('mawashiSky'); const keep = { x: ben.x, z: ben.z }; dropW(ben); ben = mkW(benCfg()); ben.mass = 1; ben.spd = 1.5; Object.assign(ben, keep); }
    resetW(ben); resetW(opp); zab.forEach(z => { z.m.visible = false; });
    opp.x = 8; opp.z = 0; opp.y = 0; opp.path = [[HALF + 1.1, 0], [HALF - 0.2, 0], [2.0, -1.2]];
    if (S.first) { ben.x = -8; ben.z = 0; ben.y = 0; ben.path = [[-HALF - 1.1, 0], [-HALF + 0.2, 0], [-2.0, 1.2]]; } else { ben.x = -2.0; ben.z = 1.2; ben.y = DY; }
    S.first = false; setPh('enter'); tone(60, 0.45, 0.5, 'sine', 0.5); setTimeout(() => tone(60, 0.45, 0.5, 'sine', 0.5), 380); }
  function setPh(p) { S.ph = p; S.phT = 0; if (p === 'salt') { [ben, opp].forEach(w => { w.at = 0; w.salted = false; }); call('SHIO · SALT', 1.4); } if (p === 'shiko') { ben.stomps = 0; opp.stomps = 0; ben.sk = null; opp.sk = null; S.prompt = 'shiko'; } if (p === 'shikiri') { S.prompt = 'wait'; [ben, opp].forEach(w => { w.sk = null; }); } }
  function startStreak() { try { audio.init && audio.init(); if (audio.wind) audio.wind.gain.value = 0.16; } catch (e) {} S.streak = 0; S.first = true; S.seed = 1 + Math.floor(Math.random() * 999); newBout(); }
  function skip() { if (S.mode !== 'bout') return; if (S.ph === 'enter' || S.ph === 'salt') { [ben, opp].forEach(w => { w.path = null; w.x = w === ben ? -2.0 : 2.0; w.z = w === ben ? 1.2 : -1.2; w.y = DY; }); setPh('shiko'); } else if (S.ph === 'shiko') setPh('shikiri'); }
  // ---------- moves ----------
  const COST = { push: 10, slap: 12, grab: 4, throw: 18, drive: 14, release: 0, wind: 0 };
  function act(w, type, next) { if (w.act || w.stun > 0 || w.fall || S.ph !== 'fight') return false; const c = COST[type];
    if (c && w.st < c * 0.5) { if (w === ben) flash('OUT OF BREATH', '#ffffff', 0.8); return false; } w.st = Math.max(0, w.st - c);
    const dur = { push: 0.48, slap: 0.66, grab: 0.34, throw: 0.8, drive: 0.6, release: 0.3, wind: w === ben ? 0 : S.P.wind }[type];
    w.act = { type, t: 0, dur, next, hits: type === 'slap' ? [0.1, 0.28, 0.46] : type === 'push' ? [0.15] : type === 'grab' ? [0.16] : type === 'throw' ? [0.3] : [], hi: 0 };
    if (type === 'drive') { w.boost = 0.6; tone(110, 0.3, 0.2, 'sawtooth', 0.7); }
    if (type === 'release') { const o = other(w), a = axisFrom(w, o); S.lock = null; w.kx -= a.x * 1.3; w.kz -= a.z * 1.3; o.kx += a.x * 0.6; o.kz += a.z * 0.6; if (w === ben) flash('LET GO', '#ffffff', 0.7); }
    return true; }
  const axisFrom = (w, o) => { const dx = o.x - w.x, dz = o.z - w.z, d = Math.hypot(dx, dz) || 1e-3; return { x: dx / d, z: dz / d, d }; };
  const cancel = w => { if (w.act && w.act.type !== 'throw') w.act = null; };
  const mark = (v, by, type) => { v.lastHit = { by, type, t: S.t }; };
  function stepAct(w, dt) { const a = w.act; if (!a) return; a.t += dt; while (a.hi < a.hits.length && a.t >= a.hits[a.hi]) { hit(w, a.type, a.hi); a.hi++; if (!w.act) return; } if (a.t >= a.dur) { w.act = null; if (a.type === 'wind' && a.next && w.stun <= 0) act(w, a.next); } }
  function whiff(w, k = 1) { const o = other(w), a = axisFrom(w, o); w.kx += a.x * 1.5 * k; w.kz += a.z * 1.5 * k; w.bal -= 14 * k; w.stun = Math.max(w.stun, 0.3 * k); w.lunge = S.t; if (w === ben) flash('MISSED', '#ffffff', 0.6); else flash('HE MISSED · NOW!', '#22c55e', 0.8); }
  function hit(w, type, i) { const o = other(w); if (o.fall || S.ph !== 'fight') return; const a = axisFrom(w, o), C = w.rad + o.rad, ratio = clamp(w.mass / o.mass, 0.6, 1.7), sf = 0.6 + 0.4 * w.st / 100, bk = o === ben ? (OPT.normal ? 0.9 : 0.72) : 1;
    if (type === 'push') { if (S.lock) return; if (a.d > C + 0.55) { whiff(w); return; } const imp = 1.9 * Math.pow(ratio, 0.8) * sf; o.kx += a.x * imp; o.kz += a.z * imp; o.bal -= 17 * ratio * bk; o.stun = Math.max(o.stun, 0.28); cancel(o); mark(o, w, 'push'); thud(1); HK.kick(o.g, 1.4); dust(o.x, o.z, 3); S.shake = 0.14;
      if (o.stumble > 0) knockDown(o, w, 'TSUKITAOSHI', -1); }
    else if (type === 'slap') { if (S.lock) return; if (a.d > C + 0.5) { if (i === 0) whiff(w, 0.4); return; } o.kx += a.x * 0.6 * ratio; o.kz += a.z * 0.6 * ratio; o.bal -= 10 * ratio * bk; o.stun = Math.max(o.stun, 0.2); cancel(o); mark(o, w, 'slap'); audio.burst && audio.burst(0.05, 4200, 0.4); HK.kick(o.g, 0.6); if (o.stumble > 0 && i === 2) knockDown(o, w, 'HATAKIKOMI', 1); }
    else if (type === 'grab') { if (S.lock) return; if (a.d > C + 0.35) { whiff(w, 0.3); return; } const busy = o.act && (o.act.type === 'push' || o.act.type === 'slap'); if (busy && Math.random() < (w === ben ? 0.3 : 0.6)) { flash(w === ben ? 'GRIP BROKEN' : 'YOU SLAPPED HIS HAND AWAY', '#ffffff', 0.8); return; } S.lock = { by: w, t: 0 }; tone(180, 0.15, 0.2, 'square', 0.8); flash(w === ben ? 'BELT GRIP!' : 'HE HAS YOUR BELT', w === ben ? '#22c55e' : '#ec3013', 1.1); }
    else if (type === 'throw') { if (!S.lock) return; const inside = S.lock.by === w; let ch = 0.25 + (100 - o.bal) / 100 * 0.6 + (ratio - 1) * 0.35 + (inside ? 0.08 : 0) + (w === ben ? (OPT.normal ? 0.08 : 0.2) : -0.12); if (o.stumble > 0) ch = 1; ch = clamp(ch, 0.08, 0.95);
      if (Math.random() < ch) { S.lock = null; throwDown(o, w, inside ? 'UWATENAGE' : 'SHITATENAGE'); } else { S.lock = null; w.bal -= 28; w.stun = 0.45; w.kx -= a.x * 1.0; w.kz -= a.z * 1.0; flash(w === ben ? 'THROW BLOCKED' : 'YOU HELD ON!', '#ffffff', 0.9); thud(0.6); } } }
  function knockDown(o, w, kim, dir) { o.fall = { kind: 'down', t: 0, dur: 0.55, pitch: dir * 1.35 }; o.act = null; S.lock = null; thud(1.3); dust(o.x, o.z, 8); decide(o, kim); }
  function throwDown(o, w, kim) { const s = Math.random() < 0.5 ? 1 : -1, dx = o.x - w.x, dz = o.z - w.z; o.fall = { kind: 'throw', t: 0, dur: 0.75, cx: w.x, cz: w.z, a0: Math.atan2(dz, dx), sweep: s * 1.7, r: Math.hypot(dx, dz), roll: s * 1.45 }; o.act = null; thud(1.4); decide(o, kim); }
  function stepFall(w, dt) { const f = w.fall; if (!f) return; f.t = Math.min(f.dur, f.t + dt); const u = ss(f.t / f.dur);
    if (f.kind === 'throw') { const a = f.a0 + f.sweep * u, r = f.r * (1 + 0.3 * u); w.x = f.cx + Math.cos(a) * r; w.z = f.cz + Math.sin(a) * r; w.yaw = Math.atan2(f.cx - w.x, f.cz - w.z); w.roll = f.roll * u; w.pitch = -0.2 * u; if (f.t >= f.dur && !f.dusted) { f.dusted = true; dust(w.x, w.z, 10); S.shake = 0.3; HK.kick(w.g, 2); } }
    else { w.pitch = f.pitch * u; if (f.t >= f.dur && !f.dusted) { f.dusted = true; dust(w.x, w.z, 8); S.shake = 0.22; } } }
  function decide(loser, kim) { if (S.ph !== 'fight') return; const win = loser === opp; S.ph = 'result'; S.phT = 0; S.res = { win, kim, loser }; S.prompt = '';
    flash(kim, win ? '#ffd23a' : '#ec3013', 3); setTimeout(() => call((win ? 'BEN' : opp.cfg.name) + ' · ' + kim, 2.2), 450); cheer(1); ben.mood = win ? 'happy' : 'sad'; opp.mood = win ? 'sad' : 'happy';
    if (win && opp.mass >= ben.mass * 1.08) { S.res.upset = true; setTimeout(() => { throwZabuton(); cheer(1.4); }, 700); } }
  function kimFor(loser) { const h = loser.lastHit, recent = h && S.t - h.t < 1.5; if (S.lock) return 'YORIKIRI'; if (recent && h.type === 'slap') return 'TSUKIDASHI'; if (recent && h.type === 'push') return 'OSHIDASHI'; if (S.t - S.contactT < 1.0) return 'OSHIDASHI'; return 'ISAMIASHI'; }
  function finishBout() { const r = S.res, o = S.oppInfo, d = { win: r.win, kim: r.kim, kimTxt: KIMARITE[r.kim] || '', opp: o.name, rank: o.rank, bout: S.n + 1, gold: 0, streak: S.streak, best: save.stat(SK.best, 0), newBest: false, relic: false, upset: !!r.upset, demo: S.demo };
    if (r.win) { S.streak++; d.streak = S.streak; d.gold = 10 + 5 * S.n + (r.upset ? 10 : 0);
      if (!S.demo) { save.addGold(d.gold); save.setStat(SK.wins, save.stat(SK.wins, 0) + 1); d.newBest = save.best(SK.best, S.streak); if (S.streak >= 5 && !save.flag('mawashiSky')) { save.addRelic('kyotoSumoTrophy'); save.setFlag('mawashiSky'); d.relic = true; } } }
    if (!S.demo) save.setStat(SK.bouts, save.stat(SK.bouts, 0) + 1); d.best = S.demo ? d.best : save.stat(SK.best, 0);
    const nx = oppFor(OPT.normal ? S.streak + 2 : S.streak, S.seed); d.next = r.win ? { name: nx.name, rank: nx.rank } : null; S.done = d; S.mode = 'done';
    if (S.demo) { if (!r.win || S.streak >= 3) { setTimeout(() => { if (S.demo) demoStop(); }, 2600); } else setTimeout(() => { if (S.demo && S.mode === 'done') newBout(); }, 2200); } }
  // ---------- brains ----------
  function brain(w, o, P, dt) { const a = axisFrom(w, o), C = w.rad + o.rad, rW = Math.hypot(w.x, w.z), rO = Math.hypot(o.x, o.z);
    let drive = P.drive; if (rO > R - 0.9) drive = Math.min(1, drive + 0.25); let mx = a.x * drive, mz = a.z * drive;
    if (w.pivot && rW > R - 0.95) { const px = -a.z * w.pivot, pz = a.x * w.pivot; mx = mx * 0.3 + px * 0.95; mz = mz * 0.3 + pz * 0.95; }
    if (w.stun > 0 || (w.act && w.act.type === 'wind')) { mx *= 0.2; mz *= 0.2; } w.mx = mx; w.mz = mz;
    w.think -= dt; if (w.think > 0 || w.act || w.stun > 0 || w.fall) return; w.think = P.react * rr(0.7, 1.3);
    w.pivot = rW > R - 0.95 && Math.random() < P.edge ? (Math.random() < 0.5 ? -1 : 1) : 0;
    if (S.lock) { const r = Math.random(); if (r < P.throwP + (o.bal < 35 ? 0.35 : 0) + Math.min(0.4, S.lock.t * 0.05)) act(w, 'throw'); else if (r < 0.6 && w.st > 25) act(w, 'drive'); else if (rW > R - 0.6 && r < 0.75 && S.lock.by !== w) act(w, 'release'); return; }
    if (a.d < C + 0.5 && Math.random() < P.aggr) { const r = Math.random(), mv = r < P.mix[0] ? 'push' : r < P.mix[1] ? 'slap' : 'grab'; if (mv === 'grab' || !P.wind) act(w, mv); else act(w, 'wind', mv); } }
  // ---------- input ----------
  function benMove() { if (S.bot) return; let sx = stick.x, sy = stick.y; if (keys.has('KeyA') || keys.has('ArrowLeft')) sx = -1; if (keys.has('KeyD') || keys.has('ArrowRight')) sx = 1; if (keys.has('KeyW') || keys.has('ArrowUp')) sy = 1; if (keys.has('KeyS') || keys.has('ArrowDown')) sy = -1;
    const m = Math.hypot(sx, sy); if (m > 1) { sx /= m; sy /= m; } const cf = V3().subVectors(S.look, camera.position); cf.y = 0; cf.normalize(); const crx = -cf.z, crz = cf.x; ben.mx = crx * sx + cf.x * sy; ben.mz = crz * sx + cf.z * sy; if (ben.stun > 0) { ben.mx *= 0.3; ben.mz *= 0.3; } }
  function benGo(q) { const T = S.tachi; if (!T || T.benGo != null) return; T.benGo = S.t; ben.charge = 0.5; ben.tq = q; S.prompt = ''; }
  function press(n) { if (PAUSE || S.mode !== 'bout') return; try { audio.init && audio.init(); } catch (e) {}
    if (S.ph === 'shiko') { stomp(ben); return; }
    if (S.ph === 'shikiri') { flash('WAIT FOR HAKKEYOI!', '#ffffff', 0.7); return; }
    if (S.ph !== 'fight') return; const T = S.tachi; if (T && T.benGo == null) { const dt = S.t - T.callAt; benGo(dt < 0.35 ? 1.45 : dt < 0.7 ? 1.1 : 0.85); return; }
    if (S.lock) { if (n === 1) act(ben, 'drive'); else if (n === 2) act(ben, 'release'); else act(ben, 'throw'); return; }
    if (n === 4) { flash('GRAB HIS BELT FIRST (3)', '#ffffff', 0.8); return; } act(ben, n === 1 ? 'push' : n === 2 ? 'slap' : 'grab'); }
  function stomp(w) { if (w.sk || w.stomps >= 2) return; w.sk = { t: 0, side: w.stomps % 2 ? -1 : 1, hit: false }; }
  const KMAP = { Digit1: 1, KeyJ: 1, Digit2: 2, KeyK: 2, Digit3: 3, KeyL: 3, Space: 3, Digit4: 4, KeyQ: 4 };
  const onKD = e => { if (KMAP[e.code]) { e.preventDefault(); if (!e.repeat && !S.demo) press(KMAP[e.code]); return; } if (/^(Key[WASD]|Arrow)/.test(e.code)) keys.add(e.code); }, onKU = e => keys.delete(e.code), onBlur = () => keys.clear();
  addEventListener('keydown', onKD); addEventListener('keyup', onKU); addEventListener('blur', onBlur);
  // ---------- poses ----------
  function poseOf(w) { const L = w.L, k = w.k, sy = L.hipY + L.torsoL * 0.93, f = w.front, fy = L.footH, B = w.R0, md = w.mood;
    const stance = (lo = 1) => ({ ...B, mood: md, hip: [0, -0.2 * k * lo, -0.02], lean: 0.32 * lo, fL: [0.37 * k, fy, 0.06 * k], fR: [-0.37 * k, fy, -0.06 * k], kL: [1.4 * k, L.hipY * 0.6, 1], kR: [-1.4 * k, L.hipY * 0.6, 1], fYawL: 0.55, fYawR: -0.55, hL: [0.3 * k, sy - 0.28 * k, f + 0.05 * k], hR: [-0.3 * k, sy - 0.28 * k, f + 0.05 * k], eL: [1.3, sy - 0.5, -0.3], eR: [-1.3, sy - 0.5, -0.3] });
    const sq = () => ({ ...B, mood: md, fL: [0.5 * k, fy, 0.05], fR: [-0.5 * k, fy, 0.05], fYawL: 0.9, fYawR: -0.9, kL: [1.2 * k, L.hipY * 0.6, 1], kR: [-1.2 * k, L.hipY * 0.6, 1], hip: [0, -0.32 * k, -0.04], lean: 0.32, hL: [0.42 * k, L.hipY * 0.55, 0.22 * k], hR: [-0.42 * k, L.hipY * 0.55, 0.22 * k], eL: [1, L.hipY, 0], eR: [-1, L.hipY, 0] });
    const an = w.anim;
    if (an === 'walk') { const ph = w.ph, s = 0.22 * k; return { ...B, mood: md, hip: [0, -Math.abs(Math.cos(ph)) * 0.025 * k + 0.012, 0], twist: Math.sin(ph) * 0.12, fL: [L.hipW + 0.02, fy + Math.max(0, -Math.sin(ph)) * 0.09 * k, Math.cos(ph) * s], fR: [-L.hipW - 0.02, fy + Math.max(0, Math.sin(ph)) * 0.09 * k, -Math.cos(ph) * s], hL: [B.hL[0], B.hL[1] + 0.03, -Math.cos(ph) * 0.2 * k + 0.05], hR: [B.hR[0], B.hR[1] + 0.03, Math.cos(ph) * 0.2 * k + 0.05], eL: [B.eL[0], sy - 0.4, -0.6], eR: [B.eR[0], sy - 0.4, -0.6] }; }
    if (an === 'kneel') return { ...B, mood: md, hip: [0, -L.hipY * 0.6, -0.18 * k], lean: 0.06, fL: [0.13 * k, fy, -0.42 * k], fR: [-0.13 * k, fy, -0.42 * k], kL: [0.2 * k, L.hipY * 0.3, 1.5], kR: [-0.2 * k, L.hipY * 0.3, 1.5], hL: [0.17 * k, L.hipY * 0.5, 0.18 * k], hR: [-0.17 * k, L.hipY * 0.5, 0.18 * k], eL: [1, L.hipY * 0.8, 0], eR: [-1, L.hipY * 0.8, 0] };
    if (an === 'gyoji') { const P = { ...B, mood: md, hR: [-0.24 * k, sy - 0.2 * k, 0.32 * k], eR: [-1, sy - 0.5, -0.3], lean: 0.05 }; if (w.pose === 'crouch') return { ...P, hip: [0, -0.18 * k, 0], lean: 0.35, hR: [-0.15 * k, sy - 0.5 * k, 0.42 * k], kL: [0.6, L.hipY * 0.6, 1], kR: [-0.6, L.hipY * 0.6, 1] }; if (w.pose === 'raise') return { ...P, hR: [-0.3 * k, sy + 0.4 * k, 0.25 * k] }; if (w.pose === 'point' && w.pt) return { ...P, [w.pt.x > 0 ? 'hL' : 'hR']: [w.pt.x * 0.65 * k, sy + 0.15 * k, w.pt.z * 0.65 * k], ...(w.pt.x > 0 ? {} : { eR: [-1, sy, -0.5] }) }; return P; }
    if (an === 'shiko') { const s = w.sk; if (!s) return sq(); const u = s.t / 1.1, sd = s.side, lift = { ...sq(), hip: [-sd * 0.26 * k, -0.12 * k, 0], side: sd * 0.28, lean: 0.25, [sd > 0 ? 'fL' : 'fR']: [sd * 0.95 * k, L.hipY * 0.95, 0.12 * k], [sd > 0 ? 'kL' : 'kR']: [sd * 1.5 * k, L.hipY * 1.4, 0.6], [sd > 0 ? 'hL' : 'hR']: [sd * 0.55 * k, L.hipY * 0.9, 0.28 * k] }, stp = { ...sq(), hip: [0, -0.4 * k, -0.04] };
      if (u < 0.55) return lerpP(sq(), lift, ss(u / 0.55)); if (u < 0.72) return lift; if (u < 0.8) return lerpP(lift, stp, (u - 0.72) / 0.08); return lerpP(stp, sq(), ss((u - 0.8) / 0.2)); }
    if (an === 'salt') { const u = clamp(w.at / 1.2, 0, 1), e = Math.sin(Math.min(1, u / 0.5) * Math.PI / 2); return { ...B, mood: 'determined', hR: [-0.3 * k + e * 0.05, L.hipY * 0.9 + e * (sy + 0.55 * k - L.hipY * 0.9), 0.15 * k + e * 0.35 * k], eR: [-1.2, sy, -0.2], lean: 0.08 - e * 0.1 }; }
    if (an === 'crouch') return { ...stance(), hip: [0, -0.44 * k, -0.08 * k], lean: 0.85, fL: [0.42 * k, fy, 0.04], fR: [-0.42 * k, fy, 0.04], hL: [0.24 * k, fy + 0.06, f + 0.2 * k], hR: [-0.24 * k, fy + 0.06, f + 0.2 * k], eL: [1.2, L.hipY, 0.3], eR: [-1.2, L.hipY, 0.3], mood: 'focus' };
    if (an === 'win') return { ...B, mood: 'happy', hip: [0, -0.06 * k, 0], lean: -0.05 };
    if (an === 'fallen') return { ...B, mood: md, hL: [0.6 * k, sy - 0.1 * k, 0.1 * k], hR: [-0.6 * k, sy - 0.1 * k, 0.1 * k], eL: [1, sy, -0.5], eR: [-1, sy, -0.5] };
    if (an === 'stand') return { ...B, mood: md, hip: [Math.sin(S.t * 0.8 + w.k) * 0.008, 0, 0] };
    // fight poses
    const P = stance(); const spd = Math.hypot(w.vx, w.vz); if (spd > 0.15) { const s = Math.min(1, spd / 1.2) * 0.1 * k; P.fL = [P.fL[0], fy + Math.max(0, Math.sin(w.ph)) * 0.05 * k, P.fL[2] + Math.sin(w.ph) * s]; P.fR = [P.fR[0], fy + Math.max(0, -Math.sin(w.ph)) * 0.05 * k, P.fR[2] - Math.sin(w.ph) * s]; }
    const a = w.act, u = a ? a.t / a.dur : 0;
    if (w.stumble > 0) return { ...P, lean: -0.15, hip: [0, -0.1 * k, -0.1 * k], hL: [0.55 * k, sy, 0.1 * k], hR: [-0.55 * k, sy + 0.1 * k, 0.1 * k], mood: 'surprised' };
    if (S.lock && (!a || a.type === 'drive' || a.type === 'wind')) { const dv = a && a.type === 'drive' ? Math.sin(u * Math.PI) : 0; return { ...P, hip: [0, -0.26 * k - dv * 0.06 * k, -0.04], lean: 0.55 + dv * 0.15, yaw: 0.35, hL: [0.36 * k, L.hipY * 1.05, f + 0.12 * k], hR: [-0.36 * k, L.hipY * 1.05, f + 0.12 * k], eL: [1.4, sy, 0.1], eR: [-1.4, sy, 0.1], mood: dv ? 'angry' : 'determined' }; }
    if (!a) return w.stun > 0 ? { ...P, lean: 0.1, mood: 'surprised' } : P;
    if (a.type === 'wind') return { ...P, hip: [0, -0.12 * k, -0.06], lean: 0.12, hL: [0.34 * k, sy - 0.12 * k, f - 0.12 * k], hR: [-0.34 * k, sy - 0.12 * k, f - 0.12 * k], mood: 'angry' };
    if (a.type === 'push') { const e = u < 0.3 ? ss(u / 0.3) : 1 - ss((u - 0.3) / 0.7); return { ...P, lean: 0.32 + e * 0.22, hL: [0.2 * k, sy - 0.22 * k + e * 0.14 * k, f + 0.05 * k + e * 0.5 * k], hR: [-0.2 * k, sy - 0.22 * k + e * 0.14 * k, f + 0.05 * k + e * 0.5 * k], eL: [0.9, sy - 0.6, -0.5], eR: [-0.9, sy - 0.6, -0.5], mood: 'angry' }; }
    if (a.type === 'slap') { const q = Math.min(2, Math.floor(u * 3)), sp = (u * 3) % 1, e = Math.sin(sp * Math.PI), sd = q % 2 ? 1 : -1, key = sd > 0 ? 'hL' : 'hR'; return { ...P, twist: -sd * e * 0.25, [key]: [sd * 0.12 * k, sy + e * 0.12 * k, f + 0.05 * k + e * 0.5 * k], mood: 'angry' }; }
    if (a.type === 'grab') { const e = ss(u); return { ...P, lean: 0.32 + e * 0.2, hL: [0.36 * k, sy - 0.28 * k - e * (sy - L.hipY * 1.05 - 0.28 * k), f + 0.05 * k + e * 0.3 * k], hR: [-0.36 * k, sy - 0.28 * k - e * (sy - L.hipY * 1.05 - 0.28 * k), f + 0.05 * k + e * 0.3 * k] }; }
    if (a.type === 'throw') { const e = Math.sin(Math.min(1, u * 1.4) * Math.PI / 2); return { ...P, twist: e * 1.0, side: e * 0.3, lean: 0.55 + e * 0.2, hL: [0.5 * k, L.hipY * 1.2 + e * 0.3 * k, f * 0.6], hR: [-0.3 * k, L.hipY * 1.05, f + 0.15 * k], mood: 'angry' }; }
    return P; }
  // ---------- camera ----------
  function fitD(span, hNeed) { const asp = CW() / CHh(), vf = camera.fov * Math.PI / 180, hf = 2 * Math.atan(Math.tan(vf / 2) * asp); return Math.max((span / 2) / Math.tan(hf / 2), (hNeed / 2) / Math.tan(vf / 2)); }
  function camShot() { const asp = CW() / CHh();
    if (S.mode === 'intro') { const a = S.t * 0.07; const rr2 = asp < 0.8 ? 10.5 : 9.4; return { pos: V3(Math.sin(a) * rr2, DY + 3.3, Math.cos(a) * rr2), look: V3(0, DY + (asp < 0.8 ? 0.7 : 1.1), 0) }; }
    const fightish = S.ph === 'fight' || S.ph === 'result' || S.ph === 'shikiri' || S.mode === 'done';
    let mid, span, hN = 2.7, dir;
    if (fightish && opp) { mid = V3((ben.x + opp.x) / 2, DY, (ben.z + opp.z) / 2); const a = axisFrom(ben, opp); let n = V3(-a.z, 0, a.x); if (n.dot(S.camDir) < 0) n.negate(); S.camDir.lerp(n, S.ph === 'fight' ? 0.035 : 0.06).normalize(); dir = S.camDir; const mr = Math.max(Math.hypot(ben.x, ben.z), Math.hypot(opp.x, opp.z)); span = a.d + 2.0 + Math.max(0, mr - (R - 1.1)) * 1.2; if (S.mode === 'done' || S.ph === 'result') span += 0.8; }
    else { mid = V3(0, DY, 0); span = 9.5; hN = 3.6; dir = S.camDir.lerp(V3(0.22, 0, 1).normalize(), 0.04).normalize(); }
    const H = CHh(), tv = Math.tan(camera.fov * Math.PI / 360), th = tv * asp, yT = 1 - 2 * SAFE.top / H, yB = -1 + 2 * SAFE.bottom / H, frac = Math.max(0.22, (yT - yB) / 2), yc = clamp((yT + yB) / 2, -0.6, 0.6);
    const hTop = fightish && opp ? Math.max(ben.L.H * ben.sc, opp.L.H * opp.sc) + 0.2 : 2.6, d = clamp(Math.max((span / 2) / th, hTop / (frac * 2 * tv)) * 1.04, fightish ? 3.8 : 7.5, asp < 0.8 ? 12 : 11), cy = DY + hTop / 2;
    return { pos: V3(mid.x, cy + d * 0.17, mid.z).addScaledVector(dir, d), look: V3(mid.x, cy - yc * d * tv, mid.z) }; }
  // ---------- main step ----------
  function moveTo(w, x, z, spd, dt) { const dx = x - w.x, dz = z - w.z, d = Math.hypot(dx, dz); if (d < 0.04) { w.vx = w.vz = 0; return true; } const s = Math.min(spd, d / dt); w.vx = dx / d * s; w.vz = dz / d * s; w.x += w.vx * dt; w.z += w.vz * dt; w.yaw = dampA(w.yaw, Math.atan2(dx, dz), 8, dt); return false; }
  const faceTo = (w, x, z, dt, l = 8) => { w.yaw = dampA(w.yaw, Math.atan2(x - w.x, z - w.z), l, dt); };
  function physics(dt) { const a = ben, b = opp; let ax0 = axisFrom(a, b); const C = a.rad + b.rad;
    for (const w of [a, b]) { const o = other(w), ax = w === a ? ax0.x : -ax0.x, az = w === a ? ax0.z : -ax0.z; let mx = w.charge > 0 ? ax : w.mx, mz = w.charge > 0 ? az : w.mz; const spd = w.charge > 0 ? 3.2 : w.spd * (w.stun > 0 ? 0.3 : 1) * (w.stumble > 0 ? 0.3 : 1);
      const r = Math.hypot(w.x, w.z); if (r > R - 0.5 && w.charge <= 0) { const ox = w.x / r, oz = w.z / r, out = mx * ox + mz * oz; if (out > 0) { const kk = w === a ? 0.85 : 0.6; mx -= ox * out * kk; mz -= oz * out * kk; } }
      w.vx = damp(w.vx, mx * spd, 7, dt); w.vz = damp(w.vz, mz * spd, 7, dt); w.charge = Math.max(0, w.charge - dt); w.boost = Math.max(0, w.boost - dt); w.stun = Math.max(0, w.stun - dt);
      if (w.stumble > 0) { w.stumble -= dt; if (w.stumble <= 0) w.bal = 35; } }
    const contact = ax0.d <= C + 0.04 || !!S.lock; const ax = ax0.x, az = ax0.z; let da = 0, db = 0;
    if (contact) { S.contactT = S.t; da = a.charge > 0 ? 1 : Math.max(0, a.mx * ax + a.mz * az); db = b.charge > 0 ? 1 : Math.max(0, -(b.mx * ax + b.mz * az));
      if (S.tachi && !S.tachi.hit && ax0.d <= C + 0.06) { const T = S.tachi; T.hit = true; const pa = a.mass * (T.benGo != null ? a.tq : 0.6), pb = b.mass * (T.oppGo != null ? b.tq : 0.6), df = pa - pb; const kd = Math.min(1.6, Math.abs(df) * 2.0); if (df > 0) { b.kx += ax * kd; b.kz += az * kd; b.bal -= Math.min(40, df * 45); } else { a.kx -= ax * kd; a.kz -= az * kd; a.bal -= Math.min(35, -df * 35); } thud(1.5); S.shake = 0.3; HK.kick(a.g, 2); HK.kick(b.g, 2); dust((a.x + b.x) / 2, (a.z + b.z) / 2, 6); if (!S.bot || S.demo) flash(a.tq >= 1.4 ? 'GREAT TACHIAI!' : a.tq >= 1.05 ? 'GOOD TACHIAI' : 'SLOW START', a.tq >= 1.4 ? '#22c55e' : a.tq >= 1.05 ? '#ffd23a' : '#ffffff', 1.0); a.charge = b.charge = 0; }
      const pw = (w, dr) => w.mass * dr * (0.5 + 0.5 * w.st / 100) * (w.boost > 0 ? 1.8 : 1) * (S.lock ? (S.lock.by === w ? 1.25 : 0.85) : 1) * (w.stun > 0 ? 0.3 : 1) * (w.stumble > 0 ? 0.2 : 1);
      const brace = w => Math.hypot(w.x, w.z) > R - 0.7 ? (w === a ? (OPT.normal ? 1.3 : 1.5) : Math.min(1.6, 1.3 + 0.03 * S.n)) : 1, Pa = pw(a, da) * brace(a), Pb = pw(b, db) * brace(b), u = clamp((Pa - Pb) * 1.0, -1.1, 1.1);
      for (const w of [a, b]) { const al = w.vx * ax + w.vz * az; let nu = u; if (!S.lock) { if (w === a && al < u && al < 0) nu = al; if (w === b && al > u && al > 0) nu = al; } w.vx += (nu - al) * ax; w.vz += (nu - al) * az; }
      const lo = u > 0 ? b : a; lo.bal -= Math.abs(u) * 9 * dt * (lo === a ? (OPT.normal ? 0.9 : 0.75) : 1); a.st = Math.max(0, a.st - da * 6 * dt); b.st = Math.max(0, b.st - db * 6 * dt); if (S.lock) S.lock.t += dt; }
    for (const [w, dr] of [[a, da], [b, db]]) { w.st = Math.min(100, w.st + (dr < 0.2 ? 9 : 3) * dt); w.bal = Math.min(100, w.bal + (contact ? 5 : 14) * dt); if (w.bal <= 0 && w.stumble <= 0 && !w.fall) { w.stumble = 1.1; w.stun = 1.1; w.bal = 0; cancel(w); if (S.lock) S.lock = null; flash(w === opp ? 'HE IS OFF BALANCE · PUSH!' : 'OFF BALANCE!', w === opp ? '#22c55e' : '#ec3013', 1.1); } }
    for (const w of [a, b]) { if (S.lock) { w.kx = w.kz = 0; } w.x += (w.vx + w.kx) * dt; w.z += (w.vz + w.kz) * dt; const fr = Math.exp(-3.5 * dt); w.kx *= fr; w.kz *= fr; w.ph += dt * Math.hypot(w.vx, w.vz) * 7; }
    const n = axisFrom(a, b); if (S.lock) { const cx = (a.x + b.x) / 2, cz = (a.z + b.z) / 2, h = (C - 0.06) / 2; a.x = cx - n.x * h; a.z = cz - n.z * h; b.x = cx + n.x * h; b.z = cz + n.z * h; }
    else if (n.d < C) { const o = C - n.d, wa = b.mass / (a.mass + b.mass), wb = 1 - wa; a.x -= n.x * o * wa; a.z -= n.z * o * wa; b.x += n.x * o * wb; b.z += n.z * o * wb; } }
  function step(dt) { S.t += dt; S.phT += dt; if (S.flash && S.t > S.flash.t) S.flash = null; if (S.call && S.t > S.callT) S.call = '';
    if (S.mode === 'intro') { ben.anim = 'shiko'; ben.x = 0; ben.z = 0; ben.y = DY; ben.yaw = dampA(ben.yaw, Math.atan2(camera.position.x, camera.position.z), 2, dt); if (!ben.sk) { if ((S.t % 3.4) < dt * 1.5) { ben.stomps = 0; stomp(ben); } } gyoji.x = 0; gyoji.z = -1.9; gyoji.yaw = 0; gyoji.anim = 'gyoji'; gyoji.pose = ''; if (opp) opp.g.visible = false; }
    else if (S.mode === 'bout') stepBout(dt);
    else if (S.mode === 'done') { for (const w of [ben, opp]) { if (w.fall) stepFall(w, dt); w.anim = w.fall ? 'fallen' : (S.done && (w === ben) === S.done.win) ? 'win' : 'stand'; } }
    // shiko stomps (any phase)
    for (const w of [ben, opp]) { if (!w || !w.sk) continue; w.sk.t += dt; if (!w.sk.hit && w.sk.t >= 1.1 * 0.8) { w.sk.hit = true; HK.kick(w.g, 1.6); w.g.updateMatrixWorld(true); const p = (w.sk.side > 0 ? w.U.J.anL : w.U.J.anR).getWorldPosition(V3()); dust(p.x, p.z, 5); if (S.mode === 'bout') { thud(1); if (w === ben) { cheer(0.8); S.shake = 0.12; } } } if (w.sk.t >= 1.1) { w.sk = null; w.stomps++; } }
    // pose every person
    for (const w of people) { if (!w.g.visible && w !== opp) continue; const tgt = poseOf(w); w.P = lerpP(w.P, tgt, 1 - Math.exp(-(w.anim === 'shiko' || w.act ? 22 : 12) * dt)); w.g.position.set(w.x, w.y, w.z); w.g.rotation.set(w.pitch, w.yaw, w.roll); if (w.blob) { w.blob.visible = w.g.visible; w.blob.position.set(w.x, groundY(w.x, w.z) + 0.012, w.z); } HK.update(w.g, w.P, dt); }
    for (const w of [ben, opp]) if (w && w.anim === 'walk' && w.U.J.belly) { if (Math.sin(w.ph) * Math.sin(w.ph - dt * 5.2) <= 0) HK.kick(w.g, 0.4); }
    if (ben.U.J.apron) ben.U.J.apron.visible = OPT.apronInBout || S.mode !== 'bout' || S.ph === 'enter' || S.ph === 'salt';
    // effects
    for (const q of salt) { if (q.life <= 0) continue; q.life -= dt; q.v.y -= 9 * dt; q.s.position.addScaledVector(q.v, dt); if (q.s.position.y < DY + 0.02) { q.s.position.y = DY + 0.02; q.v.set(0, 0, 0); } q.s.material.opacity = Math.min(1, q.life) * 0.9; }
    for (const p of ST.smokeS) { if (p.life <= 0) continue; p.life -= dt * 1.4; p.s.position.addScaledVector(p.v, dt * 1.6); p.s.material.opacity = Math.max(0, p.life) * 0.55; p.s.scale.setScalar(0.25 + (1 - p.life) * 0.6); }
    for (const z of zab) { if (!z.m.visible) continue; z.t += dt; const u = clamp(z.t / 1.1, 0, 1); if (z.t < 0) { z.m.position.set(0, -5, 0); continue; } if (u < 1) { z.m.position.lerpVectors(z.p0, z.p1, u); z.m.position.y += Math.sin(u * Math.PI) * 3.5; z.m.rotation.set(z.spin.x * u, z.spin.y * u, z.spin.z * u); } else { z.m.position.copy(z.p1); z.m.rotation.set(0, z.spin.y, 0); } }
    for (const m of motes) { m.userData.ph += dt * 0.4; m.position.y += dt * 0.08; if (m.position.y > DY + 8) m.position.y = DY + 0.4; m.position.x += Math.sin(m.userData.ph) * dt * 0.05; m.material.opacity = 0.25 + Math.sin(m.userData.ph * 3) * 0.2; }
    if (S.cheer > 0) { S.cheer -= dt * 0.6; placeCrowd(Math.min(1, S.cheer), S.t); if (S.cheer <= 0) placeCrowd(); }
    const sh = camShot(); if (S.snap) { S.snap = false; camera.position.copy(sh.pos); S.look.copy(sh.look); } const kL = S.mode === 'intro' ? 0.02 : S.ph === 'fight' ? 0.07 : 0.045; camera.position.lerp(sh.pos, kL * 60 * dt > 1 ? 1 : kL * 60 * dt); S.look.lerp(sh.look, Math.min(1, kL * 60 * dt)); camera.lookAt(S.look);
    if (S.shake > 0) { S.shake -= dt; camera.position.x += rr(-0.05, 0.05) * S.shake * 5; camera.position.y += rr(-0.05, 0.05) * S.shake * 5; } }
  function stepBout(dt) { const P = S.P; if (opp) opp.g.visible = true;
    // gyoji stays behind the pair, facing the camera side
    const mid = V3((ben.x + opp.x) / 2, 0, (ben.z + opp.z) / 2), back = mid.clone().addScaledVector(S.camDir, -1.75); if (back.length() > R + 0.4) back.setLength(R + 0.4); if (S.ph === 'enter' || S.ph === 'salt' || S.ph === 'shiko') back.set(0, 0, -1.9);
    gyoji.x = damp(gyoji.x, back.x, 3, dt); gyoji.z = damp(gyoji.z, back.z, 3, dt); faceTo(gyoji, mid.x + S.camDir.x * 2, mid.z + S.camDir.z * 2, dt, 4); gyoji.anim = 'gyoji';
    if (S.ph === 'enter') { gyoji.pose = ''; let done = true; for (const w of [ben, opp]) { if (!w.path || !w.path.length) { w.anim = 'stand'; faceTo(w, 0, 0, dt, 4); continue; } done = false; w.anim = 'walk'; w.ph += dt * 5.2; const [px, pz] = w.path[0]; if (moveTo(w, px, pz, 1.8, dt)) w.path.shift(); w.y = damp(w.y, groundY(w.x, w.z), 12, dt); } if (done && S.phT > 0.6) setPh('salt'); return; }
    if (S.ph === 'salt') { for (const w of [ben, opp]) { const off = w === ben ? 0 : 0.35; w.anim = 'salt'; w.at = Math.max(0, S.phT - off); faceTo(w, 0, 0, dt); if (!w.salted && w.at > 0.55) { w.salted = true; w.g.updateMatrixWorld(true); throwSalt(w); } } if (S.phT > 1.9) setPh('shiko'); return; }
    if (S.ph === 'shiko') { for (const w of [ben, opp]) { w.anim = 'shiko'; faceTo(w, 0, 0, dt); } if (!opp.sk && opp.stomps < 2 && S.phT > 0.6 + opp.stomps * 0.3) stomp(opp); if ((S.bot || S.phT > 6 + ben.stomps * 1.2) && !ben.sk && ben.stomps < 2) stomp(ben);
      if (ben.stomps >= 2 && opp.stomps >= 2 && !ben.sk && !opp.sk) { if (!S.shikoEnd) S.shikoEnd = S.phT; if (S.phT - S.shikoEnd > 0.35) { S.shikoEnd = 0; setPh('shikiri'); } } return; }
    if (S.ph === 'shikiri') { const C = ben.rad + opp.rad, lx = C / 2 + 0.42; let arrived = true; for (const w of [ben, opp]) { const tx = sideOf(w) * lx; if (!moveTo(w, tx, 0, 1.3, dt)) { arrived = false; w.anim = 'walk'; w.ph += dt * 5.2; } else { w.anim = 'crouch'; faceTo(w, -tx, 0, dt, 6); } } gyoji.pose = 'crouch';
      if (arrived) { S.arrT = S.arrT || S.phT; if (S.phT - S.arrT > 1.3) { S.arrT = 0; S.ph = 'fight'; S.phT = 0; S.tachi = { callAt: S.t, benGo: null, oppGo: null, hit: false }; call('HAKKEYOI!', 1.2); gyoji.pose = 'raise'; S.prompt = 'go'; tone(70, 0.3, 0.4, 'sine', 0.6); } } return; }
    if (S.ph === 'fight') { const T = S.tachi; if (T.oppGo == null && S.t - T.callAt >= P.tdelay) { T.oppGo = S.t; opp.charge = 0.5; opp.tq = 1 + 0.03 * S.n; }
      if (T.benGo == null) { if (S.bot && S.t - T.callAt >= BOT.tdelay) benGo(1.45); else if (S.t - T.callAt > 1.3) benGo(0.7); }
      if (S.phT > 1.0) gyoji.pose = '';
      if (S.bot) brain(ben, opp, S.botP || BOT, dt); else benMove(); if (T.oppGo != null) brain(opp, ben, P, dt); else { opp.mx = opp.mz = 0; } if (T.benGo == null) { ben.mx = ben.mz = 0; }
      stepAct(ben, dt); stepAct(opp, dt); physics(dt);
      for (const w of [ben, opp]) { const o = other(w); w.anim = 'fight'; if (!w.fall) faceTo(w, o.x, o.z, dt, 10); w.y = groundY(w.x, w.z); }
      S.nokT -= dt; if (S.nokT <= 0) { S.nokT = 2.2; if (S.t - S.contactT < 0.5) call('NOKOTTA! NOKOTTA!', 1.1); else if (S.phT > 2.5) call('HAKKEYOI!', 0.9); }
      if (S.ph === 'fight') { for (const w of [ben, opp]) { const lim = w === ben ? R + (OPT.normal ? -0.12 : 0.06) : R - 0.1; if (Math.hypot(w.x, w.z) > lim) { w.out = true; decide(w, kimFor(w)); break; } } }
      return; }
    if (S.ph === 'result') { const r = S.res; for (const w of [ben, opp]) { if (w.fall) { stepFall(w, dt); w.anim = 'fallen'; continue; } w.mx = w.mz = 0; w.act = null; w.vx = damp(w.vx, 0, 3, dt); w.vz = damp(w.vz, 0, 3, dt); w.x += (w.vx + w.kx) * dt; w.z += (w.vz + w.kz) * dt; w.kx *= Math.exp(-2.5 * dt); w.kz *= Math.exp(-2.5 * dt); const gy = groundY(w.x, w.z); if (w.y > gy + 0.01) { w.vy -= 9.8 * dt; w.y = Math.max(gy, w.y + w.vy * dt); if (w.y <= gy + 0.001 && !w.landed) { w.landed = true; w.fall = { kind: 'down', t: 0, dur: 0.4, pitch: -0.9 }; dust(w.x, w.z, 6); thud(1); } } else w.y = gy; w.anim = S.phT > 0.9 ? ((w === ben) === r.win ? 'win' : 'stand') : 'fight'; }
      const wn = r.win ? ben : opp, lx = wn.x - gyoji.x, lz = wn.z - gyoji.z, c = Math.cos(gyoji.yaw), s = Math.sin(gyoji.yaw), L = Math.hypot(lx, lz) || 1; gyoji.pt = { x: (lx * c - lz * s) / L, z: (lx * s + lz * c) / L }; gyoji.pose = S.phT > 0.5 ? 'point' : '';
      if (S.phT > (r.upset ? 3.6 : 2.8)) { ben.landed = opp.landed = false; finishBout(); } } }
  function frame() { raf = requestAnimationFrame(frame); { const pr = renderer.getPixelRatio(); if (Math.abs(renderer.domElement.width - Math.round(CW() * pr)) > 1 || Math.abs(renderer.domElement.height - Math.round(CHh() * pr)) > 1) onRs(); } const dt = Math.min(0.05, clock.getDelta()); if (!PAUSE) step(dt); renderer.render(scene, camera); hudT -= dt; if (hudT <= 0) { hudT = 0.1; onState(hud()); } }
  function onRs() { renderer.setSize(CW(), CHh(), false); renderer.domElement.style.width = '100%'; renderer.domElement.style.height = '100%'; camera.aspect = CW() / CHh(); camera.updateProjectionMatrix(); } addEventListener('resize', onRs); const ro = new ResizeObserver(onRs); ro.observe(container);
  function demoStart() { S.demo = true; S.bot = true; startStreak(); }
  function demoStop() { S.demo = false; S.bot = false; toIntro(); }
  function toIntro() { S.mode = 'intro'; S.ph = 'idle'; S.done = null; S.res = null; S.lock = null; S.flash = null; S.call = ''; S.prompt = ''; resetW(ben); zab.forEach(z => { z.m.visible = false; }); if (opp) opp.g.visible = false; S.camDir.set(0, 0, 1); S.snap = true; }
  function hud() { const o = S.oppInfo, inB = S.mode === 'bout', cf = V3().subVectors(S.look, camera.position); cf.y = 0; cf.normalize(); const crx = -cf.z, crz = cf.x, RR = R + 0.5, mp = w => [50 + (w.x * crx + w.z * crz) / RR * 50, 50 - (w.x * cf.x + w.z * cf.z) / RR * 50];
    const swap = !inB ? null : S.ph === 'shiko' ? [['stomp', 'STOMP'], ['stomp', 'STOMP'], ['stomp', 'STOMP']] : (S.ph === 'shikiri' || (S.ph === 'fight' && S.tachi && S.tachi.benGo == null)) ? [['drive', 'CHARGE'], ['drive', 'CHARGE'], ['drive', 'CHARGE']] : S.lock && S.ph === 'fight' ? [['drive', 'DRIVE'], ['release', 'LET GO'], ['nage', 'THROW']] : null;
    const rB = Math.hypot(ben.x, ben.z), rO = opp ? Math.hypot(opp.x, opp.z) : 0, live = inB && S.ph === 'fight';
    const prompt = !inB ? '' : S.ph === 'shiko' ? 'shiko' : S.ph === 'shikiri' ? 'wait' : live && S.tachi && S.tachi.benGo == null ? 'go' : live && S.lock ? (S.lock.by === ben ? 'grip' : 'gripped') : live && rB > R - 0.55 ? 'edge' : live && opp && opp.stumble > 0 ? 'stumble' : '';
    const quest = inB ? 'BOUT ' + (S.n + 1) + ' · VS ' + (o ? o.name : '') + ' · STREAK ' + S.streak : 'SUMO STREAK · ONE LOSS ENDS IT';
    return { mode: S.mode, ph: S.ph, quest, flash: S.flash, call: S.call, prompt, done: S.done, streak: S.streak, best: save.stat(SK.best, 0), wins: save.stat(SK.wins, 0), bouts: save.stat(SK.bouts, 0), trophy: save.flag('mawashiSky'), hp: Math.max(0, Math.round(ben.bal)), st: Math.round(ben.st), stomps: ben.stomps,
      opp: inB && o && opp ? { name: o.name, rank: o.rank, h: o.cfg.height.toFixed(2), kg: Math.round(o.mass * 165), bal: clamp(opp.bal / 100, 0, 1), st: clamp(opp.st / 100, 0, 1), n: S.n + 1, bigger: o.mass >= ben.mass * 1.08 } : null, benKg: 165,
      lock: !!S.lock, swap, ring: inB && opp ? { b: mp(ben), o: mp(opp), warnB: rB > R - 0.55, warnO: rO > R - 0.75 } : null, canSkip: inB && (S.ph === 'enter' || S.ph === 'salt' || S.ph === 'shiko'), demo: S.demo ? demoCap() : null, gold: save.data.gold, next: oppFor(OPT.normal ? S.streak + 2 : S.streak, S.seed) }; }
  function demoCap() { if (S.ph === 'shiko') return ['1·2·3', 'SHIKO: tap to stomp. The crowd loves it.']; if (S.ph === 'shikiri') return ['WAIT', 'Crouch at the white lines. Charge the moment the gyoji calls HAKKEYOI!']; if (S.ph === 'fight') { const a = ben.act; if (S.lock) return a && a.type === 'throw' ? ['3', 'THROW when his balance bar is low.'] : ['1', 'Belt grip: walk him back or tap DRIVE for YORIKIRI.']; if (a && a.type === 'slap') return ['2', 'SLAP: three fast slaps knock his balance down.']; if (a && a.type === 'grab') return ['3', 'GRAB his belt when you are chest to chest.']; return ['1', 'PUSH: walk him back, then shove him over the straw.']; } if (S.ph === 'result') return ['', 'Out of the ring or a hand down = the bout is over.']; return ['', 'Ring entry: salt purifies the ring.']; }
  frame();
  return { startStreak, nextBout() { if (S.done && S.done.win) newBout(); else startStreak(); }, toIntro, skip, demoStart, demoStop, setOpts(o) { OPT = { ...OPT, ...o }; }, setSafe(o) { Object.assign(SAFE, o); },
    melee() { if (!S.demo) press(1); }, range() { if (!S.demo) press(2); }, jump() { if (!S.demo) press(3); }, meleeUp() {}, rangeUp() {}, jumpUp() {},
    setStick(x, y) { stick.x = x; stick.y = y; }, setPaused(v) { PAUSE = !!v; }, setHudPad() {}, start() {}, talk() {}, choose() {}, closeDialog() {}, nextLine() {}, clearToast() {}, useItem() { flash('SAVE IT FOR AFTER THE BOUT', '#ffffff', 1.2); }, closeWheel() {}, skipTime() {}, eyeLook() {}, eyeRelease() {}, togglePov() { return false; }, lookBy() {}, zoomBy() {}, getCam() { return { dist: 9, pitch: 0.2 }; }, setCam() {}, setMinimap() {}, toggleSound() {}, cycleWeather() {},
    mapData() { return { p: [ben.x, ben.z, ben.yaw], b: [['DOHYO', 0, 0]], f: [], e: opp ? [[opp.x, opp.z]] : [], q: null }; },
    hud, _bot(v = true) { S.bot = !!v; }, _sim(n, cb, dt = 1 / 30) { for (let i = 0; i < n; i++) { step(dt); if (cb && cb(S, i) === false) break; } renderer.render(scene, camera); onState(hud()); }, _state: () => S, _ben: () => ben, _opp: () => opp, _press: press,
    destroy() { cancelAnimationFrame(raf); removeEventListener('resize', onRs); ro.disconnect(); removeEventListener('keydown', onKD); removeEventListener('keyup', onKU); removeEventListener('blur', onBlur); renderer.dispose(); renderer.domElement.remove(); try { audio.ctx && audio.ctx.close(); } catch (e) {} } };
}
