// 8 GATES — JIDDA · THE DEEP [jDeepDive] — deep sea diving for pearls. Scuba fox, OXYGEN tank, three zones going down:
// REEF (white pearls, 1) · TWILIGHT (gold, 3) · ABYSS (black, 10). Bank pearls at JIB's boat on the surface; bank 40 to win.
// Obstacles: urchin beds, old sea mines on chains, currents, kelp, rock arches. Creatures: jellyfish, moray eels (in holes by the clams),
// pufferfish, an octopus (ink), a shark, anglerfish (their lure looks like a pearl). Buttons (Game HUD vehicle="dive"): 1 GRAB / FLASH · 2 DOWN · 3 UP.
import * as THREE from '../../vendor/three/three.module.js';
import { rr, pick, clamp, damp, makeGradient, glowTexture, Ambience, smooth } from '../../village-game.js';
import { crestTex, canvasTex } from '../../meru-game.js';
import { foxKit, PLAYER_MALE } from '../../fox-kit.js';
import { castKit } from '../../engine/cast.js';
import { save } from '../../engine/save.js';
import { swimKit } from '../../engine/swim-kit.js';

export const PLACES = [{ id: 'deep', name: 'THE DEEP', room: 'jDeepDive', built: true, target: 240, goal: 'Bank 40 pearl points', line: 'Dive off the boat, take pearls from the clams, and bring them back up before your tank runs dry. Deeper pearls are worth more. Bubble vents refill your tank.' }];
export const DIVE = { SPEED: 4.4, DRAG: 2.0, STEP: 3, VY: 3.2, O2: 100, DRAIN: 0.9, DEEP_K: 0.02, VENT: 28, BOAT: 40, GOAL: 40, FLASH_CD: 3, FLASH_R: 9, BAG: 5, GIANT: 25 };
const sstep = (e0, e1, x) => { const t = clamp((x - e0) / (e1 - e0), 0, 1); return t * t * (3 - 2 * t); };
const lerp = (a, b, k) => a + (b - a) * k;

// MERU THEME (theme: 'meru'): THE DEEP POND [meruPearlDive] under Pearl Island, the same engine reskinned. Fresh green water, HULL PEARLS,
// NELLY in place of the shark, a raft with the pearl diver (new avatar, no lines) in place of Jib's boat, and no radio (Ben writes the voices).
const MERU_TXT = [[/JIB'S BOAT/g, 'THE RAFT'], [/JIB HAULED YOU UP/g, 'HAULED UP TO THE RAFT'], [/JIB PATCHED YOUR GLASS/g, 'GLASS PATCHED'], [/AT THE BOAT/g, 'AT THE RAFT'], [/THE BOAT/g, 'THE RAFT'], [/\bBOAT\b/g, 'RAFT'],
  [/SHARK BITE/g, 'NELLY!'], [/\bREEF\b/g, 'SHALLOWS'], [/TWILIGHT/g, 'MIDWATER'], [/ABYSS/g, "NELLY'S DEN"], [/THE DEEP(?! POND)/g, 'THE DEEP POND'], [/DEEP SEA PEARLS/g, 'HULL PEARLS'], [/JIDDA/g, 'MERU'], [/SEA MINES?/g, m => m.replace('SEA', 'OLD')], [/SEA URCHIN/g, 'SPIKE SNAIL'], [/(WHITE|GOLD|BLACK) PEARL/g, '$1 HULL PEARL']];
export async function createDeepDive({ container, onState = () => {}, theme = '' }) {
  const MERU = theme === 'meru', TX = s => { if (!MERU || typeof s !== 'string') return s; for (const [a, b] of MERU_TXT) s = s.replace(a, b); return s; };
  const BEST_KEY = MERU ? 'meru.pond.best' : 'jidda.deep.best';
  const touch = matchMedia('(pointer: coarse)').matches, CW = () => container.clientWidth || 1, CHh = () => container.clientHeight || 1;
  const renderer = new THREE.WebGLRenderer({ antialias: !touch }); renderer.setPixelRatio(Math.min(devicePixelRatio, touch ? 1.5 : 2)); renderer.setSize(CW(), CHh());
  renderer.domElement.style.cssText = 'display:block;width:100%;height:100%;touch-action:none;outline:none'; container.appendChild(renderer.domElement);
  const scene = new THREE.Scene(); scene.background = new THREE.Color(MERU ? 0x3f9a84 : 0x2a9fc0); scene.fog = new THREE.Fog(MERU ? 0x3f9a84 : 0x2a9fc0, 4, 60);
  const camera = new THREE.PerspectiveCamera(60, CW() / CHh(), 0.1, 1200);
  const grad = makeGradient(), glowTex = glowTexture(), cache = new Map(), V3 = (x = 0, y = 0, z = 0) => new THREE.Vector3(x, y, z);
  const toon = (c, extra) => { const k = c + (extra ? JSON.stringify(extra) : ''); if (!cache.has(k)) cache.set(k, new THREE.MeshToonMaterial({ color: c, gradientMap: grad, ...extra })); return cache.get(k); };
  const outlineMat = new THREE.MeshBasicMaterial({ color: 0x1a1626, side: THREE.BackSide });
  function addOutline(mesh, t = 0.04, radius) { const g = mesh.geometry; g.computeBoundingBox(); const s = V3(); g.boundingBox.getSize(s); const o = new THREE.Mesh(g, outlineMat); if (radius) o.scale.setScalar(1 + t / radius); else o.scale.set(1 + 2 * t / Math.max(s.x, 0.01), 1 + 2 * t / Math.max(s.y, 0.01), 1 + 2 * t / Math.max(s.z, 0.01)); mesh.add(o); return mesh; }
  const WORLD = new THREE.Group(); scene.add(WORLD);
  function M(geo, mat, x = 0, y = 0, z = 0, parent, outline = 0.04, radius) { const m = new THREE.Mesh(geo, mat); m.position.set(x, y, z); if (outline) addOutline(m, outline, radius); (parent || WORLD).add(m); return m; }
  const kit = foxKit({ THREE, scene, toon, M, grad, outlineMat, crestTex, rr, pick, clamp, smooth, damp }), cast = castKit({ THREE, M, toon, makeFox: kit.makeFox }), SK = swimKit({ THREE, M, toon, kit });
  const audio = new Ambience();
  const hemi = new THREE.HemisphereLight(0xcff4ff, 0x0b3a52, 1.1), sunL = new THREE.DirectionalLight(0xe8fbff, 1.6); sunL.position.set(10, 40, -10); scene.add(hemi, sunL);
  const ink = toon('#201e1d'), white = toon('#f3f2f2'), red = toon('#ec3013'), yel = toon('#ffd23a'), steel = toon('#7d8790');

  // ---------- FX ----------
  const SPN = touch ? 60 : 110, sprays = []; let spI = 0;
  for (let i = 0; i < SPN; i++) { const m = new THREE.Sprite(new THREE.SpriteMaterial({ map: glowTex, color: 0xffffff, transparent: true, depthWrite: false, opacity: 0 })); m.visible = false; scene.add(m); sprays.push({ m, v: V3(), life: 0, max: 1, s: 1, g: 9 }); }
  function spray(p, n, spd, size = 1, life = 0.9, col = 0xffffff, g = -2.5) { for (let k = 0; k < n; k++) { const s = sprays[spI = (spI + 1) % SPN]; s.m.position.copy(p); s.m.position.x += rr(-0.3, 0.3); s.m.position.z += rr(-0.3, 0.3); s.v.set(rr(-1, 1) * spd * 0.5, rr(0.3, 1) * spd, rr(-1, 1) * spd * 0.5); s.life = s.max = life * rr(0.7, 1.2); s.s = size * rr(0.7, 1.3); s.g = g; s.m.material.color.setHex(col); s.m.visible = true; } }
  const bubbles = (p, n = 3) => spray(p, n, 0.6, 0.3, 1.4, 0xdff6ff, -3);
  function fxStep(dt) { for (const s of sprays) { if (s.life <= 0) continue; s.life -= dt; if (s.life <= 0) { s.m.visible = false; continue; } s.v.y -= s.g * dt; s.m.position.addScaledVector(s.v, dt); const u = 1 - s.life / s.max; s.m.material.opacity = 0.8 * (1 - u); s.m.scale.setScalar(s.s * (0.7 + u * 0.6)); } }
  const bangTex = canvasTex(64, 64, g => { g.fillStyle = '#ec3013'; g.fillRect(4, 4, 56, 56); g.strokeStyle = '#ffffff'; g.lineWidth = 5; g.strokeRect(6, 6, 52, 52); g.fillStyle = '#fff'; g.font = '900 46px Archivo, sans-serif'; g.textAlign = 'center'; g.textBaseline = 'middle'; g.fillText('!', 32, 35); });
  const mkBang = (parent, y) => { const s = new THREE.Sprite(new THREE.SpriteMaterial({ map: bangTex, transparent: true, depthWrite: false, depthTest: false })); s.scale.set(0.8, 0.8, 1); s.position.y = y; s.visible = false; s.renderOrder = 5; parent.add(s); return s; };
  const signTex = (txt, bg, fg) => canvasTex(256, 96, g => { g.fillStyle = bg; g.fillRect(0, 0, 256, 96); g.strokeStyle = '#201e1d'; g.lineWidth = 8; g.strokeRect(4, 4, 248, 88); g.fillStyle = fg; let fs = 52; g.font = '900 ' + fs + 'px Archivo, sans-serif'; const tw = g.measureText(txt).width; if (tw > 220) { fs = Math.floor(fs * 220 / tw); g.font = '900 ' + fs + 'px Archivo, sans-serif'; } g.textBaseline = 'middle'; g.fillText(txt, 18, 52); });
  const depthSign = (txt, x, y, z, bg) => { const sp = new THREE.Sprite(new THREE.SpriteMaterial({ map: signTex(txt, bg, '#201e1d'), transparent: true, depthWrite: false, fog: false })); sp.scale.set(3.4, 1.27, 1); sp.position.set(x, y, z); WORLD.add(sp); return sp; };

  // ---------- THE SEABED: shelf by the boat → slope → the trench ----------
  const floor = (x, z) => { const shelf = -9 - 2 * Math.sin(x * 0.12) * Math.sin(z * 0.1), slope = -26 - 3 * Math.sin(x * 0.09 + z * 0.05), abyss = -54 - 4 * Math.sin(x * 0.07) - 6 * sstep(25, 55, Math.abs(x)) * -1; let y = lerp(shelf, slope, sstep(30, 60, z)); y = lerp(y, abyss, sstep(100, 125, z)); y += 10 * sstep(28, 60, Math.abs(x)) * sstep(90, 120, z); return y; };
  { const n = touch ? 90 : 130, g = new THREE.PlaneGeometry(160, 260, n, n); g.rotateX(-Math.PI / 2); g.translate(0, 0, 80); const p = g.attributes.position, col = new Float32Array(p.count * 3), sand = new THREE.Color(MERU ? '#8a7a56' : '#e3cf9a'), mid = new THREE.Color(MERU ? '#4f6a4a' : '#6f8f86'), deep = new THREE.Color(MERU ? '#22302a' : '#2b3b4a'), tc = new THREE.Color();
    for (let i = 0; i < p.count; i++) { const x = p.getX(i), z = p.getZ(i), y = floor(x, z); p.setY(i, y); tc.copy(sand).lerp(mid, sstep(-10, -28, y)).lerp(deep, sstep(-28, -55, y)); const k = 0.05 * Math.sin(x * 1.1) * Math.sin(z * 0.9); col[i * 3] = tc.r + k; col[i * 3 + 1] = tc.g + k; col[i * 3 + 2] = tc.b + k; }
    g.setAttribute('color', new THREE.BufferAttribute(col, 3)); g.computeVertexNormals(); WORLD.add(new THREE.Mesh(g, new THREE.MeshToonMaterial({ vertexColors: true, gradientMap: grad }))); }
  // the surface seen from below + light shafts + the boat + the anchor line
  const surf = new THREE.Mesh(new THREE.PlaneGeometry(600, 600), new THREE.MeshBasicMaterial({ color: MERU ? 0xb4ecc8 : 0x9fe6f2, transparent: true, opacity: 0.55, side: THREE.DoubleSide, depthWrite: false, fog: false })); surf.rotation.x = -Math.PI / 2; scene.add(surf);
  const shafts = []; for (let i = 0; i < (touch ? 8 : 14); i++) { const s = new THREE.Mesh(new THREE.PlaneGeometry(2.4, 24), new THREE.MeshBasicMaterial({ map: glowTex, color: 0xdff6ff, transparent: true, opacity: 0.12, depthWrite: false, side: THREE.DoubleSide, blending: THREE.AdditiveBlending })); s.position.set(rr(-30, 30), -11, rr(-10, 60)); s.rotation.z = 0.2; scene.add(s); shafts.push(s); }
  const boat = new THREE.Group(); boat.position.set(0, 0, 0); scene.add(boat); if (MERU) { for (let k = -3; k <= 3; k++) M(new THREE.CylinderGeometry(0.42, 0.42, 6.4, 10), toon(k % 2 ? '#8a6a48' : '#a07a52'), k * 0.86, 0.1, 0, boat, 0.03).rotation.x = Math.PI / 2; for (const z of [-2.4, 2.4]) M(new THREE.BoxGeometry(6.4, 0.2, 0.5), toon('#5c4430'), 0, 0.55, z, boat, 0.02); M(new THREE.CylinderGeometry(0.06, 0.06, 2.6, 6), toon('#201e1d'), 2.4, 1.6, -2.2, boat, 0.01); M(new THREE.BoxGeometry(1.2, 0.7, 0.04), red, 3.0, 2.5, -2.2, boat, 0.01); } else { M(new THREE.BoxGeometry(3, 1.2, 7), white, 0, 0.1, 0, boat, 0.05); M(new THREE.BoxGeometry(3.1, 0.25, 7.1), red, 0, 0.75, 0, boat, 0.03); M(new THREE.BoxGeometry(2, 1.4, 2), toon('#38bdf8'), 0, 1.4, -1.5, boat, 0.04); M(new THREE.ConeGeometry(1.5, 2.2, 4), white, 0, 0.1, 4.4, boat, 0.04).rotation.x = Math.PI / 2; }
  M(new THREE.CylinderGeometry(0.05, 0.05, 9.5, 5), toon('#e6b45a'), 0, -4.8, 2.5, null, 0); M(new THREE.TorusGeometry(0.5, 0.12, 6, 12), steel, 0, -9.6, 2.5, null, 0.02);
  const boatRing = new THREE.Mesh(new THREE.RingGeometry(4.6, 5.2, 32), new THREE.MeshBasicMaterial({ color: 0xffd23a, transparent: true, opacity: 0.6, side: THREE.DoubleSide, depthWrite: false })); boatRing.rotation.x = -Math.PI / 2; boatRing.position.y = -0.3; scene.add(boatRing);
  const jib = MERU ? kit.makeFox({ key: 'pearlDiver', torso: ['#f3f2f2', '#2e4a6b', '#16263c'], outfit: 'vest', look: { ...PLAYER_MALE, fur: '#c9b48a', furDark: '#7a5c38' }, mood: 'neutral' }) : kit.makeFox({ key: 'jib', torso: ['#fff4e2', '#38bdf8', '#1e6f9a'], outfit: 'vest', look: { ...PLAYER_MALE, fur: '#e8b277', furDark: '#8a5a2b', tailMid: '#f3e2c4', tailTip: '#ffffff', armorAccent: '#38bdf8' }, mood: 'neutral' }); jib.scale.setScalar(1.3); jib.position.set(0, 0.85, 1.4); boat.add(jib);
  depthSign(TX('REEF · 1'), -8, -6, 24, '#f3f2f2'); depthSign(TX('TWILIGHT · 3'), 10, -18, 72, '#ffd23a'); depthSign(TX('ABYSS · 10'), -6, -36, 122, '#ec3013');

  // ---------- DECOR: coral on the shelf, kelp, rock arches, marine snow, fish ----------
  const cc = MERU ? ['#5c9a43', '#3f8f3a', '#7a8a3a', '#a8b85a', '#2f6f3a', '#c9b48a'] : ['#f472b6', '#ffd23a', '#ec3013', '#a78bfa', '#5ec97e', '#fb923c'];
  for (let i = 0; i < (touch ? 50 : 90); i++) { const x = rr(-45, 45), z = rr(-15, 55), y = floor(x, z), c = toon(pick(cc)); if (Math.random() < 0.5) M(new THREE.ConeGeometry(rr(0.25, 0.5), rr(0.8, 1.8), 6), c, x, y + 0.5, z, null, 0.03); else M(new THREE.SphereGeometry(rr(0.4, 0.8), 8, 6), c, x, y + 0.2, z, null, 0.03).scale.y = 0.6; }
  const rocks = [];   // solid spheres you bump off
  const rock = (x, z, r, yo = 0) => { const y = floor(x, z) + r * 0.4 + yo, m = M(new THREE.DodecahedronGeometry(r, 0), toon(pick(['#5f6b73', '#4f5a62', '#6b7680'])), x, y, z, null, 0.06); m.rotation.set(rr(0, 3), rr(0, 3), 0); rocks.push({ x, y, z, r: r * 0.92 }); };
  for (let i = 0; i < 26; i++) rock(rr(-40, 40), rr(10, 160), rr(1.4, 3.2));
  // rock arches (swim through): two pillars + a lintel
  for (const [x, z] of [[-6, 40], [8, 92], [-10, 140]]) { const y0 = floor(x, z); for (const s of [-1, 1]) { for (let k = 0; k < 3; k++) { const r = 1.5 - k * 0.15, px = x + s * 3.6, py = y0 + 1 + k * 2.4; M(new THREE.DodecahedronGeometry(r, 0), toon('#55606a'), px, py, z, null, 0.05); rocks.push({ x: px, y: py, z, r }); } } for (let k = -2; k <= 2; k++) { const px = x + k * 1.8, py = y0 + 8 - Math.abs(k) * 0.4; M(new THREE.DodecahedronGeometry(1.4, 0), toon('#55606a'), px, py, z, null, 0.05); rocks.push({ x: px, y: py, z, r: 1.3 }); } }
  const kelpZ = [{ x: 22, z: 30, r: 9 }, { x: -24, z: 64, r: 8 }]; const kelpM = [];
  for (const k of kelpZ) for (let i = 0; i < (touch ? 24 : 40); i++) { const a = rr(0, 6.28), r = rr(0, k.r), x = k.x + Math.cos(a) * r, z = k.z + Math.sin(a) * r, y = floor(x, z), h = rr(5, 10), s = M(new THREE.CylinderGeometry(0.06, 0.16, h, 4), toon(pick(['#3f8f3a', '#2f6f3a', '#5c9a43'])), x, y + h / 2, z, null, 0); s.userData.ph = rr(0, 6); kelpM.push(s); }
  const snowN = touch ? 500 : 900, snowG = new THREE.BufferGeometry(), snowP = new Float32Array(snowN * 3); for (let i = 0; i < snowN; i++) { snowP[i * 3] = rr(-25, 25); snowP[i * 3 + 1] = rr(-25, 25); snowP[i * 3 + 2] = rr(-25, 25); } snowG.setAttribute('position', new THREE.BufferAttribute(snowP, 3)); const snow = new THREE.Points(snowG, new THREE.PointsMaterial({ color: 0xdff6ff, size: 0.08, transparent: true, opacity: 0.6, depthWrite: false })); scene.add(snow);
  const fishes = [], dm = new THREE.Object3D();
  function fishSchool(cx, cy, cz, n, col, r = 5) { const im = new THREE.InstancedMesh(new THREE.ConeGeometry(0.14, 0.5, 5), toon(col), n); im.frustumCulled = false; WORLD.add(im); fishes.push({ im, cx, cy, cz, n, r, ph: Array.from({ length: n }, () => [rr(0, 6.28), rr(0.6, 1), rr(-0.8, 0.8)]), scare: 0 }); }
  [[-10, -5, 18, '#ffd23a'], [14, -6, 36, '#38bdf8'], [-4, -16, 70, '#fb923c'], [12, -22, 100, '#a78bfa']].forEach(([x, y, z, c]) => fishSchool(x, y, z, touch ? 14 : 22, c));

  // ---------- OBSTACLES: urchins, sea mines, currents ----------
  const urchins = []; for (const [x, z] of [[-14, 30], [16, 50], [-4, 78], [20, 110], [-18, 104]]) for (let i = 0; i < 6; i++) { const ux = x + rr(-3, 3), uz = z + rr(-3, 3), uy = floor(ux, uz) + 0.4, g = new THREE.Group(); g.position.set(ux, uy, uz); WORLD.add(g); M(new THREE.SphereGeometry(0.4, 8, 6), toon('#2b1d3a'), 0, 0, 0, g, 0.03); for (let k = 0; k < 10; k++) { const sp = M(new THREE.ConeGeometry(0.05, 0.7, 4), toon('#4a2f63'), 0, 0, 0, g, 0); sp.position.set(0, 0, 0); sp.lookAt(rr(-1, 1), rr(-0.2, 1), rr(-1, 1)); sp.rotateX(Math.PI / 2); sp.translateY(0.4); } urchins.push({ x: ux, y: uy, z: uz }); }
  const mines = []; for (const [x, z, h] of [[-8, 66, 7], [6, 80, 9], [-14, 96, 8], [14, 124, 12], [0, 150, 14]]) { const y0 = floor(x, z), g = new THREE.Group(); g.position.set(x, y0 + h, z); WORLD.add(g); M(new THREE.SphereGeometry(0.9, 12, 10), toon('#3a3f44'), 0, 0, 0, g, 0.05); for (let k = 0; k < 8; k++) { const a = k / 8 * 6.28, s = M(new THREE.CylinderGeometry(0.08, 0.12, 0.5, 5), steel, Math.cos(a) * 0.9, (k % 2 ? 0.3 : -0.3), Math.sin(a) * 0.9, g, 0); s.lookAt(0, 0, 0); s.rotateX(Math.PI / 2); } const lamp = new THREE.Sprite(new THREE.SpriteMaterial({ map: glowTex, color: 0xff3a20, transparent: true, depthWrite: false })); lamp.scale.setScalar(1.2); lamp.position.y = 1; g.add(lamp); M(new THREE.CylinderGeometry(0.04, 0.04, h, 4), steel, x, y0 + h / 2, z, null, 0); mines.push({ g, lamp, x, y: y0 + h, z, st: 'idle', t: 0, gone: false }); }
  const currents = [{ x0: -40, x1: 40, z0: 84, z1: 90, y0: -40, y1: -12, vx: 5, vz: 0 }, { x0: -40, x1: 40, z0: 132, z1: 138, y0: -60, y1: -30, vx: -6, vz: 0 }];
  const streaks = []; for (const c of currents) for (let i = 0; i < (touch ? 18 : 30); i++) { const s = new THREE.Mesh(new THREE.PlaneGeometry(2.6, 0.06), new THREE.MeshBasicMaterial({ color: 0xdff6ff, transparent: true, opacity: 0.4, depthWrite: false, side: THREE.DoubleSide })); s.position.set(rr(c.x0, c.x1), rr(c.y0, c.y1), rr(c.z0, c.z1)); scene.add(s); streaks.push({ s, c }); }

  // ---------- CLAMS + PEARLS + BUBBLE VENTS ----------
  const PEARL = { 1: ['#ffffff', '#bfefff'], 3: ['#ffd23a', '#ffe9a0'], 10: ['#2b2a33', '#c7a6ff'], 25: ['#ff7ab8', '#ffc2e0'] };
  const pname = v => (v === 25 ? 'GIANT' : v === 10 ? 'BLACK' : v === 3 ? 'GOLD' : 'WHITE') + (MERU ? ' HULL' : '');
  const crackURLs = ['']; { const cv = document.createElement('canvas'); cv.width = 800; cv.height = 800; const g = cv.getContext('2d'); g.lineCap = 'round'; for (const [hx, hy] of [[130, 170], [680, 590], [190, 670]]) { for (let k = 0; k < 9; k++) { let x = hx, y = hy, a = k / 9 * 6.28 + rr(-0.2, 0.2); g.beginPath(); g.moveTo(x, y); const L = rr(90, 240); for (let q = 0; q < L; q += 18) { a += rr(-0.4, 0.4); x += Math.cos(a) * 18; y += Math.sin(a) * 18; g.lineTo(x, y); } g.strokeStyle = 'rgba(255,255,255,0.85)'; g.lineWidth = 2.4; g.stroke(); g.strokeStyle = 'rgba(20,30,40,0.4)'; g.lineWidth = 0.9; g.stroke(); } g.strokeStyle = 'rgba(255,255,255,0.7)'; g.lineWidth = 1.6; for (let r = 14; r < 60; r += 18) { g.beginPath(); g.arc(hx, hy, r + rr(-4, 4), 0, 6.28); g.stroke(); } crackURLs.push(cv.toDataURL('image/png')); } }
  const clams = [];
  function addClam(x, z, v) { const y = floor(x, z) + 0.2, g = new THREE.Group(); g.position.set(x, y, z); g.rotation.y = rr(0, 6); WORLD.add(g); const s = v === 25 ? 2.6 : v === 10 ? 1.4 : v === 3 ? 1.15 : 0.9, sh = toon(v === 25 ? '#8a3a6a' : v === 10 ? '#5b4b7a' : '#c9b8e8'); M(new THREE.SphereGeometry(0.6 * s, 12, 6, 0, 6.3, 0, 1.5), sh, 0, 0, 0, g, 0.03).scale.set(1, 0.35, 0.8); const lid = new THREE.Group(); lid.position.z = -0.42 * s; g.add(lid); M(new THREE.SphereGeometry(0.6 * s, 12, 6, 0, 6.3, 0, 1.5), sh, 0, 0, 0.42 * s, lid, 0.03).scale.set(1, 0.35, 0.8); const pearl = M(new THREE.SphereGeometry(0.2 * s, 10, 8), new THREE.MeshToonMaterial({ color: PEARL[v][0], gradientMap: grad, emissive: new THREE.Color(PEARL[v][1]), emissiveIntensity: 0.6 }), 0, 0.14 * s, 0, g, 0.015); const glow = new THREE.Sprite(new THREE.SpriteMaterial({ map: glowTex, color: PEARL[v][1], transparent: true, depthWrite: false, opacity: 0.7, fog: false })); glow.scale.setScalar(2 * s); glow.position.y = 0.3; g.add(glow); const c = { x, y, z, v, g, lid, pearl, glow, ph: rr(0, 4), taken: false, open: false, giant: v === 25, openT: 0 }; clams.push(c); return c; }
  for (let i = 0; i < 9; i++) addClam(rr(-34, 34), rr(4, 52), 1);
  for (let i = 0; i < 7; i++) addClam(rr(-30, 30), rr(64, 104), 3);
  for (const [x, z] of [[-8, 132], [10, 146], [-14, 160], [4, 170], [16, 128]]) addClam(x, z, 10);
  const giant = addClam(0, 178, DIVE.GIANT);
  const vents = [[12, 20], [-16, 74], [6, 108], [-4, 150]].map(([x, z]) => ({ x, z, y: floor(x, z) }));
  for (const v of vents) { M(new THREE.ConeGeometry(1.2, 1.4, 7), toon('#4f5a62'), v.x, v.y + 0.5, v.z, null, 0.04); const col = new THREE.Mesh(new THREE.CylinderGeometry(1.1, 1.1, -v.y, 10, 1, true), new THREE.MeshBasicMaterial({ color: 0xdff6ff, transparent: true, opacity: 0.08, depthWrite: false, side: THREE.DoubleSide })); col.position.set(v.x, v.y / 2, v.z); scene.add(col); }

  // ---------- CREATURES ----------
  const ents = [];
  function jelly(x, y, z) { const g = new THREE.Group(); g.add(new THREE.Mesh(new THREE.SphereGeometry(0.55, 12, 8, 0, 6.3, 0, 1.6), new THREE.MeshToonMaterial({ color: pick(['#f472b6', '#a78bfa', '#7dd3fc']), gradientMap: grad, transparent: true, opacity: 0.8, emissive: new THREE.Color('#5a2a6a'), emissiveIntensity: 0.4 }))); for (let k = 0; k < 6; k++) { const t = new THREE.Mesh(new THREE.CylinderGeometry(0.03, 0.02, 1.3, 4), toon('#f9b4d4')); t.position.set(Math.cos(k * 1.05) * 0.28, -0.65, Math.sin(k * 1.05) * 0.28); g.add(t); } WORLD.add(g); ents.push({ kind: 'jelly', g, x, y, z, hx: x, hy: y, hz: z, ph: rr(0, 6), stun: 0, r: 1.2 }); }
  function eel(c) { const g = new THREE.Group(); const hole = M(new THREE.TorusGeometry(0.55, 0.22, 6, 12), toon('#3a3f44'), 0, 0, 0, g, 0.02); hole.rotation.x = Math.PI / 2; const body = new THREE.Group(); g.add(body); for (let k = 0; k < 6; k++) M(new THREE.SphereGeometry(0.28 - k * 0.02, 8, 6), toon('#6b7a3a'), 0, 0, -k * 0.38, body, 0.02); const jaw = M(new THREE.BoxGeometry(0.3, 0.08, 0.35), toon('#e8d8b0'), 0, -0.12, 0.25, body, 0); for (const s of [-1, 1]) M(new THREE.SphereGeometry(0.05, 6, 4), yel, s * 0.12, 0.12, 0.12, body, 0); const x = c.x + rr(-2.4, 2.4), z = c.z + rr(1.5, 2.6), y = floor(x, z) + 0.3; g.position.set(x, y, z); WORLD.add(g); const e = { kind: 'eel', g, body, jaw, x, y, z, st: 'in', t: 0, cd: 0, stun: 0, out: 0, r: 1 }; e.bang = mkBang(g, 1.6); ents.push(e); }
  function puffer(x, y, z) { const g = new THREE.Group(); const b = M(new THREE.SphereGeometry(0.45, 12, 10), toon('#e8c25a'), 0, 0, 0, g, 0.03); const sp = new THREE.Group(); g.add(sp); for (let k = 0; k < 16; k++) { const s = M(new THREE.ConeGeometry(0.05, 0.3, 4), toon('#a8792e'), 0, 0, 0, sp, 0); s.lookAt(rr(-1, 1), rr(-1, 1), rr(-1, 1)); s.rotateX(Math.PI / 2); s.translateY(0.45); } for (const s of [-1, 1]) M(new THREE.SphereGeometry(0.07, 6, 4), ink, s * 0.18, 0.12, 0.36, g, 0); WORLD.add(g); ents.push({ kind: 'puffer', g, body: b, sp, x, y, z, hx: x, hy: y, hz: z, ph: rr(0, 6), puff: 0, stun: 0, r: 1 }); }
  function octopus(x, z) { const g = new THREE.Group(), c = toon('#c2410c'); M(new THREE.SphereGeometry(0.8, 12, 10), c, 0, 0.5, 0, g, 0.04).scale.set(1, 1.2, 1); const arms = []; for (let k = 0; k < 8; k++) { const a = new THREE.Group(); a.rotation.y = k / 8 * 6.28; g.add(a); M(new THREE.CylinderGeometry(0.12, 0.04, 1.6, 5), c, 0, -0.3, 0.6, a, 0.02).rotation.x = 1.2; arms.push(a); } for (const s of [-1, 1]) M(new THREE.SphereGeometry(0.13, 8, 6), white, s * 0.3, 0.7, 0.62, g, 0); const y = floor(x, z) + 3; g.position.set(x, y, z); WORLD.add(g); const e = { kind: 'octo', g, arms, x, y, z, hx: x, hy: y, hz: z, st: 'idle', t: 0, cd: 2, stun: 0, r: 1.4 }; e.bang = mkBang(g, 2); ents.push(e); }
  function shark(x, y, z) { if (MERU) return nellyDive(x, y, z); const g = new THREE.Group(), gr = toon('#5f707c'); const bd = M(new THREE.CapsuleGeometry(0.8, 3.2, 6, 12), gr, 0, 0, 0, g, 0.05); bd.rotation.x = Math.PI / 2; M(new THREE.CapsuleGeometry(0.68, 2.6, 6, 12), white, 0, -0.25, 0.15, g, 0).rotation.x = Math.PI / 2; const fin = M(new THREE.ConeGeometry(0.7, 1.7, 4), gr, 0, 1.2, -0.2, g, 0.04); fin.scale.set(0.25, 1, 1); fin.rotation.x = -0.3; M(new THREE.ConeGeometry(0.7, 1.4, 4), gr, 0, 0.3, -2.7, g, 0.04).rotation.x = -Math.PI / 2 + 0.3; for (const s of [-1, 1]) M(new THREE.SphereGeometry(0.11, 8, 6), ink, s * 0.5, 0.25, 1.8, g, 0); WORLD.add(g); const e = { kind: 'shark', g, x, y, z, hx: x, hy: y, hz: z, a: 0, st: 'idle', t: 0, cd: 3, stun: 0, yaw: 0, r: 2 }; e.bang = mkBang(g, 2.4); ents.push(e); }
  function nellyDive(x, y, z) { const g = new THREE.Group(), sk = toon('#3f8a6a'), bl = toon('#bfe0a8'), sp = toon('#e0a84a');
    for (let k = 0; k < 5; k++) { const r = 1.1 - k * 0.17, b = M(new THREE.SphereGeometry(r, 14, 10), sk, 0, Math.sin(k) * 0.15, -k * 1.3, g, 0.05); b.scale.set(1, 0.85, 1.25); M(new THREE.SphereGeometry(r * 0.8, 12, 8), bl, 0, -r * 0.32, -k * 1.3 + 0.1, g, 0).scale.set(0.9, 0.5, 1.1); M(new THREE.ConeGeometry(0.22, 0.6, 5), sp, 0, r * 0.85, -k * 1.3, g, 0.02); }
    const head = M(new THREE.SphereGeometry(0.85, 14, 10), sk, 0, 0.35, 1.5, g, 0.05); head.scale.set(1, 0.85, 1.3); M(new THREE.BoxGeometry(1.1, 0.25, 0.9), toon('#7a2236'), 0, 0.05, 2.3, g, 0.02); for (const s of [-1, 1]) { M(new THREE.SphereGeometry(0.2, 10, 8), white, s * 0.42, 0.8, 1.95, g, 0.02); M(new THREE.SphereGeometry(0.09, 8, 6), ink, s * 0.44, 0.82, 2.13, g, 0); M(new THREE.ConeGeometry(0.4, 0.9, 4), sk, s * 1.0, -0.2, 0.6, g, 0.03).rotation.z = s * 1.2; }
    g.scale.setScalar(1.3); WORLD.add(g); const e = { kind: 'shark', g, x, y, z, hx: x, hy: y, hz: z, a: 0, st: 'idle', t: 0, cd: 3, stun: 0, yaw: 0, r: 2.6 }; e.bang = mkBang(g, 2.4); ents.push(e); }
  function angler(x, z) { const g = new THREE.Group(), c = toon('#2b2a33'); M(new THREE.SphereGeometry(0.9, 12, 10), c, 0, 0, 0, g, 0.05).scale.set(1, 0.85, 1.1); const jaw = M(new THREE.BoxGeometry(1.2, 0.25, 0.8), toon('#3a1a20'), 0, -0.35, 0.7, g, 0); for (let k = 0; k < 5; k++) M(new THREE.ConeGeometry(0.06, 0.25, 4), white, -0.4 + k * 0.2, -0.2, 1.05, g, 0).rotation.x = Math.PI; M(new THREE.CylinderGeometry(0.03, 0.03, 1.4, 4), c, 0, 0.9, 0.6, g, 0).rotation.x = 0.7; const lure = new THREE.Sprite(new THREE.SpriteMaterial({ map: glowTex, color: 0xc7a6ff, transparent: true, depthWrite: false, fog: false })); lure.scale.setScalar(2.2); lure.position.set(0, 1.45, 1.15); g.add(lure); M(new THREE.SphereGeometry(0.15, 8, 6), new THREE.MeshBasicMaterial({ color: 0xe9dcff }), 0, 1.45, 1.15, g, 0); const y = floor(x, z) + 2.5; g.position.set(x, y, z); WORLD.add(g); const e = { kind: 'angler', g, jaw, x, y, z, hx: x, hy: y, hz: z, st: 'idle', t: 0, cd: 0, stun: 0, yaw: 0, r: 1.4 }; e.bang = mkBang(g, 2.4); ents.push(e); }
  for (let i = 0; i < 12; i++) { const z = rr(10, 160), x = rr(-30, 30); jelly(x, rr(floor(x, z) + 3, -3), z); }
  clams.filter(c => c.v >= 3).forEach((c, i) => { if (i % 2 === 0) eel(c); });
  for (let i = 0; i < 6; i++) { const z = rr(20, 120), x = rr(-30, 30); puffer(x, rr(floor(x, z) + 2, -4), z); }
  octopus(-12, 88); octopus(14, 100); shark(0, -20, 90); angler(-6, 138); angler(12, 158); angler(-7, 172);

  // ---------- THE DIVER (cast fox in scuba kit) ----------
  const ben = SK.make(cast.make('player', { gear: 'none' }), { trunks: '#201e1d' }); scene.add(ben.root); ben.ring.visible = false;
  // FISHBOWL HELMET on the head + twin tanks strapped to the back (both ride the fox's own rig, so they follow the swim pose)
  { const P = ben.P, brass = toon('#d9a64a');
    if (P && P.head) { const hb = new THREE.Group(); hb.position.set(0, 0.08, 0.1); P.head.add(hb);
      const glass = new THREE.Mesh(new THREE.SphereGeometry(0.8, 24, 18), new THREE.MeshToonMaterial({ color: '#d8f4ff', gradientMap: grad, transparent: true, opacity: 0.28, depthWrite: false })); glass.renderOrder = 3; hb.add(glass);
      const rim = new THREE.Mesh(new THREE.SphereGeometry(0.81, 24, 18), new THREE.MeshBasicMaterial({ color: 0xffffff, transparent: true, opacity: 0.18, side: THREE.BackSide, depthWrite: false })); hb.add(rim);
      const shine = new THREE.Mesh(new THREE.SphereGeometry(0.16, 10, 8), new THREE.MeshBasicMaterial({ color: 0xffffff, transparent: true, opacity: 0.75 })); shine.scale.set(1, 0.55, 0.3); shine.position.set(-0.36, 0.42, 0.55); hb.add(shine);
      M(new THREE.TorusGeometry(0.62, 0.1, 8, 24), brass, 0, -0.66, 0, hb, 0.03, 0.72).rotation.x = Math.PI / 2;
      for (let k = 0; k < 6; k++) { const a = k / 6 * 6.28; M(new THREE.SphereGeometry(0.06, 6, 4), brass, Math.cos(a) * 0.62, -0.58, Math.sin(a) * 0.62, hb, 0); }
      const valve = M(new THREE.CylinderGeometry(0.09, 0.09, 0.22, 8), brass, 0, -0.5, -0.72, hb, 0.02); valve.rotation.x = Math.PI / 2; }
    if (P && P.body) { const tb = new THREE.Group(); tb.position.set(0, 1.02, -0.42); P.body.add(tb);
      for (const sx of [-0.18, 0.18]) { M(new THREE.CylinderGeometry(0.16, 0.16, 0.85, 12), yel, sx, 0, 0, tb, 0.025); M(new THREE.SphereGeometry(0.16, 12, 8, 0, 6.3, 0, 1.6), yel, sx, 0.42, 0, tb, 0); M(new THREE.CylinderGeometry(0.05, 0.05, 0.12, 6), steel, sx, 0.55, 0, tb, 0); }
      M(new THREE.BoxGeometry(0.5, 0.08, 0.36), ink, 0, 0.18, 0.02, tb, 0); M(new THREE.BoxGeometry(0.5, 0.08, 0.36), ink, 0, -0.22, 0.02, tb, 0);
      const hose = new THREE.Mesh(new THREE.TorusGeometry(0.32, 0.045, 6, 14, Math.PI * 1.1), ink); hose.position.set(0, 0.78, 0.1); hose.rotation.set(0, Math.PI / 2, 0.2); tb.add(hose);
      tb.userData.bubbleAt = true; ben.tankG = tb; } }
  const lamp = new THREE.SpotLight(0xfff4d6, 0, 26, 0.55, 0.5, 1.2); lamp.position.set(0, 0.3, 0.5); ben.root.add(lamp); const lampT = new THREE.Object3D(); lampT.position.set(0, -0.6, 8); ben.root.add(lampT); lamp.target = lampT;
  const flashS = new THREE.Sprite(new THREE.SpriteMaterial({ map: glowTex, color: 0xffffff, transparent: true, depthWrite: false, opacity: 0, fog: false })); flashS.scale.setScalar(1); ben.root.add(flashS);

  // ---------- STATE ----------
  const G = { phase: 'ready', board: true, place: 'deep', t: 0, pen: 0, pts: 0, carry: 0, carryN: 0, banked: 0, hits: 0, o2: DIVE.O2, ty: -0.6, flashCd: 0, ink: 0, held: 0, banner: '', bannerT: 0, radio: '', radioWho: 'JIB', radioT: 0, flash: null, flashT: 0, flashId: 0, done: null, count: 0, prompt: null, blackouts: 0, best: 0 };
  const say = (s, t = 2.4) => { s = TX(s); G.banner = s; G.bannerT = t; };
  const radio = (s, who = 'JIB', t = 6) => { if (MERU) return; G.radio = s; G.radioWho = who; G.radioT = t; };
  const flash = (txt, col = '#ffd23a') => { txt = TX(txt); G.flash = { txt, col, id: ++G.flashId }; G.flashT = 1.6; };
  const award = (name, v, col) => { G.pts += v; flash(name + '  +' + v, col); audio.tone(880 + Math.min(900, v), 0.12, 0.04, 'triangle', 1.4); return v; };
  const hurt = (n, why) => { if (ben.inv > 0) return false; G.o2 = Math.max(0, G.o2 - n); ben.inv = 1.0; ben.spin += rr(-3, 3); G.hits++; G.cracks = Math.min(3, (G.cracks || 0) + 1); if (!(G.blood > 0)) setTimeout(() => radio('You are bleeding. The shark can smell that. Move.', 'JIB', 4), 900); G.blood = 6; flash(why + ' · O2 -' + n, '#ec3013'); audio.tone(1500, 0.3, 0.05, 'sawtooth', 0.4); bubbles(V3(ben.x, ben.y + 0.4, ben.z), 12); return true; };
  const zone = y => TX(y > -14 ? 'REEF' : y > -32 ? 'TWILIGHT' : 'ABYSS');
  let TT = 0;

  function reset() { Object.assign(ben, { x: 0, z: 6, y: -0.6, vx: 0, vz: 0, yaw: 0, spin: 0, inv: 0 }); Object.assign(G, { t: 0, pen: 0, pts: 0, carry: 0, carryN: 0, banked: 0, hits: 0, o2: DIVE.O2, ty: -0.6, ink: 0, held: 0, done: null, blackouts: 0, tok: 0, coins: 0, cracks: 0, blood: 0 }); for (const c of clams) { c.taken = false; c.openT = 0; c.pearl.visible = c.glow.visible = true; } for (const m of mines) { m.gone = false; m.st = 'idle'; m.g.visible = true; } for (const it of items) { it.on = true; it.g.visible = true; } cam.cut = true; }
  function rollOut() { audioOn(); reset(); G.board = false; G.phase = 'count'; G.count = 3.2; PAUSE = false; say('THE DEEP', 3); radio('Tap 2 to go down, 3 to come up. Pearls get better the deeper you go, and the tank does not. Bring them back to the boat to bank them. Nothing to grab? 1 flashes your lamp.', 'JIB', 9); emit(); }
  function bank() { if (!G.carry) return; const v = G.carry; G.banked += v; award('BANKED ' + v, v * 50, '#5ec97e'); G.carry = 0; G.carryN = 0; if (G.cracks) { G.cracks = 0; flash('BANKED ' + v + ' · JIB PATCHED YOUR GLASS', '#5ec97e'); } if (G.banked >= DIVE.GOAL) finish(); else say('BANKED ' + G.banked + ' / ' + DIVE.GOAL, 2.4); }
  function blackout() { G.blackouts++; G.pen += 20; const lost = G.carry; G.carry = 0; G.carryN = 0; ben.x = 0; ben.z = 6; ben.y = -0.6; G.ty = -0.6; ben.vx = ben.vz = 0; G.o2 = DIVE.O2; cam.cut = true; flash('TANK EMPTY · JIB HAULED YOU UP · +20 S', '#ec3013'); radio(lost ? 'Up you come. The ' + lost + ' you were carrying went back to the sea. Watch the tank.' : 'Up you come. Watch the tank, and use the bubble vents.', 'JIB', 7); }
  function finish() { const pd = PLACES[0], t = G.t + G.pen, tb = Math.max(0, Math.round((pd.target - t) * 15)), total = Math.round(G.pts + tb); let nb = false, best = total; try { nb = save.best(BEST_KEY, total); best = save.stat(BEST_KEY, total); save.setFlag(MERU ? 'meruPondDiver' : 'deepDiver'); if (MERU && save.give) for (let k = 0; k < Math.floor(G.banked / 10); k++) save.give('hullPearl'); save.addGold && save.addGold(Math.round(total / 100)); } catch (e) {}
    const grade = total >= 6000 ? 'S' : total >= 4500 ? 'A' : total >= 3200 ? 'B' : total >= 2000 ? 'C' : 'D';
    G.done = { id: 'deep', name: TX('THE DEEP'), time: t, pen: G.pen, target: pd.target, tok: G.tok, coins: G.coins, pts: Math.round(G.pts), tb, total, grade, newBest: nb, best, gold: Math.round(total / 100), stat: [['Pearl points banked', G.banked + ' / ' + DIVE.GOAL], ['Hits · tank empties', G.hits + ' · ' + G.blackouts]] }; G.phase = 'done'; radio('Forty. That is a proper haul. I will not ask how deep you went.', 'JIB', 8); }

  // ---------- tokens + coins ----------
  const tokTex = canvasTex(128, 128, g => { g.fillStyle = '#e6b45a'; g.beginPath(); g.arc(64, 64, 62, 0, 7); g.fill(); g.lineWidth = 8; g.strokeStyle = '#a8792e'; g.stroke(); g.fillStyle = '#201e1d'; g.font = '900 78px Archivo, sans-serif'; g.textAlign = 'center'; g.textBaseline = 'middle'; g.fillText('8', 64, 68); });
  const tokMat = new THREE.MeshToonMaterial({ map: tokTex, gradientMap: grad, emissive: new THREE.Color('#6a4500'), emissiveIntensity: 0.6 }), tokEdge = toon('#c8922e'), items = [];
  const addItem = (kind, x, y, z) => { const g = new THREE.Group(), c = new THREE.Mesh(kind === 'tok' ? new THREE.CylinderGeometry(0.75, 0.75, 0.18, 20) : new THREE.CylinderGeometry(0.4, 0.4, 0.1, 14), [tokEdge, tokMat, tokMat]); c.rotation.x = Math.PI / 2; if (kind === 'tok') addOutline(c, 0.05); g.add(c); g.position.set(x, y, z); WORLD.add(g); items.push({ kind, g, x, y, z, on: true }); };
  [[-6, -5, 14], [10, -8, 34], [-20, -6, 50], [4, -14, 60], [-10, -20, 86], [16, -24, 104], [0, -38, 130], [-12, -44, 156]].forEach(p => addItem('tok', ...p));
  for (const [x0, y0, z0] of [[-2, -4, 22], [6, -10, 44], [-8, -18, 76], [4, -30, 116], [-4, -42, 146]]) for (let j = 0; j < 6; j++) addItem('coin', x0 + j * 1.2, y0 - Math.sin(j / 5 * Math.PI) * 1.2, z0 + j * 0.8);

  // ---------- CAMERA ----------
  const VIEWS = ['BEHIND', 'HIGH', 'LOW'];
  const cam = { vi: 0, pos: V3(0, 2, -8), look: V3(0, 0, 6), cut: true, yawOff: 0, pitchOff: 0, drag: false, zoom: 1, dir: V3(0, 0, 1), tp: V3(), tl: V3() };
  function camStep(dt) { const port = CHh() > CW() * 1.05, Z = cam.zoom * (port ? 1.35 : 1), tp = cam.tp, tl = cam.tl;
    if (G.phase === 'ready') { const a = TT * 0.08; tp.set(Math.cos(a) * 18, 4, 14 + Math.sin(a) * 18); tl.set(0, -6, 18); }
    else { const sp = Math.hypot(ben.vx, ben.vz), d = cam.dir; if (sp > 0.6) { d.x = damp(d.x, ben.vx / sp, 1.8, dt); d.z = damp(d.z, ben.vz / sp, 1.8, dt); } const dl = Math.hypot(d.x, d.z) || 1, fx = d.x / dl, fz = d.z / dl, v = VIEWS[cam.vi], dist = (v === 'HIGH' ? 9 : v === 'LOW' ? 5 : 7) * Z, hgt = (v === 'HIGH' ? 6 : v === 'LOW' ? 0.4 : 2.6) * Z;
      tp.set(ben.x - fx * dist, ben.y + hgt, ben.z - fz * dist); tl.set(ben.x + fx * 4, ben.y - 0.3, ben.z + fz * 4); }
    if (cam.yawOff || cam.pitchOff) { const dx = tp.x - tl.x, dz = tp.z - tl.z, r = Math.hypot(dx, dz), a = Math.atan2(dx, dz) + cam.yawOff; tp.x = tl.x + Math.sin(a) * r; tp.z = tl.z + Math.cos(a) * r; tp.y += cam.pitchOff * r; }
    if (!cam.drag) { cam.yawOff = damp(cam.yawOff, 0, 3, dt); cam.pitchOff = damp(cam.pitchOff, 0, 3, dt); }
    if (cam.cut) { cam.pos.copy(tp); cam.look.copy(tl); cam.cut = false; } else { cam.pos.lerp(tp, Math.min(1, dt * 4)); cam.look.lerp(tl, Math.min(1, dt * 6)); }
    cam.pos.y = Math.max(cam.pos.y, floor(cam.pos.x, cam.pos.z) + 1); for (const r of rocks) { const dx = cam.pos.x - r.x, dy = cam.pos.y - r.y, dz = cam.pos.z - r.z, d = Math.hypot(dx, dy, dz), mm = r.r + 0.8; if (d < mm && d > 0.01) cam.pos.set(r.x + dx / d * mm, r.y + dy / d * mm, r.z + dz / d * mm); } if (G.phase !== 'ready' && ben.y < -2 && cam.pos.y > -0.4) cam.pos.y = -0.4;
    camera.position.copy(cam.pos); camera.lookAt(cam.look); camera.fov = damp(camera.fov, port ? 66 : 60, 4, dt); camera.updateProjectionMatrix();
    // the light goes as you go down
    const cy = camera.position.y, k = sstep(0, -45, cy), above = cy > 0; const fc = above ? new THREE.Color(0xbfe6f2) : new THREE.Color().setHSL(0.56, 0.7, lerp(0.42, 0.025, Math.pow(k, 0.8)));
    scene.background.copy(fc); scene.fog.color.copy(fc); scene.fog.near = above ? 60 : lerp(4, 1, k); scene.fog.far = above ? 400 : lerp(60, 24, k);
    hemi.intensity = lerp(1.1, 0.25, k); sunL.intensity = lerp(1.6, 0.1, k); lamp.intensity = lerp(0, 60, sstep(-6, -24, ben.y)); surf.position.set(camera.position.x, 0, camera.position.z); surf.visible = true;
    snow.position.copy(camera.position); for (const s of shafts) { s.material.opacity = 0.12 * (1 - k * 2); s.lookAt(camera.position.x, s.position.y, camera.position.z); } }

  // ---------- INPUT ----------
  const keys = new Set(), STK = { x: 0, y: 0 }; let PAUSE = false;
  const kx = () => (keys.has('KeyD') || keys.has('ArrowRight') ? 1 : 0) - (keys.has('KeyA') || keys.has('ArrowLeft') ? 1 : 0), ky = () => (keys.has('KeyW') || keys.has('ArrowUp') ? 1 : 0) - (keys.has('KeyS') || keys.has('ArrowDown') ? 1 : 0);
  const onKD = e => { if (e.target && /INPUT|TEXTAREA/.test(e.target.tagName)) return; if (keys.has(e.code)) return; keys.add(e.code); if (e.code === 'Digit1' || e.code === 'KeyJ') press(1); if (e.code === 'Digit2' || e.code === 'KeyK' || e.code === 'KeyQ') press(2); if (e.code === 'Space' || e.code === 'KeyE') { e.preventDefault(); press(3); } };
  const onKU = e => keys.delete(e.code); addEventListener('keydown', onKD); addEventListener('keyup', onKU);
  const stickWorld = (sx, sy) => { const fx = cam.look.x - cam.pos.x, fz = cam.look.z - cam.pos.z, l = Math.hypot(fx, fz) || 1, ux = fx / l, uz = fz / l; return { x: ux * sy - uz * sx, z: uz * sy + ux * sx }; };
  function interact() { let best = null, bd = 1e9; for (const c of clams) { if (c.taken) continue; const d = Math.hypot(c.x - ben.x, c.y + 0.2 - ben.y, c.z - ben.z) - (c.giant ? 1.8 : 0); if (d < 2.0 && d < bd) { bd = d; best = c; } } if (!best) return null; const v = best.v; if (best.giant && !best.open) return null; if (G.carryN >= DIVE.BAG) return { label: 'BAG FULL · BANK AT THE BOAT', act() { flash('BAG FULL · ' + DIVE.BAG + ' / ' + DIVE.BAG + ' · GO BANK', '#ec3013'); } }; return best.open ? { label: 'GRAB THE ' + pname(v) + ' PEARL · ' + v, act() { best.taken = true; best.pearl.visible = best.glow.visible = false; G.carry += v; G.carryN++; if (best.giant) { say('GIANT PEARL', 3); radio('That is the one my grandad talked about. Get it home before something else wants it.', 'JIB', 6); spray(V3(best.x, best.y + 1, best.z), 24, 3, 1.2, 1.2, 0xffc2e0, -1); } award(pname(v) + ' PEARL · CARRYING ' + G.carry, v * 20, PEARL[v][1]); bubbles(V3(best.x, best.y + 0.5, best.z), 10); audio.tone(1500 + v * 30, 0.25, 0.05, 'triangle', 1.6); } } : { label: 'WAIT · IT IS SHUT', act() { flash('WAIT FOR IT TO OPEN', '#ffffff'); } }; }
  function press(n) { audioOn(); if (G.board || PAUSE || G.phase !== 'run') return;
    if (n === 1) { const it = interact(); if (it) return it.act(); if (G.flashCd > 0) return flash('LAMP RECHARGING', '#8a847e'); G.flashCd = DIVE.FLASH_CD; G.flashFx = 0.5; if (!giant.taken && giant.openT <= 0 && Math.hypot(giant.x - ben.x, giant.y - ben.y, giant.z - ben.z) < DIVE.FLASH_R) { giant.openT = 5; award('THE GIANT CLAM OPENS', 100, '#ffc2e0'); audio.tone(220, 0.9, 0.08, 'sine', 2); } audio.tone(2200, 0.25, 0.05, 'sine', 0.5); let n2 = 0; for (const e of ents) { if (Math.hypot(e.x - ben.x, e.y - ben.y, e.z - ben.z) < DIVE.FLASH_R && e.kind !== 'jelly') { e.stun = 3; e.st = e.kind === 'eel' ? 'hide' : 'idle'; if (e.bang) e.bang.visible = false; n2++; } } if (G.held > 0) { G.held = 0; n2++; } if (n2) award('FLASH · ' + n2 + ' STUNNED', 30 * n2, '#ffffff'); }
    else if (n === 2) { G.ty = Math.max(floor(ben.x, ben.z) + 0.8, G.ty - DIVE.STEP); bubbles(V3(ben.x, ben.y + 0.3, ben.z), 4); }
    else { G.ty = Math.min(-0.6, G.ty + DIVE.STEP); } }
  function useItem(id) { if (G.phase !== 'run') return; if (id === 'energyPod' || id === 'amber') { try { save.take(id); } catch (e) {} G.o2 = DIVE.O2; flash('TANK FULL', '#38bdf8'); return; } flash('SAVE IT FOR THE BOAT', '#ffffff'); }

  // ---------- STEP ----------
  function entStep(e, dt) { const dx = ben.x - e.x, dy = ben.y - e.y, dz = ben.z - e.z, d = Math.hypot(dx, dy, dz), live = G.phase === 'run'; e.stun = Math.max(0, e.stun - dt); if (Math.hypot(dx, dz) > 70) { e.g.visible = false; return; } e.g.visible = true; e.t = (e.t || 0) + dt; e.cd = (e.cd || 0) - dt;
    if (e.kind === 'jelly') { e.x = lerp(e.x, e.hx + Math.cos(TT * 0.3 + e.ph) * 3, dt * 0.4); e.z = lerp(e.z, e.hz + Math.sin(TT * 0.25 + e.ph) * 3, dt * 0.4); const pu = Math.sin(TT * 2.2 + e.ph); e.y = e.hy + pu * 0.4; e.g.scale.set(1 + pu * 0.08, 1 - pu * 0.1, 1 + pu * 0.08); if (live && d < 1.3) hurt(12, 'STUNG'); }
    else if (e.kind === 'puffer') { e.x = e.hx + Math.cos(TT * 0.4 + e.ph) * 2; e.z = e.hz + Math.sin(TT * 0.4 + e.ph) * 2; e.y = e.hy + Math.sin(TT + e.ph) * 0.3; e.puff = damp(e.puff, d < 3 && !e.stun ? 1 : 0, 6, dt); const s = 1 + e.puff * 0.9; e.body.scale.setScalar(s); e.sp.scale.setScalar(0.3 + e.puff * 1.6); if (live && e.puff > 0.6 && d < 1.0 + e.puff * 0.6) hurt(6, 'PUFFERFISH SPIKES'); e.g.rotation.y = Math.atan2(dx, dz); }
    else if (e.kind === 'eel') { const near = Math.hypot(dx, dz) < 3.6 && dy < 3; if (e.st === 'in') { e.out = damp(e.out, 0, 6, dt); if (near && !e.stun && e.cd <= 0) { e.st = 'tell'; e.t = 0; } } else if (e.st === 'tell') { e.bang.visible = true; e.out = damp(e.out, 0.5, 6, dt); if (e.t > 0.5) { e.bang.visible = false; e.st = 'bite'; e.t = 0; } } else if (e.st === 'bite') { e.out = damp(e.out, 1, 14, dt); e.jaw.rotation.x = 0.5; if (live && e.t > 0.15 && d < 2.6 && !e.res) { e.res = true; hurt(15, 'EEL BITE'); } if (e.t > 0.7) { e.st = 'in'; e.cd = 2.5; e.res = false; e.jaw.rotation.x = 0; } } else if (e.st === 'hide') { e.out = damp(e.out, 0, 10, dt); if (e.stun <= 0) e.st = 'in'; }
      e.body.position.set(0, e.out * 1.0, 0); e.body.position.addScaledVector(V3(dx, 0, dz).normalize(), e.out * 1.4); e.body.rotation.y = Math.atan2(dx, dz); e.body.rotation.x = -0.5 * (1 - e.out); }
    else if (e.kind === 'octo') { e.arms.forEach((a, i) => a.rotation.z = Math.sin(TT * 3 + i) * 0.2); if (e.stun) { e.y = damp(e.y, e.hy, 2, dt); } else if (e.st === 'idle') { const m = Math.hypot(e.hx - e.x, e.hz - e.z); if (d < 9) { e.x += dx / d * 2.4 * dt; e.y += dy / d * 2.4 * dt; e.z += dz / d * 2.4 * dt; if (d < 1.8 && live) { e.st = 'grab'; e.t = 0; G.held = 2.2; G.ink = 1.6; flash('THE OCTOPUS HAS YOU · INK!', '#c2410c'); audio.burst(0.5, 300, 0.16); } } else if (m > 1) { e.x = lerp(e.x, e.hx, dt * 0.5); e.z = lerp(e.z, e.hz, dt * 0.5); } } else if (e.st === 'grab') { e.x = lerp(e.x, ben.x, dt * 6); e.y = lerp(e.y, ben.y + 0.6, dt * 6); e.z = lerp(e.z, ben.z, dt * 6); if (G.held <= 0) { e.st = 'idle'; e.stun = 3; e.cd = 3; if (e.t < 2) award('SHOOK THE OCTOPUS OFF', 60, '#ffffff'); } else if (live && (e.t % 0.7) < dt) G.o2 = Math.max(0, G.o2 - 3); } e.g.rotation.y = Math.atan2(dx, dz); }
    else if (e.kind === 'shark') { if (e.stun) { e.y += dt * 0.3; } else if (e.st === 'idle') { e.a += dt * 0.4; const hunt = d < (G.blood > 0 ? 34 : 14), tx = hunt ? ben.x : e.hx + Math.cos(e.a) * 14, ty = hunt ? ben.y : e.hy, tz = hunt ? ben.z : e.hz + Math.sin(e.a) * 14, mx = tx - e.x, my = ty - e.y, mz = tz - e.z, md = Math.hypot(mx, my, mz) || 1, sp = (hunt ? 3.6 : 2.6) * dt; e.x += mx / md * sp; e.y += my / md * sp; e.z += mz / md * sp; e.yaw = Math.atan2(mx, mz); if (hunt && d < 7 && e.cd <= 0) { e.st = 'tell'; e.t = 0; } } else if (e.st === 'tell') { e.bang.visible = true; e.yaw = Math.atan2(dx, dz); if (e.t > 0.9) { e.bang.visible = false; e.st = 'lunge'; e.t = 0; e.l = V3(dx, dy, dz).normalize(); e.res = false; } } else if (e.st === 'lunge') { e.x += e.l.x * 14 * dt; e.y += e.l.y * 14 * dt; e.z += e.l.z * 14 * dt; if (live && d < 2 && !e.res) { e.res = true; hurt(22, 'SHARK BITE'); } if (e.t > 0.7) { e.st = 'idle'; e.cd = 3; } } e.y = Math.max(e.y, floor(e.x, e.z) + 1.5); e.g.rotation.set(0, e.yaw, 0); }
    else if (e.kind === 'angler') { if (e.stun) { e.y = damp(e.y, e.hy, 2, dt); } else if (e.st === 'idle') { e.y = e.hy + Math.sin(TT * 0.8) * 0.3; e.yaw = Math.atan2(dx, dz); if (d < 4.5 && e.cd <= 0) { e.st = 'tell'; e.t = 0; } } else if (e.st === 'tell') { e.bang.visible = true; e.jaw.rotation.x = 0.6; if (e.t > 0.6) { e.bang.visible = false; e.st = 'lunge'; e.t = 0; e.l = V3(dx, dy, dz).normalize(); e.res = false; } } else if (e.st === 'lunge') { e.x += e.l.x * 10 * dt; e.y += e.l.y * 10 * dt; e.z += e.l.z * 10 * dt; if (live && d < 1.8 && !e.res) { e.res = true; hurt(20, 'ANGLERFISH'); } if (e.t > 0.6) { e.st = 'back'; e.t = 0; e.jaw.rotation.x = 0; } } else if (e.st === 'back') { e.x = lerp(e.x, e.hx, dt * 1.5); e.z = lerp(e.z, e.hz, dt * 1.5); if (e.t > 2) { e.st = 'idle'; e.cd = 2; } } e.g.rotation.set(0, e.yaw, 0); }
    e.g.position.set(e.x, e.y, e.z); if (e.stun > 0 && Math.random() < 0.2) bubbles(V3(e.x, e.y + 1, e.z), 1); }
  function step(dt) { TT += dt; demoStep(dt);
    if (G.phase === 'count') { G.count -= dt; if (G.count <= 0) { G.phase = 'run'; say('DIVE!', 1.2); audio.tone(990, 0.3, 0.08, 'square', 1.2); } }
    const live = G.phase === 'run'; if (live) G.t += dt;
    G.blood = Math.max(0, (G.blood || 0) - dt); G.flashCd = Math.max(0, G.flashCd - dt); G.ink = Math.max(0, G.ink - dt); G.held = Math.max(0, G.held - dt); ben.inv = Math.max(0, ben.inv - dt); G.flashFx = Math.max(0, (G.flashFx || 0) - dt);
    // swim: stick = horizontal (camera relative), depth goes to the target set by DOWN / UP
    const sx = live ? STK.x + kx() : 0, sy = live ? STK.y + ky() : 0, w = stickWorld(sx, sy), m = Math.min(1, Math.hypot(sx, sy)), wl = Math.hypot(w.x, w.z) || 1, slow = (G.held > 0 ? 0.25 : 1) * (kelpZ.some(k => Math.hypot(ben.x - k.x, ben.z - k.z) < k.r) ? 0.6 : 1);
    let fx = 0, fz = 0; for (const c of currents) if (ben.x > c.x0 && ben.x < c.x1 && ben.z > c.z0 && ben.z < c.z1 && ben.y > c.y0 && ben.y < c.y1) { fx += c.vx; fz += c.vz; if (!c.warn) { c.warn = true; flash('CURRENT!', '#7dd3fc'); } } else c.warn = false;
    ben.vx += (w.x / wl * m * DIVE.SPEED * slow * DIVE.DRAG - (ben.vx - fx) * DIVE.DRAG) * dt; ben.vz += (w.z / wl * m * DIVE.SPEED * slow * DIVE.DRAG - (ben.vz - fz) * DIVE.DRAG) * dt; ben.x += ben.vx * dt; ben.z += ben.vz * dt;
    if (G.phase === 'count') { ben.x = 0; ben.z = 6; ben.vx = ben.vz = 0; }
    ben.x = clamp(ben.x, -60, 60); ben.z = clamp(ben.z, -20, 185);
    const fl = floor(ben.x, ben.z) + 0.7; G.ty = Math.max(G.ty, fl); ben.y += clamp(G.ty - ben.y, -DIVE.VY * dt, DIVE.VY * dt); ben.y = Math.max(ben.y, fl);
    for (const r of rocks) { const dx = ben.x - r.x, dy = ben.y - r.y, dz = ben.z - r.z, d = Math.hypot(dx, dy, dz), mm = r.r + 0.6; if (d < mm && d > 0.01) { ben.x = r.x + dx / d * mm; ben.y = r.y + dy / d * mm; ben.z = r.z + dz / d * mm; const vn = (ben.vx * dx + ben.vz * dz) / d; if (vn < 0) { ben.vx -= dx / d * vn * 1.3; ben.vz -= dz / d * vn * 1.3; } } }
    const sp = Math.hypot(ben.vx, ben.vz); ben.paddle = m; ben.ph += dt * (m > 0.2 ? 5 : 1.6); if (sp > 0.5) { const want = Math.atan2(ben.vx - fx, ben.vz - fz), dd = Math.atan2(Math.sin(want - ben.yaw), Math.cos(want - ben.yaw)); ben.yaw += clamp(dd, -3.5 * dt, 3.5 * dt); } ben.yaw += ben.spin * dt; ben.spin *= Math.exp(-2 * dt);
    ben.under = ben.y < -0.5; ben.wade = false; ben.diving = true; ben.surfY = 0.5; SK.pose(ben, dt, TT); ben.ring.visible = false; flashS.material.opacity = G.flashFx * 1.6; flashS.scale.setScalar(2 + (0.5 - G.flashFx) * 30);
    // oxygen: drains faster the deeper you are; vents refill; the boat banks + refills
    const atTop = ben.y > -1.2, atBoat = atTop && Math.hypot(ben.x, ben.z - 0.5) < 5.5, inVent = vents.some(v => Math.hypot(ben.x - v.x, ben.z - v.z) < 1.4);
    if (live) { if (atTop) G.o2 = Math.min(DIVE.O2, G.o2 + (atBoat ? DIVE.BOAT : 12) * dt); else if (inVent) { G.o2 = Math.min(DIVE.O2, G.o2 + DIVE.VENT * dt); if (!G.ventT) { G.ventT = 1.5; flash('BUBBLE VENT · TANK FILLING', '#bfefff'); } } else G.o2 = Math.max(0, G.o2 - (DIVE.DRAIN + Math.max(0, -ben.y) * DIVE.DEEP_K) * dt);
      G.ventT = Math.max(0, (G.ventT || 0) - dt); if (atBoat && G.carry) bank(); if (G.o2 <= 0) blackout(); if (G.o2 < 25 && !G.lowWarn) { G.lowWarn = true; radio('Tank is low. Come up, or find a bubble vent.', 'JIB', 4); audio.tone(440, 0.4, 0.06, 'square', 1); } if (G.o2 > 40) G.lowWarn = false; if (G.o2 < 25) { G.hb = (G.hb || 0) - dt; if (G.hb <= 0) { G.hb = 0.35 + G.o2 / 40; audio.tone(70, 0.12, 0.1, 'sine', 0.8); } } }
    for (const v of vents) if (Math.random() < 0.5) bubbles(V3(v.x + rr(-0.6, 0.6), v.y + 1, v.z + rr(-0.6, 0.6)), 1);
    if (ben.under && Math.random() < 0.15) bubbles(V3(ben.x, ben.y + 0.4, ben.z), 1);
    for (const c of clams) { if (c.taken) continue; if (c.giant) { c.openT = Math.max(0, c.openT - dt); c.open = c.openT > 0; } else c.open = ((TT + c.ph) % 4.4) < 2.7; c.lid.rotation.x = damp(c.lid.rotation.x, c.open ? -1 : 0, 8, dt); c.glow.material.opacity = c.open ? 0.55 + 0.3 * Math.sin(TT * 6) : 0.15; }
    for (const e of ents) entStep(e, dt);
    for (const u of urchins) if (live && Math.hypot(ben.x - u.x, ben.y - u.y, ben.z - u.z) < 1.1) hurt(8, 'SEA URCHIN');
    for (const mn of mines) { if (mn.gone) continue; const d = Math.hypot(ben.x - mn.x, ben.y - mn.y, ben.z - mn.z); mn.lamp.material.opacity = mn.st === 'arm' ? (Math.sin(TT * 24) > 0 ? 1 : 0.2) : 0.5 + 0.5 * Math.sin(TT * 3); if (mn.st === 'idle' && d < 4 && live) { mn.st = 'arm'; mn.t = 0; flash('MINE · GET AWAY', '#ec3013'); } if (mn.st === 'arm') { mn.t += dt; if (Math.random() < 0.5 && Math.floor(mn.t * 8) !== Math.floor((mn.t - dt) * 8)) audio.tone(1200, 0.05, 0.04, 'square', 1); if (d > 6) mn.st = 'idle'; else if (mn.t > 1.3) { mn.gone = true; mn.g.visible = false; spray(V3(mn.x, mn.y, mn.z), 30, 6, 2, 1, 0xffd9a0, 1); audio.burst(1.2, 200, 0.3); if (d < 4.5) { hurt(30, 'MINE'); const k = 10 / (d || 1); ben.vx += (ben.x - mn.x) * k; ben.vz += (ben.z - mn.z) * k; } else award('DODGED THE MINE', 80, '#ffffff'); } } }
    for (const s of streaks) { s.s.position.x += s.c.vx * dt * 1.6; if (s.s.position.x > s.c.x1) s.s.position.x = s.c.x0; if (s.s.position.x < s.c.x0) s.s.position.x = s.c.x1; }
    for (const k of kelpM) k.rotation.z = Math.sin(TT * 1.1 + k.userData.ph) * 0.12;
    for (const f of fishes) { for (let i = 0; i < f.n; i++) { const [p0, k, yo] = f.ph[i], a = p0 + TT * 0.6, r = f.r * k; dm.position.set(f.cx + Math.cos(a) * r, f.cy + yo, f.cz + Math.sin(a) * r); dm.rotation.set(0, -a, Math.PI / 2); dm.updateMatrix(); f.im.setMatrixAt(i, dm.matrix); } f.im.instanceMatrix.needsUpdate = true; }
    if (live) for (const it of items) { if (!it.on) continue; it.g.rotation.y += dt * 3; if (Math.hypot(ben.x - it.x, ben.y - it.y, ben.z - it.z) < (it.kind === 'tok' ? 1.8 : 1.4)) { it.on = false; it.g.visible = false; if (it.kind === 'tok') { G.tok++; award('TOKEN ' + G.tok + ' / 8', 60, '#e6b45a'); if (G.tok === 8) setTimeout(() => award('ALL 8 TOKENS', 400, '#e6b45a'), 500); } else { G.coins++; G.pts += 25; audio.tone(1500 + (G.coins % 6) * 120, 0.08, 0.04, 'triangle', 1.3); } } }
    boat.position.y = Math.sin(TT * 1.2) * 0.12; boat.rotation.z = Math.sin(TT * 0.9) * 0.04; kit.animFox(jib, dt, 0, false); boatRing.visible = G.carry > 0; boatRing.material.opacity = 0.4 + 0.3 * Math.sin(TT * 4);
    const it = live ? interact() : null; G.prompt = it ? it.label : null;
    fxStep(dt);
    G.bannerT = Math.max(0, G.bannerT - dt); if (G.bannerT <= 0) G.banner = ''; G.radioT = Math.max(0, G.radioT - dt); if (G.radioT <= 0) G.radio = ''; G.flashT = Math.max(0, G.flashT - dt); if (G.flashT <= 0) G.flash = null;
    camStep(dt); }
  let last = performance.now(), raf = 0, hudT = 0, miniC = null, miniT = 0;
  function frame(now) { raf = requestAnimationFrame(frame); const rdt = Math.min(0.05, (now - last) / 1000); last = now; if (!PAUSE) step(rdt); renderer.render(scene, camera); hudT -= rdt; if (hudT <= 0) { hudT = 0.1; emit(); } miniT -= rdt; if (miniT <= 0 && miniC) { miniT = 0.25; drawMini(); } }
  function onRs() { renderer.setSize(CW(), CHh()); camera.aspect = CW() / CHh(); camera.updateProjectionMatrix(); } addEventListener('resize', onRs); const ro = new ResizeObserver(onRs); ro.observe(container);
  let audioReady = false; function audioOn() { if (audioReady) return; audioReady = true; try { audio.init(); } catch (e) {} }

  // ---------- HUD (same shape as the swim trials so the page is shared) ----------
  const _pv = V3(), fmtT = t => { const m = Math.floor(t / 60), s = t - m * 60; return m + ':' + (s < 10 ? '0' : '') + s.toFixed(1); };
  function nextGoal() { if (G.carry && (G.o2 < 40 || G.carryN >= DIVE.BAG || G.banked + G.carry >= DIVE.GOAL)) return { x: 0, y: 0, z: 0, label: 'BOAT · BANK ' + G.carry }; if (G.o2 < 30) { let b = null, bd = 1e9; for (const v of vents) { const d = Math.hypot(v.x - ben.x, v.z - ben.z); if (d < bd) { bd = d; b = v; } } return { x: b.x, y: b.y + 2, z: b.z, label: 'BUBBLE VENT' }; } let b = null, bd = 1e9; for (const c of clams) if (!c.taken && !c.giant) { const d = Math.hypot(c.x - ben.x, c.y - ben.y, c.z - ben.z) - c.v * 1.5; if (d < bd) { bd = d; b = c; } } return b ? { x: b.x, y: b.y, z: b.z, label: pname(b.v) + ' PEARL' } : { x: 0, y: 0, z: 0, label: 'BOAT' }; }
  function hud() { const pd = PLACES[0], live = G.phase === 'run'; let goal = null; if (live) { const n = nextGoal(), dd = Math.hypot(ben.x - n.x, ben.y - n.y, ben.z - n.z); if (dd > 5) { _pv.set(n.x, n.y + 0.5, n.z).project(camera); goal = { nx: _pv.x, ny: _pv.y, behind: _pv.z > 1, label: TX(n.label), dist: Math.round(dd) }; } }
    let best = 0; try { best = save.stat(BEST_KEY, 0); } catch (e) {}
    return { state: G.phase === 'ready' ? 'ready' : 'run', phase: G.phase, board: G.board, done: G.done, place: 'deep', placeName: TX(pd.name), room: MERU ? 'meruPearlDive' : pd.room, target: pd.target, time: fmtT(G.t + G.pen), over: G.t + G.pen > pd.target,
      breath: Math.round(G.o2), o2: true, under: ben.y < -2, depth: Math.max(0, -ben.y).toFixed(0), zone: zone(ben.y), wade: false, covered: false, tok: G.tok || 0, coins: G.coins || 0, pts: Math.round(G.pts),
      progress: 'BAG ' + G.carryN + '/' + DIVE.BAG + ' · BANKED ' + G.banked + ' / ' + DIVE.GOAL, fog: G.o2 < 35 ? (35 - G.o2) / 35 : 0, cracks: G.cracks || 0, crackURL: crackURLs[G.cracks || 0] || '', gauge: clamp(-ben.y / 60, 0, 1), prompt: TX(G.prompt), ink: G.ink, held: G.held > 0, banner: G.banner, radio: G.radio, radioWho: G.radioWho, flash: G.flash, count: G.phase === 'count' ? Math.ceil(G.count) : null,
      view: VIEWS[cam.vi], goal, bests: [best], kick: G.flashCd > 0 ? 1 - G.flashCd / DIVE.FLASH_CD : 1, kickName: 'LAMP', quest: TX(pd.goal) + (live ? ' · banked ' + G.banked : ''), demo: DM.on ? { cap: TX(DM.cap), key: (DEMO[DM.i] || {}).key || '', n: DM.i + 1, of: DEMO.length } : null }; }
  function emit() { onState({ course: hud() }); }
  function drawMini() { const c = miniC; if (!c.isConnected) { miniC = null; return; } const dpr = Math.min(2, devicePixelRatio || 1), w = Math.round(c.clientWidth * dpr), h = Math.round(c.clientHeight * dpr); if (!w || !h) return; if (c.width !== w) c.width = w; if (c.height !== h) c.height = h;
    const x = c.getContext('2d'), k = Math.min(w / 140, h / 220), X = px => w / 2 - px * k, Y = pz => h - 10 - (pz + 20) * k; x.fillStyle = '#0c3a52'; x.fillRect(0, 0, w, h); [['#2a9fc0', -20, 30], ['#145a7a', 30, 100], ['#062a3e', 100, 190]].forEach(([cl, a, b]) => { x.fillStyle = cl; x.fillRect(0, Y(b), w, (b - a) * k); });
    for (const cl of clams) if (!cl.taken) { x.fillStyle = PEARL[cl.v][1]; x.beginPath(); x.arc(X(cl.x), Y(cl.z), 3 * dpr, 0, 7); x.fill(); } for (const v of vents) { x.strokeStyle = '#dff6ff'; x.lineWidth = 2 * dpr; x.beginPath(); x.arc(X(v.x), Y(v.z), 4 * dpr, 0, 7); x.stroke(); }
    x.fillStyle = '#f3f2f2'; x.fillRect(X(0) - 4 * dpr, Y(0) - 7 * dpr, 8 * dpr, 14 * dpr); x.fillStyle = '#ffffff'; x.beginPath(); x.arc(X(ben.x), Y(ben.z), 5 * dpr, 0, 7); x.fill(); x.fillStyle = '#ec3013'; x.beginPath(); x.arc(X(ben.x), Y(ben.z), 3 * dpr, 0, 7); x.fill(); }

  // ---------- JIB'S DIVE SHEET ----------
  function drawBoard(g, P) { const W0 = P ? 900 : 1600, H0 = P ? 1600 : 900; g.fillStyle = '#7a4f2a'; g.fillRect(0, 0, W0, H0); const x0 = 34, y0 = 34, w = W0 - 68, h = H0 - 98; g.fillStyle = '#1f2b27'; g.fillRect(x0, y0, w, h);
    const CH = '#f2f1e8', YL = '#f5e08a', RD = '#ff9a8a', BLU = '#9fd8f5', HF = '"Caveat", "Segoe Print", "Bradley Hand", cursive';
    const txt = (s, x, y, size, col = CH, wt = 800, fam = 'Archivo, sans-serif') => { s = TX(s); g.font = `${wt} ${size}px ${fam}`; g.fillStyle = col; g.globalAlpha = 0.92; g.fillText(s, x, y); g.globalAlpha = 0.28; g.fillText(s, x + 1.6, y - 1.2); g.globalAlpha = 1; };
    const fit = (s, size, maxW, wt = 800, fam = 'Archivo, sans-serif') => { s = TX(s); g.font = `${wt} ${size}px ${fam}`; const tw = g.measureText(s).width; return tw > maxW ? Math.floor(size * maxW / tw) : size; };
    const L = 86; txt('THE DEEP', L, 160, fit('THE DEEP', 120, W0 - 2 * L, 900), CH, 900); const sub = MERU ? 'MERU  ·  PEARL ISLAND  ·  HULL PEARLS' : "JIDDA  ·  JIB'S BOAT  ·  DEEP SEA PEARLS"; txt(sub, L + 4, 214, fit(sub, 30, W0 - 2 * L), YL); g.strokeStyle = CH; g.lineWidth = 4; g.beginPath(); g.moveTo(L, 238); g.lineTo(W0 - L, 236); g.stroke();
    const rows = [['STICK', 'WASD', 'Swim', CH], ['1', 'J', 'Grab a pearl · else FLASH: stuns creatures', RD], ['2', 'K / Q', 'Down 3 m', BLU], ['3', 'SPACE / E', 'Up 3 m · bank pearls at the boat', YL]];
    const colW = P ? W0 - 2 * L : 760, ry0 = 320, rh = P ? 112 : 104;
    rows.forEach(([k, kb, d, col], i) => { const y = ry0 + i * rh, cx = L + 34, cy = y - 14; g.globalAlpha = 0.9; g.strokeStyle = col; g.lineWidth = 8; g.beginPath(); g.arc(cx, cy, 30, 0, 7); g.stroke(); g.globalAlpha = 1; g.font = `900 ${k.length > 1 ? 18 : 32}px Archivo, sans-serif`; g.textAlign = 'center'; g.fillStyle = CH; g.fillText(k, cx, cy + (k.length > 1 ? 7 : 11)); g.textAlign = 'left'; txt(kb, cx + 60, y - 24, 18, '#b9c4bf', 800); txt(d, cx + 60, y + 6, fit(d, 30, colW - 100, 700), CH, 700); });
    const sx = P ? L : 900, sy = P ? ry0 + 4 * rh + 40 : 300, sw = P ? W0 - 2 * L : W0 - 900 - L;
    txt('DEEPER = BETTER PEARLS', sx, sy, fit('DEEPER = BETTER PEARLS', 30, sw), BLU);
    [['REEF', 'WHITE PEARL · 1', '#ffffff'], ['TWILIGHT', 'GOLD PEARL · 3', YL], ['ABYSS', 'BLACK PEARL · 10', '#c7a6ff'], ['GIANT CLAM', 'FLASH IT OPEN · 25', '#ffc2e0']].forEach(([z, p, c], i) => { const y = sy + 70 + i * (P ? 100 : 84); g.fillStyle = c; g.beginPath(); g.arc(sx + 18, y - 10, 16, 0, 7); g.fill(); txt(z, sx + 56, y - 4, fit(z, 32, sw - 56, 900), CH, 900); txt(p, sx + 56, y + 30, fit(p, 30, sw - 56, 700, HF), c === '#ffffff' ? CH : c, 700, HF); });
    { const s = 'Bag holds 5 · bank 40 at the boat · watch your tank'; txt(s.toUpperCase(), L, H0 - 110, fit(s.toUpperCase(), 44, W0 - 2 * L, 700, HF), YL, 700, HF); }
    g.fillStyle = '#5e3c1f'; g.fillRect(0, H0 - 64, W0, 64); for (let i = 0; i < 4000; i++) { g.fillStyle = 'rgba(31,43,39,0.55)'; g.fillRect(x0 + Math.random() * w, y0 + Math.random() * h, 1 + Math.random() * 2, 1 + Math.random() * 2); } }
  const boardCv = document.createElement('canvas'); boardCv.width = 1600; boardCv.height = 900; const boardCvP = document.createElement('canvas'); boardCvP.width = 900; boardCvP.height = 1600;
  const paintBoards = () => { drawBoard(boardCv.getContext('2d')); drawBoard(boardCvP.getContext('2d'), true); course.boardURL = boardCv.toDataURL('image/jpeg', 0.9); course.boardURLP = boardCvP.toDataURL('image/jpeg', 0.9); emit(); };
  try { if (!document.getElementById('font-caveat')) { const lk = document.createElement('link'); lk.id = 'font-caveat'; lk.rel = 'stylesheet'; lk.href = 'https://fonts.googleapis.com/css2?family=Caveat:wght@700&display=swap'; document.head.appendChild(lk); } } catch (e) {}

  // ---------- DEMO ----------
  const DM = { on: false, i: 0, t: 0, cap: '' };
  const steerTo = (tx, tz) => { const fx = cam.look.x - cam.pos.x, fz = cam.look.z - cam.pos.z, l = Math.hypot(fx, fz) || 1, ux = fx / l, uz = fz / l, dx = tx - ben.x, dz = tz - ben.z, d = Math.hypot(dx, dz); if (d < 0.8) { STK.x = STK.y = 0; return d; } const wx = dx / d, wz = dz / d; STK.y = wx * ux + wz * uz; STK.x = -wx * uz + wz * ux; return d; };
  const tpTo = (x, y, z) => { ben.x = x; ben.y = y; ben.z = z; G.ty = y; ben.vx = ben.vz = 0; cam.cut = true; };
  const clamOf = v => clams.find(c => !c.taken && c.v === v);
  const DEMO_OLD = [
    { d: 3.4, cap: 'THE DEEP · 2 TO GO DOWN, 3 TO COME UP', on() { rollOut(); G.count = 0.01; G.radio = ''; }, tick() { steerTo(0, 16); if (DM.t > 0.6 && DM.t < 0.7) press(2); if (DM.t > 1.6 && DM.t < 1.7) press(2); } },
    { d: 3.6, cap: '1 · GRAB A PEARL WHILE THE CLAM IS OPEN', on() { const c = clamOf(1); DM.c = c; tpTo(c.x, c.y + 1.2, c.z - 3); }, tick() { const c = DM.c; steerTo(c.x, c.z - 0.5); if (c.open && !c.taken) { const it = interact(); if (it && /GRAB/.test(it.label)) it.act(); } } },
    { d: 3.4, cap: 'DEEPER PEARLS ARE WORTH MORE · GOLD IN THE TWILIGHT', on() { const c = clamOf(3); DM.c = c; tpTo(c.x, c.y + 1.2, c.z - 3); ents.filter(e => e.kind === 'eel').forEach(e => e.cd = 9); }, tick() { const c = DM.c; steerTo(c.x, c.z - 0.5); if (c.open && !c.taken) { const it = interact(); if (it && /GRAB/.test(it.label)) it.act(); } } },
    { d: 3.4, cap: 'EELS HIDE BY THE CLAMS · 1 WITH NOTHING TO GRAB = FLASH', on() { const e = ents.find(q => q.kind === 'eel'); DM.e = e; e.cd = 0; tpTo(e.x, e.y + 1.4, e.z - 4.5); }, tick() { steerTo(DM.e.x, DM.e.z - 2.6); if (DM.t > 1.9 && DM.t < 2.0) press(1); ben.inv = 1; } },
    { d: 3.6, cap: 'OLD SEA MINES · WHEN ONE BLINKS, SWIM AWAY', on() { const m = mines[1]; DM.m = m; tpTo(m.x - 5, m.y, m.z - 5); }, tick() { if (DM.t < 1.4) steerTo(DM.m.x, DM.m.z); else steerTo(DM.m.x - 20, DM.m.z - 20); ben.inv = 1; } },
    { d: 3.6, cap: 'THE ABYSS · BLACK PEARLS ARE WORTH 10 · THE LIGHT IS A LURE', on() { const a = ents.find(q => q.kind === 'angler'); DM.a = a; tpTo(a.x, a.y, a.z - 8); }, tick() { steerTo(DM.a.x, DM.a.z - 3); ben.inv = 1; } },
    { d: 3, cap: 'BUBBLE VENTS FILL YOUR TANK', on() { const v = vents[3]; tpTo(v.x, v.y + 3, v.z - 3); G.o2 = 30; }, tick() { steerTo(vents[3].x, vents[3].z); } },
    { d: 4, cap: 'BRING THEM UP TO JIB\'S BOAT TO BANK THEM · BANK 40 TO WIN', on() { tpTo(2, -4, 10); G.ty = -0.6; if (!G.carry) G.carry = 4; }, tick() { steerTo(0, 0.5); } },
    { d: 2.6, cap: 'WATCH YOUR TANK · MIND THE MINES · BEAT THE CLOCK', on() {}, tick() { STK.x = STK.y = 0; } }];
  const DEMO = [
    { d: 4, key: 'STICK', cap: 'SWIM WITH THE STICK (WASD). THE CAMERA FOLLOWS YOU', on() { rollOut(); G.count = 0.01; G.radio = ''; }, tick() { steerTo(4, 18); } },
    { d: 4, key: '2', cap: 'PRESS 2 TO GO DOWN 3 M. EACH PRESS IS ONE STEP DEEPER', on() {}, tick() { steerTo(0, 22); if (DM.t > 0.4 && DM.t < 0.47) press(2); if (DM.t > 1.8 && DM.t < 1.87) press(2); } },
    { d: 3.6, key: '1', cap: 'CLAM OPEN? PRESS 1 TO GRAB THE PEARL', on() { const c = clamOf(1); DM.c = c; tpTo(c.x, c.y + 1.2, c.z - 3); }, tick() { const c = DM.c; steerTo(c.x, c.z - 0.5); if (c.open && !c.taken && DM.t > 1) { const it = interact(); if (it && /GRAB/.test(it.label)) it.act(); } } },
    { d: 3.4, key: '1', cap: 'CLAM SHUT? WAIT FOR IT TO OPEN, THEN GRAB', on() { const c = clamOf(1); DM.c = c; tpTo(c.x, c.y + 1.2, c.z - 2.6); c.ph = -TT + 2.8; }, tick() { const c = DM.c; steerTo(c.x, c.z - 0.5); if (c.open && !c.taken && DM.t > 1.6) { const it = interact(); if (it && /GRAB/.test(it.label)) it.act(); } } },
    { d: 3.8, key: 'O2', cap: 'YOUR TANK: THE OXYGEN BAR. IT RUNS DOWN FASTER THE DEEPER YOU ARE', on() { G.o2 = 62; }, tick() { steerTo(ben.x + 2, ben.z + 4); } },
    { d: 3.6, key: '!', cap: 'HITS COST OXYGEN AND CRACK YOUR GLASS. LOW TANK FOGS IT UP', on() { G.cracks = 2; G.o2 = 22; }, tick() { STK.x = STK.y = 0; ben.inv = 1; } },
    { d: 3.4, key: '!', cap: 'GOLD PEARLS (3) LIE DEEPER. EELS HIDE IN HOLES BESIDE THEM', on() { const e = ents.find(q => q.kind === 'eel'); DM.e = e; e.cd = 1.2; tpTo(e.x, e.y + 1.4, e.z - 4.6); }, tick() { steerTo(DM.e.x, DM.e.z - 2.6); ben.inv = 1; } },
    { d: 3.4, key: '1', cap: 'NOTHING TO GRAB? 1 FLASHES YOUR LAMP AND STUNS THEM', on() {}, tick() { if (DM.t > 0.5 && DM.t < 0.57) { G.flashCd = 0; press(1); } STK.x = STK.y = 0; ben.inv = 1; } },
    { d: 4, key: '1', cap: 'AN OCTOPUS GRABS AND INKS YOU. FLASH (1) TO SHAKE IT OFF', on() { const o = ents.find(q => q.kind === 'octo'); DM.o = o; tpTo(o.x, o.y, o.z - 4); o.st = 'idle'; o.stun = 0; }, tick() { steerTo(DM.o.x, DM.o.z); if (G.held > 0 && G.held < 1.6 && !DM.f) { DM.f = true; G.flashCd = 0; press(1); } ben.inv = 1; } },
    { d: 3.8, key: '!', cap: 'SEA MINES BLINK AND BEEP WHEN YOU ARE CLOSE. SWIM AWAY FAST', on() { DM.f = false; const m = mines[1]; m.gone = false; m.g.visible = true; m.st = 'idle'; DM.m = m; tpTo(m.x - 4, m.y, m.z - 4); }, tick() { if (DM.t < 1.2) steerTo(DM.m.x, DM.m.z); else steerTo(DM.m.x - 24, DM.m.z - 24); ben.inv = 1; } },
    { d: 3.4, key: '!', cap: 'URCHINS STING, CURRENTS PUSH YOU SIDEWAYS, KELP SLOWS YOU', on() { tpTo(-20, -18, 87); }, tick() { steerTo(-20, 100); ben.inv = 1; } },
    { d: 3.8, key: '10', cap: 'THE ABYSS: BLACK PEARLS ARE WORTH 10. THAT LIGHT IS AN ANGLERFISH', on() { const a = ents.find(q => q.kind === 'angler'); DM.a = a; tpTo(a.x, a.y, a.z - 8); }, tick() { steerTo(DM.a.x, DM.a.z - 3); ben.inv = 1; } },
    { d: 4.6, key: '1', cap: 'THE GIANT CLAM STAYS SHUT. FLASH IT (1), THEN GRAB ITS PEARL: 25', on() { tpTo(giant.x, giant.y + 2, giant.z - 4.5); G.o2 = 80; G.cracks = 0; ents.filter(e => e.kind === 'angler').forEach(e => e.cd = 9); }, tick() { steerTo(giant.x, giant.z - 2.2); ben.inv = 1; if (DM.t > 0.8 && DM.t < 0.87) { G.flashCd = 0; press(1); } if (DM.t > 2 && giant.open && !giant.taken) { G.carryN = Math.min(G.carryN, DIVE.BAG - 1); const it = interact(); if (it && /GRAB/.test(it.label)) it.act(); } } },
    { d: 3.4, key: 'BAG', cap: 'YOUR BAG HOLDS 5 PEARLS. FULL? HEAD BACK AND BANK', on() { G.carryN = DIVE.BAG; }, tick() { STK.x = STK.y = 0; ben.inv = 1; } },
    { d: 3.4, key: 'O2', cap: 'TANK LOW? SIT IN A BUBBLE VENT AND IT FILLS UP', on() { const v = vents[3]; tpTo(v.x, v.y + 3, v.z - 3); G.o2 = 22; }, tick() { steerTo(vents[3].x, vents[3].z); } },
    { d: 3.6, key: '3', cap: 'PRESS 3 TO COME UP 3 M AT A TIME', on() { tpTo(2, -10, 12); if (!G.carry) G.carry = 4; }, tick() { steerTo(0, 4); if (DM.t > 0.3 && DM.t < 0.37) press(3); if (DM.t > 1.4 && DM.t < 1.47) press(3); if (DM.t > 2.5 && DM.t < 2.57) press(3); } },
    { d: 4, key: 'BANK', cap: 'SURFACE BY JIB\'S BOAT TO BANK YOUR PEARLS. BANK 40 TO WIN', on() { tpTo(1, -0.6, 7); G.ty = -0.6; }, tick() { steerTo(0, 0.5); } },
    { d: 3, key: 'GO', cap: 'TANK EMPTY = HAULED UP AND YOU LOSE WHAT YOU CARRY. GOOD LUCK', on() {}, tick() { STK.x = STK.y = 0; } }];
  function demoStep(dt) { if (!DM.on) return; const s = DEMO[DM.i]; DM.t += dt; if (s.tick) s.tick(dt); G.radio = ''; if (DM.t >= s.d) { DM.i++; DM.t = 0; if (DM.i >= DEMO.length) return demoStop(); const n = DEMO[DM.i]; DM.cap = n.cap; n.on && n.on(); } }
  function demoStart() { DM.on = true; DM.i = 0; DM.t = 0; DM.cap = DEMO[0].cap; G.board = false; PAUSE = false; DEMO[0].on(); emit(); }
  function demoStop() { DM.on = false; DM.cap = ''; STK.x = STK.y = 0; reset(); G.done = null; G.board = true; PAUSE = true; G.phase = 'ready'; emit(); }

  // ---------- API ----------
  const course = { boardURL: '', boardURLP: '', hud, say, rollOut, useItem, demoStart, demoStop,
    openBoard() { G.board = true; PAUSE = true; if (G.phase === 'done') G.done = null; emit(); }, closeBoard() { G.board = false; PAUSE = false; emit(); }, preview() {},
    _tp(x, y, z) { tpTo(x, y, z); }, _win() { G.banked = DIVE.GOAL; finish(); }, _dbg: () => ({ phase: G.phase, x: ben.x, y: ben.y, z: ben.z, o2: G.o2, carry: G.carry, banked: G.banked, zone: zone(ben.y) }) };
  const api = { course: () => course,
    start() { rollOut(); }, talk() {}, choose() {}, closeDialog() {}, nextLine() {}, clearToast() {}, closeWheel() {}, skipTime() {}, cycleWeather() {}, useItem, setHudPad() {},
    toggleSound() { audio.setMuted(!audio.muted); return audio.muted; },
    melee() { press(1); }, range() { press(2); }, jump() { press(3); },
    setPaused(v) { PAUSE = !!v || G.board; }, setStick(x, y) { STK.x = x; STK.y = y; },
    eyeLook(dx, dy) { cam.drag = true; cam.yawOff -= dx * 0.006; cam.pitchOff = clamp(cam.pitchOff - dy * 0.004, -0.6, 0.9); }, eyeRelease() { cam.drag = false; }, togglePov() { cam.vi = (cam.vi + 1) % VIEWS.length; flash('VIEW · ' + VIEWS[cam.vi], '#ffffff'); return cam.vi !== 0; },
    lookBy(dx, dy) { api.eyeLook(dx, dy); }, zoomBy(k) { cam.zoom = clamp(cam.zoom * k, 0.6, 1.8); }, getCam() { return { dist: cam.zoom * 10, pitch: cam.pitchOff }; }, setCam(d, p) { if (d != null) cam.zoom = clamp(d / 10, 0.6, 1.8); if (p != null) cam.pitchOff = p; },
    mapData() { return { p: [ben.x, ben.z, ben.yaw], indoor: false, b: [], f: [], e: ents.map(e => [e.x, e.z]), q: null }; }, setMinimap(c) { miniC = c || null; },
    reset() {}, _pump(n = 1, dt = 1 / 30) { for (let i = 0; i < n; i++) step(dt); renderer.render(scene, camera); emit(); },
    destroy() { cancelAnimationFrame(raf); removeEventListener('keydown', onKD); removeEventListener('keyup', onKU); removeEventListener('resize', onRs); ro.disconnect(); renderer.dispose(); renderer.domElement.remove(); try { audio.ctx && audio.ctx.close(); } catch (e) {} } };
  reset(); G.phase = 'ready';
  setTimeout(paintBoards, 30); setTimeout(paintBoards, 1400);
  raf = requestAnimationFrame(frame);
  return api;
}
