// Creature Workshop stage: one creature on a turntable, the player fox beside it for scale, every state on a button,
// the shared tell language on the ground (red ring / gold weak point), and a fight loop that runs the full rhythm.
import * as THREE from './vendor/three/three.module.js';
import { rr, clamp, smooth, damp, makeGradient, glowTexture, Ambience } from './village-game.js';
import { crestTex, canvasTex } from './meru-game.js';
import { foxKit } from './fox-kit.js';
import { CAST } from './engine/cast.js';
import { creatureKit, STATE_DUR } from './engine/creature-kit.js';
import { corsairFamily, stealthFamily, shrikeFamily } from './engine/corsair-kit.js';
import { zionFamilies } from './engine/zion-kit.js';
import { homeFamilies } from './engine/home-kit.js';
import { lastFamilies } from './engine/last-kit.js';
import { bakeCreature } from './engine/bake.js';
import { createBrain } from './engine/creature-ai.js';
import { creatureFx } from './engine/creature-fx.js';

export async function createCreatureLab({ container, onState = () => {}, getInsets = () => ({ top: 0, bottom: 0 }) }) {
  const W = () => container.clientWidth || 1, H = () => container.clientHeight || 1;
  const renderer = new THREE.WebGLRenderer({ antialias: true }); renderer.setPixelRatio(Math.min(devicePixelRatio, 2)); renderer.setSize(W(), H(), false);
  renderer.shadowMap.enabled = true; renderer.domElement.style.cssText = 'display:block;width:100%;height:100%;touch-action:none;outline:none'; container.appendChild(renderer.domElement);
  const scene = new THREE.Scene(); scene.background = new THREE.Color('#1a1918'); scene.fog = new THREE.Fog(0x1a1918, 14, 34);
  const camera = new THREE.PerspectiveCamera(40, W() / H(), 0.1, 100);
  const grad = makeGradient(), glowTex = glowTexture(), cache = new Map();
  const toon = (c, extra) => { const k = c + (extra ? JSON.stringify(extra) : ''); if (!cache.has(k)) cache.set(k, new THREE.MeshToonMaterial({ color: c, gradientMap: grad, ...extra })); return cache.get(k); };
  const outlineMat = new THREE.MeshBasicMaterial({ color: 0x1a1626, side: THREE.BackSide });
  function addOutline(mesh, t = 0.04, radius) { const g = mesh.geometry; g.computeBoundingBox(); const s = new THREE.Vector3(); g.boundingBox.getSize(s); const o = new THREE.Mesh(g, outlineMat); if (radius) o.scale.setScalar(1 + t / radius); else o.scale.set(1 + 2 * t / Math.max(s.x, 0.01), 1 + 2 * t / Math.max(s.y, 0.01), 1 + 2 * t / Math.max(s.z, 0.01)); mesh.add(o); return mesh; }
  function M(geo, mat, x = 0, y = 0, z = 0, parent, outline = 0.04, radius) { const m = new THREE.Mesh(geo, mat); m.position.set(x, y, z); m.castShadow = true; m.receiveShadow = true; if (outline) addOutline(m, outline, radius); (parent || scene).add(m); return m; }
  const audio = new Ambience();
  scene.add(new THREE.HemisphereLight(0xffffff, 0x4a4540, 1.15));
  const sun = new THREE.DirectionalLight(0xfff2e0, 2.4); sun.position.set(4, 9, 6); sun.castShadow = true; sun.shadow.mapSize.set(1024, 1024); Object.assign(sun.shadow.camera, { left: -6, right: 6, top: 6, bottom: -6 }); sun.shadow.bias = -0.0005; scene.add(sun);
  const rim = new THREE.DirectionalLight(0x9fd8ff, 0.8); rim.position.set(-5, 4, -6); scene.add(rim);
  const floorT = canvasTex(512, 512, g => { g.fillStyle = '#2a2826'; g.fillRect(0, 0, 512, 512); g.strokeStyle = 'rgba(255,255,255,0.07)'; g.lineWidth = 2; for (let i = 0; i <= 512; i += 32) { g.beginPath(); g.moveTo(i, 0); g.lineTo(i, 512); g.moveTo(0, i); g.lineTo(512, i); g.stroke(); } });
  floorT.wrapS = floorT.wrapT = THREE.RepeatWrapping; floorT.repeat.set(4, 4);
  const floor = new THREE.Mesh(new THREE.PlaneGeometry(60, 60), new THREE.MeshToonMaterial({ map: floorT, gradientMap: grad })); floor.rotation.x = -Math.PI / 2; floor.receiveShadow = true; scene.add(floor);
  const table = new THREE.Group(); scene.add(table);
  M(new THREE.CylinderGeometry(2.2, 2.3, 0.12, 48), toon('#3a3836'), 0, 0.06, 0, table, 0.02, 2.3);
  M(new THREE.TorusGeometry(2.2, 0.03, 6, 64), toon('#ffd23a'), 0, 0.125, 0, table, 0).rotation.x = Math.PI / 2;
  const mount = new THREE.Group(); mount.position.y = 0.12; table.add(mount);
  // the player fox for scale
  const fk = foxKit({ THREE, scene, toon, M, grad, outlineMat, crestTex, rr, pick: a => a[0], clamp, smooth, damp });
  const fox = fk.makeFox({ ...CAST.player }); fox.position.set(-2.9, 0, 0.4); fox.rotation.y = 0.5; scene.add(fox);
  // tells: red ring (melee), gold flash (weak point)
  const ring = new THREE.Mesh(new THREE.RingGeometry(1.0, 1.25, 48), new THREE.MeshBasicMaterial({ color: 0xec3013, transparent: true, opacity: 0, depthWrite: false, side: THREE.DoubleSide })); ring.rotation.x = -Math.PI / 2; ring.position.y = 0.14; mount.add(ring);
  const ringFill = new THREE.Mesh(new THREE.CircleGeometry(1.0, 48), new THREE.MeshBasicMaterial({ color: 0xec3013, transparent: true, opacity: 0, depthWrite: false })); ringFill.rotation.x = -Math.PI / 2; ringFill.position.y = 0.135; mount.add(ringFill);
  const ck = creatureKit({ THREE, toon, M }), cfx = creatureFx(THREE);
  ck.register('corsair', corsairFamily({ THREE, toon, M, fk })); ck.register('stealth', stealthFamily({ THREE, toon, M, fk })); ck.register('shrike', shrikeFamily({ THREE, toon, M, fk })); { const Z = zionFamilies({ THREE, toon, M, fk }); for (const id in Z) ck.register(id, Z[id]); const Hm = homeFamilies({ THREE, toon, M }); for (const id in Hm) ck.register(id, Hm[id]); const Ls = lastFamilies({ THREE, toon, M, fk }); for (const id in Ls) ck.register(id, Ls[id]); }
  const disc = new THREE.Mesh(new THREE.RingGeometry(0.75, 0.95, 40), new THREE.MeshBasicMaterial({ color: 0x38bdf8, transparent: true, opacity: 0, depthWrite: false, side: THREE.DoubleSide })); disc.rotation.x = -Math.PI / 2; disc.position.set(0, 0.14, 3.0); mount.add(disc);
  const discFill = new THREE.Mesh(new THREE.CircleGeometry(0.75, 40), new THREE.MeshBasicMaterial({ color: 0x38bdf8, transparent: true, opacity: 0, depthWrite: false })); discFill.rotation.x = -Math.PI / 2; discFill.position.set(0, 0.135, 3.0); mount.add(discFill);
  const chargeLane = new THREE.Mesh(new THREE.PlaneGeometry(1.2, 4.6).translate(0, 2.3 + 0.9, 0), new THREE.MeshBasicMaterial({ color: 0xff8a1a, transparent: true, opacity: 0, depthWrite: false, side: THREE.DoubleSide })); chargeLane.rotation.x = -Math.PI / 2; chargeLane.position.y = 0.14; mount.add(chargeLane);
  const wall = new THREE.Mesh(new THREE.BoxGeometry(2.4, 1.4, 0.3), new THREE.MeshToonMaterial({ color: '#5a5550', gradientMap: grad })); wall.position.set(0, 0.82, 5.4); wall.visible = false; mount.add(wall);
  const flying = [], stuck = [], drops = [], minis = [], novas = [], rollers = []; let slamT = 9;
  const dropDisc = () => { const r = new THREE.Mesh(new THREE.RingGeometry(0.5, 0.65, 32), new THREE.MeshBasicMaterial({ color: 0x38bdf8, transparent: true, opacity: 0.9, depthWrite: false, side: THREE.DoubleSide })); r.rotation.x = -Math.PI / 2; const f = new THREE.Mesh(new THREE.CircleGeometry(0.5, 32), new THREE.MeshBasicMaterial({ color: 0x38bdf8, transparent: true, opacity: 0.25, depthWrite: false })); f.rotation.x = -Math.PI / 2; f.position.y = -0.005; r.add(f); return r; };
  // the fan tell: three lanes that light up while the arm draws back
  const lanes = [-0.32, 0, 0.32].map(a => { const p = new THREE.Mesh(new THREE.PlaneGeometry(0.16, 4.2), new THREE.MeshBasicMaterial({ color: 0xec3013, transparent: true, opacity: 0, depthWrite: false, side: THREE.DoubleSide })); p.geometry.translate(0, 2.1 + 0.5, 0); p.rotation.set(-Math.PI / 2, 0, -a); p.position.y = 0.14; mount.add(p); return p; });
  const shards = [];
  let ai = null, foxHp = 100, foxA = 0, foxFlash = 0, bake = true, cur = null, state = 'idle', st = 0, turn = true, tells = true, loop = false, loopI = 0, showFox = true, weakFlash = 0;
  const LOOP = ['move', 'windup', 'attack', 'recover', 'idle']; const ease3 = k => k * k * k;
  let flock = [];
  function setCreatureOuter(name) { ai = null; fox.position.set(-2.9, 0, 0.4); setCreature(name); }
  function setCreature(name) { if (cur) mount.remove(cur); flock.forEach(f => mount.remove(f.g)); flock = []; cur = ck.build(name); if (cur && bake) bakeCreature(THREE, cur); if (cur) { mount.add(cur); cfx.attach(cur); cfx.spawn(cur, () => { slamT = 0; audio.burst(0.3, 300, 0.25); }); cur.position.z = 0.3; if (cur.userData.flock) for (const [x, z, o] of [[-1.1, -0.8, 1.3], [1.0, -0.6, 2.6], [-0.4, -1.6, 3.9], [0.9, -1.7, 5.1]]) { const f = ck.build(name); f.position.set(x, 0, z); f.rotation.y = rr(-1.5, 1.5); mount.add(f); flock.push({ g: f, x, z, o, ry: f.rotation.y }); } } play('idle'); push(); }
  function play(s) { if (cur && (s === 'hurt' || s === 'stagger' || s === 'armorBreak')) cfx.hit(cur); state = s; st = 0; if (cur) { cur.rotation.set(0, 0, 0); cur.position.set(0, 0, 0.3); } if (cur) ck.enter(cur, s); if (s === 'windup' && tells && !(cur && cur.userData.willThrow)) { audio.tone(900, 0.05, 0.05, 'square'); setTimeout(() => audio.tone(900, 0.05, 0.05, 'square'), 230); } if (s === 'recover' && tells) audio.tone(1320, 0.18, 0.04, 'triangle', 1.5); if (s === 'die') audio.burst(0.3, 2400, 0.2); if (s === 'armorBreak') audio.burst(0.25, 1800, 0.18); push(); }
  function shatter(n, col) { if (!cur) return; const p = new THREE.Vector3(); cur.userData.weak.getWorldPosition(p); for (let i = 0; i < n; i++) { const m = new THREE.Mesh(new THREE.OctahedronGeometry(rr(0.05, 0.12), 0), new THREE.MeshBasicMaterial({ color: col })); m.position.copy(p); scene.add(m); shards.push({ m, v: new THREE.Vector3(rr(-3, 3), rr(2, 5), rr(-3, 3)), t: 1.4 }); } }
  const push = () => onState({ ai: !!ai, aiHp: ai ? ai.hp : 0, aiMax: ai ? ai.max : 0, foxHp, aiRole: ai ? ai.role : '', bake, before: cur ? (cur.userData.callsBefore || cur.userData.calls) : 0, phase: cur && cur.userData.boss && cur.userData.family !== 'specimen' ? cur.userData.phase : 0, state, name: cur ? cur.userData.variant : null, calls: cur ? cur.userData.calls : 0, size: cur ? (cur.userData.height / 1.55).toFixed(2) : 0, turn, tells, loop, showFox });
  // orbit
  let yaw = 0.6, pitch = 0.32, dist = 7.2, drag = null;
  const el = renderer.domElement;
  el.addEventListener('pointerdown', e => { drag = { x: e.clientX, y: e.clientY }; el.setPointerCapture(e.pointerId); });
  el.addEventListener('pointermove', e => { if (!drag) return; yaw -= (e.clientX - drag.x) * 0.008; pitch = clamp(pitch + (e.clientY - drag.y) * 0.005, 0.05, 1.2); drag = { x: e.clientX, y: e.clientY }; });
  el.addEventListener('pointerup', () => drag = null); el.addEventListener('pointercancel', () => drag = null);
  el.addEventListener('wheel', e => { dist = clamp(dist + e.deltaY * 0.005, 3.5, 14); e.preventDefault(); }, { passive: false });
  const ro = new ResizeObserver(() => { renderer.setSize(W(), H(), false); camera.aspect = W() / H(); camera.updateProjectionMatrix(); }); ro.observe(container);
  const clock = new THREE.Clock(); let raf = 0, t = 0, vOff = 0, darkK = 0, flick = 0; const box = new THREE.Box3(), sph = new THREE.Sphere(), v1 = new THREE.Vector3(), tb = new THREE.Box3();
  const visBox = o => { if (!o.visible) return; if (o.isMesh && o.material && o.material.side !== THREE.BackSide) { if (!o.geometry.boundingBox) o.geometry.computeBoundingBox(); tb.copy(o.geometry.boundingBox).applyMatrix4(o.matrixWorld); box.union(tb); } for (const c of o.children) visBox(c); };
  function frame() {
    raf = requestAnimationFrame(frame); const dt = Math.min(clock.getDelta(), 0.05); t += dt; st += dt;
    if (turn && state !== 'move') table.rotation.y += dt * 0.35;
    if (cur) {
      const dur = ck.dur(cur, state);
      if (ai) {   // TRY THE AI: the creature fights the fox with the shared enemy brain
        const cw = cur.getWorldPosition(new THREE.Vector3()), dx = fox.position.x - cw.x, dz = fox.position.z - cw.z, d = Math.hypot(dx, dz);
        const ns = ai.update(dt, d, state, st); if (ns) play(ns);
        if (!cur.userData.burrow && !cur.userData.boss || cur.userData.family === 'night') cur.rotation.y = Math.atan2(dx, dz);
        const mv = state === 'move' ? ai.speed * ai.moveSign(d) : (ai.role === 'charge' && state === 'attack') ? 6 : 0;
        if (mv && !cur.userData.burrow && !cur.userData.boss && d > 0.9) { cur.position.x += dx / d * mv * dt; cur.position.z += dz / d * mv * dt; const L = Math.hypot(cur.position.x, cur.position.z); if (L > 3.2) { cur.position.x *= 3.2 / L; cur.position.z *= 3.2 / L; } }
        if (ai.strike && d <= ai.range + 0.6) { foxHp = Math.max(0, foxHp - (cur.userData.boss ? 15 : 8)); foxFlash = 0.3; audio.tone(220, 0.12, 0.06, 'square', 0.6); if (foxHp <= 0) foxHp = 100; }
        foxA += dt * (ai.role === 'ranged' ? 0.35 : 0.5); const R = ai.role === 'ranged' ? 4.2 : (cur.userData.boss ? 4.0 : 2.4) + Math.sin(t * 0.7) * 0.6;
        const tx = cw.x + Math.sin(foxA) * R, tz = cw.z + Math.cos(foxA) * R; fox.position.x = damp(fox.position.x, tx, 3, dt); fox.position.z = damp(fox.position.z, tz, 3, dt); fox.rotation.y = Math.atan2(cw.x - fox.position.x, cw.z - fox.position.z);
        foxFlash = Math.max(0, foxFlash - dt); fox.position.y = foxFlash > 0 ? Math.sin(foxFlash * 40) * 0.05 : 0;
        if ((t % 0.25) < dt) push();
      } else
      if (loop && ((state === 'move' && st > 1.6) || (state === 'idle' && st > 0.8) || (dur && st > dur))) { loopI = (loopI + 1) % LOOP.length; play(LOOP[loopI]); }
      else if (cur.userData.charge && state === 'attack' && st > dur) { slamT = 0; audio.burst(0.4, 300, 0.3); audio.tone(60, 0.3, 0.07, 'square', 0.5); play('stagger'); }   // it hits the wall and stuns itself
      else if (dur && st > dur && state !== 'die') play('idle');
      if (ai) {} else if (cur.userData.trail && cur.userData.family === 'belt') { cur.position.set(0, 0, 0); cur.rotation.y = 0; } else if ((cur.userData.family === 'scarab' && (state === 'windup' || state === 'attack' || state === 'recover')) || (cur.userData.kind === 'hulk' && state !== 'move')) { cur.position.set(0, 0, 0.3); cur.rotation.y = 0; } else if (cur.userData.burrow) { cur.position.set(0, 0, 0); cur.rotation.y = 0; } else if (state === 'move' && cur.userData.turret) { cur.position.set(0, 0, 0.3); } else if (state === 'move' && cur.userData.ranged) { const a = st * 1.1; cur.position.set(Math.sin(a) * 0.5, 0, 0.3 - Math.min(1.2, st * 0.8)); cur.rotation.y = 0; } else if (state === 'move') { const a = st * 1.1; cur.position.set(Math.sin(a) * 1.1, 0, 0.3 + (Math.cos(a) - 1) * 0.5); cur.rotation.y = a + Math.PI / 2; }
      cfx.pre(cur); ck.animate(cur, state, st, dt, { speed: 1 }); cfx.post(cur, dt);
      for (const f of flock) { const ws = state === 'windup' || state === 'attack'; f.g.rotation.y = ws ? damp(f.g.rotation.y, 0, 25, dt) : state === 'idle' ? damp(f.g.rotation.y, f.ry, 3, dt) : f.g.rotation.y; ck.animate(f.g, state === 'move' ? 'idle' : state, st, dt, { off: f.o }); if (state === 'attack') f.g.position.z = f.z + clamp(st / 0.6) * 1.6; else if (state === 'idle') f.g.position.z = damp(f.g.position.z, f.z, 3, dt); }
      if (state === 'armorBreak' && st < dt * 1.5) shatter(cur.userData.family === 'golem' && cur.userData.crust < 2 ? 5 : 12, cur.userData.weakBase);
      if (cur.userData.family === 'crab' && state === 'die' && st > 0.7 && st - dt <= 0.7) shatter(22, cur.userData.weakBase);
      for (const ev of cur.userData.events.splice(0)) try {
        if (ev === 'rip') { audio.burst(0.35, 300, 0.25); audio.tone(110, 0.3, 0.06, 'sawtooth', 0.6); }
        if (ev === 'throw') { const from = new THREE.Vector3(); cur.userData.joints.arms[1].fist.getWorldPosition(from); const to = mount.localToWorld(new THREE.Vector3(0, 0.2, 3.0)); const sl = new THREE.Mesh(new THREE.BoxGeometry(0.5, 0.5, 0.14).scale(cur.scale.x, cur.scale.x, cur.scale.x), new THREE.MeshBasicMaterial({ color: cur.userData.slabColor })); sl.position.copy(from); scene.add(sl); flying.push({ m: sl, from, to, t: 0, dur: 0.7 }); audio.tone(180, 0.2, 0.05, 'triangle'); }
        if (ev === 'fan') { const from = new THREE.Vector3(); cur.userData.joints.thrower.hand.getWorldPosition(from); for (const a of [-0.32, 0, 0.32]) { const to = mount.localToWorld(new THREE.Vector3(Math.sin(a) * 4.6, 0.6, 0.3 + Math.cos(a) * 4.6)); const s = new THREE.Mesh(new THREE.OctahedronGeometry(0.09, 0).scale(1, 1, 3), new THREE.MeshBasicMaterial({ color: cur.userData.slabColor })); s.position.copy(from); s.lookAt(to); scene.add(s); flying.push({ m: s, from: from.clone(), to, t: 0, dur: 0.38, flat: true }); } audio.tone(1400, 0.08, 0.04, 'triangle', 0.6); setTimeout(() => audio.tone(1700, 0.06, 0.03, 'triangle'), 40); }
        if (ev === 'stick') { const from = new THREE.Vector3(); cur.userData.joints.arms[1].fist.getWorldPosition(from); for (const a of [-0.5, -0.15, 0.2, 0.55]) { const to = mount.localToWorld(new THREE.Vector3(Math.sin(a) * 4.2, 0.12, 0.3 + Math.cos(a) * 4.2 + rr(-0.4, 0.4))); const s = new THREE.Mesh(new THREE.OctahedronGeometry(0.18, 0).scale(1, 3, 1), new THREE.MeshBasicMaterial({ color: '#e09bff' })); s.position.copy(from); scene.add(s); flying.push({ m: s, from: from.clone(), to, t: 0, dur: 0.55, stick: true }); } audio.tone(900, 0.1, 0.04, 'triangle'); }
        if (ev === 'rain') { for (let i = 0; i < 6; i++) { const p = mount.localToWorld(new THREE.Vector3(rr(-4, 4), 0.14, rr(2.4, 5.5))); const d = dropDisc(); d.position.copy(p); scene.add(d); const s = new THREE.Mesh(new THREE.OctahedronGeometry(0.2, 0).scale(1, 2.6, 1), new THREE.MeshBasicMaterial({ color: '#c79bff' })); s.position.set(p.x, 9, p.z); s.visible = false; scene.add(s); drops.push({ d, s, t: -0.15 * i, p }); } }
        if (ev === 'summon') { for (const sx of [-1, 1]) { const c = ck.build('Crystal Crab'); c.scale.setScalar(0.7); scene.add(c); const p = mount.localToWorld(new THREE.Vector3(sx * 1.6, 0.6, 1.4)); c.position.copy(p); minis.push({ c, sx, t: 0, p }); } audio.tone(500, 0.2, 0.05, 'square', 1.6); }
        if (ev === 'bolt') { const from = new THREE.Vector3(); cur.userData.joints.barrels.getWorldPosition(from); const to = mount.localToWorld(new THREE.Vector3(rr(-0.15, 0.15), 1.1, 5.2)); const s = new THREE.Mesh(new THREE.BoxGeometry(0.06, 0.06, 0.5), new THREE.MeshBasicMaterial({ color: cur.userData.slabColor })); s.position.copy(from); s.lookAt(to); scene.add(s); flying.push({ m: s, from: from.clone(), to, t: 0, dur: 0.25, flat: true }); audio.tone(1200, 0.05, 0.04, 'square', 0.5); }
        if (ev === 'rev') audio.tone(80 + Math.random() * 20, 0.1, 0.04, 'sawtooth', 1.4);
        if (ev === 'spark' || ev === 'explode') { const p = new THREE.Vector3(); cur.userData.weak.getWorldPosition(p); const n = ev === 'explode' ? 30 : 8; for (let j = 0; j < n; j++) { const s = new THREE.Mesh(new THREE.BoxGeometry(0.05, 0.05, 0.05), new THREE.MeshBasicMaterial({ color: j % 3 ? '#ffd23a' : '#ffffff' })); s.position.copy(p); scene.add(s); shards.push({ m: s, v: new THREE.Vector3(rr(-4, 4), rr(2, 6), rr(-4, 4)), t: 0.9 }); } audio.burst(ev === 'explode' ? 0.5 : 0.12, ev === 'explode' ? 500 : 3000, 0.25); }
        if (ev === 'honk') { audio.tone(520, 0.12, 0.05, 'square', 0.8); setTimeout(() => audio.tone(470, 0.14, 0.05, 'square', 0.8), 70); }
        if (ev === 'feathers' || ev === 'scales') { const p = new THREE.Vector3(); (ev === 'scales' ? cur.userData.joints.head : cur.userData.joints.body).getWorldPosition(p); for (let j = 0; j < 18; j++) { const s = new THREE.Mesh(ev === 'scales' ? new THREE.BoxGeometry(0.1, 0.02, 0.1) : new THREE.PlaneGeometry(0.08, 0.16), new THREE.MeshBasicMaterial({ color: ev === 'scales' ? cur.userData.slabColor : (j % 2 ? '#ff7fb0' : '#ffc2d9'), side: THREE.DoubleSide })); s.position.copy(p); scene.add(s); shards.push({ m: s, v: new THREE.Vector3(rr(-2, 2), rr(1, 3), rr(-2, 2)), t: 1.4, float: ev === 'feathers' }); } audio.burst(0.15, 2500, 0.12); }
        if (ev === 'rumble') audio.burst(0.15, 160, 0.2);
        if (ev === 'burst' || ev === 'thud') { const p = cur.userData.hp.clone(); cur.localToWorld(p); p.y = 0.2; for (let j = 0; j < (ev === 'burst' ? 26 : 14); j++) { const s = new THREE.Mesh(new THREE.SphereGeometry(rr(0.04, 0.1), 5, 4), new THREE.MeshBasicMaterial({ color: cur.userData.slabColor })); s.position.copy(p); scene.add(s); shards.push({ m: s, v: new THREE.Vector3(rr(-3, 3), rr(3, 7), rr(-3, 3)), t: 1.2 }); } audio.burst(0.45, 220, 0.3); audio.tone(70, 0.4, 0.07, 'sawtooth', 0.5); }
        if (ev === 'shot') { const from = new THREE.Vector3(); cur.userData.muzzle.getWorldPosition(from); const to = mount.localToWorld(new THREE.Vector3(0, 1.0, 5.2)); const s = new THREE.Mesh(new THREE.SphereGeometry(0.05, 6, 5), new THREE.MeshBasicMaterial({ color: '#ffd23a' })); s.position.copy(from); scene.add(s); flying.push({ m: s, from: from.clone(), to, t: 0, dur: 0.22, flat: true }); for (let j = 0; j < 8; j++) { const p = new THREE.Mesh(new THREE.SphereGeometry(rr(0.04, 0.09), 5, 4), new THREE.MeshBasicMaterial({ color: j % 2 ? '#d8d0c0' : '#ffb020', transparent: true, opacity: 0.8 })); p.position.copy(from); scene.add(p); shards.push({ m: p, v: new THREE.Vector3(rr(-0.5, 0.5), rr(0.2, 1), rr(0.5, 1.5)), t: 0.6, float: true }); } audio.burst(0.18, 1200, 0.3); audio.tone(110, 0.15, 0.06, 'square', 0.4); }
        if (ev === 'swing') audio.burst(0.12, 4000, 0.15);
        if (ev === 'rally') { audio.tone(330, 0.15, 0.05, 'sawtooth', 1.3); setTimeout(() => audio.tone(440, 0.25, 0.05, 'sawtooth', 1.2), 140); }
        if (ev === 'hat') { const h = cur.userData.hat, p = new THREE.Vector3(); h.getWorldPosition(p); const c = h.clone(); c.position.copy(p); c.scale.setScalar(cur.scale.x); scene.add(c); shards.push({ m: c, v: new THREE.Vector3(rr(-1, 1), 4, -1.5), t: 1.3 }); audio.tone(700, 0.08, 0.04, 'triangle'); }
        if (ev === 'splash') { const p = new THREE.Vector3(); cur.getWorldPosition(p); p.y = 0.3; for (let j = 0; j < 30; j++) { const s = new THREE.Mesh(new THREE.SphereGeometry(rr(0.04, 0.09), 5, 4), new THREE.MeshBasicMaterial({ color: j % 3 ? '#5fa8c8' : '#3f6b3a' })); s.position.copy(p); scene.add(s); shards.push({ m: s, v: new THREE.Vector3(rr(-2.5, 2.5), rr(2, 5), rr(-2.5, 2.5)), t: 1.1 }); } audio.burst(0.4, 900, 0.25); }
        if (ev === 'dig' || ev === 'pop' || ev === 'dust' || ev === 'chips') { const p = new THREE.Vector3(); (cur.userData.joints.body || cur.userData.joints.torso || cur).getWorldPosition(p); if (ev === 'dig' || ev === 'pop') p.y = 0.2; const col = ev === 'chips' ? cur.userData.slabColor : '#e0c48a'; const n = ev === 'pop' ? 22 : ev === 'dust' ? 16 : 5; for (let j = 0; j < n; j++) { const s = new THREE.Mesh(new THREE.SphereGeometry(rr(0.03, 0.08), 5, 4), new THREE.MeshBasicMaterial({ color: col, transparent: true, opacity: 0.85 })); s.position.copy(p); scene.add(s); shards.push({ m: s, v: new THREE.Vector3(rr(-2, 2), rr(1.5, ev === 'pop' ? 5 : 3), rr(-2, 2)), t: 0.9, float: ev === 'dust' }); } if (ev === 'dig') { const md = new THREE.Mesh(new THREE.SphereGeometry(0.35, 10, 6), new THREE.MeshToonMaterial({ color: '#e0c48a', gradientMap: grad })); md.scale.set(1, 0.15, 1); md.position.copy(mount.localToWorld(new THREE.Vector3(rr(-0.1, 0.1), 0.02, 0.3 + clamp(st / 0.9) * 1.4))); scene.add(md); stuck.push({ m: md, t: 1.2 }); } audio.burst(ev === 'pop' ? 0.35 : 0.08, ev === 'pop' ? 300 : 900, 0.18); }
        if (ev === 'cone') { const from = new THREE.Vector3(); cur.userData.joints.noz.getWorldPosition(from); for (let j = 0; j < 46; j++) { const a = rr(-0.38, 0.38), sp = rr(4, 7); const v = new THREE.Vector3(Math.sin(a) * sp, rr(0, 1.2), Math.cos(a) * sp); v.applyQuaternion(mount.getWorldQuaternion(new THREE.Quaternion())); const s = new THREE.Mesh(new THREE.SphereGeometry(rr(0.04, 0.1), 5, 4), new THREE.MeshBasicMaterial({ color: j % 3 ? '#ffb020' : '#e0c48a', transparent: true, opacity: 0.9 })); s.position.copy(from); scene.add(s); shards.push({ m: s, v, t: 0.7, float: true }); } audio.burst(0.5, 700, 0.3); }
        if (ev === 'blind') { const p = new THREE.Vector3(); cur.userData.joints.sac.getWorldPosition(p); for (let j = 0; j < 40; j++) { const s = new THREE.Mesh(new THREE.SphereGeometry(rr(0.06, 0.16), 5, 4), new THREE.MeshBasicMaterial({ color: '#f1dcae', transparent: true, opacity: 0.7 })); s.position.copy(p); scene.add(s); shards.push({ m: s, v: new THREE.Vector3(rr(-3, 3), rr(0.5, 3), rr(-3, 3)), t: 1.6, float: true }); } audio.burst(0.5, 500, 0.3); }
        if (ev === 'grab') { audio.tone(140, 0.2, 0.05, 'sawtooth', 0.8); audio.burst(0.15, 1200, 0.12); }
        if (ev === 'drain') { audio.tone(300, 0.25, 0.03, 'sine', 0.6); }
        if (ev === 'suck' || ev === 'spit') { const c = new THREE.Vector3(); cur.getWorldPosition(c); c.y = 1.0; for (let j = 0; j < (ev === 'spit' ? 30 : 8); j++) { const a = rr(0, 6.3), d = ev === 'suck' ? rr(2.2, 3.2) : 0.5; const p = c.clone().add(new THREE.Vector3(Math.cos(a) * d, rr(-0.6, 0.8), Math.sin(a) * d)); const s = new THREE.Mesh(new THREE.SphereGeometry(rr(0.03, 0.07), 5, 4), new THREE.MeshBasicMaterial({ color: cur.userData.slabColor })); s.position.copy(p); scene.add(s); const v = ev === 'suck' ? c.clone().sub(p).multiplyScalar(1.6) : p.clone().sub(c).normalize().multiplyScalar(rr(4, 7)); shards.push({ m: s, v, t: ev === 'suck' ? 0.6 : 0.8, float: true }); } audio.burst(ev === 'spit' ? 0.4 : 0.15, ev === 'spit' ? 900 : 500, 0.2); }
        if (ev === 'lockon') { audio.tone(1800, 0.05, 0.04, 'square'); setTimeout(() => audio.tone(1800, 0.05, 0.04, 'square'), 90); setTimeout(() => audio.tone(2400, 0.12, 0.05, 'square'), 180); }
        if (ev === 'hiss') audio.burst(0.3, 6000, 0.05);
        if (ev === 'clank') { audio.tone(220, 0.08, 0.06, 'square'); setTimeout(() => audio.tone(180, 0.1, 0.05, 'square'), 80); }
        if (ev === 'pools') { const open = 3 - (cur.userData.shut || 0); cur.userData.poolAt = []; for (let j = 0; j < Math.max(1, open * 2); j++) { const p = mount.localToWorld(new THREE.Vector3(rr(-3, 3), 0.14, rr(1.6, 4.6))); const r = new THREE.Mesh(new THREE.CircleGeometry(0.7, 28), new THREE.MeshBasicMaterial({ color: 0xa855f7, transparent: true, opacity: 0.45, depthWrite: false })); r.rotation.x = -Math.PI / 2; r.position.copy(p); scene.add(r); stuck.push({ m: r, t: 2.0 }); cur.userData.poolAt.push(p); } }
        if (ev === 'steam') { const pts = (cur.userData.poolAt && cur.userData.poolAt.length ? cur.userData.poolAt : [cur.position.clone()]); for (const p of pts) for (let j = 0; j < 12; j++) { const s = new THREE.Mesh(new THREE.SphereGeometry(rr(0.12, 0.25), 6, 5), new THREE.MeshBasicMaterial({ color: '#f1f5f9', transparent: true, opacity: 0.75 })); s.position.copy(p); scene.add(s); shards.push({ m: s, v: new THREE.Vector3(rr(-0.4, 0.4), rr(4, 7), rr(-0.4, 0.4)), t: 0.9, float: true }); } audio.burst(0.7, 4500, 0.25); cur.userData.poolAt = []; }
        if (ev === 'chunks' || ev === 'splash' || ev === 'explodeSmall' || ev === 'fizzle' || ev === 'smoke') { const p = new THREE.Vector3(); (cur.userData.joints.torso || cur.userData.joints.body || cur).getWorldPosition(p); if (ev === 'splash') { p.copy(mount.localToWorld(new THREE.Vector3(0, 0.2, cur.userData.reach || 1.5))); } const n = { chunks: 10, splash: 18, explodeSmall: 24, fizzle: 8, smoke: 3 }[ev]; for (let j = 0; j < n; j++) { const lava = ev !== 'chunks' && ev !== 'smoke' && ev !== 'fizzle'; const s = new THREE.Mesh(ev === 'chunks' ? new THREE.DodecahedronGeometry(rr(0.08, 0.16), 0) : new THREE.SphereGeometry(rr(0.04, ev === 'smoke' ? 0.2 : 0.09), 5, 4), new THREE.MeshBasicMaterial({ color: ev === 'chunks' ? '#3a3230' : ev === 'smoke' || ev === 'fizzle' ? '#5a5250' : (j % 2 ? '#ffb020' : '#ff5a1a'), transparent: true, opacity: 0.9 })); s.position.copy(p); scene.add(s); shards.push({ m: s, v: ev === 'smoke' ? new THREE.Vector3(rr(-0.2, 0.2), rr(0.8, 1.4), rr(-0.2, 0.2)) : new THREE.Vector3(rr(-3, 3), rr(2, 5), rr(-3, 3)), t: ev === 'smoke' ? 1.8 : 1.0, float: ev === 'smoke' || ev === 'fizzle' }); } if (ev === 'explodeSmall') { audio.burst(0.35, 500, 0.3); const r = new THREE.Mesh(new THREE.CircleGeometry(0.9, 24), new THREE.MeshBasicMaterial({ color: 0xff8a1a, transparent: true, opacity: 0.5, depthWrite: false })); r.rotation.x = -Math.PI / 2; r.position.set(p.x, 0.15, p.z); scene.add(r); stuck.push({ m: r, t: 0.5 }); } else if (ev !== 'smoke') audio.burst(0.15, ev === 'fizzle' ? 6000 : 900, 0.15); }
        if (ev === 'lob') { const from = new THREE.Vector3(); cur.userData.joints.lava.getWorldPosition(from); const tgt = mount.localToWorld(new THREE.Vector3(rr(-1.2, 1.2), 0.15, rr(3, 4.4))); const d = dropDisc(); d.position.copy(tgt); scene.add(d); const s = new THREE.Mesh(new THREE.SphereGeometry(0.2, 10, 8), new THREE.MeshBasicMaterial({ color: '#ffb020' })); s.position.copy(from); scene.add(s); flying.push({ m: s, from: from.clone(), to: tgt.clone(), t: 0, dur: 0.9, pool: true, disc: d }); audio.tone(160, 0.25, 0.05, 'sawtooth', 0.7); }
        if (ev === 'flake' || ev === 'breath' || ev === 'frostStep' || ev === 'chill') { const p = new THREE.Vector3(); (ev === 'breath' ? cur.userData.joints.head : cur.userData.joints.torso).getWorldPosition(p); if (ev === 'frostStep' || ev === 'chill') { p.copy(mount.localToWorld(new THREE.Vector3(ev === 'chill' ? 0 : cur.position.x, 0.14, ev === 'chill' ? 1.8 : cur.position.z))); const r = new THREE.Mesh(new THREE.CircleGeometry(ev === 'chill' ? 1.2 : 0.25, 16), new THREE.MeshBasicMaterial({ color: 0xdfeaf0, transparent: true, opacity: 0.7, depthWrite: false })); r.rotation.x = -Math.PI / 2; r.position.copy(p); scene.add(r); stuck.push({ m: r, t: ev === 'chill' ? 1.5 : 2.5 }); if (ev === 'chill') audio.burst(0.3, 5000, 0.15); continue; } const n = ev === 'breath' ? 4 : 2; for (let j = 0; j < n; j++) { const s = new THREE.Mesh(new THREE.SphereGeometry(rr(0.03, 0.08), 5, 4), new THREE.MeshBasicMaterial({ color: ev === 'breath' ? '#dfeaf0' : '#8a8884', transparent: true, opacity: 0.8 })); s.position.copy(p); scene.add(s); const fw = mount.localToWorld(new THREE.Vector3(0, 0, 1)).sub(mount.getWorldPosition(new THREE.Vector3())).normalize(); shards.push({ m: s, v: ev === 'breath' ? fw.multiplyScalar(1.5).add(new THREE.Vector3(rr(-0.3, 0.3), rr(-0.1, 0.3), 0)) : new THREE.Vector3(rr(-0.3, 0.3), rr(-0.2, 0.3), rr(-0.3, 0.3)), t: 1.4, float: true }); } }
        if (ev === 'sweep') { slamT = 0; audio.burst(0.35, 600, 0.25); }
        if (ev === 'nova') { const c0 = mount.localToWorld(new THREE.Vector3(0, 0.15, 0.3)); const r = new THREE.Mesh(new THREE.RingGeometry(0.9, 1.4, 40), new THREE.MeshBasicMaterial({ color: 0xff8a1a, transparent: true, opacity: 0.8, depthWrite: false, side: THREE.DoubleSide })); r.rotation.x = -Math.PI / 2; r.position.copy(c0); scene.add(r); novas.push({ m: r, t: 0 }); audio.burst(0.6, 400, 0.3); audio.tone(60, 0.5, 0.07, 'sawtooth', 0.6); }
        if (ev === 'footprint') { const p = mount.localToWorld(new THREE.Vector3(cur.position.x + rr(-0.12, 0.12), 0.14, cur.position.z)); const f = new THREE.Mesh(new THREE.CircleGeometry(0.09, 8), new THREE.MeshBasicMaterial({ color: 0x1a1918, transparent: true, opacity: 0.8, depthWrite: false })); f.scale.y = 1.6; f.rotation.x = -Math.PI / 2; f.position.copy(p); scene.add(f); stuck.push({ m: f, t: 2.5 }); audio.tone(200, 0.03, 0.02, 'triangle'); for (let j = 0; j < 3; j++) { const s = new THREE.Mesh(new THREE.SphereGeometry(0.03, 4, 3), new THREE.MeshBasicMaterial({ color: '#c9b090' })); s.position.copy(p); scene.add(s); shards.push({ m: s, v: new THREE.Vector3(rr(-0.4, 0.4), rr(0.4, 1), rr(-0.4, 0.4)), t: 0.6, float: true }); } }
        if (ev === 'decloak') { audio.tone(900, 0.2, 0.04, 'sine', 0.4); }
        if (ev === 'stingShot') { const from = new THREE.Vector3(); cur.userData.joints.bead.getWorldPosition(from); const to = mount.localToWorld(new THREE.Vector3(0, 1.0, 5)); const s = new THREE.Mesh(new THREE.ConeGeometry(0.03, 0.3, 5).rotateX(Math.PI / 2), new THREE.MeshBasicMaterial({ color: '#ff3b3b' })); s.position.copy(from); s.lookAt(to); scene.add(s); flying.push({ m: s, from: from.clone(), to, t: 0, dur: 0.35, flat: true }); audio.tone(1500, 0.06, 0.04, 'triangle'); }
        if (ev === 'bristle') audio.burst(0.15, 3500, 0.12);
        if (ev === 'spores') { const p = mount.localToWorld(new THREE.Vector3(cur.position.x, 0.15, cur.position.z + 1.0)); const r = new THREE.Mesh(new THREE.CircleGeometry(0.85, 24), new THREE.MeshBasicMaterial({ color: 0xa855f7, transparent: true, opacity: 0.5, depthWrite: false })); r.rotation.x = -Math.PI / 2; r.position.copy(p); scene.add(r); stuck.push({ m: r, t: 2.0 }); for (let j = 0; j < 14; j++) { const s = new THREE.Mesh(new THREE.SphereGeometry(rr(0.03, 0.07), 5, 4), new THREE.MeshBasicMaterial({ color: cur.userData.slabColor, transparent: true, opacity: 0.8 })); s.position.copy(p); s.position.y = 0.5; scene.add(s); shards.push({ m: s, v: new THREE.Vector3(rr(-0.8, 0.8), rr(0.3, 1.2), rr(-0.8, 0.8)), t: 1.5, float: true }); } audio.burst(0.25, 1500, 0.12); }
        if (ev === 'seeds') { const from = new THREE.Vector3(); cur.userData.joints.cap.getWorldPosition(from); for (let j = 0; j < 3; j++) { const to = mount.localToWorld(new THREE.Vector3(rr(-1.6, 1.6), 0.15, rr(2.2, 3.8))); const s = new THREE.Mesh(new THREE.SphereGeometry(0.07, 6, 5), new THREE.MeshBasicMaterial({ color: '#84cc16' })); s.position.copy(from); scene.add(s); flying.push({ m: s, from: from.clone(), to, t: 0, dur: 0.7, seed: true }); } audio.tone(700, 0.08, 0.04, 'triangle', 1.3); }
        if (ev === 'summon' && cur.userData.family === 'queen') { for (let j = 0; j < 3; j++) { const h = ck.build('Hornet'); h.scale.setScalar(0.8); scene.add(h); const p = mount.localToWorld(new THREE.Vector3((j - 1) * 0.8, 0, 0.6)); h.position.copy(p); minis.push({ c: h, hornet: true, t: -j * 0.25, p, sx: j - 1 }); } audio.tone(300, 0.4, 0.05, 'sawtooth', 1.4); continue; }
        if (ev === 'gust') { const p = mount.localToWorld(new THREE.Vector3(rr(-1.5, 1.5), rr(0.4, 2.4), 1.2)); const fw = mount.localToWorld(new THREE.Vector3(0, 0, 1)).sub(mount.getWorldPosition(new THREE.Vector3())).normalize(); const s = new THREE.Mesh(new THREE.BoxGeometry(0.02, 0.02, 0.5), new THREE.MeshBasicMaterial({ color: '#dff4ff', transparent: true, opacity: 0.7 })); s.position.copy(p); s.lookAt(p.clone().add(fw)); scene.add(s); shards.push({ m: s, v: fw.multiplyScalar(9), t: 0.6, float: true }); audio.burst(0.08, 2000, 0.08); }
        if (ev === 'logThrow') { const from = new THREE.Vector3(); cur.userData.joints.arms[1].el.getWorldPosition(from); const to = mount.localToWorld(new THREE.Vector3(rr(-1, 1), 0.2, rr(3.2, 4.4))); const d = dropDisc(); d.position.copy(to); d.position.y = 0.14; scene.add(d); const s = new THREE.Mesh(new THREE.CylinderGeometry(0.16, 0.18, 1.4, 8), new THREE.MeshToonMaterial({ color: '#5a4030', gradientMap: grad })); s.position.copy(from); scene.add(s); flying.push({ m: s, from: from.clone(), to, t: 0, dur: 0.8, pool: false, disc: d, log: true }); audio.tone(120, 0.2, 0.05, 'triangle'); }
        if (ev === 'chop') { audio.burst(0.3, 1200, 0.2); setTimeout(() => audio.burst(0.5, 200, 0.3), 600); }
        if (ev === 'clod') { const from = new THREE.Vector3(); cur.userData.joints.paws[1].getWorldPosition(from); const to = mount.localToWorld(new THREE.Vector3(rr(-1, 1), 0.15, rr(3.4, 4.4))); const d = dropDisc(); d.position.copy(to); scene.add(d); const s = new THREE.Mesh(new THREE.DodecahedronGeometry(0.2, 0), new THREE.MeshBasicMaterial({ color: '#6b4a2a' })); s.position.copy(from); scene.add(s); flying.push({ m: s, from: from.clone(), to, t: 0, dur: 0.75, disc: d, log: true }); audio.tone(200, 0.1, 0.04, 'triangle'); }
        if (ev === 'snuff') { audio.tone(240, 0.3, 0.04, 'sine', 0.4); audio.burst(0.2, 3000, 0.06); }
        if (ev === 'relight') { audio.tone(660, 0.1, 0.04, 'triangle'); setTimeout(() => audio.tone(990, 0.15, 0.04, 'triangle'), 90); }
        if (ev === 'spit' && cur.userData.joints.throat) { const from = new THREE.Vector3(); cur.userData.joints.throat.getWorldPosition(from); const to = mount.localToWorld(new THREE.Vector3(0, 1.5, 5)); const s = new THREE.Mesh(new THREE.SphereGeometry(0.08, 8, 6), new THREE.MeshBasicMaterial({ color: '#b8e05a' })); s.position.copy(from); scene.add(s); flying.push({ m: s, from: from.clone(), to, t: 0, dur: 0.4, flat: true }); audio.burst(0.12, 1800, 0.15); }
        if (ev === 'hum') audio.tone(110, 0.15, 0.03, 'sawtooth', 1.05);
        if (ev === 'linen') { const p = new THREE.Vector3(); cur.userData.joints.core.getWorldPosition(p); for (let j = 0; j < 10; j++) { const s = new THREE.Mesh(new THREE.PlaneGeometry(0.06, 0.4), new THREE.MeshBasicMaterial({ color: cur.userData.slabColor, side: THREE.DoubleSide })); s.position.copy(p); scene.add(s); shards.push({ m: s, v: new THREE.Vector3(rr(-1.5, 1.5), rr(0.5, 2), rr(-1.5, 1.5)), t: 1.6, float: true }); } audio.burst(0.25, 3500, 0.15); }
        if (ev === 'collar') { const p = new THREE.Vector3(); (cur.userData.joints.collars[cur.userData.phase - 1] || cur.userData.joints.torso).getWorldPosition(p); for (let j = 0; j < 16; j++) { const s = new THREE.Mesh(new THREE.BoxGeometry(0.05, 0.05, 0.05), new THREE.MeshBasicMaterial({ color: j % 2 ? '#ffd23a' : '#ffffff' })); s.position.copy(p); scene.add(s); shards.push({ m: s, v: new THREE.Vector3(rr(-3, 3), rr(1, 4), rr(-3, 3)), t: 0.9 }); } audio.tone(1200, 0.08, 0.05, 'square'); audio.tone(80, 0.5, 0.07, 'sawtooth', 0.6); }
        if (ev === 'rattle') audio.tone(1200 + Math.random() * 400, 0.03, 0.03, 'square');
        if (ev === 'fallLane') { const r2 = new THREE.Mesh(new THREE.PlaneGeometry(2.2, 1.4), new THREE.MeshBasicMaterial({ color: 0xec3013, transparent: true, opacity: 0.45, depthWrite: false, side: THREE.DoubleSide })); r2.rotation.x = -Math.PI / 2; r2.position.copy(mount.localToWorld(new THREE.Vector3(1.3, 0.15, cur.position.z))); scene.add(r2); stuck.push({ m: r2, t: 1.6 }); }
        if (ev === 'boltThrow') { const from = new THREE.Vector3(); cur.userData.joints.arm.getWorldPosition(from); for (const a of [-0.08, 0.08]) { const to = mount.localToWorld(new THREE.Vector3(a * 10, 1.0, 5)); const s = new THREE.Mesh(new THREE.CylinderGeometry(0.05, 0.05, 0.14, 6), new THREE.MeshBasicMaterial({ color: '#9aa0a8' })); s.position.copy(from); scene.add(s); flying.push({ m: s, from: from.clone(), to, t: 0, dur: 0.4, flat: true }); } audio.tone(900, 0.06, 0.04, 'triangle'); }
        if (ev === 'flash') audio.tone(1800, 0.05, 0.05, 'square');
        if (ev === 'paint') { const from = new THREE.Vector3(); cur.userData.nozzle.getWorldPosition(from); const fw = mount.localToWorld(new THREE.Vector3(0, 0, 1)).sub(mount.getWorldPosition(new THREE.Vector3())).normalize(); for (let j = 0; j < 3; j++) { const s = new THREE.Mesh(new THREE.SphereGeometry(rr(0.05, 0.12), 5, 4), new THREE.MeshBasicMaterial({ color: ['#ec3013', '#ffd23a', '#38bdf8'][j], transparent: true, opacity: 0.7 })); s.position.copy(from); scene.add(s); shards.push({ m: s, v: fw.clone().multiplyScalar(rr(3, 5)).add(new THREE.Vector3(rr(-0.6, 0.6), rr(-0.2, 0.4), rr(-0.6, 0.6))), t: 0.8, float: true }); } audio.burst(0.05, 5000, 0.06); }
        if (ev === 'snowball' || ev === 'wormSpit') { const from = new THREE.Vector3(); (ev === 'snowball' ? cur.userData.joints.arms[1].hand : cur.userData.joints.mouth).getWorldPosition(from); const to = mount.localToWorld(new THREE.Vector3(0, 1.2, 5)); const s = new THREE.Mesh(new THREE.SphereGeometry(ev === 'snowball' ? 0.12 : 0.08, 8, 6), new THREE.MeshBasicMaterial({ color: ev === 'snowball' ? '#f4f8fb' : '#b8e05a' })); s.position.copy(from); scene.add(s); flying.push({ m: s, from: from.clone(), to, t: 0, dur: 0.4, flat: true }); audio.burst(0.1, 2500, 0.12); }
        if (ev === 'snowpuff') { const p = new THREE.Vector3(); cur.getWorldPosition(p); p.y = 1.0; for (let j = 0; j < 24; j++) { const s = new THREE.Mesh(new THREE.SphereGeometry(rr(0.06, 0.16), 6, 5), new THREE.MeshBasicMaterial({ color: '#f4f8fb', transparent: true, opacity: 0.9 })); s.position.copy(p); scene.add(s); shards.push({ m: s, v: new THREE.Vector3(rr(-2.5, 2.5), rr(1, 4), rr(-2.5, 2.5)), t: 1.2, float: true }); } audio.burst(0.3, 3000, 0.15); }
        if (ev === 'rollball') { const s = new THREE.Mesh(new THREE.SphereGeometry(1, 14, 10), new THREE.MeshToonMaterial({ color: '#f4f8fb', gradientMap: grad })); s.scale.setScalar(0.25); const p = mount.localToWorld(new THREE.Vector3(0.6, 0.4, 1.4)); s.position.copy(p); scene.add(s); rollers.push({ m: s, t: 0, p, dir: mount.localToWorld(new THREE.Vector3(0, 0, 1)).sub(mount.getWorldPosition(new THREE.Vector3())).normalize() }); audio.burst(0.3, 400, 0.15); }
        if (ev === 'iceFloor') { const r = new THREE.Mesh(new THREE.CircleGeometry(4.2, 40), new THREE.MeshBasicMaterial({ color: 0xa8e0f5, transparent: true, opacity: 0.55, depthWrite: false })); r.rotation.x = -Math.PI / 2; r.position.copy(mount.localToWorld(new THREE.Vector3(0, 0.15, 1.5))); scene.add(r); stuck.push({ m: r, t: 3 }); audio.burst(0.5, 6000, 0.12); }
        if (ev === 'wail') { audio.tone(220, 1.2, 0.06, 'sine', 0.6); setTimeout(() => audio.tone(180, 1.0, 0.05, 'sine', 0.7), 400); const c0 = mount.localToWorld(new THREE.Vector3(0, 0.15, 0.6)); const r = new THREE.Mesh(new THREE.RingGeometry(0.9, 1.2, 40), new THREE.MeshBasicMaterial({ color: 0xc084fc, transparent: true, opacity: 0.6, depthWrite: false, side: THREE.DoubleSide })); r.rotation.x = -Math.PI / 2; r.position.copy(c0); scene.add(r); novas.push({ m: r, t: 0 }); }
        if (ev === 'growl') audio.tone(90 + Math.random() * 20, 0.18, 0.05, 'sawtooth', 0.9);
        if (ev === 'squeak') audio.tone(2400 + Math.random() * 600, 0.05, 0.04, 'square', 1.2);
        if (ev === 'howl') { audio.tone(400, 0.9, 0.05, 'sine', 1.6); }
        if (ev === 'whistle') { audio.tone(2200, 0.15, 0.05, 'sine'); setTimeout(() => audio.tone(2600, 0.25, 0.05, 'sine'), 160); }
        if (ev === 'flicker') { audio.burst(0.1, 8000, 0.08); flick = 0.5; }
        if (ev === 'swarm') audio.burst(0.6, 3000, 0.1);
        if (ev === 'ink') { const p = new THREE.Vector3(); cur.userData.joints.body.getWorldPosition(p); for (let j = 0; j < 30; j++) { const s = new THREE.Mesh(new THREE.SphereGeometry(rr(0.1, 0.25), 6, 5), new THREE.MeshBasicMaterial({ color: '#2a1030', transparent: true, opacity: 0.7 })); s.position.copy(p); scene.add(s); shards.push({ m: s, v: new THREE.Vector3(rr(-1.5, 1.5), rr(-0.5, 1), rr(-1.5, 1.5)), t: 2.0, float: true }); } audio.burst(0.4, 300, 0.15); }
        if (ev === 'clack') { const p = new THREE.Vector3(); cur.userData.joints.claws[1].hand.getWorldPosition(p); for (let j = 0; j < 6; j++) { const s = new THREE.Mesh(new THREE.BoxGeometry(0.03, 0.03, 0.03), new THREE.MeshBasicMaterial({ color: j % 2 ? '#ffffff' : '#e09bff' })); s.position.copy(p); scene.add(s); shards.push({ m: s, v: new THREE.Vector3(rr(-1.5, 1.5), rr(1, 2.5), rr(-1.5, 1.5)), t: 0.35 }); } audio.tone(2200, 0.03, 0.05, 'square'); }
        if (ev === 'step') { const p = cur.getWorldPosition(new THREE.Vector3()); p.y = 0.2; for (let j = 0; j < 5; j++) { const s = new THREE.Mesh(new THREE.SphereGeometry(rr(0.05, 0.1), 5, 4), new THREE.MeshBasicMaterial({ color: '#b8a8c8', transparent: true, opacity: 0.7 })); s.position.copy(p); scene.add(s); shards.push({ m: s, v: new THREE.Vector3(rr(-1, 1), rr(0.3, 0.8), rr(-1, 1)), t: 0.6, float: true }); } audio.tone(60, 0.12, 0.06, 'sine', 0.7); }
        if (ev === 'paintSplash') { const p = new THREE.Vector3(); cur.userData.weak.getWorldPosition(p); for (let j = 0; j < 22; j++) { const s = new THREE.Mesh(new THREE.SphereGeometry(rr(0.05, 0.11), 6, 5), new THREE.MeshBasicMaterial({ color: ['#ec3013', '#ff8a1a', '#ffd23a', '#5cd65c', '#38bdf8', '#6b5cff', '#d64fd6'][j % 7] })); s.position.copy(p); scene.add(s); shards.push({ m: s, v: new THREE.Vector3(rr(-3, 3), rr(1, 4), rr(0.5, 3)), t: 1.0 }); } audio.burst(0.2, 1500, 0.15); }
        if (ev === 'ripple') { const p = cur.getWorldPosition(new THREE.Vector3()); p.y = 0.15; const r = new THREE.Mesh(new THREE.RingGeometry(0.3, 0.36, 24), new THREE.MeshBasicMaterial({ color: 0xdff4ff, transparent: true, opacity: 0.7, depthWrite: false, side: THREE.DoubleSide })); r.rotation.x = -Math.PI / 2; r.position.copy(p); scene.add(r); novas.push({ m: r, t: 0 }); }
        if (ev === 'feather1') { const p = new THREE.Vector3(); cur.userData.joints.body.getWorldPosition(p); const s = new THREE.Mesh(new THREE.PlaneGeometry(0.06, 0.14), new THREE.MeshBasicMaterial({ color: '#ffc2d9', side: THREE.DoubleSide })); s.position.copy(p); scene.add(s); shards.push({ m: s, v: new THREE.Vector3(rr(-0.4, 0.4), rr(0.2, 0.6), rr(-0.4, 0.4)), t: 2.5, float: true }); }
        if (ev === 'squawk') { audio.tone(1300, 0.08, 0.05, 'square', 0.7); setTimeout(() => audio.tone(1100, 0.1, 0.05, 'square', 0.8), 90); }
        if (ev === 'drip') { const p = new THREE.Vector3(); (cur.userData.dripAt || cur.userData.joints.head || cur).getWorldPosition(p); p.x += rr(-0.25, 0.25); p.z += rr(-0.15, 0.15); p.y += rr(0.4, 1.0); const s = new THREE.Mesh(new THREE.SphereGeometry(0.025, 5, 4), new THREE.MeshBasicMaterial({ color: '#5fa8c8' })); s.position.copy(p); scene.add(s); shards.push({ m: s, v: new THREE.Vector3(0, -0.5, 0), t: 0.7 }); }
        if (ev === 'coins') { const p = new THREE.Vector3(); cur.userData.pouch.getWorldPosition(p); for (let j = 0; j < 7; j++) { const s = new THREE.Mesh(new THREE.CylinderGeometry(0.04, 0.04, 0.01, 10), new THREE.MeshBasicMaterial({ color: '#ffd23a' })); s.position.copy(p); scene.add(s); shards.push({ m: s, v: new THREE.Vector3(rr(-1.5, 1.5), rr(2, 3.5), rr(-1.5, 1.5)), t: 1.0 }); } audio.tone(2600, 0.05, 0.04, 'triangle'); setTimeout(() => audio.tone(3100, 0.05, 0.04, 'triangle'), 60); }
        if (ev === 'sandDrool' || ev === 'sandTrickle' || ev === 'sandFall' || ev === 'chimney') { const src = ev === 'sandDrool' ? cur.userData.joints.noz : ev === 'chimney' ? cur.userData.joints.pipe : ev === 'sandFall' ? cur.userData.joints.segs[3 + Math.floor(Math.random() * 6)] : (cur.userData.joints.torso || cur); const p = new THREE.Vector3(); src.getWorldPosition(p); if (ev === 'chimney') p.y += 0.6; const steam = ev === 'chimney'; const s = new THREE.Mesh(new THREE.SphereGeometry(steam ? rr(0.12, 0.22) : rr(0.025, 0.05), 5, 4), new THREE.MeshBasicMaterial({ color: steam ? '#f1f5f9' : '#e0c48a', transparent: true, opacity: steam ? 0.7 : 0.9 })); s.position.copy(p); scene.add(s); shards.push({ m: s, v: steam ? new THREE.Vector3(rr(-0.2, 0.2), rr(1, 1.6), rr(-0.2, 0.2)) : new THREE.Vector3(rr(-0.2, 0.2), -0.3, rr(-0.2, 0.2)), t: steam ? 1.6 : 0.8, float: steam }); }
        if (ev === 'whistle') { audio.tone(1900, 0.18, 0.04, 'sine', 1.08); }
        if (ev === 'lavaDrip' || ev === 'emberRise' || ev === 'lavaPop' || ev === 'chimney2') { const U2 = cur.userData, src = ev === 'lavaPop' ? U2.joints.lava : ev === 'emberRise' && U2.family === 'cinder' ? U2.joints.heart : (U2.joints.torso || U2.joints.body || cur); const p = new THREE.Vector3(); src.getWorldPosition(p); if (ev === 'chimney2') { p.copy(cur.getWorldPosition(new THREE.Vector3())); p.y = 0.2; } p.x += rr(-0.3, 0.3); p.z += rr(-0.2, 0.2); const lava = ev === 'lavaDrip' || ev === 'lavaPop'; const s = new THREE.Mesh(new THREE.SphereGeometry(ev === 'chimney2' ? 0.12 : rr(0.025, 0.05), 5, 4), new THREE.MeshBasicMaterial({ color: ev === 'chimney2' ? '#e8eef2' : lava ? '#ff8a1a' : (Math.random() > 0.5 ? '#ffd23a' : '#ff5a1a'), transparent: true, opacity: 0.85 })); s.position.copy(p); scene.add(s); shards.push({ m: s, v: ev === 'lavaDrip' ? new THREE.Vector3(0, -0.6, 0) : ev === 'lavaPop' ? new THREE.Vector3(rr(-0.6, 0.6), rr(1, 2), rr(-0.6, 0.6)) : new THREE.Vector3(rr(-0.2, 0.2), rr(0.6, 1.4), rr(-0.2, 0.2)), t: ev === 'lavaPop' ? 0.6 : 1.2, float: ev !== 'lavaPop' }); if (ev === 'lavaPop') audio.tone(180, 0.05, 0.03, 'sine', 1.6); }
        if (ev === 'crackle') audio.burst(0.05, 5000, 0.08);
        if (ev === 'heartThump') { audio.tone(55, 0.15, 0.08, 'sine', 0.7); }
        if (ev === 'hum2') audio.tone(140, 0.4, 0.02, 'sine', 1.02);
        if (ev === 'buzzDive') { audio.tone(420, 0.5, 0.04, 'sawtooth', 0.45); }
        if (ev === 'chirp') { audio.tone(3000, 0.05, 0.03, 'sine', 1.3); setTimeout(() => audio.tone(3400, 0.05, 0.03, 'sine', 1.2), 80); }
        if (ev === 'honey' || ev === 'puff' || ev === 'dirt' || ev === 'butterfly') { const U2 = cur.userData; const p = new THREE.Vector3(); (ev === 'dirt' ? U2.joints.paws[1] : ev === 'puff' ? (U2.joints.body) : cur).getWorldPosition(p); if (ev === 'honey') { p.x += rr(-1.4, 1.4); p.z += rr(-1.4, 1.4); p.y = 0.7; } if (ev === 'butterfly') p.y = 1.2; const col = { honey: '#e0a020', puff: U2.slabColor, dirt: '#6b4a2a', butterfly: ['#f4a6b8', '#ffd23a', '#38bdf8'][Math.floor(Math.random() * 3)] }[ev]; const n = ev === 'puff' ? 5 : ev === 'dirt' ? 3 : 1; for (let j = 0; j < n; j++) { const s = new THREE.Mesh(ev === 'butterfly' ? new THREE.PlaneGeometry(0.1, 0.07) : new THREE.SphereGeometry(ev === 'puff' ? 0.06 : 0.035, 5, 4), new THREE.MeshBasicMaterial({ color: col, transparent: true, opacity: 0.85, side: THREE.DoubleSide })); s.position.copy(p); scene.add(s); shards.push({ m: s, v: ev === 'honey' ? new THREE.Vector3(0, -0.5, 0) : ev === 'butterfly' ? new THREE.Vector3(rr(-0.6, 0.6), rr(0.3, 0.8), rr(-0.6, 0.6)) : new THREE.Vector3(rr(-1, 1), rr(0.3, 1.5), rr(-1, 1)), t: ev === 'butterfly' ? 2.5 : 0.8, float: ev !== 'dirt' }); } }
        if (ev === 'scorch') { const hd = cur.userData.joints.head, q = new THREE.Vector3(0, 0, 1).applyQuaternion(hd.getWorldQuaternion(new THREE.Quaternion())); const p = hd.getWorldPosition(new THREE.Vector3()).addScaledVector(q.setY(0).normalize(), 4); p.y = 0.15; const s = new THREE.Mesh(new THREE.CircleGeometry(0.22, 10), new THREE.MeshBasicMaterial({ color: 0x2a1a10, transparent: true, opacity: 0.7, depthWrite: false })); s.rotation.x = -Math.PI / 2; s.position.copy(p); scene.add(s); stuck.push({ m: s, t: 2.5 }); }
        if (ev === 'breath2') audio.burst(0.25, 700, 0.05);
        if (ev === 'exhaust') { const p = new THREE.Vector3(); cur.userData.joints.stack.getWorldPosition(p); p.y += 0.4; const s = new THREE.Mesh(new THREE.SphereGeometry(rr(0.08, 0.16), 5, 4), new THREE.MeshBasicMaterial({ color: '#4a4846', transparent: true, opacity: 0.7 })); s.position.copy(p); scene.add(s); shards.push({ m: s, v: new THREE.Vector3(rr(-0.2, 0.2), rr(1, 1.6), rr(-0.4, 0)), t: 1.4, float: true }); }
        if (ev === 'horn') { audio.tone(330, 0.35, 0.06, 'square', 1.0); setTimeout(() => audio.tone(262, 0.4, 0.06, 'square', 1.0), 350); }
        if (ev === 'boing') audio.tone(300, 0.25, 0.05, 'sine', 2.5);
        if (ev === 'paintMark') { const p = mount.localToWorld(new THREE.Vector3(rr(-0.8, 0.8), 0.15, rr(1.2, 2.8))); const s = new THREE.Mesh(new THREE.CircleGeometry(rr(0.15, 0.3), 10), new THREE.MeshBasicMaterial({ color: ['#ec3013', '#ffd23a', '#38bdf8'][Math.floor(Math.random() * 3)], transparent: true, opacity: 0.8, depthWrite: false })); s.rotation.x = -Math.PI / 2; s.position.copy(p); scene.add(s); stuck.push({ m: s, t: 3 }); }
        if (ev === 'snowflake') { const p = cur.getWorldPosition(new THREE.Vector3()); p.x += rr(-1.2, 1.2); p.z += rr(-1.2, 1.2); p.y = 3; const s = new THREE.Mesh(new THREE.SphereGeometry(0.025, 5, 4), new THREE.MeshBasicMaterial({ color: '#ffffff' })); s.position.copy(p); scene.add(s); shards.push({ m: s, v: new THREE.Vector3(rr(-0.2, 0.2), -0.8, rr(-0.2, 0.2)), t: 3.5, float: true }); }
        if (ev === 'tear') { const hd = cur.userData.joints.head; for (const sx of [-0.26, 0.26]) { const p = hd.localToWorld(new THREE.Vector3(sx, -0.05, 0.62)); const s = new THREE.Mesh(new THREE.SphereGeometry(0.035, 6, 5), new THREE.MeshBasicMaterial({ color: '#a8e0f5' })); s.position.copy(p); scene.add(s); shards.push({ m: s, v: new THREE.Vector3(0, -0.4, 0), t: 1.6, float: true }); } }
        if (ev === 'drool' || ev === 'bubble' || ev === 'mothDust') { const U2 = cur.userData; const src = ev === 'drool' ? U2.joints.jaw : ev === 'bubble' ? U2.joints.body : U2.joints.moths[Math.floor(Math.random() * U2.joints.moths.length)].m; const p = new THREE.Vector3(); src.getWorldPosition(p); const s = new THREE.Mesh(new THREE.SphereGeometry(ev === 'bubble' ? rr(0.05, 0.1) : 0.025, 6, 5), new THREE.MeshBasicMaterial({ color: ev === 'drool' ? '#dff4ff' : ev === 'bubble' ? '#c8e8ff' : '#fff6c8', transparent: true, opacity: 0.8 })); s.position.copy(p); scene.add(s); shards.push({ m: s, v: ev === 'drool' ? new THREE.Vector3(0, -0.6, 0) : ev === 'bubble' ? new THREE.Vector3(rr(-0.2, 0.2), rr(0.6, 1), rr(-0.2, 0.2)) : new THREE.Vector3(0, -0.15, 0), t: ev === 'mothDust' ? 0.9 : 1.4, float: true }); }
        if (ev === 'glint') { audio.tone(4200, 0.08, 0.03, 'sine'); }
        if (ev === 'tick') audio.tone(2600, 0.02, 0.02, 'square');
        if (ev === 'roar') { audio.tone(90, 0.6, 0.08, 'sawtooth', 0.7); audio.burst(0.5, 400, 0.2); }
        if (ev === 'slam') { slamT = 0; audio.burst(0.4, 250, 0.3); audio.tone(70, 0.35, 0.07, 'square', 0.5); }
        if (ev === 'shatter') { shatter(40, cur.userData.weakBase); audio.burst(0.5, 600, 0.3); }
      }
      catch (e) { console.warn('creature event', e); }
      const fanK = tells && cur.userData.ranged && state === 'windup' ? clamp(st / ck.dur(cur, 'windup')) : 0, la = cur.userData.laneAngles; lanes.forEach((l, i) => l.material.opacity = (!la || (i === 1)) ? fanK * 0.45 : 0);
      const chK = tells && cur.userData.charge && (state === 'windup' || state === 'attack') ? (state === 'windup' ? clamp(st / ck.dur(cur, 'windup')) : 1) : 0; chargeLane.material.opacity = chK * (0.35 + 0.15 * Math.sin(t * 16)); wall.visible = !!cur.userData.charge;
      if (cur.userData.charge && state === 'attack') { const k = clamp(st / ck.dur(cur, 'attack')); cur.position.z = 0.3 + ease3(k) * 3.6; }
      if (cur.userData.charge && (state === 'stagger' || state === 'recover')) cur.position.z = 3.9;
      const throwing = cur.userData.willThrow && (state === 'windup' || (state === 'attack')) || flying.length > 0, dk = tells && throwing ? 1 : 0;
      disc.material.opacity = dk * 0.9; discFill.material.opacity = dk * (0.2 + 0.15 * Math.sin(t * 10));
      const open = state === 'recover' || state === 'stagger'; weakFlash = open && tells ? 0.5 + 0.5 * Math.sin(t * 12) : 0;
      cur.userData.weakMat.emissive.copy(open && tells ? new THREE.Color('#ffd23a') : cur.userData.weakBase); cur.userData.weakMat.emissiveIntensity = open && tells ? 0.8 + weakFlash : 0.9;
      const melee = !cur.userData.willThrow && !cur.userData.ranged, tellK = tells && melee && state === 'windup' ? clamp(st / ck.dur(cur, 'windup')) : tells && melee && state === 'attack' ? 1 - clamp(st / ck.dur(cur, 'attack')) : 0;
      ring.material.opacity = tellK > 0 ? 0.9 : 0; ringFill.material.opacity = tellK * 0.35; ring.position.z = ringFill.position.z = (cur.userData.reach || 1.1); { const rs = (cur.userData.reach || 1.1) / 1.1; ring.scale.setScalar(rs); } ringFill.scale.setScalar(Math.max(0.01, tellK));
    }
    for (let i = flying.length - 1; i >= 0; i--) { const f = flying[i]; f.t += dt; const k = Math.min(1, f.t / f.dur); f.m.position.lerpVectors(f.from, f.to, k); if (!f.flat) { f.m.position.y += Math.sin(k * Math.PI) * 2.2; f.m.rotation.x += dt * 9; f.m.rotation.z += dt * 5; } if (f.disc) f.disc.material.opacity = 0.6 + 0.3 * Math.sin(t * 14);
      if (k >= 1 && f.log) { flying.splice(i, 1); scene.remove(f.m); scene.remove(f.disc); for (let j = 0; j < 12; j++) { const s = new THREE.Mesh(new THREE.BoxGeometry(rr(0.05, 0.15), 0.05, 0.05), new THREE.MeshBasicMaterial({ color: f.m.material.color })); s.position.copy(f.to); scene.add(s); shards.push({ m: s, v: new THREE.Vector3(rr(-3, 3), rr(2, 5), rr(-3, 3)), t: 1 }); } audio.burst(0.3, 600, 0.25); continue; }
      if (k >= 1 && f.seed) { flying.splice(i, 1); scene.remove(f.m); const sp = ck.build('Sporeling'); sp.scale.setScalar(0.01); sp.position.copy(f.to); sp.position.y = 0.12; scene.add(sp); minis.push({ c: sp, sprout: true, t: 0, p: f.to.clone(), sx: 0 }); continue; }
      if (k >= 1 && f.pool) { flying.splice(i, 1); scene.remove(f.m); scene.remove(f.disc); const r = new THREE.Mesh(new THREE.CircleGeometry(0.8, 28), new THREE.MeshBasicMaterial({ color: 0xa855f7, transparent: true, opacity: 0.55, depthWrite: false })); r.rotation.x = -Math.PI / 2; r.position.copy(f.to); r.position.y = 0.15; scene.add(r); stuck.push({ m: r, t: 2.2 }); audio.burst(0.25, 700, 0.2); continue; }
      if (k >= 1 && f.stick) { flying.splice(i, 1); f.m.position.copy(f.to); f.m.rotation.set(rr(-0.4, 0.4), 0, rr(-0.4, 0.4)); stuck.push({ m: f.m, t: 4 }); audio.burst(0.12, 2600, 0.12); continue; }
      if (k >= 1) { scene.remove(f.m); flying.splice(i, 1); const p = f.to; for (let j = 0; j < 14; j++) { const s = new THREE.Mesh(new THREE.OctahedronGeometry(rr(0.05, 0.12), 0), new THREE.MeshBasicMaterial({ color: f.m.material.color })); s.position.copy(p); scene.add(s); shards.push({ m: s, v: new THREE.Vector3(rr(-3, 3), rr(2, 5), rr(-3, 3)), t: 1.2 }); } audio.burst(0.3, 1800, 0.22); } }
    for (let i = stuck.length - 1; i >= 0; i--) { const s = stuck[i]; s.t -= dt; if (s.t < 0.4) s.m.scale.setScalar(Math.max(0.01, s.t / 0.4)); if (s.t <= 0) { scene.remove(s.m); stuck.splice(i, 1); } }
    for (let i = drops.length - 1; i >= 0; i--) { const q = drops[i]; q.t += dt; q.d.visible = q.t > 0; q.d.material.opacity = 0.6 + 0.3 * Math.sin(t * 14); if (q.t > 0.7) { q.s.visible = true; q.s.position.y = Math.max(0.3, 9 - (q.t - 0.7) * 22); } if (q.t > 1.12) { scene.remove(q.d); scene.remove(q.s); drops.splice(i, 1); for (let j = 0; j < 8; j++) { const s = new THREE.Mesh(new THREE.OctahedronGeometry(rr(0.05, 0.1), 0), new THREE.MeshBasicMaterial({ color: '#c79bff' })); s.position.copy(q.p); s.position.y = 0.3; scene.add(s); shards.push({ m: s, v: new THREE.Vector3(rr(-3, 3), rr(2, 4), rr(-3, 3)), t: 1 }); } audio.burst(0.15, 2200, 0.12); } }
    for (let i = minis.length - 1; i >= 0; i--) { const q = minis[i]; q.t += dt; if (q.hornet) { const tt = Math.max(0, q.t); q.c.position.set(q.p.x + Math.sin(tt * 3 + q.sx) * 1.2 + q.sx * tt, 0, q.p.z + tt * 1.6); ck.animate(q.c, 'move', q.t + 5, dt, {}); if (q.t > 2.8) { scene.remove(q.c); minis.splice(i, 1); } continue; }
      if (q.sprout) { q.c.scale.setScalar(Math.min(0.6, q.t * 0.4)); ck.animate(q.c, 'idle', q.t, dt, {}); if (q.t > 3) { scene.remove(q.c); minis.splice(i, 1); } continue; } const out = Math.min(1, q.t / 0.5); q.c.position.set(q.p.x + q.sx * q.t * 1.2, out < 1 ? 0.6 - out * 0.48 + Math.sin(out * Math.PI) * 0.6 : 0.12, q.p.z + q.t * 1.4); q.c.rotation.y = q.sx * 0.6; ck.animate(q.c, 'move', q.t, dt, { speed: 1 }); if (q.t > 2.6) { scene.remove(q.c); minis.splice(i, 1); } }
    for (let i = novas.length - 1; i >= 0; i--) { const q = novas[i]; q.t += dt; q.m.scale.setScalar(1 + q.t * 4); q.m.material.opacity = 0.8 * (1 - q.t / 1.0); if (q.t > 1) { scene.remove(q.m); novas.splice(i, 1); } }
    for (let i = rollers.length - 1; i >= 0; i--) { const q = rollers[i]; q.t += dt; const sc = 0.25 + q.t * 0.35; q.m.scale.setScalar(sc); q.m.position.copy(q.p).addScaledVector(q.dir, q.t * 2.6); q.m.position.y = sc; q.m.rotation.x += dt * 2.6 / sc; if (q.t > 2.2) { scene.remove(q.m); rollers.splice(i, 1); } }
    slamT += dt; if (cur && slamT < 0.5) { ringFill.material.opacity = 0.5 * (1 - slamT / 0.5); ringFill.scale.setScalar(1 + slamT * 3); ring.material.opacity = 0.9 * (1 - slamT / 0.5); }
    for (let i = shards.length - 1; i >= 0; i--) { const s = shards[i]; s.t -= dt; s.v.y -= (s.float ? 2.5 : 12) * dt; if (s.float) s.v.multiplyScalar(0.97); s.m.position.addScaledVector(s.v, dt); if (s.m.position.y < 0.15) { s.m.position.y = 0.15; s.v.multiplyScalar(0.4); s.v.y = Math.abs(s.v.y); } s.m.rotation.x += dt * 8; if (s.t <= 0) { scene.remove(s.m); shards.splice(i, 1); } }
    { const dark = cur && cur.userData.dark ? 1 : 0; darkK = damp(darkK, dark, 3, dt); flick = Math.max(0, flick - dt); sun.intensity = 2.4 * (1 - darkK * 0.85) * (flick > 0 && Math.sin(t * 60) > 0 ? 0.2 : 1); scene.children.forEach(o => { if (o.isHemisphereLight) o.intensity = 1.15 * (1 - darkK * 0.8); }); }
    fox.visible = showFox || !!ai; if (fox.visible) fk.animFox(fox, dt, ai ? 2 : 0, false);
    // frame the real bounds of the creature (+ fox) inside the clear band below the notes card and above the controls
    const Hh = H(), Ww = W(), ins = getInsets(), top = Math.min(ins.top, Hh * 0.4), bot = Math.min(ins.bottom, Hh * 0.6), band = Math.max(120, Hh - top - bot - 16);
    box.makeEmpty(); if (cur && cur.userData.frame) { const f = cur.userData.frame; box.expandByPoint(v1.set(-1.7, 0, -1.2)); box.expandByPoint(v1.set(1.7, 2.6, 2.6)); } else if (cur) visBox(cur); if (showFox) visBox(fox); if (box.isEmpty()) box.set(new THREE.Vector3(-1, 0, -1), new THREE.Vector3(1, 1.5, 1));
    const c = box.getCenter(v1.clone()), sz = box.getSize(new THREE.Vector3()), tv = Math.tan(camera.fov * Math.PI / 360), tvb = tv * band / Hh, th = tv * camera.aspect;
    const D = Math.min(24, (Math.max(sz.y / 2 / tvb, Math.max(sz.x, sz.z) / 2 / th) + Math.max(sz.x, sz.z) / 2) * 1.05 * (dist / 7.2));
    camera.position.set(c.x + Math.sin(yaw) * D * Math.cos(pitch), c.y + Math.sin(pitch) * D, c.z + Math.cos(yaw) * D * Math.cos(pitch)); camera.lookAt(c);
    scene.fog.near = D * 0.9; scene.fog.far = D * 2.5 + 10;
    vOff = damp(vOff, Hh / 2 - (top + 8 + band / 2), 8, dt); camera.setViewOffset(Ww, Hh, 0, vOff, Ww, Hh);
    renderer.render(scene, camera);
  }
  frame();
  return {
    setCreature: setCreatureOuter, play, setPhase(n) { if (cur) { ck.setPhase(cur, n); play('idle'); } }, canBuild: n => ck.canBuild(n),
    respawn() { if (cur) cfx.despawn(cur, () => setCreature(cur.userData.variant)); },
    setBake(v) { bake = v; if (cur) setCreature(cur.userData.variant); },
    setTurntable(v) { turn = v; if (!v) table.rotation.y = 0; push(); }, setTells(v) { tells = v; push(); }, setFox(v) { showFox = v; push(); },
    setLoop(v) { loop = v; loopI = 0; play(v ? 'move' : 'idle'); },
    setAI(v) { if (v && cur) { loop = false; turn = false; table.rotation.y = 0; setCreature(cur.userData.variant); ai = createBrain(cur, ck); foxHp = 100; } else { ai = null; fox.position.set(-2.9, 0, 0.4); fox.rotation.y = 0.5; if (cur) setCreature(cur.userData.variant); } push(); },
    aiHit(weak) { if (!ai || !cur) return; const ns = ai.hurt(12, weak, state); cfx.hit(cur); audio.burst(0.12, weak ? 4000 : 2000, 0.2); if (weak) audio.tone(1500, 0.08, 0.05, 'triangle'); if (ns) play(ns); if (ai.dead) setTimeout(() => { if (ai && ai.dead && cur) cfx.despawn(cur, () => { if (ai && cur) { setCreature(cur.userData.variant); ai = createBrain(cur, ck); push(); } }); }, 2200); push(); },
    destroy() { cancelAnimationFrame(raf); ro.disconnect(); renderer.dispose(); el.remove(); },
  };
}
